# -*- coding: utf-8 -*-
"""RSC dışındaki kaynaklar: vakaların gerçek olaylara ve özel kullanımlara dayanan bilgileri için.
Her bağlantı 2026-10-07'de indirilip ilgili bilginin sayfada geçtiği denetlendi (kaynak_dogrula.py)."""

W = "Vikipedi (İngilizce)"

EK_KAYNAK = {
    # Seviye 1
    "Altın Madalyanın Sırrı": [f"{W}: Olympic medal — https://en.wikipedia.org/wiki/Olympic_medal"],
    "Karanlıkta Parlayan Rakamlar": [f"{W}: Radium Girls — https://en.wikipedia.org/wiki/Radium_Girls"],
    "Element Yapan Element": [f"{W}: Tennessine — https://en.wikipedia.org/wiki/Tennessine"],
    "Duman Dedektöründeki Yeni Element": ["ABD Çevre Koruma Ajansı (EPA): Americium in Ionization Smoke Detectors — https://www.epa.gov/radtown/americium-ionization-smoke-detectors"],
    # Seviye 2
    "Havadan Ekmek": [f"{W}: Haber process — https://en.wikipedia.org/wiki/Haber_process"],
    "Gökyüzündeki Görünmez Kalkan": [f"{W}: Montreal Protocol — https://en.wikipedia.org/wiki/Montreal_Protocol"],
    "İznik Çinisinin Mavisi": [f"{W}: İznik pottery — https://en.wikipedia.org/wiki/%C4%B0znik_pottery"],
    "Özgürlük Heykelinin Yeşili": [f"{W}: Statue of Liberty — https://en.wikipedia.org/wiki/Statue_of_Liberty"],
    "Kralların Mor Boyası": [f"{W}: Tyrian purple — https://en.wikipedia.org/wiki/Tyrian_purple"],
    "Uydudaki Şaşmaz Saat": [f"{W}: Rubidium standard — https://en.wikipedia.org/wiki/Rubidium_standard"],
    "Tuzdaki Gizli Koruyucu": [f"{W}: Iodised salt — https://en.wikipedia.org/wiki/Iodised_salt"],
    "Taşı Kum Tanesine Çeviren Işık": [f"{W}: Laser lithotripsy — https://en.wikipedia.org/wiki/Laser_lithotripsy"],
    "Evrenin Yaşı Kadar Şaşmayan Saat": [f"{W}: Atomic clock — https://en.wikipedia.org/wiki/Atomic_clock"],
    "PET Tarayıcısının Parlayan Kristalleri": [f"{W}: Lutetium–yttrium oxyorthosilicate — https://en.wikipedia.org/wiki/Lutetium%E2%80%93yttrium_oxyorthosilicate"],
    # Seviye 3
    "Derinlerin Gazı": [f"{W}: Heliox — https://en.wikipedia.org/wiki/Heliox"],
    "Apollo 13'ün Patlayan Tankı": [f"{W}: Apollo 13 — https://en.wikipedia.org/wiki/Apollo_13"],
    "Hiçbir Şeyin Yapışmadığı Tava": [f"{W}: Polytetrafluoroethylene — https://en.wikipedia.org/wiki/Polytetrafluoroethylene"],
    "Reaktördeki Sıvı Metal": [f"{W}: Sodium-cooled fast reactor — https://en.wikipedia.org/wiki/Sodium-cooled_fast_reactor"],
    "Kutunun İkinci Hayatı": [f"{W}: Aluminium recycling — https://en.wikipedia.org/wiki/Aluminium_recycling"],
    "Lastiğin Sırrı": [f"{W}: Vulcanization — https://en.wikipedia.org/wiki/Vulcanization"],
    "Pul Pul Parlayan Müze": [f"{W}: Guggenheim Museum Bilbao — https://en.wikipedia.org/wiki/Guggenheim_Museum_Bilbao"],
    "Model T'nin Sağlam Çeliği": [f"{W}: Ford Model T — https://en.wikipedia.org/wiki/Ford_Model_T"],
    "Darbelerle Sertleşen Ray": [f"{W}: Mangalloy — https://en.wikipedia.org/wiki/Mangalloy"],
    "Otomatın Tanıdığı Para": [f"{W}: Euro coins — https://en.wikipedia.org/wiki/Euro_coins"],
    "Mikrop Tutmayan Kapı Kolu": [f"{W}: Antimicrobial copper-alloy touch surfaces — https://en.wikipedia.org/wiki/Antimicrobial_copper-alloy_touch_surfaces"],
    "Mavi Işığın Nobel'i": ["Nobel Vakfı: The Nobel Prize in Physics 2014 — https://www.nobelprize.org/prizes/physics/2014/summary/"],
    "Yeşil Duvar Kâğıdı": [f"{W}: Scheele's green — https://en.wikipedia.org/wiki/Scheele%27s_green"],
    "Karanlıkta Parlayan Yıldızlar": [f"{W}: Strontium aluminate — https://en.wikipedia.org/wiki/Strontium_aluminate"],
    "Ufalanan Org Boruları": [f"{W}: Tin pest — https://en.wikipedia.org/wiki/Tin_pest"],
    "İnce Ama Ağır Dart Oku": [f"{W}: Darts — https://en.wikipedia.org/wiki/Darts"],
    "Siyahlaşan Dil": [f"{W}: Bismuth subsalicylate — https://en.wikipedia.org/wiki/Bismuth_subsalicylate"],
    "Kararmayan Gümüş Kolye": [f"{W}: Rhodium — https://en.wikipedia.org/wiki/Rhodium"],
    # Seviye 4
    "Dibe Batan Buz": [f"{W}: Heavy water — https://en.wikipedia.org/wiki/Heavy_water"],
    "Mermi Durduran Seramik": [f"{W}: Boron carbide — https://en.wikipedia.org/wiki/Boron_carbide"],
    "Hawaii'deki Ölçüm Eğrisi": ["NOAA Küresel İzleme Laboratuvarı: Trends in Atmospheric Carbon Dioxide — https://gml.noaa.gov/ccgg/trends/",
                                 f"{W}: Mauna Loa Observatory — https://en.wikipedia.org/wiki/Mauna_Loa_Observatory"],
    "Yüzükteki Taş Gerçek mi?": [f"{W}: Diamond simulant — https://en.wikipedia.org/wiki/Diamond_simulant"],
    "Kasadaki Kırmızı Çizgi": [f"{W}: Helium–neon laser — https://en.wikipedia.org/wiki/Helium%E2%80%93neon_laser"],
    "Denizden Çıkan Metal": [f"{W}: Magnesium — https://en.wikipedia.org/wiki/Magnesium"],
    "Direkler Arasındaki Teller": [f"{W}: Aluminium conductor steel-reinforced cable — https://en.wikipedia.org/wiki/Aluminium_conductor_steel-reinforced_cable"],
    "Yeşile Boğulan Göl": [f"{W}: Eutrophication — https://en.wikipedia.org/wiki/Eutrophication"],
    "Aşınan Heykeller": [f"{W}: Acid rain — https://en.wikipedia.org/wiki/Acid_rain"],
    "Boruların Gizli Elementi": [f"{W}: Polyvinyl chloride — https://en.wikipedia.org/wiki/Polyvinyl_chloride"],
    "Tarladaki Ağır Taş": [f"{W}: Widmanstätten pattern — https://en.wikipedia.org/wiki/Widmanst%C3%A4tten_pattern"],
    "Bataryanın Etik Bedeli": [f"{W}: Cobalt — https://en.wikipedia.org/wiki/Cobalt"],
    "Soğuk Tabaktaki Ayna": [f"{W}: Marsh test — https://en.wikipedia.org/wiki/Marsh_test"],
    "'Ah, Acıyor!' Hastalığı": [f"{W}: Itai-itai disease — https://en.wikipedia.org/wiki/Itai-itai_disease"],
    "Silinip Yeniden Yazılan Disk": [f"{W}: GeSbTe — https://en.wikipedia.org/wiki/GeSbTe"],
    "Mavi Parlayan Toz": [f"{W}: Goiânia accident — https://en.wikipedia.org/wiki/Goi%C3%A2nia_accident"],
    "Telefonun İçindeki Koltan": [f"{W}: Coltan — https://en.wikipedia.org/wiki/Coltan"],
    "Dinozorları Yok Eden Kanıt": [f"{W}: Alvarez hypothesis — https://en.wikipedia.org/wiki/Alvarez_hypothesis"],
    "Fanusların Altındaki Kilogram": [f"{W}: International Prototype of the Kilogram — https://en.wikipedia.org/wiki/International_Prototype_of_the_Kilogram"],
    "Minamata'nın Kedileri": [f"{W}: Minamata disease — https://en.wikipedia.org/wiki/Minamata_disease"],
    "Romandaki Zehir": [f"{W}: The Pale Horse — https://en.wikipedia.org/wiki/The_Pale_Horse"],
    "Benzindeki Görünmez Tehlike": [f"{W}: Tetraethyllead — https://en.wikipedia.org/wiki/Tetraethyllead"],
    "Gökkuşağı Renkli Kristal": [f"{W}: Bismuth — https://en.wikipedia.org/wiki/Bismuth"],
    "Otuz Yıl Atan Kalp Pili": [f"{W}: Artificial cardiac pacemaker — https://en.wikipedia.org/wiki/Artificial_cardiac_pacemaker"],
    "Havada Asılı Duran Mıknatıs": [f"{W}: Yttrium barium copper oxide — https://en.wikipedia.org/wiki/Yttrium_barium_copper_oxide"],
}
