# -*- coding: utf-8 -*-
"""Seviye 1 (Gözlem) — yeni vakalar, birinci bölüm."""
from sablon import S, V, Y

VAKALAR = [
    V("H", 1, "enerji", "Sessiz Otobüs",
      "Şehrin yeni otobüsü durağa neredeyse hiç ses çıkarmadan yanaştı. Egzozundan duman değil, yalnızca ince bir buhar "
      "çıkıyor. Şoför, otobüsün depolarında sıkıştırılmış bir gaz taşıdığını ve bu gazın havadaki oksijenle birleşerek "
      "elektrik ürettiğini söylüyor. Görevin: depodaki gazın hangi element olduğunu bulmak.",
      [("deney", "Egzozdan çıkan madde", "Egzozun önüne tutulan soğuk bir cam buğulandı; camda yalnızca su damlacıkları toplandı. Duman ya da is yok."),
       ("fiziksel", "Depodaki gaz", "Depodaki gaz renksiz ve kokusuz. Bilinen bütün gazların en hafifi.")],
      gozlem=S("Egzozdan yalnızca su çıkması (K1) depodaki yakıt hakkında neyi gösterir?",
               "Yakıtın atomları oksijenle birleşince su oluşuyor.",
               Y("Otobüs yakıt olarak su kullanıyor.", "iliski", "Su yanmaz ve enerji vermez; su, yakıtın oksijenle birleşmesinin sonucudur.", "K1"),
               Y("Yakıt, kömür gibi karbon içeriyor.", "veri", "Karbon içeren bir yakıt yanınca is ve karbondioksit çıkar; camda is görülmedi (K1).", "K1"),
               ipucu="Su molekülü hangi iki elementten oluşur? Biri havadan geliyor.",
               aciklama="Su molekülü iki elementten oluşur. Bunlardan biri havadan gelen oksijen olduğuna göre, yakıtta suyun diğer elementi bulunmalıdır."),
      kullanim=S("Hidrojen bu otobüste neden 'temiz yakıt' sayılıyor?",
                 "Oksijenle birleşip enerji verirken geriye yalnızca su bırakıyor",
                 Y("Hiç enerji vermediği için çevreye zarar vermiyor", "iliski", "Otobüs bu gazla çalışıyor; yani gaz enerji veriyor. Temiz olmasının nedeni atığının yalnızca su olması.", "K1"),
                 Y("Havadan ağır olduğu için yere çöküp dağılmadığı için", "veri", "Hidrojen bilinen en hafif gazdır (K2); havadan ağır değil.", "K2"),
                 Y("Renksiz ve kokusuz olduğu için", "iliski", "Renk ve koku, bir yakıtın atığını belirlemez. Önemli olan yandığında ne oluştuğu.", "K2"),
                 ipucu="Egzozdan ne çıkıyordu?",
                 aciklama="Yakıt hücresinde hidrojen, havadaki oksijenle birleşerek elektrik üretir; atık olarak yalnızca su oluşur. Bu yüzden hidrojenle çalışan otobüslerde egzozdan karbondioksit ya da is çıkmaz.")),

    V("O", 1, "saglik", "Dağcının Tüpü",
      "Everest'e tırmanan bir dağcı, 8000 metrenin üzerinde sırtındaki tüpten gaz soluyor. Aynı tüpten hastanelerde de "
      "nefes darlığı çeken hastalara gaz veriliyor. Görevin: tüpteki gazın hangi element olduğunu bulmak.",
      [("deney", "Kor hâlindeki çubuk", "Tüpten alınan gaza alevi sönmüş ama hâlâ kor hâlinde olan bir tahta çubuk sokuldu: çubuk yeniden alev aldı."),
       ("fiziksel", "Yüksekteki hava", "8000 metrede hava basıncı deniz seviyesindekinin yaklaşık üçte biri. Her nefeste akciğerlere giren gaz miktarı çok azalır.")],
      gozlem=S("Kor hâlindeki çubuğun yeniden alev alması (K1) tüpteki gaz hakkında neyi gösterir?",
               "Gaz yanmayı güçlü biçimde destekliyor.",
               Y("Gaz yanmayı söndürüyor.", "veri", "Çubuk sönmedi; tam tersine yeniden alev aldı (K1).", "K1"),
               Y("Gazın kendisi bir yakıttır.", "iliski", "Yanan, tahta çubuktur. Gaz yanmayı destekler; bu onu yakıt yapmaz.", "K1"),
               ipucu="Bir şeyin yanabilmesi için havadaki hangi gaz gerekir?",
               aciklama="Kor hâlindeki çubuğun yeniden alevlenmesi, yanmayı destekleyen gazın klasik tanıma deneyidir."),
      kullanim=S("Dağcılar yüksek irtifada neden bu gazı soluyor?",
                 "Hücrelerin enerji üretmek için oksijene ihtiyacı var; seyrek havada her nefeste yeterince oksijen alınamıyor",
                 Y("Gaz vücudu ısıttığı için", "iliski", "Soluduğumuz oksijen vücudu doğrudan ısıtmaz; hücrelerin enerji üretmesini sağlar.", "K2"),
                 Y("Gaz havadan hafif olduğu için dağcıyı hafifletir", "iliski", "Soluduğumuz gaz vücudu hafifletmez; dağcının ihtiyacı nefesle yeterli oksijen almak (K2).", "K2"),
                 Y("Yüksekte havada hiç oksijen kalmadığı için", "veri", "Havada hâlâ oksijen var; ama basınç düştüğü için her nefeste daha az oksijen giriyor (K2).", "K2"),
                 ipucu="K2'de yüksekteki havanın nasıl değiştiği yazıyor.",
                 aciklama="Hava yaklaşık %21 oksijen içerir; bu oran yüksekte de aynıdır. Ama basınç düşünce her nefeste akciğerlere giren oksijen azalır. Tüpteki oksijen, hücrelerin enerji üretmesi için gereken oksijeni sağlar.")),

    V("N", 1, "ev", "Dumanlı Dondurma",
      "Bir dondurmacı, dondurma karışımının üzerine bir termos kaptan buz gibi bir sıvı döküyor. Kaptan beyaz bir sis "
      "yükseliyor ve dondurma birkaç saniyede donuyor. Müşteriler 'Bu sıvı ne, yenir mi?' diye soruyor. Görevin: sıvının hangi "
      "elementin sıvı hâli olduğunu bulmak.",
      [("fiziksel", "Sıvının davranışı", "Sıvı, karışıma dökülünce hemen kaynayıp gaza dönüşüyor. Kaynama sıcaklığı −196 °C civarında."),
       ("fiziksel", "Gazın kimliği", "Kaynayan sıvıdan çıkan gaz renksiz ve kokusuz; soluduğumuz havanın yaklaşık %78'ini oluşturuyor.")],
      gozlem=S("Kaptan yükselen beyaz sis (K1, K2) neden oluşur?",
               "Çok soğuk gaz, havadaki su buharını soğutup minik damlacıklara dönüştürür.",
               Y("Sis, gazın kendi rengidir.", "veri", "Gaz renksizdir (K2); görülen beyazlık başka bir şeyden kaynaklanıyor.", "K2"),
               Y("Sıvı yanıyor ve duman çıkarıyor.", "iliski", "Ortada alev yok; sıvı yanmıyor, kaynıyor (K1). Sis bir duman değil.", "K1"),
               ipucu="Kışın nefesimiz neden beyaz görünür?",
               aciklama="Sıvının kendisi renksizdir. Çok soğuk gaz, çevredeki havada bulunan su buharını yoğunlaştırır; beyaz sis bu minik su damlacıklarıdır."),
      kullanim=S("Dondurmacı neden bu elementin sıvı hâlini kullanıyor?",
                 "Çok soğuk olduğu için dondurmayı çok hızlı dondurur; buharlaşıp gittiği için de dondurmada kalmaz",
                 Y("Dondurmaya tat ve renk kattığı için", "veri", "Gaz renksiz ve kokusuz (K2); dondurmada da kalmıyor, buharlaşıp gidiyor.", "K2"),
                 Y("Dondurmanın besin değerini artırdığı için", "kanitsiz", "Bu gazın dondurmaya besin kattığını gösteren bir kanıt yok; gaz tamamen buharlaşıyor.", "K1"),
                 Y("Yanıcı olduğu için karışımı ısıtıp kıvamlandırdığı için", "veri", "Sıvı karışımı ısıtmıyor, −196 °C'de dondurur (K1).", "K1"),
                 ipucu="K1'deki kaynama sıcaklığına bak.",
                 aciklama="Sıvı azot −196 °C'de kaynar. Dondurmayı o kadar hızlı dondurur ki iri buz kristalleri oluşamaz; dondurma pürüzsüz olur. Azot buharlaşıp havaya karışır. Yine de çok soğuk olduğu için yalnızca eğitimli kişiler kullanmalı; sıvı hâldeyken yutulursa ciddi yaralanmalara yol açabilir.")),

    V("Fe", 1, "uzay", "Kızıl Gezegen",
      "Teleskopla Mars'a bakan bir öğrenci 'Neden kırmızı?' diye soruyor. Mars'a gönderilen araçlar, yüzeydeki tozun "
      "büyük bölümünün bir metalin oksidi olduğunu ölçtü. Görevin: Mars'a rengini veren metali bulmak.",
      [("fiziksel", "Mars'ın tozu", "Mars yüzeyindeki toz kırmızımsı kahverengi. Ölçümler, tozun önemli bir bölümünün bir metalin oksijenle oluşturduğu bileşik olduğunu gösteriyor."),
       ("kimyasal", "Dünya'daki benzeri", "Aynı metalden yapılmış bir çivi nemli havada bırakılınca birkaç gün içinde kırmızımsı kahverengi bir tabakayla kaplanıyor.")],
      gozlem=S("Dünya'daki çivinin kırmızımsı kahverengi tabakayla kaplanması (K2) neyi gösterir?",
               "Metal nem ve oksijenle tepkimeye girip pas oluşturdu.",
               Y("Çivi boyandı.", "kanitsiz", "Çiviye boya sürüldüğüne dair bir kanıt yok; renk kendiliğinden oluştu.", "K2"),
               Y("Metal eriyip rengi değişti.", "iliski", "Nemli havada bir metal erimez. Renk değişimi kimyasal bir tepkimeden kaynaklanıyor.", "K2"),
               ipucu="Pas nasıl oluşur?",
               aciklama="Bazı metaller nem ve oksijenle tepkimeye girerek kırmızımsı kahverengi bir oksit, yani pas oluşturur."),
      kullanim=S("Mars'ın kırmızı görünmesinin nedeni hangisidir?",
                 "Yüzeydeki tozun içinde bol miktarda pas, yani demir oksit bulunması",
                 Y("Mars'ın Güneş'e çok yakın olup kızarması", "veri", "Mars, Güneş'e Dünya'dan daha uzaktır; renk sıcaklıktan değil, tozun bileşiminden geliyor (K1).", "K1"),
                 Y("Mars'ta sıvı demir göllerinin bulunması", "kanitsiz", "Ölçümler tozda demirin oksidini buldu (K1); sıvı demir gölü gösteren bir kanıt yok.", "K1"),
                 Y("Kırmızı rengin Mars atmosferindeki oksijenden gelmesi", "iliski", "Oksijen gazı renksizdir. Kırmızı renk, oksijenin demirle oluşturduğu bileşikten gelir.", "K1"),
                 ipucu="K1 ve K2'yi birlikte düşün: Dünya'da aynı renk nasıl oluşuyordu?",
                 aciklama="Mars'ın yüzeyini örten toz demir oksit (pas) bakımından zengindir. Pasın kırmızımsı rengi gezegene 'Kızıl Gezegen' adını verdirmiştir.")),

    V("Na", 1, "sanayi", "Sarı Sokak Lambaları",
      "Eski bir mahallede gece sokak lambaları turuncu-sarı bir ışık saçıyor. Bu ışık altında kırmızı bir araba bile gri "
      "görünüyor. Belediye bu lambaların çok az elektrikle çok ışık verdiğini söylüyor. Görevin: lambanın içinde ışık "
      "veren elementi bulmak.",
      [("fiziksel", "Lambanın ışığı", "Lamba yalnızca tek bir renkte, turuncu-sarı ışık veriyor. Bu yüzden altındaki nesnelerin renkleri ayırt edilemiyor."),
       ("deney", "Mutfakta alev testi", "Ocaktaki alevin üzerine bir tutam sofra tuzu serpilince alev de aynı turuncu-sarı renkte parladı.")],
      gozlem=S("Sofra tuzunun alevi aynı sarı renge boyaması (K2) neyi gösterir?",
               "Lambadaki element sofra tuzunda da bulunan bir elementtir.",
               Y("Lambanın içinde sofra tuzu yanıyor.", "kanitsiz", "Aynı rengi vermeleri, aynı elementi içerdiklerini gösterir; lambanın içinde tuz olduğunu göstermez.", "K2"),
               Y("Bütün tuzlar alevi sarıya boyar.", "kanitsiz", "Tek bir deney bütün tuzlar hakkında sonuç çıkarmaya yetmez. Farklı elementler alevi farklı renklere boyar.", "K2"),
               ipucu="Her element alevi kendine özgü bir renge boyar.",
               aciklama="Alev testinde her element kendine özgü bir renk verir. Sofra tuzundaki metal, alevi turuncu-sarıya boyar."),
      kullanim=S("Bu lambalar sokak aydınlatmasında neden kullanılıyordu?",
                 "Sodyum buharı elektrikle uyarılınca çok az enerjiyle çok parlak sarı ışık verdiği için",
                 Y("Renkleri olduğu gibi gösterdiği için", "veri", "Lambanın altında renkler ayırt edilemiyor (K1).", "K1"),
                 Y("Hiç elektrik harcamadığı için", "veri", "Lamba elektrikle çalışıyor; yalnızca harcadığı elektriğe göre çok ışık veriyor.", "K1"),
                 Y("Sodyum metali havada parladığı için", "iliski", "Işık, elektrik akımının sodyum buharını uyarmasından gelir; metalin parlaklığından değil.", "K1"),
                 ipucu="Belediye bu lambaları neden seviyordu?",
                 aciklama="Düşük basınçlı sodyum lambaları, elektrik akımı sodyum buharından geçerken tek renkte turuncu-sarı ışık verir. En verimli lambalar arasındaydı; ancak renkleri gösteremedikleri için bugün yerlerini LED'lere bırakıyorlar.")),

    V("Ca", 1, "cevre", "Pamukkale'nin Beyaz Basamakları",
      "Pamukkale'de sıcak su kaynaklarından çıkan su, yamaçtan aşağı akarken bembeyaz taş basamaklar oluşturuyor. Bir turist "
      "'Bu beyazlık tuz mu, kar mı?' diye soruyor. Görevin: bu beyaz taşın içindeki metalik elementi bulmak.",
      [("deney", "Sirke testi", "Basamaklardan düşen küçük bir taş parçasının üzerine sirke damlatıldı; taş köpürerek gaz çıkardı."),
       ("fiziksel", "Kaynak suyu", "Kaynaktan çıkan su ılık ve içinde çözünmüş mineraller var. Su havayla temas edip soğudukça içindeki gazı kaybediyor ve taş çökeltiyor.")],
      gozlem=S("Taşın sirkeyle köpürmesi (K1) neyi gösterir?",
               "Taş, asitle karşılaşınca gaz (karbondioksit) çıkaran bir karbonat içeriyor.",
               Y("Taş sofra tuzudur.", "veri", "Sofra tuzu sirkeyle köpürmez; gaz çıkışı karbonatların özelliğidir.", "K1"),
               Y("Taş erimekte olan kardır.", "veri", "Kar sirkeyle köpürmez ve sıcak suyun yanında kalamaz.", "K2"),
               ipucu="Kireç taşı sirkeyle karşılaşınca ne olur?",
               aciklama="Karbonat içeren taşlar (örneğin kireç taşı) asitlerle tepkimeye girerek karbondioksit gazı çıkarır; köpürme bu gazdır."),
      kullanim=S("Pamukkale'deki beyaz basamaklar nasıl oluşur?",
                 "Sudaki çözünmüş kalsiyum bileşiği, su karbondioksit kaybedince kalsiyum karbonat olarak çöker",
                 Y("Suyun donup buz tutmasıyla", "veri", "Kaynak suyu ılıktır (K2); basamaklar buzdan değil taştan.", "K2"),
                 Y("Sudaki sofra tuzunun kurumasıyla", "veri", "Taş sirkeyle köpürüyor (K1); sofra tuzu köpürmez.", "K1"),
                 Y("İnsanların taşları beyaza boyamasıyla", "kanitsiz", "Basamakların doğal olarak, sudan çökelerek oluştuğu gözleniyor (K2).", "K2"),
                 ipucu="K2: Su soğudukça ve gaz kaybettikçe ne oluyor?",
                 aciklama="Kaynak suyu kalsiyum bikarbonat içerir. Su yüzeye çıkıp karbondioksit kaybedince kalsiyum karbonat çöker ve traverten denilen beyaz taşı oluşturur. Pamukkale, UNESCO Dünya Mirası Listesi'ndedir."),
      kaynak=["UNESCO Dünya Mirası Merkezi: Hierapolis-Pamukkale — https://whc.unesco.org/en/list/485"]),

    V("Si", 1, "enerji", "Çatıdaki Güneş Paneli",
      "Bir okulun çatısına koyu mavi güneş panelleri yerleştirildi. Paneller güneşli günlerde okulun elektriğinin bir "
      "bölümünü karşılıyor. Panelleri yapan firma, hücrelerin 'kumda bol bulunan bir elementten' yapıldığını söylüyor. "
      "Görevin: bu elementi bulmak.",
      [("fiziksel", "Panelin hücreleri", "Her hücre ince, koyu mavi-gri, parlak bir plakadan yapılmış. Güneş ışığı vurunca hücreden elektrik akımı alınıyor."),
       ("kimyasal", "Hammadde", "Hücrelerin elementi, kumun ve kuvarsın ana bileşeninde oksijenle birlikte bulunuyor. Yer kabuğunda oksijenden sonra en bol element.")],
      gozlem=S("Güneş ışığı vurunca hücreden elektrik akımı alınması (K1) neyi gösterir?",
               "Hücrenin malzemesi ışığın enerjisini elektrik enerjisine dönüştürebiliyor.",
               Y("Hücre güneş ışığını depolayıp geceleri yayıyor.", "kanitsiz", "Kanıtlar yalnızca ışık vurduğunda akım alındığını söylüyor; depolama gösteren bir kanıt yok.", "K1"),
               Y("Hücre ısındığı için yanıyor ve enerji veriyor.", "iliski", "Hücrede yanma yok; ışık doğrudan elektriğe dönüşüyor.", "K1"),
               ipucu="Panelin işi neydi?",
               aciklama="Güneş hücresinde ışık, malzemedeki elektronları serbest bırakır ve bu elektronlar akım oluşturur. Buna fotovoltaik etki denir."),
      kullanim=S("Silisyum güneş panellerinde neden kullanılır?",
                 "Yarı iletken olduğu için ışığı soğurup elektrik akımı oluşturabilir ve yer kabuğunda çok bol bulunur",
                 Y("Elektriği hiç iletmediği için", "iliski", "Hiç iletmeyen bir madde akım üretemezdi; silisyum bir yarı iletkendir.", "K1"),
                 Y("Metal olduğu ve paslanmadığı için", "veri", "Silisyum metal değil, yarı metaldir. Paneldeki görevi paslanmamak değil, ışığı elektriğe dönüştürmek.", "K1"),
                 Y("Çok ağır olduğu için panelleri rüzgâra karşı sağlam tuttuğu için", "iliski", "Panelin ağırlığı elektrik üretimini açıklamaz; hücrelerin işi ışıktan elektrik üretmek.", "K1"),
                 ipucu="K1 ve K2'deki iki özelliği birleştir: ne yapabiliyor ve ne kadar bol?",
                 aciklama="Silisyum bir yarı iletkendir: ışığın enerjisiyle serbest kalan elektronlar akım oluşturur. Kumdaki silisyum dioksitten elde edildiği için hammaddesi boldur. Güneş panellerinin büyük çoğunluğu silisyumdan yapılır.")),

    V("Mg", 1, "tarih", "Fotoğrafçının Göz Kamaştıran Işığı",
      "Bir müzeye 1880'lerden kalma bir fotoğraf makinesi ve yanında kullanılmamış bir paket 'flaş tozu' bağışlandı. O "
      "dönemde fotoğrafçılar karanlık ortamda bu tozu yakarak çok kısa ama çok parlak bir ışık elde ederdi. Görevin: "
      "tozdaki metalin hangi element olduğunu bulmak.",
      [("deney", "Tozun yanması", "Az miktarda toz yakıldığında göz kamaştıran beyaz bir ışık çıktı; geriye beyaz bir toz kaldı."),
       ("fiziksel", "Paketteki şerit", "Paketteki metal şerit gümüşi ve parlak; elde tutulduğunda şaşırtıcı derecede hafif.")],
      gozlem=S("Yanmadan sonra geriye beyaz bir toz kalması (K1) neyi gösterir?",
               "Metal havadaki oksijenle birleşip yeni bir madde (oksit) oluşturdu.",
               Y("Metal yanınca tamamen yok oldu.", "veri", "Geriye beyaz bir toz kaldı; madde yok olmadı, başka bir maddeye dönüştü (K1).", "K1"),
               Y("Beyaz toz metalin erimiş hâlidir.", "iliski", "Erime fiziksel bir değişimdir; eriyen metal gümüşi kalırdı. Renk ve görünüş değiştiğine göre yeni bir madde oluştu.", "K1"),
               ipucu="Yanma, bir maddenin oksijenle tepkimesidir.",
               aciklama="Yanma bir kimyasal tepkimedir: metal oksijenle birleşip beyaz bir oksit oluşturur."),
      kullanim=S("Bu metal 1800'lerde flaş tozunda neden kullanılıyordu?",
                 "Yanarken çok kısa sürede çok parlak beyaz ışık verdiği için",
                 Y("Çok ağır bir metal olduğu için", "veri", "Paketteki şerit elde şaşırtıcı derecede hafif (K2); üstelik ağırlığın ışıkla ilgisi yok.", "K2"),
                 Y("Elektriği iyi ilettiği için", "iliski", "Flaş tozu elektrikle değil, yanarak ışık verir; iletkenlik bu kullanımın nedeni değildir.", "K1"),
                 Y("Hiçbir maddeyle tepkimeye girmediği için", "veri", "Toz yandı ve beyaz bir toza dönüştü (K1); yani oksijenle tepkimeye girdi.", "K1"),
                 ipucu="Fotoğrafçının karanlıkta neye ihtiyacı vardı? K1'deki gözleme bak.",
                 aciklama="Magnezyum havadaki oksijenle hızla birleşirken göz kamaştıran beyaz bir ışık verir. Bu yüzden eski flaş tozlarında kullanıldı; bugün de işaret fişeklerinde ve havai fişeklerde beyaz ışık için kullanılır.")),

    V("K", 1, "saglik", "Muzdaki Radyoaktiflik",
      "Bir fen şenliğinde öğrenciler radyasyon ölçen bir Geiger sayacını bir muz yığınına yaklaştırdı. Sayaç, odanın normal "
      "değerinden biraz daha sık tıkırdadı. Bir veli korktu: 'Muz radyoaktif mi? Çocuklarım yememeli mi?' Görevin: muzdaki "
      "bu hafif radyasyonun hangi elementten geldiğini bulmak.",
      [("deney", "Geiger sayacı", "Muz yığınının yanında sayaç biraz daha sık tıkırdıyor; ölçülen radyasyon çok düşük."),
       ("kimyasal", "Besin etiketi", "Muz, kaslarımızın ve kalbimizin çalışması için gerekli olan bir mineral bakımından zengin. Bu elementin atomlarının yalnızca çok küçük bir bölümü (yaklaşık on binde biri) radyoaktif.")],
      gozlem=S("Sayacın muzun yanında daha sık tıkırdaması (K1) neyi gösterir?",
               "Muzdaki bazı atomlar radyasyon yayıyor.",
               Y("Muz çürümüş ve bozulmuştur.", "iliski", "Çürüme radyasyon yaymaz; sayaç radyasyonu ölçer.", "K1"),
               Y("Muz tehlikeli derecede radyoaktiftir.", "veri", "Ölçülen radyasyon çok düşük (K1); tehlikeli bir düzey gösteren bir kanıt yok.", "K1"),
               ipucu="Geiger sayacı neyi ölçer?",
               aciklama="Geiger sayacı radyasyonu ölçer. Tıkırtının biraz artması muzda radyasyon yayan atomlar olduğunu gösterir; ama ölçülen değer çok düşüktür."),
      kullanim=S("Muz radyasyon yaydığı hâlde onu yemek neden güvenlidir?",
                 "Potasyum atomlarının yalnızca çok küçük bir bölümü radyoaktiftir ve muzdan alınan radyasyon çok düşüktür",
                 Y("Potasyum hiç radyoaktif değildir; sayaç bozuktur", "veri", "Etikette bu elementin atomlarının bir bölümünün radyoaktif olduğu yazıyor (K2).", "K2"),
                 Y("Muz pişirilince radyasyonu yok olur", "kanitsiz", "Pişirmek atom çekirdeğini değiştirmez; bu iddiayı destekleyen bir kanıt yok.", "K2"),
                 Y("Radyasyon yalnızca muzun kabuğunda olduğu için", "kanitsiz", "Kanıtlarda radyasyonun yalnızca kabukta olduğuna dair bir bilgi yok.", "K1"),
                 ipucu="K2'de radyoaktif atomların oranı yazıyor.",
                 aciklama="Potasyumun doğal izotoplarından biri olan potasyum-40 radyoaktiftir, ama potasyum atomlarının yalnızca yaklaşık %0,012'si bu izotoptur. Vücudumuz potasyum miktarını sabit tuttuğu için muz yemek radyasyon dozunu fark edilir biçimde artırmaz.")),

    V("S", 1, "cevre", "Yanardağın Mavi Alevi",
      "Endonezya'daki Ijen yanardağında geceleri kraterde mavi alevler görülüyor. Gündüz aynı yerde, gaz çıkan çatlakların "
      "çevresinde sarı kristaller birikiyor. Madenciler bu sarı maddeyi toplayıp sırtlarında taşıyor. Görevin: sarı "
      "maddenin hangi element olduğunu bulmak.",
      [("fiziksel", "Sarı kristaller", "Çatlakların çevresinde biriken madde parlak sarı, kırılgan bir katı. Saf hâlde bir element olarak doğada bulunuyor."),
       ("deney", "Yakma deneyi", "Sarı katının küçük bir parçası yakıldığında mavi bir alevle yandı ve keskin, boğucu kokulu bir gaz çıktı.")],
      gozlem=S("Sarı katının yakılınca mavi alevle yanması (K2) neyi açıklar?",
               "Kraterdeki mavi alevler bu sarı maddenin yanmasından kaynaklanıyor olabilir.",
               Y("Mavi alev, yanardağın lavının rengidir.", "veri", "Lav kırmızı-turuncu renkte parlar; mavi renk sarı katı yanınca görüldü (K2).", "K2"),
               Y("Sarı madde yanmaz bir maddedir.", "veri", "Sarı madde yakıldığında yandı (K2).", "K2"),
               ipucu="Deneyde görülen alev rengi ile kraterdeki alev rengini karşılaştır.",
               aciklama="Bu sarı madde yanarken mavi alev verir ve keskin kokulu bir gaz oluşturur. Ijen'deki mavi alevler de sıcak gazlarla gelen bu maddenin yanmasından kaynaklanır."),
      kullanim=S("Ijen'deki mavi alevlerin nedeni hangisidir?",
                 "Çatlaklardan çıkan sıcak gazlardaki kükürdün havadaki oksijenle yanması",
                 Y("Kraterde mavi renkli bir sıvı metal bulunması", "kanitsiz", "Kanıtlar kraterde sarı bir ametal buldu (K1); mavi sıvı metale dair bir kanıt yok.", "K1"),
                 Y("Kükürdün kendisinin mavi renkte olması", "veri", "Kükürt sarı renklidir (K1); mavi olan, yanarken çıkan alevdir.", "K1"),
                 Y("Ay ışığının sarı kristallere yansıması", "iliski", "Yansıyan ışık alev oluşturmaz; deneyde mavi alev maddenin yanmasıyla görüldü (K2).", "K2"),
                 ipucu="K2'deki deneyle karşılaştır.",
                 aciklama="Ijen'de çatlaklardan çıkan sıcak gazlar kükürt içerir. Kükürt havadaki oksijenle yanınca mavi alevler oluşur. Bu yanma keskin kokulu, zehirli kükürt dioksit gazı da üretir; bu yüzden madenciler sağlık riski altında çalışır."),
      kaynak=["Vikipedi (İngilizce): Ijen — https://en.wikipedia.org/wiki/Ijen"]),

    V("Cl", 1, "saglik", "Musluk Suyundaki Koku",
      "Bir öğrenci, evdeki musluk suyunun hafifçe 'havuz gibi' koktuğunu fark etti. Belediyenin su arıtma tesisi, şebekeye "
      "verilen suya mikropları öldürmesi için az miktarda bir madde eklediğini açıklıyor. Görevin: bu maddenin ana "
      "elementini bulmak.",
      [("kimyasal", "Arıtma tesisi raporu", "Suya eklenen madde, mikropları öldüren güçlü bir dezenfektan. Saf hâli sarımsı yeşil, zehirli bir gaz."),
       ("kimyasal", "Mutfaktaki akrabası", "Aynı element sofra tuzunun da yapısında, sodyumla birlikte bulunuyor.")],
      gozlem=S("Arıtma tesisinin suya bu maddeyi az miktarda eklemesinin nedeni nedir (K1)?",
               "Madde mikropları öldürüyor; ama saf hâli zehirli olduğu için çok az kullanılıyor.",
               Y("Suyun tadını tatlandırmak için", "kanitsiz", "Raporda maddenin görevi mikropları öldürmek olarak yazıyor (K1).", "K1"),
               Y("Suyu renklendirip temiz görünmesini sağlamak için", "veri", "Musluk suyu renksiz; eklenen madde suyu renklendirmiyor.", "K1"),
               ipucu="K1'de maddenin görevi ve saf hâli anlatılıyor.",
               aciklama="Bu element ve bileşikleri mikropları öldürür. Saf hâli zehirli bir gaz olduğu için suya çok düşük ve denetlenen miktarlarda eklenir."),
      kullanim=S("İçme suyuna klor eklenmesinin en önemli nedeni hangisidir?",
                 "Sudaki bakteri gibi mikropları öldürerek su yoluyla bulaşan hastalıkları önlemek",
                 Y("Suyu sertleştirip kireç oluşmasını önlemek", "kanitsiz", "Raporda maddenin görevi mikrop öldürmek olarak geçiyor (K1).", "K1"),
                 Y("Suya sofra tuzu kazandırmak", "iliski", "Klor sofra tuzunda da bulunur (K2) ama suya tuz katmak için değil, dezenfeksiyon için eklenir.", "K2"),
                 Y("Klor sarımsı yeşil renkli olduğu için suyu güzel göstermek", "veri", "Saf klor gazı sarımsı yeşildir ama sudaki az miktar suyu renklendirmez; amaç dezenfeksiyondur.", "K1"),
                 ipucu="K1: Madde ne yapıyor?",
                 aciklama="1900'lerin başında içme suyunun klorlanmaya başlanması kolera ve tifo gibi su yoluyla bulaşan hastalıkları büyük ölçüde azalttı. Klor, mikropların hücre yapısını bozarak onları öldürür.")),

    V("P", 1, "ev", "Kibrit Kutusunun Yan Yüzü",
      "Bir öğrenci kibriti kutunun yanındaki koyu kırmızı-kahverengi şeride sürtünce kibrit hemen tutuştu. Aynı kibriti "
      "bir taşa sürtünce hiçbir şey olmadı. Görevin: şeritteki tutuşmayı başlatan elementi bulmak.",
      [("deney", "Sürtünme deneyi", "Kibrit yalnızca kutunun yan yüzündeki şeride sürtülünce tutuşuyor; başka yüzeylerde tutuşmuyor."),
       ("kimyasal", "Şeridin içeriği", "Şeritte kırmızı renkli bir toz var. Bu elementin beyaz renkli başka bir hâli de vardır; o hâli havada kendiliğinden tutuşabilir ve karanlıkta parlar.")],
      gozlem=S("Kibritin yalnızca kutunun şeridinde tutuşması (K1) neyi gösterir?",
               "Tutuşmayı başlatan madde kibritin başında değil, kutunun şeridinde.",
               Y("Kibrit yalnızca pürüzlü yüzeylerde tutuşur.", "veri", "Taş da pürüzlüdür ama kibrit taşta tutuşmadı (K1).", "K1"),
               Y("Kibritin başı ıslak olduğu için başka yerde tutuşmuyor.", "kanitsiz", "Kibritin ıslak olduğuna dair bir kanıt yok; aynı kibrit şeritte hemen tutuştu.", "K1"),
               ipucu="Aynı kibrit bir yerde tutuşuyor, bir yerde tutuşmuyor. Fark nerede?",
               aciklama="Güvenlik kibritlerinde tutuşmayı başlatan kırmızı madde kutunun şeridindedir. Bu yüzden kibrit yalnızca o şeride sürtülünce tutuşur."),
      kullanim=S("Kibrit kutularında fosforun beyaz hâli yerine kırmızı hâli neden kullanılır?",
                 "Kırmızı fosfor kendiliğinden tutuşmadığı için güvenlidir; sürtünme ısısıyla ancak kibrit başı değince tutuşmayı başlatır",
                 Y("Kırmızı fosfor daha parlak yandığı için", "kanitsiz", "Seçimin nedeni parlaklık değil, güvenlik: beyaz hâli havada kendiliğinden tutuşabilir (K2).", "K2"),
                 Y("Beyaz fosfor hiç yanmadığı için", "veri", "Beyaz fosfor havada kendiliğinden tutuşabilir (K2); yani çok kolay yanar.", "K2"),
                 Y("Kırmızı renk kutuyu daha güzel gösterdiği için", "iliski", "Renk bir sonuçtur, seçim nedeni değil. Asıl neden iki hâlin tepkimeye yatkınlığındaki fark.", "K2"),
                 ipucu="K2'de iki hâlin farkı yazıyor.",
                 aciklama="Beyaz fosfor havada kendiliğinden tutuşabilen tehlikeli bir maddedir; 1800'lerde kibrit fabrikası işçilerini zehirlemişti. Güvenlik kibritlerinde kutunun şeridindeki kırmızı fosfor kullanılır: sürtünme ısısı küçük bir miktarını tutuşturur ve kibrit başını yakar.")),
]
