# -*- coding: utf-8 -*-
"""Seviye 1 (Gözlem) — yeni vakalar, ikinci bölüm."""
from sablon import S, V, Y

VAKALAR = [
    V("C", 1, "tarih", "Buzuldaki Adamın Yaşı",
      "1991'de Alpler'de iki dağcı, eriyen bir buzulun içinde bir insan bedeni buldu. Önce yakın zamanda kaybolmuş bir "
      "dağcı sanıldı. Bilim insanları, bedenin ve yanındaki eşyaların yaşını, bütün canlıların yapısında bulunan bir "
      "elementin radyoaktif bir izotopunu ölçerek belirledi: yaklaşık 5300 yıl. Görevin: bu elementi bulmak.",
      [("kimyasal", "Canlıların ortak elementi", "Bu element bütün canlıların yapısındaki moleküllerin (proteinler, yağlar, şekerler) iskeletini oluşturur."),
       ("deney", "Radyoaktif saat", "Canlılar yaşarken bu elementin radyoaktif bir izotopunu çevrelerinden alır. Canlı ölünce bu izotopun miktarı yaklaşık 5700 yılda yarıya iner.")],
      gozlem=S("Bedendeki radyoaktif izotopun azalmış olması (K2) neyi gösterir?",
               "Ölümden bu yana uzun bir zaman geçmiş; azalma miktarı geçen süreyi gösterir.",
               Y("Kişi ölmeden önce radyasyona maruz kalmış.", "iliski", "İzotopun azalması, canlı öldükten sonra kendiliğinden olur; radyasyona maruz kalmayla ilgili değil (K2).", "K2"),
               Y("İzotop buzun içinde donup kaybolmuş.", "kanitsiz", "Radyoaktif bozunma sıcaklıktan etkilenmez; donma izotopu yok etmez.", "K2"),
               ipucu="K2: Canlı ölünce izotopa ne oluyor?",
               aciklama="Canlı ölünce çevresinden yeni izotop almaz; içindeki radyoaktif izotop bilinen bir hızla bozunur. Kalan miktar ölçülerek ölümden bu yana geçen süre hesaplanır."),
      kullanim=S("Bu yöntem neden yalnızca bir zamanlar canlı olan şeylerin yaşını bulmakta kullanılır?",
                 "Çünkü bu izotopu yalnızca canlılar yaşarken çevrelerinden alır; ölünce alım durur ve 'saat' işlemeye başlar",
                 Y("Çünkü taşlar ve metaller hiç karbon içermez", "kanitsiz", "Bazı taşlar (örneğin kireç taşı) karbon içerir. Yöntemin anahtarı, izotopun canlıyken alınıp ölünce alınmamasıdır (K2).", "K2"),
                 Y("Çünkü canlılar öldükten sonra izotop çoğalır", "veri", "İzotop ölünce çoğalmaz; yaklaşık 5700 yılda yarıya iner (K2).", "K2"),
                 Y("Çünkü bu element yalnızca buzda korunur", "iliski", "Buz yalnızca bedeni korumuştur; yöntem buzdan bağımsız olarak bütün canlı kalıntılarda çalışır.", "K1"),
                 ipucu="K2'yi yeniden oku: izotopu kimler, ne zaman alıyor?",
                 aciklama="Radyokarbon (karbon-14) yöntemi bütün canlıların karbon içermesine dayanır. Canlı yaşarken havadaki karbondioksitten ya da besinlerden karbon-14 alır; ölünce alım durur ve karbon-14 bozunarak azalır. Buzul Adam Ötzi'nin yaklaşık 5300 yıl önce yaşadığı böyle belirlendi."),
      kaynak=["Güney Tirol Arkeoloji Müzesi: Ötzi — https://www.iceman.it/en/"]),

    V("Ti", 1, "saglik", "Güneş Kremindeki Beyaz",
      "Yaz tatilinde bir öğrenci, sürdüğü güneş kreminin cildinde beyaz bir tabaka bıraktığını fark etti. Kremin "
      "içindekiler listesinde '... dioksit' yazıyor; ilk kelime silinmiş. Görevin: kremin içindeki bu oksidin metalini bulmak.",
      [("fiziksel", "Beyaz tabaka", "Krem cilde sürülünce beyaz bir iz bırakıyor. İçindeki oksit, beyaz duvar boyalarında da kullanılan, çok parlak beyaz bir toz."),
       ("kimyasal", "Oksidin özellikleri", "Bu oksit suda çözünmüyor, zehirsiz ve güneş ışığındaki morötesi (UV) ışınları soğurup saçıyor.")],
      gozlem=S("Kremin ciltte beyaz iz bırakması (K1) neyi gösterir?",
               "Kremde ışığı güçlü biçimde saçan beyaz bir toz var.",
               Y("Krem cildi beyazlatıyor.", "kanitsiz", "Beyazlık kremin içindeki tozdan geliyor; cildin rengini değiştirdiğine dair bir kanıt yok.", "K1"),
               Y("Kremin içinde tuz var.", "kanitsiz", "Beyaz renk tek başına tuz olduğunu göstermez; kanıt bu oksidin boyalarda kullanılan beyaz bir toz olduğunu söylüyor (K1).", "K1"),
               ipucu="Beyaz duvar boyasıyla güneş kreminin ortak noktası ne?",
               aciklama="Bu oksidin tozu ışığı güçlü biçimde saçtığı için bembeyaz görünür; boyalarda, kâğıtlarda ve güneş kremlerinde bu yüzden kullanılır."),
      kullanim=S("Titanyum dioksit güneş kremlerinde neden kullanılır?",
                 "Morötesi ışınları soğurup saçarak cildi korur ve zehirsizdir",
                 Y("Cildi serinletip terlemeyi önlediği için", "kanitsiz", "Kanıtlarda böyle bir özellik yok; oksidin özelliği UV ışınlarını soğurup saçması (K2).", "K2"),
                 Y("Suda çözünüp cilde işlediği için", "veri", "Bu oksit suda çözünmüyor (K2).", "K2"),
                 Y("Titanyum metali parlak olduğu için", "iliski", "Kremde metal değil, oksidi var. Koruyucu özellik oksidin UV ışınlarını soğurmasından gelir.", "K2"),
                 ipucu="K2'de oksidin ışığa ne yaptığı yazıyor.",
                 aciklama="Titanyum dioksit parçacıkları güneşin morötesi ışınlarını soğurur ve saçar; böylece ışınlar cilde ulaşmadan durdurulur. Bu oksit aynı zamanda dünyanın en çok kullanılan beyaz boya maddesidir.")),

    V("Cr", 1, "ev", "Paslanmayan Çatal",
      "Bir lokantanın çatallarının arkasında '18/10' yazıyor. Çatallar yıllardır bulaşık makinesinde yıkandığı hâlde hiç "
      "paslanmamış. Görevin: bu çeliği paslanmaz yapan ve ilk sayının gösterdiği metali bulmak.",
      [("alasim", "Çatalın etiketi", "'18/10', çeliğin içinde ağırlıkça %18 bir metal ve %10 nikel bulunduğunu gösteriyor. Geri kalanı demir."),
       ("kimyasal", "Görünmez kalkan", "Bu metal, havadaki oksijenle çatalın yüzeyinde gözle görülmeyen çok ince bir oksit tabakası oluşturuyor. Tabaka çizilse bile kendini yeniliyor.")],
      gozlem=S("'18/10' etiketi (K1) çatal hakkında neyi gösterir?",
               "Çatal saf bir metal değil; birkaç metalin karışımından oluşan bir alaşım.",
               Y("Çatal 18 yıl önce, 10. ayda üretilmiş.", "veri", "K1, sayıların çelikteki metallerin yüzdesini gösterdiğini söylüyor.", "K1"),
               Y("Çatal tamamen nikelden yapılmış.", "veri", "Çatalın yalnızca %10'u nikel; geri kalanı başka metaller (K1).", "K1"),
               ipucu="K1'de sayıların ne anlama geldiği yazıyor.",
               aciklama="Alaşım, bir metalin başka metallerle (ya da elementlerle) karıştırılmasıyla elde edilir. 18/10 çelikte %18 oranında aranan metal ve %10 oranında nikel vardır."),
      kullanim=S("Krom çeliği neden paslanmaz yapar?",
                 "Yüzeyde ince, sıkı ve kendini yenileyen bir krom oksit tabakası oluşturup demirin oksijen ve suyla temasını keser",
                 Y("Kromun mıknatısa çekilmesi pası iter", "iliski", "Mıknatıslık paslanmayı engellemez; koruma yüzeydeki oksit tabakasından gelir (K2).", "K2"),
                 Y("Krom demirden çok daha yumuşak olduğu için", "iliski", "Yumuşaklık paslanmayla ilgili değil; krom aslında çeliği sertleştirir. Koruma oksit tabakasından gelir.", "K2"),
                 Y("Krom hiç oksijenle tepkimeye girmediği için", "veri", "Krom oksijenle tepkimeye girer; koruyucu tabaka zaten bu tepkimeyle oluşan oksittir (K2).", "K2"),
                 ipucu="K2'deki 'görünmez kalkan' nasıl oluşuyor?",
                 aciklama="Paslanmaz çelikte en az %10,5 krom bulunur. Krom, yüzeyde çok ince ama sıkı bir krom oksit tabakası oluşturur; bu tabaka demiri su ve oksijenden korur ve çizilince kendini yeniler.")),

    V("Zn", 1, "sanayi", "Çizilse de Paslanmayan Tel",
      "Bir bahçenin tel örgüsü yıllardır yağmur altında durduğu hâlde paslanmamış. Hatta bir yerinde tel çizilip içi "
      "görünmesine rağmen orada da pas yok. Üretici telin 'galvanizli', yani başka bir metalle kaplanmış çelik olduğunu "
      "söylüyor. Görevin: kaplama metalini bulmak.",
      [("fiziksel", "Kaplamanın görünüşü", "Telin yüzeyi mat gri ve üzerinde kristal desenler var. Kaplamanın altında çelik bulunuyor."),
       ("kimyasal", "Feda edilen metal", "Kaplama metali demirden daha kolay tepkimeye giriyor. Çizik yerinde bile önce kaplama aşınıyor, demir korunuyor.")],
      gozlem=S("Çizik yerinde bile pas oluşmaması (K2) neyi gösterir?",
               "Kaplama metali demirin yerine kendisi aşınarak demiri koruyor.",
               Y("Çelik hiçbir zaman paslanmaz.", "veri", "Kaplamasız çelik paslanır; korumayı kaplama metali sağlıyor (K2).", "K2"),
               Y("Çizikten içeri su giremez.", "kanitsiz", "Çizik telin içini açığa çıkardı; suyun giremediğine dair bir kanıt yok.", "K2"),
               ipucu="K2: Hangi metal önce aşınıyor?",
               aciklama="Kaplama metali demirden daha etkindir; çizik olsa bile önce kaplama aşınır. Bu yüzden ona 'feda edilen metal' denir."),
      kullanim=S("Çeliği paslanmaya karşı korumak için neden çinko kaplanır?",
                 "Çinko demirden daha kolay tepkimeye girdiği için demirin yerine kendisi aşınır",
                 Y("Çinko mıknatısa çekildiği için suyu iter", "iliski", "Mıknatıslık suyu itmez. Koruma, çinkonun demirden daha etkin olmasından gelir (K2).", "K2"),
                 Y("Çinko hiç tepkimeye girmediği için", "veri", "Tam tersi: çinko demirden daha kolay tepkimeye girer (K2).", "K2"),
                 Y("Çinko kaplama telin daha parlak görünmesini sağladığı için", "veri", "Kaplama mat gri (K1); amaç parlaklık değil, korumadır.", "K1"),
                 ipucu="K2'deki 'feda edilen metal' ifadesine bak.",
                 aciklama="Galvanizleme, çeliğin çinkoyla kaplanmasıdır. Çinko hem bir kalkan gibi demiri örter hem de çizilse bile demirden önce aşınarak onu korur. Üretilen çinkonun çoğu bu iş için kullanılır.")),

    V("Sn", 1, "ev", "Konserve Kutusunun İçi",
      "Bir öğrenci, açtığı konserve kutusunun içinin gümüşi ve parlak olduğunu fark etti. Kutuya mıknatıs yaklaştırınca "
      "mıknatıs kutuya yapıştı. Üretici kutunun 'ince bir metal tabakasıyla kaplanmış çelik' olduğunu söylüyor. Görevin: "
      "kaplama metalini bulmak.",
      [("deney", "Mıknatıs testi", "Mıknatıs kutuya yapışıyor. Kutunun gövdesi çelikten."),
       ("fiziksel", "Kaplama metali", "Kaplama metali gümüşi ve parlak; zehirsiz; besinlerdeki asitlerle kolay kolay tepkimeye girmiyor. 232 °C gibi düşük bir sıcaklıkta eriyor; bu yüzden lehim telinde de kullanılıyor.")],
      gozlem=S("Mıknatısın kutuya yapışması (K1) neyi gösterir?",
               "Kutunun gövdesi mıknatısa çekilen bir metal (çelik) içeriyor.",
               Y("Kaplama metali mıknatısa çekiliyor.", "kanitsiz", "Mıknatıs gövdedeki çeliğe yapışır; bu deney kaplama metalinin mıknatısa çekilip çekilmediğini göstermez.", "K1"),
               Y("Kutu tamamen kaplama metalinden yapılmış.", "veri", "K1, gövdenin çelikten yapıldığını söylüyor.", "K1"),
               ipucu="Hangi metaller mıknatısa çekilir?",
               aciklama="Demir ve çelik mıknatısa çekilir. Konserve kutularının gövdesi çeliktir; içi başka bir metalin ince tabakasıyla kaplanır."),
      kullanim=S("Konserve kutularının içi neden kalayla kaplanır?",
                 "Kalay zehirsizdir ve besinlerdeki asitlerle kolay tepkimeye girmez; çeliği paslanmaktan korur",
                 Y("Kalay mıknatısa çekildiği için kutuyu sağlamlaştırır", "veri", "Mıknatısa çekilen kutunun çelik gövdesidir (K1); kaplamanın görevi korumaktır.", "K1"),
                 Y("Kalay düşük sıcaklıkta eridiği için konserveyi ısıtır", "iliski", "Erime noktası lehimde işe yarar ama kaplamanın görevini açıklamaz; kaplama besini ve çeliği korur.", "K2"),
                 Y("Kalay besinlere tat kattığı için", "kanitsiz", "Kalayın besine tat kattığına dair bir kanıt yok; zehirsiz ve tepkimeye girmeyen bir kaplamadır (K2).", "K2"),
                 ipucu="K2'de kalayın besinlerle ilişkisi anlatılıyor.",
                 aciklama="Teneke denilen malzeme, ince kalayla kaplanmış çeliktir. Kalay zehirsizdir ve besinlerdeki asitlere dayanır; çeliği paslanmaktan, besini de demir tadından korur.")),

    V("Pb", 1, "saglik", "Röntgen Odasındaki Ağır Önlük",
      "Dişçide röntgen çekilirken hasta bir önlük giydirdi. Önlük şaşırtıcı derecede ağırdı. Hemşire, önlüğün içinde "
      "röntgen ışınlarını durduran bir metal levha olduğunu söyledi. Görevin: bu metali bulmak.",
      [("fiziksel", "Önlüğün ağırlığı", "İnce bir önlük olduğu hâlde birkaç kilogram geliyor. İçindeki metal çok yoğun."),
       ("deney", "Film testi", "Önlüğün arkasına konan röntgen filmi, ışın verildiği hâlde hiç kararmadı. Önlüksüz film ise tamamen karardı.")],
      gozlem=S("Önlüğün arkasındaki filmin kararmaması (K2) neyi gösterir?",
               "Önlükteki metal röntgen ışınlarını durduruyor.",
               Y("Röntgen cihazı çalışmıyordu.", "veri", "Önlüksüz film aynı ışınlarla karardı (K2); cihaz çalışıyordu.", "K2"),
               Y("Film ışığa duyarsızdı.", "veri", "Aynı tür film önlüksüzken karardı (K2).", "K2"),
               ipucu="İki filmi karşılaştır: aralarındaki tek fark ne?",
               aciklama="İki film arasındaki tek fark önlüktü. Önlüğün arkasındaki film kararmadığına göre önlük ışınları durdurdu. Bu, kontrollü bir deneyin mantığıdır."),
      kullanim=S("Röntgen önlüklerinde kurşun neden kullanılır?",
                 "Çok yoğun bir metal olduğu için röntgen ışınlarını ince bir tabakayla bile durdurabilir",
                 Y("Hafif olduğu için önlüğü rahat yaptığı için", "veri", "Önlük çok ağır (K1); kurşun hafif değil, çok yoğun bir metaldir.", "K1"),
                 Y("Elektriği iyi ilettiği için ışınları toprağa aktardığı için", "iliski", "Röntgen ışınları elektrik akımı değildir; kurşun onları yoğunluğu sayesinde soğurur.", "K2"),
                 Y("Parlak olduğu için ışınları ayna gibi yansıttığı için", "iliski", "Kurşun parlak değildir ve röntgen ışınlarını yansıtarak değil, soğurarak durdurur.", "K2"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Kurşun çok yoğun bir metaldir; atomları ışınları soğurur. Bu yüzden röntgen önlüklerinde ve radyasyon korumasında kullanılır. Ancak kurşun zehirlidir; bu yüzden önlüğün içinde kaplanmış olarak bulunur.")),

    V("Ag", 1, "sanat", "Altın Madalyanın Sırrı",
      "Bir müzede sergilenen olimpiyat altın madalyasının kesit modeli ziyaretçileri şaşırttı: madalyanın yüzeyi altın "
      "sarısı, ama içi beyazımsı gri bir metal. Rehber, olimpiyat kurallarına göre altın madalyanın büyük bölümünün başka "
      "bir değerli metalden yapıldığını söylüyor. Görevin: madalyanın içindeki metali bulmak.",
      [("fiziksel", "Madalyanın kesiti", "Dışta ince bir altın kaplama; içte parlak, beyazımsı gri bir metal."),
       ("kimyasal", "İç metalin davranışı", "İç metalden yapılmış bir kaşık, yumurtalı yemeklerle temas edince kararıyor; elektriği bütün metaller içinde en iyi ileten metal.")],
      gozlem=S("Kesitteki görünüm (K1) madalya hakkında neyi gösterir?",
               "Madalya tamamen altından değil; altın, başka bir metalin üzerine kaplanmış.",
               Y("Madalyanın içi zamanla solmuş altındır.", "kanitsiz", "Altın solmaz ve kararmaz; içteki metal farklı bir metal (K1, K2).", "K2"),
               Y("Madalya tamamen gri bir metalden yapılmış, altın yok.", "veri", "Dışta ince bir altın kaplama var (K1).", "K1"),
               ipucu="Dış ve iç kısmı karşılaştır.",
               aciklama="Olimpiyat altın madalyalarının büyük bölümü başka bir değerli metaldir; altın yalnızca yüzeydeki ince kaplamadır."),
      kullanim=S("Altın madalyanın içinin gümüşten yapılmasının en olası nedeni hangisidir?",
                 "Gümüş de değerli ve parlak bir metaldir ama altından çok daha bol ve ucuzdur",
                 Y("Gümüş altından daha ağır olduğu için", "kanitsiz", "Gümüş altından daha hafiftir. Kanıtlarda ağırlıkla ilgili bir bilgi yok; seçimin nedeni bolluk ve maliyet.", "K1"),
                 Y("Gümüş elektriği iyi ilettiği için", "iliski", "Gümüş elektriği çok iyi iletir (K2) ama bir madalyada elektrik iletmenin önemi yok.", "K2"),
                 Y("Gümüş hiç kararmadığı için", "veri", "Gümüş kükürtlü maddelerle temas edince kararır (K2).", "K2"),
                 ipucu="Altın ve gümüşün hangisi daha nadir?",
                 aciklama="Olimpiyat kurallarına göre altın madalyalar en az %92,5 saflıkta gümüşten yapılır ve en az 6 gram altınla kaplanır. Tamamen altından bir madalya çok pahalıya mal olurdu.")),

    V("Au", 1, "uzay", "Astronotun Altın Vizörü",
      "Bir uzay müzesindeki astronot kaskının vizörü sarı renkli bir ayna gibi parlıyor. Rehber, vizöre insan saçından "
      "binlerce kat ince bir metal tabakası kaplandığını söylüyor. Görevin: bu metali bulmak.",
      [("fiziksel", "Vizörün kaplaması", "Kaplama sarı renkli ve ayna gibi parlak. O kadar ince ki astronot içinden dışarıyı görebiliyor."),
       ("kimyasal", "Kaplamanın dayanıklılığı", "Bu metal yıllar geçse de kararmıyor, paslanmıyor; güneş ışığındaki kızılötesi (ısı) ışınları çok iyi yansıtıyor.")],
      gozlem=S("Kaplamanın yıllarca kararmadan kalması (K2) neyi gösterir?",
               "Metal, oksijen ve nemle neredeyse hiç tepkimeye girmiyor.",
               Y("Kaplama sürekli yenileniyor.", "kanitsiz", "Kaplamanın yenilendiğine dair bir kanıt yok; metalin kendisi kararmıyor (K2).", "K2"),
               Y("Uzayda oksijen olmadığı için her metal kararmadan kalır.", "veri", "Kask yeryüzünde de havayla temas eder ve müzede de kararmamış; dayanıklılık metalin kendi özelliği (K2).", "K2"),
               ipucu="Kararma ve paslanma hangi tepkimelerle olur?",
               aciklama="Bu metal soy bir metaldir: oksijen ve suyla neredeyse hiç tepkimeye girmez. Bu yüzden yüzyıllarca parlak kalır."),
      kullanim=S("Astronot vizörlerinde neden ince bir altın tabakası kullanılır?",
                 "Altın, güneşin ısı ışınlarını çok iyi yansıtır, çok ince olunca ışık geçirir ve hiç bozulmaz",
                 Y("Altın ağır olduğu için kaskı dengelediği için", "iliski", "Tabaka çok ince (K1); ağırlıkla bir ilgisi yok.", "K1"),
                 Y("Altın ışığı hiç geçirmediği için", "veri", "Kaplama o kadar ince ki astronot dışarıyı görebiliyor (K1).", "K1"),
                 Y("Altın elektriği iyi ilettiği için telsiz bağlantısı sağladığı için", "iliski", "Altın elektriği iyi iletir ama vizördeki görevi ışınları yansıtmaktır (K2).", "K2"),
                 ipucu="K1 ve K2'deki özellikleri birleştir.",
                 aciklama="Uzayda güneş ışınları süzülmeden gelir. Vizördeki ince altın tabakası kızılötesi ışınları ve parlak ışığı yansıtarak astronotun gözünü ve yüzünü korur; yine de yeterince ışık geçirir. Altın hiç kararmadığı için yıllarca aynı işi görür.")),

    V("B", 1, "ev", "Fırından Buzdolabına Cam",
      "Bir anne, buzdolabından çıkardığı cam kabı doğrudan sıcak fırına koydu; kap çatlamadı. Aynı şeyi sıradan bir "
      "bardakla yapınca bardak çatladı. Cam kabın etiketinde 'ısıya dayanıklı cam, Türkiye'nin dünyanın en büyük rezervine "
      "sahip olduğu bir elementin oksidini içerir' yazıyor. Görevin: bu elementi bulmak.",
      [("deney", "Isı şoku testi", "Isıya dayanıklı cam ani sıcaklık değişiminde çatlamadı; sıradan cam çatladı. Isıya dayanıklı cam ısınınca çok az genleşiyor."),
       ("tarih", "Maden kaydı", "Bu elementin dünyadaki bilinen rezervlerinin büyük bölümü Türkiye'de, Eskişehir, Kütahya ve Balıkesir yöresindeki madenlerde bulunuyor. Ana minerali, temizlik ürünlerinde ve camlarda da kullanılan beyaz bir tuz.")],
      gozlem=S("Sıradan camın ani sıcaklık değişiminde çatlaması ama diğerinin çatlamaması (K1) neyi gösterir?",
               "İki camın ısınınca genleşme miktarı farklı; az genleşen cam çatlamıyor.",
               Y("Isıya dayanıklı cam daha kalın olduğu için çatlamıyor.", "kanitsiz", "Kanıtlarda kalınlıktan söz edilmiyor; fark camın genleşme özelliğinde (K1).", "K1"),
               Y("Sıradan cam soğukta erir.", "iliski", "Cam soğukta erimez; çatlama, camın bir bölümünün diğerinden farklı genleşmesinden olur.", "K1"),
               ipucu="Bir cam kabın bir yüzü hızla ısınıp genleşirken diğer yüzü soğuk kalırsa ne olur?",
               aciklama="Ani ısınan camın bir bölümü genleşirken diğer bölümü genleşemez; bu gerilme camı çatlatır. Az genleşen cam bu gerilmeye dayanır."),
      kullanim=S("Isıya dayanıklı camlara bor oksit neden eklenir?",
                 "Camın ısınınca daha az genleşmesini sağlar; böylece ani sıcaklık değişimlerinde çatlamaz",
                 Y("Camı daha parlak ve renkli yaptığı için", "kanitsiz", "Kanıtlarda renkten söz edilmiyor; önemli olan genleşmenin azalması (K1).", "K1"),
                 Y("Camı mıknatısa çekilir yaptığı için", "iliski", "Mıknatıslık camın ısıya dayanıklılığıyla ilgili değil.", "K1"),
                 Y("Türkiye'de bol bulunduğu için camı hafiflettiği için", "iliski", "Bolluk bir elementi ucuzlatır ama camın ısıya dayanıklılığını açıklamaz. Dayanıklılığın nedeni az genleşmedir (K1).", "K2"),
                 ipucu="K1'de iki cam arasındaki fark yazıyor.",
                 aciklama="Borosilikat cam, içine bor oksit katılmış camdır. Isınınca çok az genleşir; bu yüzden laboratuvar camlarında ve fırın kaplarında kullanılır. Türkiye, dünyanın bilinen bor rezervlerinin en büyük bölümüne sahiptir."),
      kaynak=["Eti Maden İşletmeleri Genel Müdürlüğü: Bor — https://www.etimaden.gov.tr/"]),

    V("Li", 1, "enerji", "Tuz Çölündeki Hafif Metal",
      "Şili'deki Atacama tuz çölünün altındaki tuzlu su, geniş havuzlara pompalanıp güneşte buharlaştırılıyor. Geriye kalan "
      "tuzlardan, telefonların ve elektrikli arabaların pillerinde kullanılan bir metal elde ediliyor. Görevin: bu metali bulmak.",
      [("fiziksel", "Yağda yüzen metal", "Saf metal o kadar hafif ki gazyağının bile üzerinde yüzüyor. Bilinen en hafif metal."),
       ("deney", "Alev testi", "Metalin tuzlarından biri alevin üzerine serpilince alev koyu kırmızı (lal rengi) oldu.")],
      gozlem=S("Metalin gazyağının üzerinde yüzmesi (K1) neyi gösterir?",
               "Metalin yoğunluğu gazyağının yoğunluğundan küçük.",
               Y("Metal suyu ve yağı iter.", "iliski", "Yüzme, itmeyle değil yoğunlukla ilgilidir.", "K1"),
               Y("Metal havadan hafiftir.", "veri", "Havadan hafif olsaydı uçardı; metal yalnızca gazyağından hafif (K1).", "K1"),
               ipucu="Bir cisim hangi durumda bir sıvının üzerinde yüzer?",
               aciklama="Bir katı, yoğunluğu sıvınınkinden küçükse yüzer. Bu metalin yoğunluğu (0,53 g/cm³) suyunkinin yarısı kadardır."),
      kullanim=S("Lityum telefon ve araba pillerinde neden kullanılır?",
                 "Çok hafif olduğu ve kolayca elektron verebildiği için küçük bir kütlede çok enerji depolanmasını sağlar",
                 Y("Alevi kırmızıya boyadığı için", "iliski", "Alev rengi bir tanıma testidir (K2); pildeki görevini açıklamaz.", "K2"),
                 Y("Çok ağır olduğu için pili sağlamlaştırdığı için", "veri", "Lityum bilinen en hafif metal (K1).", "K1"),
                 Y("Hiçbir maddeyle tepkimeye girmediği için", "kanitsiz", "Pil kimyasal tepkimelerle çalışır; lityumun işe yaraması tam tersine kolay tepkimeye girmesinden gelir.", "K1"),
                 ipucu="Bir telefon pilinin hem hafif hem de güçlü olması gerekir.",
                 aciklama="Lityum en hafif metaldir ve en dıştaki tek elektronunu kolayca verir. Bu yüzden lityum iyon piller aynı kütlede diğer pillerden çok daha fazla enerji depolar.")),

    V("Ne", 1, "sanat", "Kızıl Turuncu Tabela",
      "Eski bir sinemanın girişindeki tabela geceleri kızıl turuncu bir ışıkla parlıyor. Tabelayı tamir eden usta, cam "
      "tüplerin içinde çok az miktarda bir gaz bulunduğunu ve gazın ancak tüpten yüksek gerilimli elektrik geçince "
      "parladığını söylüyor. Görevin: tüpteki gazı bulmak.",
      [("deney", "Elektrik verilince", "Tüpten yüksek gerilimli elektrik geçince gaz kızıl turuncu bir ışık yayıyor; elektrik kesilince ışık sönüyor."),
       ("kimyasal", "Gazın davranışı", "Gaz hiçbir maddeyle tepkimeye girmiyor; tüpün içinde yıllarca değişmeden kalıyor.")],
      gozlem=S("Gazın yalnızca elektrik geçince parlaması (K1) neyi gösterir?",
               "Işığın enerjisi elektrikten geliyor; elektrik gazın atomlarını uyarıyor.",
               Y("Gaz yanıyor.", "veri", "Gaz hiçbir maddeyle tepkimeye girmiyor (K2); yanma bir tepkimedir.", "K2"),
               Y("Gaz gün boyunca güneş ışığını depolayıp gece yayıyor.", "veri", "Işık elektrik kesilince hemen sönüyor (K1); depolanmış ışık olsaydı sönmezdi.", "K1"),
               ipucu="Elektrik kesilince ne oluyor?",
               aciklama="Elektrik akımı gaz atomlarındaki elektronları uyarır; elektronlar eski enerji düzeylerine dönerken her elemente özgü renklerde ışık yayar."),
      kullanim=S("Neon reklam tabelalarında neden kullanılır?",
                 "Elektrikle uyarılınca parlak kızıl turuncu ışık verir ve tepkimeye girmediği için tüpte yıllarca bozulmadan kalır",
                 Y("Yanıcı olduğu için parlak alev verdiği için", "veri", "Neon tepkimeye girmez (K2), yani yanmaz.", "K2"),
                 Y("Kendisi kızıl turuncu renkli bir gaz olduğu için", "iliski", "Neon renksiz bir gazdır; renk yalnızca elektrik geçerken yayılan ışıktan gelir (K1).", "K1"),
                 Y("Havadan ağır olduğu için tüpte kaldığı için", "iliski", "Tüp kapalıdır; gazın tüpte kalması ağırlığıyla ilgili değil. Önemli olan ışığın rengi ve tepkimeye girmemesi.", "K2"),
                 ipucu="K1 ve K2'deki iki özelliği birleştir.",
                 aciklama="Neon elektrikle uyarılınca kendine özgü kızıl turuncu ışığını yayar. Yalnızca kırmızı tabelalarda saf neon bulunur; başka renkler için başka gazlar ya da tüpün içindeki renkli kaplamalar kullanılır.")),

    V("Ar", 1, "ev", "Çift Camın Arasındaki Gaz",
      "Yeni bir evin pencereleri iki cam katmanından oluşuyor. Satıcı, iki camın arasındaki boşluğun hava değil, havada "
      "zaten bulunan başka bir gazla doldurulduğunu ve bunun evi daha sıcak tuttuğunu söylüyor. Görevin: bu gazı bulmak.",
      [("kimyasal", "Gazın davranışı", "Gaz renksiz ve kokusuz; hiçbir maddeyle tepkimeye girmiyor."),
       ("fiziksel", "Havadaki payı", "Bu gaz soluduğumuz havanın yaklaşık %1'ini oluşturuyor; azot ve oksijenden sonra havada en bol bulunan gaz. Isıyı havadan daha az iletiyor.")],
      gozlem=S("Bu gazın havada azot ve oksijenden sonra en bol gaz olması (K2) neyi gösterir?",
               "Gaz havadan kolayca ve ucuza elde edilebilir.",
               Y("Gaz havanın büyük bölümünü oluşturur.", "veri", "Gaz havanın yalnızca yaklaşık %1'ini oluşturur (K2).", "K2"),
               Y("Gaz soluduğumuz için zararsızdır, bu yüzden pencerede kullanılır.", "iliski", "Pencerede kullanılmasının nedeni ısıyı az iletmesi; havada bulunması onu yalnızca kolay elde edilir yapar.", "K2"),
               ipucu="Bir gazın havada bol olması onu elde etmeyi nasıl etkiler?",
               aciklama="Bu gaz havanın yaklaşık %0,9'unu oluşturur. Sıvı havanın ayrılmasıyla büyük miktarlarda ve ucuza elde edilir."),
      kullanim=S("Çift camlı pencerelerde camların arasına neden argon doldurulur?",
                 "Argon ısıyı havadan daha az ilettiği için evden dışarıya ısı kaybını azaltır; tepkimeye girmediği için de bozulmaz",
                 Y("Argon havadan hafif olduğu için camları hafifletir", "iliski", "Pencerenin ağırlığı ısı yalıtımını açıklamaz; önemli olan gazın ısıyı az iletmesi (K2).", "K2"),
                 Y("Argon yanıcı olduğu için camı ısıtır", "veri", "Argon hiçbir maddeyle tepkimeye girmez (K1); yanmaz.", "K1"),
                 Y("Argon renkli olduğu için güneş ışığını süzer", "veri", "Argon renksizdir (K1).", "K1"),
                 ipucu="K2'nin son cümlesine bak.",
                 aciklama="Argon ısıyı havadan daha yavaş iletir; bu yüzden camların arasındaki argon tabakası evden dışarıya ısı kaçışını azaltır. Tepkimeye girmediği için yıllarca değişmeden kalır.")),

    V("U", 1, "enerji", "Akkuyu'nun Yakıtı",
      "Mersin'deki Akkuyu Nükleer Güç Santrali'nin yakıtı, parmak ucu büyüklüğünde siyah seramik tabletlerden oluşuyor. "
      "Bir öğrenci 'Bu kadar küçük bir şey nasıl bu kadar elektrik üretebilir?' diye soruyor. Görevin: yakıttaki elementi bulmak.",
      [("fiziksel", "Yakıt tableti", "Tabletler bu elementin oksidinden yapılmış. Tek bir tablet, yaklaşık bir ton kömürün yanmasıyla elde edilen kadar enerji verebiliyor."),
       ("deney", "Çekirdek bölünmesi", "Bu elementin bazı atomlarının çekirdeği bir nötron çarpınca ikiye bölünüyor; bu sırada büyük bir enerji ve yeni nötronlar açığa çıkıyor.")],
      gozlem=S("Küçük bir tabletin bir ton kömür kadar enerji vermesi (K1) neyi gösterir?",
               "Atom çekirdeklerinden elde edilen enerji, kömürün yanmasından elde edilenden çok daha büyük.",
               Y("Tablet çok hızlı yanıyor.", "iliski", "Tabletler yanmaz; enerji çekirdeklerin bölünmesinden gelir (K2).", "K2"),
               Y("Tablet kömürden yapılmıştır.", "veri", "Tabletler bu elementin oksidinden yapılmış (K1).", "K1"),
               ipucu="Kömürün enerjisi yanmadan, yani bir kimyasal tepkimeden gelir. Tabletin enerjisi nereden geliyor?",
               aciklama="Kimyasal tepkimelerde (yanma gibi) atomların elektronları yer değiştirir. Nükleer tepkimelerde ise çekirdekler değişir; bu tepkimeler milyonlarca kat daha fazla enerji verir."),
      kullanim=S("Uranyum nükleer santrallerde neden yakıt olarak kullanılır?",
                 "Uranyum-235 çekirdekleri bir nötronla bölünür, büyük enerji ve yeni nötronlar verir; böylece zincirleme tepkime sürdürülebilir",
                 Y("Uranyum havada kendiliğinden alev aldığı için", "iliski", "Santraldeki enerji yanmadan değil, çekirdek bölünmesinden gelir (K2).", "K2"),
                 Y("Uranyum elektriği çok iyi ilettiği için", "iliski", "Elektrik, açığa çıkan ısıyla üretilen buharın türbini döndürmesiyle elde edilir; uranyumun iletkenliğiyle ilgisi yok.", "K2"),
                 Y("Uranyum tabletleri hiç ısınmadığı için güvenli olduğu için", "veri", "Çekirdek bölünmesi büyük bir enerji açığa çıkarır (K2); tabletler çok ısınır, bu ısı suyu buhara çevirir.", "K2"),
                 ipucu="K2'deki tepkimede açığa çıkan yeni nötronlar ne yapabilir?",
                 aciklama="Bölünen her uranyum-235 çekirdeği yeni nötronlar saçar; bunlar başka çekirdekleri böler. Bu zincirleme tepkime denetimli biçimde sürdürülür; açığa çıkan ısı suyu buhara çevirir, buhar türbinleri döndürerek elektrik üretir."),
      kaynak=["Akkuyu Nükleer A.Ş. — https://akkuyu.com/tr"]),

    V("Rn", 1, "saglik", "Bodrumdaki Görünmez Misafir",
      "Bir ailenin bodrum katına konan bir ölçüm cihazı, havada yüksek düzeyde radyoaktif bir gaz buldu. Gaz evin altındaki "
      "kayalardan sızıyor. Pencereler açılıp havalandırma yapılınca ölçülen değer düştü. Görevin: bu gazın hangi element "
      "olduğunu bulmak.",
      [("fiziksel", "Gazın özellikleri", "Gaz renksiz, kokusuz ve tatsız; bu yüzden ancak bir ölçüm cihazıyla fark edilebiliyor. Kayalardaki radyumun bozunmasıyla oluşuyor."),
       ("deney", "Havalandırma", "Kapalı bodrumda ölçülen değer yüksekti. Havalandırma yapılınca değer belirgin biçimde düştü.")],
      gozlem=S("Havalandırma yapılınca ölçülen değerin düşmesi (K2) neyi gösterir?",
               "Gaz kapalı ortamlarda birikiyor; temiz havayla seyreltilince azalıyor.",
               Y("Gaz havayla tepkimeye girip yok oluyor.", "kanitsiz", "Havalandırma gazı dışarı taşır ve seyreltir; gazın havayla tepkimeye girdiğine dair bir kanıt yok.", "K2"),
               Y("Cihaz bozuktu.", "kanitsiz", "Değerin havalandırmayla tutarlı biçimde değişmesi cihazın doğru çalıştığını gösteriyor.", "K2"),
               ipucu="Kapalı ve havalandırılmış bodrumu karşılaştır.",
               aciklama="Bu gaz yerden sızar ve kapalı, havasız yerlerde birikir. Düzenli havalandırma gazın düzeyini düşürür."),
      kullanim=S("Radon bir soy gaz olduğu hâlde neden sağlık için tehlikelidir?",
                 "Radyoaktiftir: solunduğunda akciğerlerde bozunarak hücrelere zarar veren ışınlar yayar",
                 Y("Akciğerlerdeki oksijenle tepkimeye girip zehir oluşturduğu için", "iliski", "Radon bir soy gazdır ve tepkimeye girmez. Tehlikesi radyoaktif olmasından gelir.", "K1"),
                 Y("Keskin kokusu boğazı tahriş ettiği için", "veri", "Radon kokusuzdur (K1).", "K1"),
                 Y("Havadan hafif olduğu için akciğerleri şişirdiği için", "iliski", "Radon havadan çok daha ağırdır; üstelik tehlikesi ağırlığıyla değil radyoaktifliğiyle ilgilidir.", "K1"),
                 ipucu="K1'de gazın nasıl oluştuğu yazıyor.",
                 aciklama="Radon, kayalardaki uranyum ve radyumun bozunmasıyla oluşan radyoaktif bir soy gazdır. Dünya Sağlık Örgütü'ne göre radon, sigaradan sonra akciğer kanserinin en önemli nedenlerinden biridir. Evlerde ölçüm ve havalandırma önerilir."),
      kaynak=["Dünya Sağlık Örgütü: Radon and health — https://www.who.int/news-room/fact-sheets/detail/radon-and-health"]),

    V("Ra", 1, "tarih", "Karanlıkta Parlayan Rakamlar",
      "1920'lerden kalma bir kol saatinin rakamları, hiç ışık almadığı hâlde karanlıkta hafifçe parlıyor. O yıllarda bu "
      "rakamları boyayan işçiler, fırçalarının ucunu dudaklarıyla sivriltirdi; birçoğu yıllar sonra ağır hastalandı. "
      "Görevin: boyaya parlaklık veren radyoaktif elementi bulmak.",
      [("fiziksel", "Kendi kendine parlayan boya", "Boya hiç ışık almasa da sürekli hafifçe parlıyor. Boyada, sürekli ışın yayan bir elementin tuzu ve bu ışınlarla parlayan bir madde var."),
       ("kimyasal", "Kemiklerdeki iz", "Hastalanan işçilerin kemiklerinde bu element birikmişti. Element, kemiklerin ana elementlerinden kalsiyumla aynı grupta.")],
      gozlem=S("Boyanın hiç ışık almadan sürekli parlaması (K1) neyi gösterir?",
               "Işığın enerjisi, boyadaki elementin sürekli yaydığı ışınlardan geliyor.",
               Y("Boya gün ışığını depolayıp geceleri yayıyor.", "veri", "Boya hiç ışık almasa da parlıyor (K1); depolanmış ışık olsaydı bir süre sonra sönerdi.", "K1"),
               Y("Boya yanıyor.", "kanitsiz", "Boya yanmıyor; ortada alev ya da yanma ürünü yok.", "K1"),
               ipucu="Işığın enerjisi nereden geliyor olabilir?",
               aciklama="Boyadaki radyoaktif elementin yaydığı ışınlar parlayan maddeye (çinko sülfür) çarpar ve onu ışık yaymaya zorlar. Enerji radyoaktif bozunmadan gelir."),
      kullanim=S("Boyayı yalayan işçilerin kemiklerinde neden radyum birikti?",
                 "Radyum kalsiyumla aynı grupta olduğu için vücut onu kalsiyum gibi kemiklere yerleştirdi",
                 Y("Radyum çok ağır olduğu için kemiklere çöktü", "iliski", "Bir elementin vücutta nereye gideceğini ağırlığı değil kimyasal davranışı belirler.", "K2"),
                 Y("Radyum kemikleri ışıldattığı için", "kanitsiz", "Kemiklerin ışıldadığına dair bir kanıt yok; asıl neden radyumun kalsiyuma benzemesi (K2).", "K2"),
                 Y("İşçiler kalsiyum tableti aldığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K2"),
                 ipucu="K2: Aynı gruptaki elementlerin kimyasal davranışları nasıldır?",
                 aciklama="Aynı gruptaki elementler benzer kimyasal davranışlar gösterir. Radyum kalsiyuma benzediği için kemiklere yerleşir ve orada ışın yayarak zarar verir. 'Radyum Kızları' olarak anılan işçilerin yaşadıkları, iş sağlığı ve güvenliği kurallarının gelişmesinde önemli rol oynadı. Bugün radyumlu boya kullanılmıyor.")),

    V("Eu", 1, "adli", "Avro Banknotunun Kırmızı Işığı",
      "Bir döviz bürosu, sahte olduğundan şüphelendiği bir avro banknotunu morötesi (UV) lambanın altına tuttu. Gerçek "
      "banknotta bazı lifler ve desenler kırmızı renkte parladı; şüpheli banknotta bu kırmızı parıltı yoktu. Görevin: "
      "gerçek banknota kırmızı parıltıyı veren elementi bulmak.",
      [("deney", "UV lambası", "Gerçek banknotta morötesi ışık altında kırmızı renkte parlayan lifler var. Sahte banknotta kırmızı parıltı yok."),
       ("kimyasal", "Mürekkebin elementi", "Kırmızı parıltıyı veren element bir lantanit. Eski renkli televizyon ekranlarında da kırmızı rengi bu elementin bileşikleri veriyordu.")],
      gozlem=S("Sahte banknotta kırmızı parıltının olmaması (K1) neyi gösterir?",
               "Sahte banknotun mürekkebinde gerçek banknottaki özel madde yok.",
               Y("Sahte banknot daha eski olduğu için parıltısını kaybetmiş.", "kanitsiz", "Banknotların yaşı hakkında bir kanıt yok.", "K1"),
               Y("UV lambası sahte banknotta çalışmadı.", "kanitsiz", "Aynı lamba gerçek banknotu parlattı (K1).", "K1"),
               ipucu="İki banknotu aynı lamba altında karşılaştır.",
               aciklama="Gerçek avro banknotlarının mürekkebinde ve liflerinde morötesi ışık altında parlayan özel bileşikler bulunur. Bu bileşikleri taklit etmek zordur."),
      kullanim=S("Evropiyum banknotlarda neden kullanılır?",
                 "Morötesi ışık altında kendine özgü kırmızı ışık yayar; bu özelliği taklit etmek zor olduğu için sahtecilik ortaya çıkar",
                 Y("Banknotu daha dayanıklı yaptığı için", "kanitsiz", "Kanıtlarda dayanıklılıktan söz edilmiyor; görevi UV altında kırmızı parlamak (K1).", "K1"),
                 Y("Gün ışığında kırmızı göründüğü için", "veri", "Kırmızı parıltı yalnızca morötesi ışık altında görülüyor (K1).", "K1"),
                 Y("Radyoaktif olduğu için kendiliğinden parladığı için", "iliski", "Evropiyumun parlaması radyoaktiflikten değil, morötesi ışığı soğurup kırmızı ışık olarak yaymasından gelir.", "K1"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Evropiyum bileşikleri morötesi ışığı soğurur ve keskin bir kırmızı ışık olarak geri yayar (floresans). Avro banknotlarındaki bu kırmızı parıltı, sahte banknotları ayırt etmenin yollarından biridir. Aynı özellik eski televizyon ekranlarında ve tasarruflu ampullerde de kullanılmıştır.")),

    V("Nd", 1, "teknoloji", "Kulaklıktaki Küçük Dev",
      "Bir öğrenci bozulan kablosuz kulaklığını söktü. İçinden bir mercimek tanesi büyüklüğünde ama şaşırtıcı derecede güçlü "
      "bir mıknatıs çıktı: masadaki ataşları birkaç santimetre uzaktan çekiyor. Görevin: bu mıknatısa adını veren "
      "lantanit elementini bulmak.",
      [("fiziksel", "Mıknatısın gücü", "Mercimek büyüklüğündeki mıknatıs, kendi ağırlığının yüzlerce katı demiri taşıyabiliyor."),
       ("alasim", "Mıknatısın bileşimi", "Mıknatıs üç elementten yapılmış bir alaşım: demir, bor ve bir lantanit. Bu tür mıknatıslar 1983'te bulundu.")],
      gozlem=S("Bu kadar küçük bir mıknatısın bu kadar güçlü olması (K1) kulaklık için neden önemli?",
               "Güçlü ve küçük bir mıknatıs, küçücük bir kulaklıkta bile yüksek ve net ses üretilmesini sağlar.",
               Y("Mıknatıs kulaklığı ağırlaştırarak kulakta durmasını sağlar.", "veri", "Mıknatıs mercimek büyüklüğünde (K1); kulaklığı ağırlaştırmaz.", "K1"),
               Y("Mıknatıs pili şarj eder.", "kanitsiz", "Kanıtlarda mıknatısın pili şarj ettiğine dair bir bilgi yok.", "K1"),
               ipucu="Hoparlörler ve kulaklıklar sesi mıknatıs ve elektrik akımıyla üretir.",
               aciklama="Hoparlörde elektrik akımı bir bobini mıknatısın alanında titreştirir ve ses oluşur. Mıknatıs ne kadar güçlüyse küçük bir hoparlörden o kadar iyi ses alınır."),
      kullanim=S("Neodim mıknatıslar küçük elektronik cihazlarda neden tercih edilir?",
                 "Bilinen en güçlü kalıcı mıknatıslar oldukları için çok küçük boyutta bile güçlü bir manyetik alan sağlarlar",
                 Y("Elektriği hiç iletmedikleri için", "iliski", "İletkenlik, mıknatısın gücünü açıklamaz.", "K1"),
                 Y("Tamamen neodimden yapıldıkları için hafif oldukları için", "veri", "Mıknatıs demir, bor ve neodimden oluşan bir alaşım (K2).", "K2"),
                 Y("Isıtılınca güçlendikleri için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; mıknatıslar genellikle ısınınca zayıflar.", "K1"),
                 ipucu="K1'deki güç ve boyut bilgisini birleştir.",
                 aciklama="1983'te bulunan neodim-demir-bor mıknatısları bilinen en güçlü kalıcı mıknatıslardır. Telefonların, kulaklıkların ve hoparlörlerin küçülmesini sağladılar; rüzgâr türbinlerinde ve elektrikli araç motorlarında da kullanılırlar.")),

    V("Er", 1, "teknoloji", "Okyanus Altındaki İnternet",
      "Kıtaları birbirine bağlayan internet kabloları okyanusun dibinden binlerce kilometre boyunca uzanıyor. Kabloların "
      "içindeki cam liflerde ışık olarak taşınan veri, yol boyunca zayıflıyor. Belli aralıklarla konan 'yükselteçler' "
      "ışığı yeniden güçlendiriyor. Görevin: yükseltecin camına katılan lantanit elementini bulmak.",
      [("fiziksel", "Zayıflayan ışık", "Cam lifte ilerleyen ışık sinyali, kilometrelerce yol aldıktan sonra zayıflıyor ve güçlendirilmesi gerekiyor."),
       ("kimyasal", "Yükseltecin sırrı", "Yükselteçteki cam lifin içine bir lantanit katılmış. Bu element, ayrıca bir lazerle uyarıldığında lifteki zayıf ışık sinyalini güçlendiriyor. Cama katıldığında cama pembe bir renk de veriyor.")],
      gozlem=S("Işık sinyalinin uzun yolda zayıflaması (K1) neden bir sorundur?",
               "Sinyal çok zayıflarsa veri karşı kıyıya okunamaz hâlde ulaşır.",
               Y("Işık zayıflayınca rengi değişir ve kablo kırılır.", "kanitsiz", "Kanıtlarda kablonun kırıldığına dair bir bilgi yok.", "K1"),
               Y("Işık lifin içinde hiç ilerleyemez.", "veri", "Işık kilometrelerce ilerliyor, yalnızca zayıflıyor (K1).", "K1"),
               ipucu="Uzaktan gelen bir fısıltıyı anlamak neden zordur?",
               aciklama="Her sinyal yol boyunca zayıflar. Okunabilir kalması için belli aralıklarla güçlendirilmesi gerekir."),
      kullanim=S("Erbiyum internet kablolarındaki yükselteçlerde neden kullanılır?",
                 "Cam life katılan erbiyum, lazerle uyarılınca lifteki zayıf ışık sinyalini doğrudan güçlendirebilir",
                 Y("Cama pembe renk verip kabloyu güzelleştirdiği için", "iliski", "Pembe renk erbiyumun bir yan etkisidir (K2); asıl görevi sinyali güçlendirmektir.", "K2"),
                 Y("Elektriği çok iyi ilettiği için", "iliski", "Bu kablolarda veri elektrikle değil ışıkla taşınır (K1).", "K1"),
                 Y("Kabloyu su geçirmez yaptığı için", "kanitsiz", "Kanıtlarda erbiyumun su yalıtımı sağladığına dair bir bilgi yok.", "K2"),
                 ipucu="K2: Element lifin içinde ne yapıyor?",
                 aciklama="Erbiyum katkılı lif yükselteçleri, ışık sinyalini elektriğe çevirmeden doğrudan güçlendirir. Kıtalar arası internet trafiğinin büyük bölümü bu yükselteçler sayesinde okyanusları aşar.")),

    V("Ce", 1, "ev", "Çakmağın Kıvılcımı",
      "Bir kamp çakmağının tekerleği çevrilince içindeki küçük gri çubuktan parlak kıvılcımlar fışkırıyor ve gaz tutuşuyor. "
      "Satıcı çubuğa 'çakmak taşı' dense de bunun bir taş değil, bir metal alaşımı olduğunu söylüyor. Görevin: alaşımın "
      "ana elementini bulmak.",
      [("deney", "Kıvılcım", "Çubuk sert bir yüzeyle kazınınca kopan minik parçacıklar havada kendiliğinden tutuşup parlak kıvılcımlar oluşturuyor."),
       ("alasim", "Çubuğun bileşimi", "Çubuk, ağırlıkça yaklaşık yarısı tek bir lantanitten oluşan ve içinde demir ile başka lantanitler de bulunan bir alaşım.")],
      gozlem=S("Kazınan minik parçacıkların havada kendiliğinden tutuşması (K1) neyi gösterir?",
               "Alaşımdaki metal oksijenle çok kolay tepkimeye giriyor; sürtünme ısısı tutuşmaya yetiyor.",
               Y("Çubuğun içinde gaz var.", "kanitsiz", "Kıvılcımlar çubuktan kopan katı parçacıklardan oluşuyor (K1).", "K1"),
               Y("Çubuk elektrik üretiyor.", "iliski", "Çakmak taşında kıvılcım elektrikle değil, metal parçacıklarının tutuşmasıyla oluşur.", "K1"),
               ipucu="Parçacıklar havada neyle tepkimeye giriyor olabilir?",
               aciklama="Bu metal havadaki oksijenle çok kolay tepkimeye girer. Kazınan ince parçacıklar sürtünmeyle ısınıp tutuşur ve kıvılcım olur."),
      kullanim=S("Seryum çakmak taşlarında neden kullanılır?",
                 "Kazınınca kopan parçacıkları havada kolayca tutuşup sıcak kıvılcımlar oluşturduğu için",
                 Y("Çok sert olduğu için hiç aşınmadığı için", "veri", "Çakmak taşı her kullanımda kazınarak aşınır (K1).", "K1"),
                 Y("Tepkimeye girmeyen bir metal olduğu için güvenli olduğu için", "veri", "Seryum oksijenle çok kolay tepkimeye girer (K1); kıvılcım da bu yüzden oluşur.", "K1"),
                 Y("Seryum mıknatıs olduğu için tekerleği çevirdiği için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; tekerleği el çevirir.", "K2"),
                 ipucu="K1'deki gözleme bak.",
                 aciklama="Çakmak taşı, büyük bölümü seryum olan 'mischmetal' alaşımına demir katılarak yapılır. Seryum kazındığında kıvılcım veren çok az elementten biridir. Seryum oksit ayrıca kendi kendini temizleyen fırınlarda ve egzoz katalizörlerinde kullanılır.")),

    V("Tc", 1, "saglik", "Altı Saatlik Işık",
      "Bir hastanın kemiklerinin görüntüsü çekilecek. Hastaya çok az miktarda radyoaktif bir madde enjekte ediliyor; özel "
      "bir kamera, maddenin yaydığı gama ışınlarını yakalayarak kemiklerin görüntüsünü oluşturuyor. Ertesi gün maddenin "
      "radyoaktifliği büyük ölçüde geçmiş oluyor. Görevin: bu maddedeki elementi bulmak.",
      [("deney", "Kısa ömürlü ışınım", "Maddenin radyoaktifliği yaklaşık 6 saatte yarıya iniyor. Bir gün sonra başlangıçtakinin yaklaşık on altıda birine düşüyor."),
       ("tarih", "Yapay element", "Bu element doğada kalıcı olarak bulunmuyor, çünkü bütün izotopları radyoaktif. Yapay yolla elde edilen ilk element. Mendeleyev boşluğunu önceden görmüş ve ona 'eka-mangan' demişti.")],
      gozlem=S("Radyoaktifliğin 6 saatte yarıya inmesi (K1) hasta için neden iyi bir şey?",
               "Görüntü çekildikten kısa süre sonra madde etkisini yitirir; hasta daha az radyasyon alır.",
               Y("Madde 6 saat içinde vücuttan tamamen kaybolur.", "veri", "Radyoaktiflik 6 saatte yalnızca yarıya iniyor; bir gün sonra bile biraz kalıyor (K1).", "K1"),
               Y("Kısa ömür, kameranın görüntü çekmesini zorlaştırır.", "iliski", "Madde görüntü için yeterince uzun süre ışın yayar; kısa ömür çekimi engellemez, dozu azaltır.", "K1"),
               ipucu="Hasta radyasyonu ne kadar süre alıyor?",
               aciklama="Yarılanma süresi kısa olan bir madde, görüntü çekmeye yetecek kadar ışın yayar, sonra hızla azalır. Böylece hastanın aldığı radyasyon dozu düşük kalır."),
      kullanim=S("Teknesyum-99m tıbbi görüntülemede neden çok kullanılır?",
                 "Vücudun dışından kamerayla yakalanabilen gama ışınları yayar ve kısa yarılanma süresi sayesinde hastaya düşük doz verir",
                 Y("Doğada bol bulunduğu ve ucuz olduğu için", "veri", "Bu element doğada kalıcı olarak bulunmuyor; yapay yolla üretiliyor (K2).", "K2"),
                 Y("Hiç radyoaktif olmadığı için", "veri", "Bütün izotopları radyoaktif (K2); kamera da zaten yaydığı ışınları yakalıyor.", "K2"),
                 Y("Kemikleri güçlendirdiği için", "kanitsiz", "Madde görüntü almak için kullanılıyor; kemikleri güçlendirdiğine dair bir kanıt yok.", "K1"),
                 ipucu="K1'deki iki özellik: hangi ışını yayıyor ve ne kadar sürede azalıyor?",
                 aciklama="Teknesyum-99m'nin yaydığı gama ışınları vücuttan çıkıp kameraya ulaşabilir; yaklaşık 6 saatlik yarılanma süresi dozu düşük tutar. Farklı bileşikleri farklı organlarda toplandığı için kemik, kalp ve böbrek görüntülemesinde kullanılır.")),

    V("Po", 1, "teknoloji", "Fotoğrafçının Toz Fırçası",
      "Eski bir fotoğraf stüdyosunda, film negatiflerinden tozu almak için kullanılan özel bir fırça bulundu. Fırçanın "
      "sapında 'radyoaktif kaynak içerir, her yıl yenisiyle değiştirin' yazıyor. Fırça, filmlerin üzerindeki statik "
      "elektriği gidererek tozun yapışmasını önlüyormuş. Görevin: kaynaktaki elementi bulmak.",
      [("deney", "Alfa ışınları", "Kaynak alfa parçacıkları yayıyor. Alfa parçacıkları havada yalnızca birkaç santimetre gidebiliyor ve bir kâğıt yaprağıyla bile durduruluyor. Havadaki molekülleri iyonlaştırıyor."),
       ("fiziksel", "Kısa ömür", "Kaynağın etkinliği yaklaşık 138 günde yarıya iniyor. Bu yüzden fırçanın yılda bir değiştirilmesi gerekiyor.")],
      gozlem=S("Fırçanın her yıl değiştirilmesi gerekmesi (K2) neyi gösterir?",
               "Kaynaktaki radyoaktif madde zamanla azalıyor; bir yıl sonra işini yapacak kadar ışın yaymıyor.",
               Y("Fırçanın kılları bir yılda aşınıyor.", "kanitsiz", "Etikette değiştirme nedeni radyoaktif kaynak olarak gösteriliyor (K2).", "K2"),
               Y("Kaynak bir yıl sonra daha tehlikeli hâle geliyor.", "veri", "Kaynağın etkinliği zamanla azalıyor (K2); artmıyor.", "K2"),
               ipucu="138 günde yarıya inen bir şey bir yılda ne kadar kalır?",
               aciklama="138 günde yarıya inen bir kaynak bir yılda (yaklaşık 2,6 yarılanma süresi) başlangıçtakinin yaklaşık altıda birine düşer."),
      kullanim=S("Polonyum antistatik fırçalarda neden kullanılıyordu?",
                 "Yaydığı alfa parçacıkları havayı iyonlaştırır; iyonlar film üzerindeki statik elektriği nötrleştirir ve toz yapışmaz",
                 Y("Alfa ışınları tozu yakıp yok ettiği için", "iliski", "Alfa parçacıkları tozu yakmaz; havayı iyonlaştırarak statik elektriği giderir (K1).", "K1"),
                 Y("Polonyum uzun ömürlü olduğu için fırça yıllarca kullanılabildiği için", "veri", "Etkinliği 138 günde yarıya iniyor (K2); fırça yılda bir değiştiriliyor.", "K2"),
                 Y("Alfa ışınları kâğıdı ve filmi delip geçebildiği için", "veri", "Alfa parçacıkları bir kâğıt yaprağıyla bile durdurulur (K1).", "K1"),
                 ipucu="K1'de alfa parçacıklarının havaya ne yaptığı yazıyor.",
                 aciklama="Polonyum-210 alfa parçacıkları yayar. Bu parçacıklar havadaki molekülleri iyonlaştırır; iyonlar filmdeki elektrik yükünü nötrleştirir. Alfa parçacıkları çok kısa mesafede durdurulduğu için kaynak kapalı bir kapsül içinde güvenle kullanılabiliyordu.")),

    V("Th", 1, "adli", "Tıkırdayan Eski Objektif",
      "Bir koleksiyoncu, 1960'lardan kalma çok kaliteli bir fotoğraf makinesi objektifini satın aldı. Bir arkadaşı Geiger "
      "sayacını objektife yaklaştırınca sayaç belirgin biçimde tıkırdadı. Üretici, o yıllarda bazı objektif camlarına "
      "ışığı daha iyi kıran bir metal oksidi katıldığını söylüyor. Görevin: bu metali bulmak.",
      [("deney", "Geiger sayacı", "Sayaç objektifin yanında belirgin biçimde, uzaklaşınca daha seyrek tıkırdıyor. Radyasyon zayıf."),
       ("kimyasal", "Camdaki oksit", "Cama katılan oksit, camın ışığı kırma gücünü artırıyor. Oksidin metali zayıf radyoaktif; en yaygın izotopunun yarılanma süresi yaklaşık 14 milyar yıl.")],
      gozlem=S("Sayacın objektife yaklaşınca daha sık tıkırdaması (K1) neyi gösterir?",
               "Radyasyon objektifin kendisinden geliyor.",
               Y("Radyasyon odanın duvarlarından geliyor.", "veri", "Sayaç objektiften uzaklaşınca seyrekleşiyor (K1); kaynak objektif.", "K1"),
               Y("Objektif elektrik üretiyor.", "iliski", "Geiger sayacı elektrik değil radyasyon ölçer.", "K1"),
               ipucu="Sayaç ne zaman sık, ne zaman seyrek tıkırdıyor?",
               aciklama="Sayacın, kaynağa yaklaştıkça daha sık tıkırdaması radyasyonun kaynağını gösterir: objektifin camı."),
      kullanim=S("Bazı eski objektiflerin camına toryum oksit neden katılıyordu?",
                 "Toryum oksit camın ışığı kırma gücünü artırarak daha ince ve daha kaliteli objektifler yapılmasını sağlıyordu",
                 Y("Camı radyoaktif yapıp karanlıkta parlattığı için", "iliski", "Radyoaktiflik istenmeyen bir yan etkidir; oksidin katılma nedeni ışığı daha iyi kırmasıdır (K2).", "K2"),
                 Y("Camı mıknatısa çekilir yaptığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K2"),
                 Y("Toryumun radyoaktifliği birkaç yılda bittiği için güvenli olduğu için", "veri", "En yaygın izotopunun yarılanma süresi yaklaşık 14 milyar yıl (K2); radyoaktifliği bitmez.", "K2"),
                 ipucu="K2'de oksidin cama ne kattığı yazıyor.",
                 aciklama="Toryum dioksit camın kırma indisini artırır; bu yüzden geçmişte kaliteli fotoğraf objektiflerinde kullanıldı. Radyasyonu zayıf olsa da bugün bu amaçla kullanılmıyor. Toryumun en yaygın izotopu toryum-232'nin yarılanma süresi 14 milyar yıldır.")),

    V("Pu", 1, "uzay", "Plüton'a Giden Araç",
      "Plüton'un fotoğraflarını çeken New Horizons uzay aracı, Güneş'ten o kadar uzaklaştı ki güneş panelleri işe yaramaz "
      "hâle gelirdi. Araç elektriğini, içindeki radyoaktif bir maddenin sürekli ürettiği ısıdan elde ediyor. Görevin: bu "
      "maddedeki elementi bulmak.",
      [("fiziksel", "Uzaktaki Güneş", "Plüton'un çevresinde güneş ışığı, Dünya'dakinden yaklaşık bin kat daha zayıf."),
       ("deney", "Sıcak tablet", "Araçtaki madde, radyoaktif bozunma sırasında sürekli ısı üretiyor. Bu maddedeki izotopun yarılanma süresi yaklaşık 88 yıl.")],
      gozlem=S("Plüton'un çevresinde güneş ışığının çok zayıf olması (K1) neden önemli?",
               "Güneş panelleri yeterli elektrik üretemez; aracın başka bir enerji kaynağına ihtiyacı var.",
               Y("Araç karanlıkta göremediği için fotoğraf çekemez.", "kanitsiz", "Araç Plüton'un fotoğraflarını çekti; sorun görmek değil elektrik üretmek.", "K1"),
               Y("Araç çok soğuk olduğu için hareket edemez.", "kanitsiz", "Kanıtlar enerji kaynağıyla ilgili; aracın hareket edemediğine dair bir bilgi yok.", "K1"),
               ipucu="Güneş paneli neyle elektrik üretir?",
               aciklama="Güneş panelleri ışıkla elektrik üretir. Işık bin kat zayıfsa paneller de çok az elektrik üretir; bu yüzden uzak gezegenlere giden araçlar başka bir enerji kaynağı taşır."),
      kullanim=S("Uzak gezegenlere giden araçlarda plütonyum-238 neden kullanılır?",
                 "Bozunurken yıllarca sürekli ve düzenli ısı üretir; bu ısı elektriğe çevrilerek güneş ışığına gerek kalmadan araç çalıştırılır",
                 Y("Yandığında roket yakıtı olarak itiş gücü verdiği için", "iliski", "Plütonyum yakılmaz; bozunurken ısı üretir ve bu ısı elektriğe çevrilir (K2).", "K2"),
                 Y("Birkaç gün içinde bütün enerjisini verdiği için", "veri", "Yarılanma süresi yaklaşık 88 yıl (K2); enerjisini yıllarca yavaş yavaş verir.", "K2"),
                 Y("Güneş ışığını depolayıp geceleri verdiği için", "iliski", "Plütonyum güneş ışığı depolamaz; ısısı kendi bozunmasından gelir (K2).", "K2"),
                 ipucu="K2'deki yarılanma süresini düşün.",
                 aciklama="Radyoizotop termoelektrik jeneratörler, plütonyum-238'in bozunma ısısını elektriğe çevirir. Plüton'a giden New Horizons ile Mars'taki Curiosity aracı böyle çalışır. Plüton'a plütonyumla gidilmesi de ilginç bir rastlantıdır: element adını o dönemde gezegen sayılan Plüton'dan almıştır.")),

    V("Cm", 1, "tarih", "Çocuk Programındaki Büyük Sır",
      "11 Kasım 1945'te Amerika'da çocukların soru sorduğu bir radyo programına konuk olan kimyacı Glenn Seaborg'a bir "
      "çocuk 'Yeni element buldunuz mu?' diye sordu. Seaborg, savaş yıllarında gizli tutulan iki yeni elementi ilk kez bu "
      "programda açıkladı. Bunlardan biri plütonyumdan üretilmişti. Görevin: bu elementi bulmak.",
      [("tarih", "Gizli keşif", "Element 1944'te üretildi ama savaş sürdüğü için keşif gizli tutuldu. Resmî duyuru radyo programından bir hafta sonra yapıldı."),
       ("fiziksel", "Elementin görünüşü", "Radyoaktif, gümüş renkli bir metal; havada hızla kararıyor. Uzay görevlerinde cihazlara güç sağlamak için kullanıldı.")],
      gozlem=S("Metalin havada hızla kararması (K2) neyi gösterir?",
               "Metal havadaki oksijenle kolayca tepkimeye giriyor.",
               Y("Metal havadaki ışığı soğuruyor.", "iliski", "Kararma, metal yüzeyinde yeni bir maddenin (oksidin) oluşmasıdır; ışık soğurmakla açıklanmaz.", "K2"),
               Y("Metal hiç tepkimeye girmeyen soy bir metaldir.", "veri", "Soy metaller (altın gibi) kararmaz; bu metal havada hızla kararıyor (K2).", "K2"),
               ipucu="Gümüş renkli bir yüzey neden kararır?",
               aciklama="Bir metalin havada kararması, yüzeyinde oksijenle tepkimeye girerek oksit tabakası oluşturduğunu gösterir."),
      kullanim=S("Küriyum uzay görevlerinde cihazlara nasıl güç sağlayabilir?",
                 "Radyoaktif bozunması sırasında ısı üretir; bu ısı elektriğe çevrilebilir",
                 Y("Yandığında roket yakıtı gibi itiş gücü verir", "iliski", "Küriyum yakıt olarak yakılmaz; enerjisi radyoaktif bozunmadan gelir.", "K2"),
                 Y("Güneş ışığını depolar ve gece verir", "kanitsiz", "Küriyumun güneş ışığı depoladığına dair bir kanıt yok; enerjisi kendi bozunmasından gelir.", "K2"),
                 Y("Havada hızla karardığı için ısı yalıtımı sağlar", "iliski", "Kararma bir yüzey tepkimesidir; güç sağlamakla bir ilgisi yok.", "K2"),
                 ipucu="Radyoaktif bir madde bozunurken çevresine ne verir?",
                 aciklama="Küriyum gibi radyoaktif elementler bozunurken çevrelerine ısı verir. Bu ısı, uzay araçlarında elektriğe çevrilebilir. Küriyum ayrıca bazı Mars araçlarının kayaların bileşimini ölçen aletlerinde ışın kaynağı olarak kullanıldı."),
      yapi="ozel", yapi_ozel=("atom_numarasi", "Çekirdek hesabı",
                              "Element, plütonyum-239 atomlarına alfa parçacıkları çarptırılarak üretildi. Plütonyumun atom numarası 94; bir alfa parçacığı 2 proton ve 2 nötron taşır ve çekirdeğe eklendi."),
      konum_soru="Çekirdek hesabına ({yapi}) göre yeni elementin atom numarası kaç? Elementi periyodik tabloda bul ve işaretle.",
      konum_ipucu="Çekirdeğe eklenen protonları plütonyumun proton sayısına ekle.",
      konum_aciklama="Plütonyumun 94 protonuna alfa parçacığının 2 protonu eklenince 96 protonlu bir çekirdek oluşur: küriyum (Cm, atom numarası 96).",
      savunma_yapi="çekirdek hesabı ({yapi}) atom numarasının 94 + 2 = 96 olduğunu gösteriyor"),

    V("Np", 1, "ev", "Duman Dedektöründeki Yeni Element",
      "40 yıllık bir duman dedektörünün içindeki radyoaktif kaynak incelendi. Kaynağın başlangıçta yalnızca amerikyum "
      "içerdiği biliniyordu. Ölçümler, kaynakta artık az miktarda yeni bir element de bulunduğunu gösterdi. Görevin: bu "
      "yeni elementi bulmak.",
      [("deney", "Yavaş bozunma", "Amerikyum-241'in yarılanma süresi yaklaşık 432 yıl. 40 yılda atomlarının yalnızca yaklaşık %6'sı bozunmuş."),
       ("tarih", "İlk uranyum ötesi element", "Bu yeni element, uranyumdan daha ağır olan ve yapay yolla üretilen ilk elementti; 1940'ta bulundu.")],
      gozlem=S("Kaynakta yeni elementin yalnızca az miktarda bulunması (K1) neyi gösterir?",
               "Amerikyum çok yavaş bozunuyor; 40 yılda atomlarının yalnızca küçük bir bölümü dönüşmüş.",
               Y("Yeni element dedektörden dışarı sızmış.", "kanitsiz", "Kaynağın sızdığına dair bir kanıt yok; az miktar, bozunmanın yavaşlığıyla açıklanıyor (K1).", "K1"),
               Y("Amerikyum 40 yılda tamamen bozunmuş.", "veri", "40 yılda atomların yalnızca yaklaşık %6'sı bozunmuş (K1).", "K1"),
               ipucu="432 yıllık yarılanma süresine göre 40 yıl kısa mı, uzun mu?",
               aciklama="Yarılanma süresi 432 yıl olan bir madde 40 yılda çok az azalır; bu yüzden dedektör onlarca yıl çalışabilir."),
      kullanim=S("Eski duman dedektörlerinde neptünyum nasıl ortaya çıkar?",
                 "Dedektördeki amerikyum alfa ışıması yaparak zamanla neptünyuma dönüşür",
                 Y("Dedektör üretilirken içine neptünyum konur", "veri", "Kaynağın başlangıçta yalnızca amerikyum içerdiği biliniyor; neptünyum sonradan oluştu.", "{yapi}"),
                 Y("Havadaki toz dedektörün içinde neptünyuma dönüşür", "iliski", "Toz bir elemente dönüşmez; yeni element amerikyumun bozunmasından gelir ({yapi}).", "{yapi}"),
                 Y("Duman neptünyum içerir", "kanitsiz", "Dumanın neptünyum içerdiğine dair bir kanıt yok.", "{yapi}"),
                 ipucu="Çekirdek hesabındaki ({yapi}) bozunmayı düşün.",
                 aciklama="Amerikyum-241 alfa ışıması yaparak neptünyum-237'ye dönüşür. Neptünyum, uranyumdan sonra gelen ilk elementtir; adını da Uranüs'ten sonra gelen Neptün gezegeninden alır."),
      yapi="ozel", yapi_ozel=("atom_numarasi", "Çekirdek hesabı",
                              "Amerikyumun atom numarası 95. Amerikyum atomları alfa parçacığı yayarak bozunur; bir alfa parçacığı 2 proton ve 2 nötron taşır ve çekirdekten çıkar."),
      konum_soru="Çekirdek hesabına ({yapi}) göre yeni elementin atom numarası kaç? Elementi periyodik tabloda bul ve işaretle.",
      konum_ipucu="Çekirdekten çıkan protonları amerikyumun proton sayısından çıkar.",
      konum_aciklama="Amerikyumun 95 protonundan alfa parçacığıyla 2 proton ayrılınca 93 protonlu bir çekirdek kalır: neptünyum (Np, atom numarası 93).",
      savunma_yapi="çekirdek hesabı ({yapi}) atom numarasının 95 − 2 = 93 olduğunu gösteriyor"),

    V("Cf", 1, "sanayi", "Petrol Kuyusundaki Nötron Kaynağı",
      "Bir petrol arama ekibi, yerin kilometrelerce altına bir ölçüm aleti indirdi. Aletin ucundaki küçük bir kaynak "
      "çevresindeki kayalara nötronlar gönderiyor; geri dönen sinyallerden kayanın içinde su mu, petrol mü olduğu "
      "anlaşılıyor. Görevin: bu güçlü nötron kaynağındaki elementi bulmak.",
      [("deney", "Nötron yağmuru", "Kaynaktaki çekirdekler kendiliğinden ikiye bölünüyor ve her bölünmede birkaç nötron saçılıyor. Bir mikrogram madde saniyede milyonlarca nötron yayıyor."),
       ("tarih", "Üretim", "Element bir nükleer reaktörde plütonyumun nötronlarla bombardımanıyla, yalnızca miligram miktarlarında üretiliyor. Adını ilk üretildiği ABD eyaletinden alıyor.")],
      gozlem=S("Çekirdeklerin kendiliğinden bölünüp nötron saçması (K1) bu maddeyi neden kullanışlı yapar?",
               "Hiçbir makineye gerek kalmadan, küçücük bir kaynaktan sürekli nötron elde edilir.",
               Y("Bölünme sırasında petrol oluşur.", "iliski", "Çekirdek bölünmesi petrol oluşturmaz; nötronlar kayadaki petrolü ya da suyu bulmaya yarar.", "K1"),
               Y("Kaynak hiç ışıma yapmaz, bu yüzden güvenlidir.", "veri", "Kaynak sürekli nötron yayıyor (K1).", "K1"),
               ipucu="Bir nötron kaynağı olmasa ekip ne kullanmak zorunda kalırdı?",
               aciklama="Bu maddenin çekirdekleri kendiliğinden bölünerek nötron yayar. Bu yüzden küçük, taşınabilir ve sürekli çalışan bir nötron kaynağıdır."),
      kullanim=S("Kaliforniyum petrol kuyularında ve maden aramada neden kullanılır?",
                 "Çok güçlü bir nötron kaynağıdır; gönderdiği nötronlarla kayadaki su, petrol ya da altın-gümüş cevheri gibi maddeler tanınabilir",
                 Y("Kayaları eriterek petrolü yüzeye çıkardığı için", "kanitsiz", "Kaynak kayaları eritmez; nötronlar yalnızca kayanın içeriğini anlamaya yarar (hikâye).", "K1"),
                 Y("Doğada bol bulunduğu ve ucuz olduğu için", "veri", "Element yalnızca reaktörlerde miligram miktarlarında üretiliyor (K2).", "K2"),
                 Y("Hiç radyoaktif olmadığı için", "veri", "Çekirdekleri kendiliğinden bölünüyor (K1); element radyoaktif.", "K1"),
                 ipucu="K1'deki 'nötron yağmuru' bu işte nasıl kullanılıyor?",
                 aciklama="Kaliforniyum-252 çok güçlü bir nötron yayıcıdır. Petrol kuyularında su ve petrol katmanlarını bulmakta, altın ve gümüş cevherlerini tanımakta, taşınabilir metal dedektörlerinde ve uçaklardaki metal yorgunluğunu bulmakta kullanılır.")),

    V("Bk", 1, "tarih", "Element Yapan Element",
      "2009'da Amerika'daki bir araştırma reaktöründe aylar süren bir çalışmayla yalnızca 22 miligram nadir bir radyoaktif "
      "element üretildi ve hemen Rusya'daki bir laboratuvara gönderildi. Orada bu elementin atomlarına kalsiyum çekirdekleri "
      "çarptırılarak periyodik tablonun 117. elementi tennesin üretildi. Görevin: hedef olarak kullanılan elementi bulmak.",
      [("fiziksel", "Acele edilen gönderi", "Hedef olarak kullanılan izotopun yarılanma süresi yaklaşık 320 gün. Bu yüzden üretilir üretilmez kullanılması gerekiyordu."),
       ("tarih", "Elementin adı", "Hedef element, ilk kez 1949'da Kaliforniya'daki bir üniversite kentinde üretilmişti ve adını o kentten aldı.")],
      gozlem=S("Hedef elementin üretilir üretilmez kullanılması gerekmesinin nedeni (K1) nedir?",
               "Yarılanma süresi yaklaşık 320 gün olduğu için beklendikçe miktarı azalacaktı.",
               Y("Element havayla temas edince patladığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; acelenin nedeni bozunma (K1).", "K1"),
               Y("Elementin ömrü milyarlarca yıl olduğu için acele etmeye gerek yoktu", "veri", "Yarılanma süresi yaklaşık 320 gün (K1).", "K1"),
               ipucu="K1'deki yarılanma süresine bak.",
               aciklama="320 günde yarıya inen bir hedef, birkaç ay beklenince belirgin biçimde azalır. Elde yalnızca 22 miligram olduğu için zaman kaybetmemek gerekiyordu."),
      kullanim=S("Tennesin üretmek için hedef olarak neden berkelyum seçildi?",
                 "Berkelyumun 97 protonu, kalsiyumun 20 protonuyla birleşince tam 117 proton elde edildiği için",
                 Y("Berkelyum çok ucuz ve bol olduğu için", "veri", "Yalnızca 22 miligram üretilebildi (hikâye); berkelyum çok nadir ve pahalıdır.", "K1"),
                 Y("Berkelyum kararlı olduğu için yıllarca saklanabildiği için", "veri", "Yarılanma süresi yaklaşık 320 gün (K1); kararlı değil.", "K1"),
                 Y("Berkelyumun adı tennesine benzediği için", "iliski", "Bir elementin adı çekirdek tepkimesini etkilemez; önemli olan proton sayısı ({yapi}).", "{yapi}"),
                 ipucu="Çekirdek hesabındaki ({yapi}) proton sayılarını topla.",
                 aciklama="İki çekirdek birleşince proton sayıları toplanır: 97 + 20 = 117. Oak Ridge'de üretilen 22 miligram berkelyum-249, Dubna'daki laboratuvarda kalsiyum-48 çekirdekleriyle bombardıman edildi ve 117. element tennesin üretildi."),
      yapi="ozel", yapi_ozel=("atom_numarasi", "Çekirdek hesabı",
                              "Kalsiyum-48 çekirdeği 20 proton taşıyor. Hedef elementin bir çekirdeğiyle birleşince 117 protonlu tennesin çekirdeği oluştu."),
      konum_soru="Çekirdek hesabına ({yapi}) göre hedef elementin atom numarası kaç? Elementi periyodik tabloda bul ve işaretle.",
      konum_ipucu="Hedefin proton sayısı + 20 = 117",
      konum_aciklama="İki çekirdek birleşince protonları toplanır. Hedefin proton sayısı = 117 − 20 = 97: berkelyum (Bk, atom numarası 97).",
      savunma_yapi="çekirdek hesabı ({yapi}) atom numarasının 117 − 20 = 97 olduğunu gösteriyor"),

    V("Es", 1, "tarih", "İki Yüz Atomluk Keşif",
      "1 Kasım 1952'de Pasifik'teki bir mercan adasında ilk termonükleer patlama denemesi yapıldı. Uçaklarla toplanan "
      "serpinti örnekleri Kaliforniya'ya gönderildi. Bilim insanları bir ay içinde örneklerde yeni bir elementin yaklaşık "
      "200 atomunu buldu; keşif 1955'e kadar gizli tutuldu. Görevin: bu elementi bulmak.",
      [("fiziksel", "Yarılanma süresi", "Bulunan izotopun yarılanma süresi yaklaşık 20,5 gün."),
       ("tarih", "Gözle görülen ilk örnek", "Elementin gözle görülebilecek ve tartılabilecek kadarı ancak 1961'de biriktirilebildi; bu miktar gramın yalnızca yaklaşık on milyonda biriydi.")],
      gozlem=S("Elementin gözle görülebilecek kadarının ancak 1961'de, yani keşiften yaklaşık 9 yıl sonra biriktirilebilmesi (K2) neyi gösterir?",
               "Element çok az miktarda üretilebiliyor ve kısa sürede bozunduğu için biriktirmek çok zor.",
               Y("Element renksiz olduğu için görülemiyordu.", "kanitsiz", "Sorun renk değil miktar: tartılabilecek kadarı bile çok zor biriktirildi (K2).", "K2"),
               Y("Bilim insanları elementi 9 yıl boyunca aramadı.", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; zorluk elementin kendisinden kaynaklanıyor (K1, K2).", "K2"),
               ipucu="K1 ve K2'yi birlikte düşün.",
               aciklama="Bu element yalnızca çok küçük miktarlarda üretilebilir ve yaklaşık 20 günde yarıya iner. Biriktirmek bu yüzden yıllar aldı."),
      kullanim=S("Aynştaynyumun günlük hayatta bir kullanım alanı olmamasının en önemli nedeni hangisidir?",
                 "Çok az miktarda üretilebilir ve kısa sürede bozunur; yalnızca araştırmalarda kullanılır",
                 Y("Çok ucuz olduğu için kimse ilgilenmez", "kanitsiz", "Element yalnızca birkaç yüz atomluk miktarlarda bulundu (hikâye); ucuz değil, elde edilmesi çok zor.", "K2"),
                 Y("Yarılanma süresi milyarlarca yıl olduğu için tehlikesiz ama işe yaramaz olduğu için", "veri", "Yarılanma süresi yaklaşık 20,5 gün (K1).", "K1"),
                 Y("Einstein'ın adını taşıdığı için kullanılması yasak olduğu için", "kanitsiz", "Bir elementin adı kullanımını yasaklamaz; bu iddiayı destekleyen bir kanıt yok.", "K2"),
                 ipucu="K1 ve K2: Ne kadar elde edilebiliyor, ne kadar dayanıyor?",
                 aciklama="Aynştaynyum ancak nükleer reaktörlerde miligramdan bile az miktarlarda üretilebilir ve hızla bozunur. Bu yüzden yalnızca bilimsel araştırmalarda, daha ağır elementler üretmek için kullanılır."),
      yapi="ozel", yapi_ozel=("atom_numarasi", "Çekirdek hesabı",
                              "Patlamada bazı uranyum çekirdekleri (atom numarası 92) çok sayıda nötron yakaladı. Ardından 7 beta bozunması oldu; her beta bozunmasında çekirdekteki bir nötron protona dönüşür."),
      konum_soru="Çekirdek hesabına ({yapi}) göre yeni elementin atom numarası kaç? Elementi periyodik tabloda bul ve işaretle.",
      konum_ipucu="Her beta bozunması proton sayısını 1 artırır. 92 + 7 = ?",
      konum_aciklama="Her beta bozunmasında bir nötron protona dönüşür ve atom numarası 1 artar. 7 bozunma sonunda 92 + 7 = 99: aynştaynyum (Es, atom numarası 99).",
      savunma_yapi="çekirdek hesabı ({yapi}) atom numarasının 92 + 7 = 99 olduğunu gösteriyor"),

    V("Fm", 1, "tarih", "Reaktördeki Son Durak",
      "Bir araştırma reaktöründe plütonyum yıllarca nötronlarla bombardıman ediliyor. Çekirdekler nötron yakaladıkça "
      "ağırlaşıyor, beta bozunmalarıyla bir üst elemente dönüşüyor. Ama bu yolla ulaşılabilen en ağır elementte zincir "
      "duruyor. Görevin: bu 'son durak' elementini bulmak.",
      [("deney", "Zincirin sonu", "Bu elementin bir sonraki izotopu bir saniyenin binde biri kadar kısa bir sürede kendiliğinden bölünüyor; bu yüzden daha fazla nötron yakalayıp ağırlaşamıyor."),
       ("tarih", "Keşif", "Element ilk kez 1952'deki termonükleer denemenin kalıntılarında bulundu. Adı, ilk nükleer reaktörü çalıştıran fizikçinin onuruna verildi.")],
      gozlem=S("Bir sonraki izotopun neredeyse anında bölünmesi (K1) zincirin neden burada durduğunu nasıl açıklar?",
               "Çekirdek yeni bir nötron yakalayıp ağırlaşmadan önce bölünüyor; bu yüzden daha ağır elementler bu yolla oluşamıyor.",
               Y("Reaktördeki nötronlar bitiyor.", "kanitsiz", "Kanıtlar zincirin durmasını çekirdeğin bölünmesine bağlıyor (K1); nötronların bittiğine dair bilgi yok.", "K1"),
               Y("Çekirdek çok kararlı olduğu için daha fazla nötron almıyor.", "veri", "Tam tersi: çekirdek çok kararsız, hemen bölünüyor (K1).", "K1"),
               ipucu="Bölünen bir çekirdek nötron yakalamaya devam edebilir mi?",
               aciklama="Bu elementin bir sonraki izotopu bir saniyenin binde birinden kısa sürede kendiliğinden bölünür. Bu yüzden nötron yakalama zinciri burada durur; daha ağır elementler ancak çekirdeklerin çarpıştırılmasıyla üretilebilir."),
      kullanim=S("Fermiyumun yalnızca araştırmalarda kullanılmasının nedeni hangisidir?",
                 "Ancak mikrogram miktarlarında üretilebilmesi ve izotoplarının kısa sürede bozunması",
                 Y("Doğada çok bol bulunduğu için değersiz olması", "kanitsiz", "Fermiyum doğada bulunmaz; reaktörlerde çok az miktarda üretilir.", "K2"),
                 Y("Hiç radyoaktif olmaması", "veri", "İzotopları kendiliğinden bölünüyor (K1); fermiyum radyoaktif.", "K1"),
                 Y("Adının Fermi'den gelmesi", "iliski", "Bir elementin adı, kullanım alanını belirlemez.", "K2"),
                 ipucu="K1 ve K2: Ne kadar ve ne kadar süreliğine elde edilebiliyor?",
                 aciklama="Fermiyum reaktörlerde yalnızca mikrogram miktarlarında üretilebilir ve hızla bozunur. Nötron yakalama yoluyla elde edilebilen en ağır element olduğu için bilim tarihinde özel bir yeri vardır.")),

    V("Pm", 1, "saglik", "Raptiye Büyüklüğünde Pil",
      "1970'lerde bazı kalp pillerinde ve askerî cihazlarda raptiye büyüklüğünde özel 'atom pilleri' kullanıldı. Bu pillerde "
      "radyoaktif bir element, ışıldayan bir maddeyi parlatıyor; bu ışık küçük bir güneş hücresiyle elektriğe çevriliyordu. "
      "Görevin: pildeki radyoaktif elementi bulmak.",
      [("deney", "Işıktan elektrik", "Pilin içindeki radyoaktif madde ışıldayan bir tozu sürekli parlatıyor; bu zayıf ışığa bakan küçük bir güneş hücresi elektrik üretiyor."),
       ("tarih", "Boş kutu", "Bu element, neodim ile samaryum arasında yer alan bir lantanit. Bütün izotopları radyoaktif ve en uzun ömürlüsünün yarılanma süresi yalnızca yaklaşık 18 yıl; bu yüzden Dünya'da doğal olarak bulunmuyor.")],
      gozlem=S("Pilde enerjinin hangi sırayla dönüştüğünü (K1) en iyi hangisi anlatır?",
               "Radyoaktif bozunma → ışık → elektrik",
               Y("Elektrik → ışık → radyoaktif bozunma", "veri", "Sıra ters yazılmış; enerji radyoaktif maddeden başlıyor (K1).", "K1"),
               Y("Yanma → ısı → elektrik", "iliski", "Pilde yanma yok; enerji radyoaktif bozunmadan geliyor (K1).", "K1"),
               ipucu="K1'deki cümleyi baştan sona izle.",
               aciklama="Radyoaktif maddenin ışınları ışıldayan tozu parlatır, güneş hücresi de bu ışığı elektriğe çevirir."),
      kullanim=S("Prometyumun doğada bulunmamasının nedeni hangisidir?",
                 "Bütün izotopları radyoaktiftir ve Dünya'nın yaşına göre çok kısa sürede bozunurlar",
                 Y("Çok hafif olduğu için atmosferden uzaya kaçtığı için", "iliski", "Prometyum ağır bir metaldir; bulunmamasının nedeni bozunmasıdır (K2).", "K2"),
                 Y("Bütün prometyum pillerde kullanılıp tükendiği için", "kanitsiz", "Prometyum insanlar kullanmadan önce de doğada yoktu (K2).", "K2"),
                 Y("Diğer lantanitlerle tepkimeye girip kaybolduğu için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; asıl neden kısa yarılanma süresi (K2).", "K2"),
                 ipucu="K2'deki yarılanma süresini Dünya'nın yaşıyla (yaklaşık 4,5 milyar yıl) karşılaştır.",
                 aciklama="Prometyumun en uzun ömürlü izotopunun yarılanma süresi yaklaşık 18 yıldır. Dünya oluştuğunda var olan prometyum çoktan bozundu. Bugün nükleer reaktörlerde üretilir.")),

    V("At", 1, "tarih", "Yeryüzünün En Nadir Elementi",
      "Bir müzedeki periyodik tablo sergisinde her elementin bir örneği var; ama bir kutu boş. Etikette 'Bu elementin "
      "gözle görülebilecek kadarı hiç toplanamadı' yazıyor. Görevin: boş kutunun elementini bulmak.",
      [("fiziksel", "Kısa ömür", "Elementin en kararlı izotoplarının yarılanma süresi yalnızca 8 saat kadar. Bu yüzden tartılabilecek miktarda hiç elde edilemedi."),
       ("kimyasal", "Kimyasal akrabası", "Kütle spektrometresiyle yapılan ölçümler, bu elementin diğer halojenler gibi, özellikle de iyot gibi davrandığını gösterdi.")],
      gozlem=S("Elementin yarılanma süresinin 8 saat kadar olması (K1) müzedeki kutunun neden boş olduğunu nasıl açıklar?",
               "Element üretilse bile kısa sürede bozunur; sergilenecek kadar biriktirilemez.",
               Y("Element renksiz olduğu için kutu boş görünüyor.", "kanitsiz", "Etikette elementin gözle görülebilecek kadarının hiç toplanamadığı yazıyor; renkle ilgili değil.", "K1"),
               Y("Element havada yandığı için kutuda durmuyor.", "kanitsiz", "Kanıtlar bozunmayı gösteriyor (K1); yanmaya dair bir bilgi yok.", "K1"),
               ipucu="8 saatte yarıya inen bir madde bir haftada ne kadar kalır?",
               aciklama="Bir haftada 21 yarılanma süresi geçer; madde başlangıçtakinin yaklaşık milyonda birine düşer. Bu yüzden bu element sergilenemez."),
      kullanim=S("Astatinin hangi gruba ait olduğu nasıl anlaşıldı?",
                 "Ölçümler kimyasal olarak iyota benzediğini gösterdi; periyodik tabloda da iyotun altında, halojenler grubunda yer alır",
                 Y("Gözle görülen rengine bakılarak", "veri", "Elementin gözle görülebilecek kadarı hiç toplanamadı (hikâye, K1).", "K1"),
                 Y("Tartılıp yoğunluğu ölçülerek", "veri", "Tartılabilecek miktarda hiç elde edilemedi (K1).", "K1"),
                 Y("Soy gazlar gibi hiç tepkimeye girmediği için", "veri", "Astatin bir halojen gibi davranıyor (K2); soy gaz değil.", "K2"),
                 ipucu="K2'de yapılan ölçümün sonucu yazıyor.",
                 aciklama="Astatin yer kabuğunda en az bulunan doğal elementtir. Çok az miktarlarla yapılan deneyler onun iyot gibi davrandığını gösterdi. Bugün yalnızca araştırmalarda, örneğin bazı kanser tedavisi çalışmalarında incelenir.")),

    V("Fr", 1, "tarih", "Doğanın Son Sırrı",
      "1939'da Paris'teki Curie Enstitüsü'nde çalışan Marguerite Perey, aktinyum örneklerinin beklenmedik bir ışıma "
      "yaptığını fark etti. İzini sürdüğü ışınım, doğada bulunan ve o güne kadar keşfedilmemiş son elementten geliyordu. "
      "Görevin: bu elementi bulmak.",
      [("kimyasal", "Kimyasal davranış", "Yeni element sezyum gibi davranıyor; alkali metaller grubunun en ağır üyesi."),
       ("fiziksel", "Kısa ömür", "En kararlı izotopunun yarılanma süresi yalnızca 22 dakika. Yer kabuğunun tamamında herhangi bir anda yalnızca çok küçük bir miktarı bulunuyor.")],
      gozlem=S("Elementin sezyum gibi davranması (K1) periyodik tablodaki yeri hakkında neyi gösterir?",
               "Sezyumla aynı grupta, yani alkali metallerin bulunduğu 1A grubunda yer alır.",
               Y("Sezyumla aynı periyotta yer alır.", "iliski", "Benzer kimyasal davranış aynı periyotta değil, aynı grupta olmanın sonucudur.", "K1"),
               Y("Soy gazların yanında yer alır.", "veri", "Element bir alkali metal (K1); soy gaz değil.", "K1"),
               ipucu="Periyodik tabloda benzer özellikteki elementler nasıl dizilir?",
               aciklama="Aynı gruptaki elementlerin son katmanlarındaki elektron sayısı aynıdır; bu yüzden kimyasal davranışları benzer. Bu element 1A grubunda, sezyumun altındadır."),
      kullanim=S("Fransiyumun hiçbir kullanım alanı olmamasının nedeni hangisidir?",
                 "En kararlı izotopunun bile yarılanma süresi 22 dakika olduğu için biriktirilemez",
                 Y("Hiç tepkimeye girmediği için", "veri", "Alkali metaller çok etkin metallerdir (K1).", "K1"),
                 Y("Çok zehirli olduğu için kullanılması yasak olduğu için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; asıl neden çok kısa ömrü (K2).", "K2"),
                 Y("Sezyumdan daha ucuz olduğu için kimse ilgilenmediği için", "kanitsiz", "Fransiyum biriktirilemediği için satın alınabilecek bir madde değil.", "K2"),
                 ipucu="K2'deki yarılanma süresine bak.",
                 aciklama="Fransiyum doğada keşfedilen son elementtir. Yarılanma süresi çok kısa olduğu için yalnızca birkaç atomuyla araştırma yapılabilir; hiçbir kullanım alanı yoktur.")),

    V("Ac", 1, "tarih", "Karanlıkta Mavi Parıltı",
      "1899'da Paris'te André Debierne, uranyum cevherinden çok güçlü ışınım yapan yeni bir element ayırdı. Bir ton cevherde "
      "bu elementten yalnızca yaklaşık 150 miligram bulunuyor. Elementin metali karanlıkta soluk mavi bir ışıkla parlıyor. "
      "Görevin: bu elementi bulmak.",
      [("fiziksel", "Mavi parıltı", "Metal karanlıkta soluk mavi parlıyor. Işık, metalin çok güçlü radyoaktifliğinin çevresindeki havayı uyarmasından kaynaklanıyor."),
       ("tarih", "Cevherdeki miktar", "Bir ton uranyum cevherinde (uranyum oksit) bu elementten yaklaşık 150 miligram var. Cevherden çıkan izotopun yarılanma süresi yaklaşık 22 yıl.")],
      gozlem=S("Bir ton cevherde yalnızca 150 miligram bulunması (K2) neyi gösterir?",
               "Element cevherde çok az bulunur; az miktar elde etmek için bile çok fazla cevher işlemek gerekir.",
               Y("Element cevherin yarısını oluşturur.", "veri", "150 miligram, bir tonun çok küçük bir bölümüdür (K2).", "K2"),
               Y("Cevher işlenince element çoğalır.", "kanitsiz", "Cevherin işlenmesi elementi çoğaltmaz; yalnızca ayırır.", "K2"),
               ipucu="Bir ton kaç miligramdır? (1 ton = 1 000 000 000 miligram)",
               aciklama="150 miligram, bir tonun yaklaşık on milyonda biridir. Bu yüzden bu tür nadir elementlerin keşfi tonlarca cevherin işlenmesini gerektirdi."),
      kullanim=S("Aktinyumun karanlıkta parlamasının nedeni hangisidir?",
                 "Çok güçlü radyoaktifliğinin çevresindeki havayı uyararak ışık yaydırması",
                 Y("Gündüz güneş ışığını depolayıp gece yayması", "veri", "Işık havayı uyaran radyoaktiflikten geliyor (K1); depolanmış güneş ışığından değil.", "K1"),
                 Y("Metalin havada yanması", "kanitsiz", "Kanıtlarda yanmaya dair bir bilgi yok; ışığın kaynağı radyoaktiflik (K1).", "K1"),
                 Y("Mavi renkli bir boyayla kaplanması", "kanitsiz", "Kanıtlarda boyadan söz edilmiyor; ışık metalin kendi radyoaktifliğinden geliyor (K1).", "K1"),
                 ipucu="K1'in ikinci cümlesine bak.",
                 aciklama="Aktinyum çok güçlü bir alfa ışını kaynağıdır; ışınları çevresindeki havayı uyarır ve soluk mavi bir ışık oluşur. Bugün yalnızca araştırmalarda, örneğin bazı kanser tedavisi çalışmalarında kullanılır.")),
]
