# -*- coding: utf-8 -*-
"""Seviye 2 (Çıkarım) — yeni vakalar, birinci bölüm."""
from sablon import S, V, Y

VAKALAR = [
    V("H", 2, "uzay", "Roketin Dev Deposu",
      "Bir uzay mekiğinin turuncu dış yakıt deposu müzede sergileniyor. Rehber, deponun içinde iki ayrı sıvı bulunduğunu "
      "anlatıyor: sıvı oksijen ve kütlesine göre en çok enerji veren yakıt. Görevin: bu yakıtın hangi element olduğunu bulmak.",
      [("kimyasal", "Motorun dumanı", "Yakıt sıvı oksijenle birlikte yakılıyor. Motorlardan çıkan beyaz bulutun büyük bölümü su buharı."),
       ("fiziksel", "Kilogram başına enerji", "Bu yakıtın bir kilogramı yandığında, bir kilogram benzinden yaklaşık üç kat fazla enerji veriyor.")],
      gozlem=S("Yakıtın kilogram başına çok enerji vermesi (K2) bir roket için neden önemlidir?",
               "Roket kalkarken taşıdığı yakıtı da kaldırmak zorunda; aynı enerji için daha az kütle taşımak gerekir.",
               Y("Roket ne kadar ağır olursa o kadar hızlı uçar.", "iliski", "Ağırlık arttıkça roketi kaldırmak için daha çok enerji gerekir; ağırlık hızı artırmaz.", "K2"),
               Y("Yakıtın enerjisi roketin rengini belirler.", "iliski", "Yakıtın enerjisiyle deponun rengi arasında bir neden-sonuç bağı yok.", "K2"),
               ipucu="Bir roketin kaldırması gereken kütlenin büyük bölümü nedir?",
               aciklama="Bir roketin kalkış kütlesinin çoğu yakıttır. Kilogram başına çok enerji veren bir yakıt, roketin daha hafif olmasını sağlar."),
      kullanim=S("Sıvı hidrojen roket yakıtı olarak neden seçilir?",
                 "Kilogram başına çok yüksek enerji verir ve oksijenle yanınca yalnızca su oluşur",
                 Y("Oda sıcaklığında sıvı olduğu için kolay saklandığı için", "veri", "Hidrojen ancak çok düşük sıcaklıkta sıvılaşır ({olcum}); oda sıcaklığında gazdır.", "{olcum}"),
                 Y("Yanmadığı için güvenli olduğu için", "veri", "Yakıt oksijenle yakılıyor (K1); hidrojen yanıcıdır.", "K1"),
                 Y("Çok ağır olduğu için roketi dengelediği için", "veri", "Hidrojen en hafif elementtir; seçilme nedeni kilogram başına enerjisi (K2).", "K2"),
                 ipucu="K1 ve K2'deki iki özelliği birleştir.",
                 aciklama="Hidrojen, kilogram başına bilinen en yüksek kimyasal enerjiyi veren yakıtlardan biridir ve oksijenle yanınca su oluşur. Ancak −253 °C'nin altında sıvı kaldığı için çok iyi yalıtılmış depolarda saklanması gerekir."),
      yapi="dizilim", adaylar=["He", "H", "Ne", "N"]),

    V("H", 2, "ev", "Suyun İkiye Ayrılması",
      "Fen dersinde öğretmen, içine biraz tuz katılmış suyun içinden elektrik geçirdi. İki elektrotta da kabarcıklar oluştu "
      "ve ters çevrilmiş iki tüpte iki farklı gaz toplandı. Görevin: eksi kutupta toplanan gazın hangi element olduğunu bulmak.",
      [("deney", "Gazların hacmi", "Eksi kutupta toplanan gazın hacmi, artı kutupta toplanan gazın hacminin iki katı.", "serbest"),
       ("deney", "Kibrit testi", "Eksi kutuptaki gazla dolu tüpün ağzına yanan bir kibrit yaklaştırılınca gaz 'pıt' sesiyle küçük bir patlamayla yandı.", "serbest")],
      gozlem=S("Eksi kutuptaki gazın hacminin diğerinin iki katı olması (K1) su molekülü hakkında neyi düşündürür?",
               "Su molekülünde bu elementin atomları, diğer elementin atomlarının iki katı kadar.",
               Y("İki gaz aynı elementtir.", "veri", "Gazlar farklı tüplerde toplandı ve kibrit testi yalnızca birinde 'pıt' sesi verdi (K2).", "K2"),
               Y("Eksi kutup daha çok elektrik harcadığı için daha çok gaz çıkar.", "iliski", "İki elektrottan aynı akım geçer; hacim farkı suyun yapısından kaynaklanır.", "K1"),
               ipucu="Su molekülünün formülünü düşün.",
               aciklama="Su ayrışınca bir elementten iki hacim, diğerinden bir hacim gaz oluşur. Bu, su molekülündeki atom oranını yansıtır."),
      kullanim=S("Hidrojen neden 'geleceğin temiz yakıtı' olarak görülüyor?",
                 "Sudan elde edilebilir ve yandığında yeniden su oluşur; karbondioksit açığa çıkmaz",
                 Y("Hiç enerji vermediği için doğaya zarar vermediği için", "iliski", "Hidrojen yanınca enerji verir (K2'deki küçük patlama bunu gösteriyor); temiz olmasının nedeni atığının su olması.", "K2"),
                 Y("Havadan ağır olduğu için atmosfere karışmadığı için", "veri", "Hidrojen en hafif gazdır.", "{tablo}"),
                 Y("Elektrolizde artı kutupta toplandığı için", "veri", "Bu gaz eksi kutupta toplandı (hikâye); üstelik toplandığı kutup, yakıt olmasının nedeni değildir.", "K1"),
                 ipucu="Hidrojen nereden elde edildi ve yanınca ne oluşur?",
                 aciklama="Hidrojen sudan elektrolizle elde edilebilir ve oksijenle yanınca yeniden su oluşturur. Elektrik güneş ya da rüzgârdan sağlanırsa bu döngü karbondioksit salınmadan işler."),
      yapi="izotop", izotop=1, adaylar=["He", "H", "Ne", "N"]),

    V("He", 2, "saglik", "MR Cihazının Soğuk Kalbi",
      "Bir hastanedeki MR cihazının mıknatısı, içindeki tellerin elektriğe hiç direnç göstermemesi için aşırı soğuk tutuluyor. "
      "Teknisyen, mıknatısı çevreleyen sıvı soğutucunun yavaş yavaş buharlaştığını ve düzenli olarak tamamlandığını söylüyor. "
      "Görevin: bu soğutucunun hangi elementin sıvı hâli olduğunu bulmak.",
      [("fiziksel", "Süper iletken teller", "Mıknatısın telleri ancak mutlak sıfırın (−273 °C) birkaç derece üzerine kadar soğutulunca elektriğe hiç direnç göstermiyor."),
       ("kimyasal", "Buharlaşan gaz", "Soğutucudan buharlaşan gaz renksiz, kokusuz ve hiçbir maddeyle tepkimeye girmiyor.")],
      gozlem=S("Tellerin mutlak sıfıra çok yakın bir sıcaklıkta tutulması gerekmesi (K1) soğutucu hakkında neyi gösterir?",
               "Soğutucu sıvının kaynama noktası son derece düşük olmalı.",
               Y("Soğutucu çok yüksek sıcaklıkta kaynamalı.", "veri", "Yüksek sıcaklıkta kaynayan bir sıvı telleri bu kadar soğuk tutamaz (K1).", "K1"),
               Y("Soğutucu elektriği iyi iletmeli.", "iliski", "Soğutucunun görevi telleri soğutmak; elektriği teller iletir.", "K1"),
               ipucu="Bir sıvı, kaynama noktasının altında kalan bir şeyi soğutabilir.",
               aciklama="Bir sıvı kaynarken sıcaklığı sabit kalır. Telleri −269 °C'de tutabilen bir soğutucunun kaynama noktası da o kadar düşük olmalıdır."),
      kullanim=S("Helyum MR cihazlarında neden soğutucu olarak kullanılır?",
                 "Bütün maddeler içinde en düşük kaynama noktasına sahip olduğu için mıknatısı mutlak sıfıra çok yakın sıcaklıklarda tutabilir",
                 Y("Havadan hafif olduğu için cihazı hafiflettiği için", "iliski", "Hafiflik balonlarda işe yarar; MR'da önemli olan çok düşük kaynama noktası ({olcum}).", "{olcum}"),
                 Y("Elektriği çok iyi ilettiği için", "iliski", "Elektriği süper iletken teller iletir; helyumun görevi soğutmaktır (K1).", "K1"),
                 Y("Tellerle tepkimeye girip onları güçlendirdiği için", "veri", "Helyum hiçbir maddeyle tepkimeye girmez (K2).", "K2"),
                 ipucu="Tabloda kaynama noktalarını karşılaştır.",
                 aciklama="Sıvı helyum −269 °C'de kaynar; hiçbir madde bu kadar düşük sıcaklıkta kaynamaz. Bu yüzden MR cihazlarının ve parçacık hızlandırıcılarının süper iletken mıknatıslarını soğutmakta kullanılır."),
      yapi="dizilim", adaylar=["H", "He", "Ne", "N"]),

    V("Be", 2, "uzay", "Uzay Teleskobunun Aynası",
      "James Webb Uzay Teleskobu'nun 6,5 metrelik ana aynası, 18 altıgen parçadan oluşuyor. Mühendisler parçaları çok hafif "
      "ve çok sert bir metalden yapıp üzerlerini ince bir altın tabakasıyla kapladı. Görevin: ayna parçalarının metalini bulmak.",
      [("fiziksel", "Ayna parçaları", "Her parça hafif ama çok sert bir metalden yapılmış; ışığı yansıtan yüzey, metalin üzerindeki ince altın tabakası."),
       ("fiziksel", "Soğukta şekil", "Teleskobun aynaları yaklaşık −220 °C'de çalışıyor. Aynanın metali bu soğukta bile şeklini neredeyse hiç değiştirmiyor.")],
      gozlem=S("Ayna parçalarının üzerine ince bir altın tabakası kaplanması (K1) neyi gösterir?",
               "Işığı yansıtma işini altın yapıyor; aynanın ana metali ise başka bir özelliği için seçilmiş.",
               Y("Aynanın tamamı altından yapılmış.", "veri", "Altın yalnızca yüzeydeki ince tabaka; parçalar başka bir metalden (K1).", "K1"),
               Y("Altın, teleskobu daha ağır ve dengeli yapmak için kaplanmış.", "iliski", "Tabaka çok ince; amacı ağırlık değil, ışığı yansıtmak.", "K1"),
               ipucu="Bir aynada ışığı hangi kısım yansıtır?",
               aciklama="Altın, teleskobun gözlediği kızılötesi ışığı çok iyi yansıtır. Aynanın ana metali ise hafifliği, sertliği ve soğukta şeklini koruması için seçildi."),
      kullanim=S("Berilyum bu teleskobun aynasında neden kullanıldı?",
                 "Çok hafif ve sert olduğu, aşırı soğukta bile şeklini koruduğu için",
                 Y("Işığı çok iyi yansıttığı için", "veri", "Işığı yansıtan, üzerindeki altın tabakası (K1).", "K1"),
                 Y("Soğukta büzülüp aynayı küçülttüğü için", "veri", "Metal soğukta şeklini neredeyse hiç değiştirmiyor (K2).", "K2"),
                 Y("Çok yoğun olduğu için teleskobu sarsıntılara karşı sabitlediği için", "veri", "Ölçülen yoğunluk ({olcum}) çok düşük; berilyum çok hafif bir metaldir.", "{olcum}"),
                 ipucu="K1, K2 ve ölçümü birlikte düşün.",
                 aciklama="Berilyum alüminyumdan bile hafif ama çok daha serttir ve çok düşük sıcaklıklarda neredeyse hiç genleşip büzülmez. Uzaya fırlatılacak dev bir aynanın hem hafif olması hem de soğukta kusursuz şeklini koruması gerekiyordu."),
      yapi="dizilim", adaylar=["Li", "Be", "B", "Mg"],
      kaynak=["NASA, Webb Uzay Teleskobu: Webb's Mirrors — https://science.nasa.gov/mission/webb/webbs-mirrors/"]),

    V("B", 2, "enerji", "Reaktörün Frenleri",
      "Bir nükleer santralin soğutma suyuna, nötronları güçlü biçimde yutan bir elementin bileşiği katılıyor. Mühendis, "
      "bu bileşiğin miktarını ayarlayarak reaktördeki tepkimenin hızını denetlediklerini söylüyor. Görevin: bu elementi bulmak.",
      [("kimyasal", "Nötron yutan madde", "Suya katılan madde bu elementin bir asidi. Elementin bir izotopu nötronları çok iyi yutuyor."),
       ("kimyasal", "Günlük hayattaki akrabaları", "Aynı elementin bileşikleri göz damlalarında, hafif antiseptiklerde ve ısıya dayanıklı camlarda da bulunuyor.")],
      gozlem=S("Soğutma suyuna nötron yutan bir madde katılması (K1) reaktörde ne işe yarar?",
               "Bölünmeleri sürdüren nötronların bir kısmını yutarak zincirleme tepkimeyi yavaşlatır.",
               Y("Nötron sayısını artırıp tepkimeyi hızlandırır.", "veri", "Madde nötronları yutuyor (K1); yutulan nötron sayısı azalır.", "K1"),
               Y("Suyu ısıtarak buhar üretir.", "iliski", "Isıyı çekirdek bölünmesi üretir; bu maddenin görevi nötronları yutmak (K1).", "K1"),
               ipucu="Zincirleme tepkimeyi ne sürdürür?",
               aciklama="Zincirleme tepkimeyi nötronlar sürdürür. Nötronların bir kısmı yutulursa daha az bölünme olur ve tepkime yavaşlar."),
      kullanim=S("Bor nükleer santrallerde neden kullanılır?",
                 "Bor-10 izotopu nötronları çok iyi yutar; böylece zincirleme tepkime denetim altında tutulur",
                 Y("Bor yanınca santrale ek enerji verdiği için", "iliski", "Bor santralde yakılmaz; görevi nötronları yutmak (K1).", "K1"),
                 Y("Bor radyasyonu artırdığı için", "veri", "Bor nötronları yutarak tepkimeyi yavaşlatır (K1); radyasyonu artırmaz.", "K1"),
                 Y("Bor ısıya dayanıklı cam yaptığı için reaktörü yalıttığı için", "iliski", "Isıya dayanıklı cam borun başka bir kullanımıdır (K2); reaktördeki görevi nötron yutmak.", "K2"),
                 ipucu="K1'deki özellik reaktörde neyi denetler?",
                 aciklama="Bor-10 izotopu nötronları çok iyi yutar. Bu yüzden borik asit soğutma suyuna katılır, bor karbür de kontrol çubuklarında kullanılır. Türkiye dünyanın en büyük bor rezervlerine sahiptir."),
      yapi="dizilim", adaylar=["Be", "B", "Al", "Si"], ozellik="erime"),

    V("C", 2, "ev", "Musluktaki Siyah Taneler",
      "Bir ailenin musluğuna takılan su arıtma filtresinin içinden siyah, gözenekli taneler çıktı. Filtre, çeşme suyundaki "
      "kötü koku ve tadı gideriyormuş. Görevin: tanelerin hangi elementten oluştuğunu bulmak.",
      [("fiziksel", "Dev iç yüzey", "Tanelerin içi sünger gibi gözenekli. Bir gram tanenin iç yüzey alanı birkaç yüz metrekareyi buluyor."),
       ("deney", "Yakma deneyi", "Taneler yakılınca geriye neredeyse hiç kül kalmadı. Çıkan gaz kireç suyunu bulandırdı.", "serbest")],
      gozlem=S("Bir gram tanenin iç yüzeyinin birkaç yüz metrekare olması (K1) neyi gösterir?",
               "Taneler çok gözenekli; maddelerin tutunabileceği çok geniş bir yüzeyleri var.",
               Y("Taneler suda çözünüyor.", "kanitsiz", "Kanıtlarda tanelerin çözündüğüne dair bir bilgi yok; yüzey alanı gözeneklilikten geliyor.", "K1"),
               Y("Taneler çok ağır.", "iliski", "Yüzey alanı ağırlığı göstermez; tanelerin içindeki gözeneklerin çokluğunu gösterir.", "K1"),
               ipucu="Bir sünger neden çok su tutar?",
               aciklama="Gözenekli bir maddenin içinde sayısız minik kanal vardır. Bu kanalların duvarları çok geniş bir yüzey oluşturur."),
      kullanim=S("Aktif karbon su filtrelerinde neden kullanılır?",
                 "Çok gözenekli yapısı, sudaki koku ve tat veren maddeleri yüzeyinde tutar",
                 Y("Suyu kaynatarak mikropları öldürdüğü için", "iliski", "Filtre suyu kaynatmaz; maddeleri yüzeyinde tutar (K1).", "K1"),
                 Y("Suya karbon ekleyerek tadını güzelleştirdiği için", "iliski", "Aktif karbon suya bir şey eklemez, sudaki maddeleri tutar.", "K1"),
                 Y("Suda çözünüp kirleri dibe çöktürdüğü için", "kanitsiz", "Tanelerin suda çözündüğüne dair bir kanıt yok.", "K1"),
                 ipucu="K1'deki dev yüzey ne işe yarar?",
                 aciklama="Aktif karbon, karbonlu maddelerin özel olarak işlenmesiyle elde edilir ve çok gözeneklidir. Sudaki ya da havadaki birçok maddeyi yüzeyine tutar (adsorpsiyon). Su filtrelerinde ve gaz maskelerinde kullanılır."),
      yapi="dizilim", olcum=False),

    V("N", 2, "tarih", "Havadan Ekmek",
      "1909'da Alman kimyacı Fritz Haber, havada bol bulunan bir gazı hidrojenle birleştirerek amonyak elde etmeyi başardı. "
      "Bugün vücudumuzdaki bu elementin yaklaşık yarısı, bu yöntemle üretilen gübrelerle yetişen besinlerden geliyor. Görevin: "
      "Haber'in havadan aldığı gazın elementini bulmak.",
      [("tarih", "Haber'in tepkimesi", "Gaz, yüksek basınç ve sıcaklıkta, demir katalizör üzerinde hidrojenle birleşip amonyak oluşturuyor."),
       ("kimyasal", "Bitkilerin sorunu", "Bu gaz havanın yaklaşık %78'ini oluşturuyor; ama bitkilerin çoğu onu havadan doğrudan alamıyor.", "serbest")],
      gozlem=S("Bitkilerin bu gazı havadan doğrudan alamaması (K2) gübreyi neden gerekli kılar?",
               "Bitkiler bu elementi topraktaki bileşiklerden almak zorunda; toprakta azalınca gübreyle eklenmesi gerekir.",
               Y("Bitkiler bu elemente hiç ihtiyaç duymaz.", "kanitsiz", "Gübrenin ürünleri artırdığı biliniyor (hikâye); bitkilerin bu elemente ihtiyacı var.", "K2"),
               Y("Gübre havadaki gazı yok eder.", "iliski", "Gübre havadaki gazı yok etmez; elementi bitkinin alabileceği bir biçimde toprağa verir.", "K2"),
               ipucu="Bitki bu elementi havadan alamıyorsa nereden alır?",
               aciklama="Bitkiler proteinleri için bu elemente ihtiyaç duyar ama onu çoğunlukla topraktaki bileşiklerden alır. Hasatla topraktan çekilen miktar gübreyle geri verilir."),
      kullanim=S("Haber'in buluşu neden 'havadan ekmek' olarak anıldı?",
                 "Havadaki azot gübreye dönüştürülerek tahıl yetiştirmede kullanılabilir hâle geldi",
                 Y("Haber havadan doğrudan un elde ettiği için", "iliski", "Haber havadaki gazdan amonyak elde etti (K1); un değil.", "K1"),
                 Y("Azot ekmeğin kabarmasını sağladığı için", "kanitsiz", "Ekmeğin kabarması başka bir olaydır; buluşun önemi gübre üretimidir (K1).", "K1"),
                 Y("Azot havada çok az bulunduğu için değerli olduğu için", "veri", "Azot havanın yaklaşık %78'ini oluşturur (K2).", "K2"),
                 ipucu="Amonyak neye dönüştürülüyor?",
                 aciklama="Haber–Bosch yöntemiyle havadaki azot, hidrojenle birleştirilip amonyağa dönüştürülür. Amonyaktan yapılan gübreler tarımda verimi büyük ölçüde artırdı."),
      yapi="dizilim", adaylar=["N", "O", "F", "Ne"]),

    V("O", 2, "cevre", "Gökyüzündeki Görünmez Kalkan",
      "Atmosferin 15–35 kilometre yükseklikleri arasında, bir elementin üç atomlu moleküllerinin yoğunlaştığı bir tabaka var. "
      "1980'lerde bu tabakanın Antarktika üzerinde inceldiği fark edildi ve dünya ülkeleri bazı kimyasalları yasakladı. "
      "Görevin: bu üç atomlu molekülü oluşturan elementi bulmak.",
      [("kimyasal", "Üç atomlu molekül", "Tabakadaki moleküller aynı elementin üç atomundan oluşuyor. Soluduğumuz havadaki iki atomlu molekülleri de aynı element oluşturuyor."),
       ("fiziksel", "Tabakanın görevi", "Bu moleküller Güneş'ten gelen zararlı morötesi ışınların çoğunu soğuruyor.")],
      gozlem=S("Aynı elementin hem iki hem üç atomlu molekül oluşturması (K1) neyi gösterir?",
               "Bir element, atomlarının farklı sayıda bağlanmasıyla özellikleri farklı molekül biçimleri oluşturabilir.",
               Y("İki molekül farklı elementlerden oluşur.", "veri", "K1'e göre iki molekül de aynı elementten oluşuyor.", "K1"),
               Y("Üç atomlu molekül bir karışımdır.", "veri", "Tek bir elementin atomlarından oluşan molekül saf bir maddedir; karışım değildir.", "K1"),
               ipucu="Elmas ve grafit de aynı elementin farklı biçimleridir.",
               aciklama="Aynı elementin farklı yapıdaki biçimlerine allotrop denir. Üç atomlu biçim (ozon) ile iki atomlu biçimin özellikleri çok farklıdır."),
      kullanim=S("Ozon tabakası canlılar için neden önemlidir?",
                 "Güneşin zararlı morötesi ışınlarının çoğunu soğurarak yeryüzündeki canlıları korur",
                 Y("Soluduğumuz oksijeni üretir", "iliski", "Soluduğumuz oksijeni bitkiler üretir; ozon tabakasının görevi morötesi ışınları soğurmak (K2).", "K2"),
                 Y("Dünya'yı ısıtarak donmayı önler", "kanitsiz", "Kanıtlar tabakanın morötesi ışınları soğurduğunu söylüyor (K2); Dünya'yı ısıtma görevinden söz etmiyor.", "K2"),
                 Y("Yağmur bulutlarını oluşturur", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K2"),
                 ipucu="K2'de tabakanın görevi yazıyor.",
                 aciklama="Ozon (O₃) morötesi ışınları soğurur. 1980'lerde bazı soğutucu gazların (CFC'ler) ozonu yok ettiği anlaşıldı; 1987'de imzalanan Montreal Protokolü ile bu gazlar yasaklandı ve tabaka yavaş yavaş iyileşiyor."),
      yapi="dizilim", adaylar=["N", "O", "F", "Ar"]),

    V("Na", 2, "ev", "Keki Kabartan Toz",
      "Bir pastacı, kek hamuruna bir kaşık beyaz toz katınca kekin fırında iki katına kadar kabardığını gösterdi. Paketin "
      "üzerinde tozun kimyasal adının yalnızca ikinci kısmı okunabiliyor: '... hidrojen karbonat'. Görevin: tozdaki metali bulmak.",
      [("deney", "Sirke testi", "Toz sirkeyle karışınca köpürerek gaz çıkardı. Kek hamurunda da fırında ısınınca aynı gazın kabarcıkları oluşuyor."),
       ("kimyasal", "Etiket", "Tozun kimyasal adı '... hidrojen karbonat'; ilk kelime, tozdaki metalin adı.")],
      gozlem=S("Tozun sirkeyle köpürmesi (K1) keki kabartma işini nasıl açıklar?",
               "Toz gaz kabarcıkları oluşturuyor; hamura hapsolan kabarcıklar keki şişiriyor.",
               Y("Toz hamuru ısıtarak pişiriyor.", "iliski", "Hamuru fırın pişirir; tozun görevi gaz üretmek (K1).", "K1"),
               Y("Toz suyu emerek hamuru büyütüyor.", "kanitsiz", "Kanıtlar tozun gaz çıkardığını gösteriyor (K1); su emdiğine dair bir bilgi yok.", "K1"),
               ipucu="Köpürme neyin işaretidir?",
               aciklama="Karbonatlar asitle ya da ısıyla karbondioksit gazı çıkarır. Hamurun içinde oluşan gaz kabarcıkları kekin kabarmasını sağlar."),
      kullanim=S("Kabartma tozu (sodyum hidrojen karbonat) keki nasıl kabartır?",
                 "Isınınca ya da asitle karşılaşınca karbondioksit gazı çıkarır; kabarcıklar hamuru şişirir",
                 Y("Sodyum metali hamurda yanarak ısı verdiği için", "iliski", "Tozda metal sodyum değil, sodyum bileşiği var; kabarma gaz çıkışıyla olur (K1).", "K1"),
                 Y("Hamura tuz tadı vererek mayalanmayı hızlandırdığı için", "kanitsiz", "Kanıtlar tozun gaz çıkardığını gösteriyor (K1); mayalanmayla ilgili bir kanıt yok.", "K1"),
                 Y("Alevi sarıya boyadığı için fırını daha sıcak yaptığı için", "iliski", "Alev rengi bir tanıma testidir ({olcum}); fırının sıcaklığını değiştirmez.", "{olcum}"),
                 ipucu="K1'deki gazı düşün.",
                 aciklama="Sodyum hidrojen karbonat (NaHCO₃) ısınınca ya da asitlerle karşılaşınca karbondioksit gazı çıkarır. Kek hamurunda oluşan bu gaz kabarcıkları keki kabartır."),
      yapi="iyon",
      tablo_ozel=dict(
          baslik="Bazı elementlerin alev testi renkleri",
          satirlar=[["Element", "Alev testi rengi"], ["Lityum", "Koyu kırmızı"], ["Sodyum", "Parlak turuncu-sarı"],
                    ["Potasyum", "Lila (açık mor)"], ["Kalsiyum", "Turuncu-kırmızı"], ["Bakır", "Mavi-yeşil"]],
          olcum=("Alev testi", "Kabartma tozu alevin üzerine serpilince alev parlak turuncu-sarı renkte yandı.", "deney"),
          soru="Alev testine ({olcum}) ve tabloya ({tablo}) göre kabartma tozundaki metal hangisidir?",
          ipucu="Gözlenen alev rengini tablodaki renklerle karşılaştır.",
          aciklama="Parlak turuncu-sarı alev rengi sodyuma özgüdür. Bu test, iyon analiziyle bulduğun sonucu destekliyor.",
          dogru="Sodyum",
          secenekler=[("Lityum", "Lityum alevi koyu kırmızıya boyar ({tablo}); gözlenen renk turuncu-sarıydı.", "veri"),
                      ("Sodyum", "", ""),
                      ("Potasyum", "Potasyum alevi lilaya boyar ({tablo}).", "veri"),
                      ("Kalsiyum", "Kalsiyum alevi turuncu-kırmızıya boyar ({tablo}); sodyumun parlak turuncu-sarısından farklıdır.", "veri")],
          savunma="alev testinde görülen parlak turuncu-sarı renk ({olcum}) yalnızca sodyumla uyumlu")),

    V("Mg", 2, "cevre", "Yaprağın Yeşil Kalbi",
      "Bir bahçıvan, domates fidelerinin yapraklarının damarların arasından sarardığını fark etti. Tarım danışmanı toprağa bir "
      "elementin tuzunu eklemesini önerdi; birkaç hafta sonra yeni yapraklar koyu yeşil çıktı. Görevin: bu elementi bulmak.",
      [("deney", "Bahçe deneyi", "Tuz eklenen fidelerin yeni yaprakları yeşil çıktı; tuz eklenmeyen fidelerde sararma devam etti."),
       ("kimyasal", "Klorofilin merkezi", "Yaprağa yeşil rengini veren klorofil molekülünün tam ortasında bu elementin bir iyonu bulunuyor.")],
      gozlem=S("Tuz eklenen ve eklenmeyen fidelerin karşılaştırılması (K1) neyi gösterir?",
               "Sararmanın nedeni bu elementin eksikliği; element eklenince sorun düzeliyor.",
               Y("Fideler daha çok sulandığı için yeşillendi.", "kanitsiz", "İki grup arasındaki fark tuzdu (K1); sulamanın değiştiğine dair bir kanıt yok.", "K1"),
               Y("Tuz eklemek her bitkiyi yeşillendirir.", "kanitsiz", "Deney yalnızca bu fidelerdeki sararmayı inceledi; her bitki için genelleme yapmaya yetmez.", "K1"),
               ipucu="İki grup arasındaki tek fark neydi?",
               aciklama="Bir deneyde yalnızca bir şey değiştirilirse (burada eklenen tuz), sonuçtaki fark o değişikliğe bağlanabilir. Buna kontrollü deney denir."),
      kullanim=S("Bitkiler magnezyuma neden ihtiyaç duyar?",
                 "Işığı yakalayıp fotosentez yapan klorofil molekülünün merkezinde magnezyum bulunur",
                 Y("Magnezyum bitkiyi böceklerden korur", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; magnezyum klorofilin merkezinde (K2).", "K2"),
                 Y("Magnezyum yaprakları sarıya boyar", "veri", "Tam tersi: magnezyum eksik olunca yapraklar sarardı (K1).", "K1"),
                 Y("Magnezyum toprağı yumuşatır", "kanitsiz", "Kanıtlar magnezyumun yaprağın yeşil rengindeki görevini gösteriyor (K2).", "K2"),
                 ipucu="K2'yi oku.",
                 aciklama="Klorofil molekülünün merkezinde bir magnezyum iyonu bulunur. Magnezyum eksik olunca klorofil azalır ve yapraklar damarların arasından sararır. Bu durum magnezyum sülfat gibi gübrelerle düzeltilir."),
      yapi="iyon", adaylar=["Na", "Mg", "Al", "Ca"]),

    V("Al", 2, "sanayi", "Rayların Ateşli Kaynağı",
      "Gece yarısı demiryolu işçileri iki rayın arasına küçük bir kalıp yerleştirip içine gri bir toz karışımı döktü. Karışım "
      "tutuşturulunca göz kamaştıran bir ışıkla yandı ve birkaç saniyede kalıba akkor hâlinde sıvı demir aktı; iki ray "
      "birbirine kaynadı. Görevin: karışımdaki gümüşi metal tozunun elementini bulmak.",
      [("deney", "Yanma", "Karışım birkaç saniyede yandı; o kadar çok ısı açığa çıktı ki oluşan demir sıvı hâle geldi."),
       ("kimyasal", "Karışımın içeriği", "Karışımda demir oksit ve gümüşi bir metalin tozu var. Bu metal, demir oksitteki oksijeni koparıp alıyor ve kendisi oksit oluyor.")],
      gozlem=S("Tepkimede oluşan demirin sıvı hâlde çıkması (K1) neyi gösterir?",
               "Tepkime çok büyük bir ısı açığa çıkarıyor; sıcaklık demirin erime noktasını aşıyor.",
               Y("Demir oda sıcaklığında sıvıdır.", "veri", "Demir oda sıcaklığında katıdır; sıvı çıkmasının nedeni tepkimenin ısısı (K1).", "K1"),
               Y("Tepkime ısı çekiyor.", "veri", "Isı çeken bir tepkime demiri eritemezdi; tepkime ısı veriyor (K1).", "K1"),
               ipucu="Demirin erime noktası 1500 °C'nin üzerinde.",
               aciklama="Demir 1538 °C'de erir. Tepkimeden sıvı demir çıkması, açığa çıkan ısının sıcaklığı bu değerin üstüne çıkardığını gösterir."),
      kullanim=S("Termit kaynağında alüminyum tozu neden kullanılır?",
                 "Alüminyum oksijene demirden daha çok ilgi duyar; demir oksitten oksijeni alırken çok büyük bir ısı açığa çıkar",
                 Y("Alüminyum erimiş demiri soğuttuğu için", "veri", "Tepkime ısı veriyor ve demiri eritiyor (K1); alüminyum soğutmuyor.", "K1"),
                 Y("Alüminyum mıknatıs olduğu için rayları bir arada tuttuğu için", "iliski", "Raylar mıknatısla değil, sıvı demirle kaynıyor (K1).", "K1"),
                 Y("Alüminyum ağır olduğu için kalıbı sabitlediği için", "veri", "Ölçülen yoğunluk ({olcum}) düşük; alüminyum hafif bir metaldir.", "{olcum}"),
                 ipucu="K2'de metalin demir oksite ne yaptığı yazıyor.",
                 aciklama="Termit tepkimesinde alüminyum, demir oksitteki oksijeni alır: alüminyum oksit ve demir oluşur. Tepkime o kadar çok ısı verir ki demir eriyerek kalıba akar ve rayları birleştirir."),
      yapi="dizilim", adaylar=["Mg", "Al", "Si", "Ti"]),

    V("Si", 2, "teknoloji", "Çipin Kalbi",
      "Bir bilgisayar çipi fabrikasında, ayna gibi parlayan ince kristal diskler üretiliyor. Mühendis, disklerin bilinen en "
      "saf maddelerden biri olduğunu ve üzerlerine milyarlarca minik elektronik anahtar yerleştirildiğini anlatıyor. "
      "Görevin: disklerin elementini bulmak.",
      [("kimyasal", "Aşırı saflık", "Disk %99,9999999 saflıkta. Yalnızca belirli bölgelerine çok az miktarda bor ya da fosfor katılıyor."),
       ("iletkenlik", "Ne iletken ne yalıtkan", "Bu madde elektriği metaller kadar iyi iletmiyor ama yalıtkanlar kadar kötü de iletmiyor. İletkenliği katkı maddeleriyle ayarlanabiliyor.")],
      gozlem=S("Maddenin iletkenliğinin katkı maddeleriyle ayarlanabilmesi (K2) neden önemlidir?",
               "Aynı malzemenin farklı bölgeleri farklı iletkenlikte yapılarak akımı açıp kapayan elektronik anahtarlar üretilebilir.",
               Y("Katkı maddeleri diski daha parlak yapar.", "iliski", "Katkı maddeleri iletkenliği ayarlamak için eklenir (K2); parlaklık için değil.", "K2"),
               Y("Katkı maddeleri diski yalıtkan yapar.", "veri", "Katkı maddeleri iletkenliği ayarlar (K2); maddeyi tamamen yalıtkan yapmak amaç değil.", "K2"),
               ipucu="Bir elektronik anahtar ne yapar?",
               aciklama="Yarı iletkenlerin iletkenliği katkı maddeleriyle ayarlanır. Böylece transistör denilen ve akımı açıp kapayan minik anahtarlar yapılır; bir çipte milyarlarca transistör vardır."),
      kullanim=S("Silisyum bilgisayar çiplerinde neden kullanılır?",
                 "Yarı iletkendir, iletkenliği katkı maddeleriyle ayarlanır ve kumdan bol miktarda elde edilir",
                 Y("Elektriği bakırdan daha iyi ilettiği için", "veri", "Silisyum elektriği metaller kadar iyi iletmez (K2).", "K2"),
                 Y("Hiç elektrik iletmediği için çipi yalıttığı için", "veri", "Silisyum bir yarı iletkendir; elektriği bir miktar iletir (K2).", "K2"),
                 Y("Çok yoğun olduğu için çipi sağlamlaştırdığı için", "iliski", "Yoğunluk çipin çalışmasını açıklamaz; önemli olan iletkenliğinin ayarlanabilmesi (K2).", "K2"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Silisyum yarı iletkendir: bor ya da fosfor gibi katkılarla iletkenliği tam istenen değere ayarlanabilir. Çok saf olarak üretilebilir ve hammaddesi (kum) çok boldur. Bu yüzden elektronik çağına 'silisyum çağı' da denir."),
      yapi="dizilim", adaylar=["Al", "Si", "P", "Ge"]),

    V("P", 2, "saglik", "Kalıtımın Omurgası",
      "Bir biyoloji laboratuvarında öğrenciler muzdan DNA çıkardı. Öğretmen, DNA molekülünün sarmal merdivenine benzeyen "
      "yapısının 'korkuluklarının' şeker ve bir elementin oksijenle oluşturduğu gruplardan yapıldığını anlattı. Görevin: bu elementi bulmak.",
      [("kimyasal", "DNA'nın omurgası", "DNA zincirinin omurgası, şeker molekülleri ile bu elementin dört oksijen atomuyla oluşturduğu grupların art arda dizilmesinden oluşuyor."),
       ("kimyasal", "Hücrenin enerji parası", "Hücrelerin enerji taşıyıcı molekülü ATP'de bu elementin üç grubu art arda bağlı. Enerji, bu grupların arasındaki bağ koparken açığa çıkıyor.")],
      gozlem=S("Bu elementin hem DNA'da hem de ATP'de bulunması (K1, K2) neyi gösterir?",
               "Element hem kalıtım hem de enerji aktarımı için canlılarda vazgeçilmez.",
               Y("Element yalnızca bitkilerde bulunur.", "kanitsiz", "DNA ve ATP bütün canlılarda bulunur; muz örneği bu elementin yalnızca bitkilerde olduğunu göstermez.", "K1"),
               Y("Element canlılar için zehirlidir.", "veri", "Element DNA ve ATP'nin yapısında; canlılar için gerekli (K1, K2).", "K2"),
               ipucu="DNA ve ATP her canlıda var mı?",
               aciklama="Bütün canlılar kalıtım bilgisini DNA'da saklar ve enerjiyi ATP ile taşır. İkisinde de bu elementin oksijenli grupları bulunur."),
      kullanim=S("Fosfatlı gübreler tarımda neden kullanılır?",
                 "Bitkiler DNA, ATP ve hücre zarları için fosfora ihtiyaç duyar; hasatla topraktan çekilen fosfor gübreyle geri verilir",
                 Y("Fosfor bitkileri karanlıkta parlattığı için", "iliski", "Beyaz fosforun parlaması başka bir olaydır; gübredeki fosfat bitkinin yapı taşıdır (K1, K2).", "K1"),
                 Y("Fosfor toprağı ısıttığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K2"),
                 Y("Bitkiler fosforu havadan bol miktarda alabildiği için", "kanitsiz", "Bitkiler fosforu havadan almaz; topraktaki fosfatlardan alır.", "K1"),
                 ipucu="K1 ve K2'de fosforun canlılardaki görevleri yazıyor.",
                 aciklama="Fosfor bileşiklerinin en büyük kullanım alanı gübrelerdir. Ancak fazla fosfat göllere ve denizlere karışırsa yosunların aşırı çoğalmasına yol açabilir."),
      yapi="dizilim", adaylar=["Al", "Si", "P", "S"]),

    V("S", 2, "ev", "Soğanın Gözyaşı",
      "Mutfakta soğan doğrayan herkesin gözleri yaşarıyor. Bir öğrenci bunun nedenini araştırdı: soğan hücreleri kesilince "
      "uçucu bir gaz açığa çıkıyor ve bu gaz gözdeki sıvıya ulaşınca tahriş ediyor. Görevin: gazın içindeki kilit elementi bulmak.",
      [("deney", "Uçucu gaz", "Soğan kesilince hücrelerindeki maddeler karışıp hızla buharlaşan bir gaz oluşturuyor; gaz göze ulaşınca göz yaşarıyor."),
       ("kimyasal", "Gazın bileşimi", "Gazın molekülünde karbon, hidrojen ve oksijenin yanında, sarımsağa ve çürük yumurtaya da kokusunu veren bir element bulunuyor.")],
      gozlem=S("Göz yaşarmasının ancak soğan kesilince başlaması (K1) neyi gösterir?",
               "Gaz, hücreler parçalanınca içlerindeki maddelerin karışmasıyla oluşuyor.",
               Y("Gaz soğanın kabuğunda hazır bekliyor.", "veri", "Bütün soğan göz yaşartmıyor; gaz ancak kesilince oluşuyor (K1).", "K1"),
               Y("Göz yaşaran bıçağın metalinden.", "kanitsiz", "Gözü tahriş eden, soğandan çıkan gaz (K1); bıçağın metali değil.", "K1"),
               ipucu="Bütün bir soğan masada dururken göz yaşartıyor mu?",
               aciklama="Soğan hücreleri sağlamken maddeler ayrı bölmelerde durur. Kesilince karışırlar ve göz yaşartan gazı oluşturan tepkimeler başlar."),
      kullanim=S("Kükürt içeren bileşikler soğan ve sarımsakta neden bu kadar dikkat çekici bir etki yapar?",
                 "Kükürtlü küçük moleküller uçucudur ve burun ile göz çok düşük miktarlarını bile algılar",
                 Y("Kükürt bileşikleri renkli olduğu için", "kanitsiz", "Etki gazın renginden değil, uçuculuğundan ve tahriş ediciliğinden geliyor (K1).", "K1"),
                 Y("Kükürt bileşikleri çok ağır olduğu için havada kalamaz", "veri", "Gaz uçucu ve göze kadar ulaşıyor (K1).", "K1"),
                 Y("Kükürt bileşikleri suda hiç çözünmediği için", "veri", "Gaz gözdeki sıvıya ulaşıp onu tahriş ediyor (hikâye); yani suyla etkileşiyor.", "K1"),
                 ipucu="K1: Gaz nasıl göze ulaşıyor?",
                 aciklama="Soğan ve sarımsağın keskin kokusu ve göz yaşartıcı etkisi kükürtlü bileşiklerden gelir. Bu moleküller küçük ve uçucudur; insan burnu onları çok düşük derişimlerde bile algılar."),
      yapi="iyon", adaylar=["Si", "P", "S", "Cl"], ozellik="erime"),

    V("K", 2, "cevre", "Tarladaki Mor Alev",
      "Bir çiftçi, buğday tarlasındaki bitkilerin yaprak kenarlarının kahverengileşip kuruduğunu gördü. Ziraat mühendisi "
      "toprağa bir gübre önerdi. Okuldaki öğrenciler gübreden bir tutam alıp alev testi yaptı. Görevin: gübredeki ana metali bulmak.",
      [("deney", "Alev testi", "Gübreden bir tutam alevin üzerine serpilince alev açık mor (lila) renge büründü.", "serbest"),
       ("kimyasal", "Eksiklik belirtisi", "Bu elementin eksikliğinde bitkilerin yaprak kenarları kahverengileşip kuruyor; bitki suyu iyi kullanamıyor.")],
      gozlem=S("Alevin lila renge bürünmesi (K1) neyi gösterir?",
               "Gübre, alevi kendine özgü lila renge boyayan bir element içeriyor.",
               Y("Gübre yanıcıdır.", "iliski", "Alev testinde madde alevin rengini değiştirir; bu, maddenin yanıcı olduğunu göstermez.", "K1"),
               Y("Lila renk her gübrede görülür.", "kanitsiz", "Tek bir gübreyle yapılan test bütün gübreler hakkında sonuç çıkarmaya yetmez.", "K1"),
               ipucu="Alev testi neyi tanımaya yarar?",
               aciklama="Alev testinde metal iyonları alevi kendilerine özgü renklere boyar. Bu renk, elementin bir çeşit parmak izidir."),
      kullanim=S("Potaslı gübreler neden kullanılır?",
                 "Bitkiler su dengesini ve birçok enzimin çalışmasını potasyumla sağlar; hasatla topraktan çekilen potasyum gübreyle geri verilir",
                 Y("Potasyum yaprakları mora boyadığı için", "iliski", "Mor renk alev testinde görüldü (K1); yaprakları boyamaz.", "K1"),
                 Y("Potasyum bitkileri dondan koruyan bir yalıtım tabakası oluşturduğu için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; eksiklik belirtisi su kullanımıyla ilgili (K2).", "K2"),
                 Y("Potasyum metali toprakta yanarak ısı verdiği için", "iliski", "Gübrede metal değil potasyum tuzları bulunur; görevi bitkinin besin ihtiyacını karşılamak.", "K2"),
                 ipucu="K2'deki eksiklik belirtisine bak.",
                 aciklama="Potasyum, bitkilerin yapraklarındaki gözeneklerin açılıp kapanmasını ve su dengesini düzenler, birçok enzimin çalışmasına yardım eder. Potasyum bileşiklerinin en büyük kullanım alanı gübrelerdir."),
      yapi="iyon", adaylar=["Na", "K", "Ca", "Rb"]),

    V("Sc", 2, "sanat", "Stadyumu Gündüze Çeviren Lambalar",
      "Akşam oynanan bir futbol maçında stadyumu aydınlatan dev lambaların ışığı gün ışığına çok benziyor; televizyon "
      "kameraları formaların renklerini doğru gösterebiliyor. Lamba üreticisi, cıva buharlı lambalara bir metalin iyodürünü "
      "kattıklarını söylüyor. Görevin: bu metali bulmak.",
      [("fiziksel", "Işığın rengi", "Lambaların ışığı gün ışığına çok benziyor; kameralar renkleri doğru gösterebiliyor."),
       ("fiziksel", "Hafif ama dayanıklı", "Metal, alüminyuma yakın hafiflikte ama erime noktası çok daha yüksek. Alüminyumla alaşımı bazı bisiklet kadrolarında ve beyzbol sopalarında kullanılıyor.")],
      gozlem=S("Lambaların ışığının gün ışığına benzemesi (K1) televizyon yayını için neden önemlidir?",
               "Kameralar renkleri gün ışığındaki gibi doğru kaydedebilir.",
               Y("Gün ışığına benzeyen ışık daha az elektrik harcar.", "kanitsiz", "Kanıtlar ışığın rengini anlatıyor (K1); elektrik tüketiminden söz etmiyor.", "K1"),
               Y("Gün ışığına benzeyen ışık oyuncuları ısıtır.", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K1"),
               ipucu="Sokak lambalarının sarı ışığı altında renkler nasıl görünür?",
               aciklama="Tek renkli ışık altında renkler ayırt edilemez. Gün ışığına benzeyen, birçok renk içeren ışık ise renkleri doğru gösterir."),
      kullanim=S("Skandiyum iyodür stadyum lambalarına neden katılır?",
                 "Lambanın ışığını gün ışığına benzetir; renkler kamerada doğru görünür",
                 Y("Lambayı hafiflettiği için", "iliski", "Hafiflik skandiyumun alaşımlardaki bir avantajıdır (K2); lambadaki görevi ışığın rengini düzeltmek (K1).", "K1"),
                 Y("Lambanın ışığını tek bir sarı renge indirdiği için", "veri", "Lambanın ışığı gün ışığına benziyor (K1); tek renkli değil.", "K1"),
                 Y("Skandiyum iyodür ışığı tamamen söndürdüğü için", "veri", "Lambalar stadyumu aydınlatıyor (K1).", "K1"),
                 ipucu="K1'deki etkiye bak.",
                 aciklama="Skandiyum iyodür cıva buharlı lambalara katıldığında, lambanın yaydığı ışık gün ışığına benzer hâle gelir. Bu lambalar televizyon çekimlerinde ve stadyumlarda renklerin doğru görünmesini sağlar."),
      yapi="dizilim", adaylar=["Ca", "Sc", "Ti", "Al"]),

    V("Ti", 2, "saglik", "Tüy Kadar Hafif Gözlük",
      "Bir gözlükçü, yeni bir gözlük çerçevesini elinden bırakınca çerçeve masaya bir tüy gibi kondu. Gözlükçü, çerçevenin "
      "yıllarca terle temas ettiği hâlde paslanmayacağını ve cilde alerji yapmayacağını söylüyor. Görevin: çerçevenin metalini bulmak.",
      [("kimyasal", "Ter testi", "Çerçeve yıllarca terle temas etmiş eski bir çerçeveyle karşılaştırıldı: ikisinde de pas ya da kararma yok, cilde alerji yapmamışlar."),
       ("fiziksel", "Hafif ve sağlam", "Çerçevenin metali çelik kadar sağlam ama yoğunluğu çeliğin yalnızca yaklaşık yarısı kadar.")],
      gozlem=S("Çerçevenin yıllarca terle temas ettiği hâlde paslanmaması (K1) neyi gösterir?",
               "Metal tuzlu su ve terle kolay kolay tepkimeye girmiyor; korozyona dayanıklı.",
               Y("Metal suyu iterek hiç ıslanmıyor.", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; çerçeve terle temas etti ama paslanmadı.", "K1"),
               Y("Metal her yıl yeniden boyanıyor.", "kanitsiz", "Çerçevenin boyandığına dair bir kanıt yok.", "K1"),
               ipucu="Ter, tuz içeren bir sıvıdır.",
               aciklama="Ter tuzlu bir sıvıdır ve birçok metali aşındırır. Paslanmayan bir metal, yüzeyinde koruyucu bir oksit tabakası oluşturan dayanıklı bir metaldir."),
      kullanim=S("Titanyum gözlük çerçevelerinde neden tercih edilir?",
                 "Hafif, sağlam, paslanmaz ve cilde alerji yapmaz",
                 Y("Çok ağır olduğu için gözlüğü yerinde tuttuğu için", "veri", "Metal çok hafif (K2 ve ölçüm {olcum}).", "K2"),
                 Y("Terle tepkimeye girip renk değiştirdiği için", "veri", "Çerçeve terle temas ettiği hâlde değişmedi (K1).", "K1"),
                 Y("Mıknatısa güçlü çekildiği için", "kanitsiz", "Kanıtlarda mıknatıslıkla ilgili bir bilgi yok; titanyum mıknatısa çekilmez.", "K1"),
                 ipucu="K1 ve K2'deki özellikleri birleştir.",
                 aciklama="Titanyum çelik kadar sağlam ama ondan yaklaşık %45 daha hafiftir. Yüzeyindeki ince oksit tabakası onu korozyona karşı korur ve vücutla uyumludur; bu yüzden gözlüklerde, saatlerde ve tıbbi implantlarda kullanılır."),
      yapi="dizilim", adaylar=["Sc", "Ti", "V", "Cr"]),
]
