# -*- coding: utf-8 -*-
"""Seviye 2 (Çıkarım) — yeni vakalar, ikinci bölüm."""
from sablon import S, V, Y

VAKALAR = [
    V("Cr", 2, "sanat", "Yakutun Kırmızısı",
      "Bir kuyumcu, kırmızı bir yakut taşının rengini neyin verdiğini merak ediyor. Yakut aslında renksiz bir mineralden "
      "(alüminyum oksit) oluşur; kırmızı rengi içine karışmış çok az miktardaki bir elementten gelir. Görevin: bu elementi bulmak.",
      [("fiziksel", "Taşın rengi", "Taş koyu kırmızı ve ışığı geçiriyor. Aynı mineralin saf hâli renksiz."),
       ("kimyasal", "Analiz raporu", "Taşta, alüminyum ve oksijenin yanında yüzde birden az miktarda bir geçiş metali bulundu.")],
      gozlem=S("Saf mineralin renksiz olması ama yakutun kırmızı olması (K1, K2) neyi gösterir?",
               "Rengi, minerale karışmış az miktardaki başka bir element veriyor.",
               Y("Yakut tamamen farklı bir mineraldir.", "kanitsiz", "Analiz yakutta da aynı mineralin elementlerini buldu (K2); fark yalnızca karışan az miktardaki elementte.", "K2"),
               Y("Taş, ışık altında boyandığı için kırmızıdır.", "kanitsiz", "Böyle bir işleme dair hiçbir kanıt yok.", "K1"),
               ipucu="İki taş arasındaki tek fark ne?",
               aciklama="Çok az miktardaki bir safsızlık bile bir taşın rengini tamamen değiştirebilir."),
      kullanim=S("Yakutun kırmızı renginin nedeni hangisidir?",
                 "İçindeki az miktardaki krom iyonlarının bazı renkleri soğurup kırmızıyı geçirmesi",
                 Y("Taşın çok sert olması", "iliski", "Sertlik rengi belirlemez; saf mineral de aynı sertliktedir ama renksizdir (K1).", "K1"),
                 Y("Alüminyumun kendisinin kırmızı olması", "veri", "Saf mineral renksiz (K1); renk karışan başka bir elementten geliyor (K2).", "K2"),
                 Y("Krom metalinin parlak gümüşi rengi", "iliski", "Taşın içinde krom metal olarak değil, iyon olarak bulunur; metalin rengi taşın rengini açıklamaz.", "K2"),
                 ipucu="Saf mineral renksiz. Renk, karışan elementten geliyor.",
                 aciklama="Yakut, içine çok az krom karışmış alüminyum oksittir. Krom iyonları görünür ışığın bir kısmını soğurur ve taş kırmızı görünür. Zümrüdün yeşilini de yine krom iyonları verir; elementin adı da Yunanca 'renk' anlamına gelir."),
      yapi="dizilim", adaylar=["V", "Cr", "Mn", "Fe"]),

    V("Mn", 2, "enerji", "Pilin İçindeki Siyah Toz",
      "Bir kimya öğretmeni, biten bir alkalin pili güvenli biçimde keserek içini gösterdi. Pilin içinde nemli, siyah bir toz "
      "vardı. Öğretmen bu tozun bir metal oksidi olduğunu ve pilin elektrik üretmesinde görev aldığını söyledi. Görevin: oksidin metalini bulmak.",
      [("kimyasal", "Siyah toz", "Pilin içindeki siyah toz bir metalin dioksidi. Pil çalışırken bu toz kimyasal olarak değişiyor."),
       ("alasim", "Başka bir kullanım", "Aynı metal, demiryolu makaslarında ve taş kırıcılarda kullanılan, darbe aldıkça sertleşen çeliklere de katılıyor.")],
      gozlem=S("Pil çalışırken siyah tozun kimyasal olarak değişmesi (K1) neyi gösterir?",
               "Pilin elektriği bir kimyasal tepkimeden geliyor; toz bu tepkimeye katılıyor.",
               Y("Pilde elektrik hazır olarak depolanmıştır, toz yalnızca dolgu malzemesidir.", "veri", "Toz pil çalışırken değişiyor (K1); yani tepkimede görev alıyor.", "K1"),
               Y("Toz pil ısınınca eriyip elektrik üretir.", "kanitsiz", "Kanıtlarda tozun eridiğine dair bir bilgi yok; değişim kimyasal (K1).", "K1"),
               ipucu="Pil, kimyasal enerjiyi hangi enerjiye çevirir?",
               aciklama="Pillerde kimyasal tepkimeler sırasında elektronlar dış devreden geçer; bu elektron akışı elektrik akımıdır. Siyah toz bu tepkimenin bir tarafıdır."),
      kullanim=S("Mangan dioksit alkalin pillerde neden kullanılır?",
                 "Pildeki tepkimede elektronları kabul eden madde olarak görev yapar ve akımın oluşmasını sağlar",
                 Y("Pili soğutmak için", "kanitsiz", "Kanıtlar tozun tepkimede değiştiğini gösteriyor (K1); soğutma görevinden söz etmiyor.", "K1"),
                 Y("Pili ağırlaştırıp dengelemek için", "iliski", "Pildeki maddelerin görevi ağırlık değil, kimyasal tepkime (K1).", "K1"),
                 Y("Darbe aldıkça sertleşerek pilin kabını korumak için", "iliski", "Darbeyle sertleşme, manganlı çeliklerin özelliğidir (K2); pildeki görevi tepkimeye katılmak.", "K2"),
                 ipucu="K1: Toz pil çalışırken ne yapıyor?",
                 aciklama="Alkalin pillerde çinko elektron verir, mangan dioksit ise elektronları alır. Elektronlar bu sırada dış devreden geçerek cihazı çalıştırır. Mangan ayrıca çok sert ve darbeye dayanıklı çeliklerin yapımında kullanılır."),
      yapi="dizilim", adaylar=["Cr", "Mn", "Fe", "Co"]),

    V("Fe", 2, "saglik", "Yorgunluğun Nedeni",
      "Sürekli yorgun hisseden bir öğrencinin kan tahlilinde hemoglobin değeri düşük çıktı. Doktor kırmızı et, mercimek, "
      "kuru üzüm ve yeşil yapraklı sebzeler önerdi. Görevin: hemoglobinin merkezindeki ve bu besinlerde bulunan elementi bulmak.",
      [("kimyasal", "Hemoglobinin merkezi", "Kandaki hemoglobin molekülünün merkezinde bir metal iyonu bulunuyor. Oksijen bu iyona bağlanarak taşınıyor."),
       ("fiziksel", "Kanın rengi", "Kanın kırmızı rengi, oksijenin hemoglobindeki bu metal iyonuna bağlanmasından geliyor.")],
      gozlem=S("Hemoglobinin düşük olması (tahlil) ve oksijenin hemoglobine bağlanarak taşınması (K1) yorgunluğu nasıl açıklar?",
               "Hemoglobin azsa kan hücrelere daha az oksijen taşır; hücreler daha az enerji üretir.",
               Y("Hemoglobin az olunca kan kırmızı rengini tamamen kaybeder.", "veri", "Hemoglobin azalınca kan rengini tamamen kaybetmez; sorun daha az oksijen taşınmasıdır (K1).", "K1"),
               Y("Hemoglobin fazla olduğu için vücut yoruluyor.", "veri", "Tahlilde hemoglobin düşük çıktı (hikâye).", "K1"),
               ipucu="Hücreler enerji üretmek için neye ihtiyaç duyar?",
               aciklama="Hücreler enerji üretmek için oksijen kullanır. Oksijeni taşıyan hemoglobin azalınca dokulara giden oksijen azalır ve yorgunluk görülür."),
      kullanim=S("Demir eksikliği neden yorgunluğa yol açar?",
                 "Demir, oksijeni akciğerlerden dokulara taşıyan hemoglobinin merkezindedir; az olursa hücrelere daha az oksijen gider",
                 Y("Demir kemikleri güçlendiren ana element olduğu için", "iliski", "Kemiklerin ana elementi kalsiyumdur; demirin görevi oksijen taşımak (K1).", "K1"),
                 Y("Demir mıknatısa çekildiği için kanın akmasını sağladığı için", "iliski", "Kanın akışı mıknatıslıkla ilgili değil; demirin görevi oksijeni bağlamak (K1).", "K1"),
                 Y("Demir kana sarı renk verdiği için", "veri", "Kan kırmızı renkli; bu renk oksijenin demir iyonuna bağlanmasından geliyor (K2).", "K2"),
                 ipucu="K1'deki görev nedir?",
                 aciklama="Hemoglobinin merkezindeki demir iyonu oksijene bağlanır. Demir eksikliğinde yeterince hemoglobin yapılamaz; buna demir eksikliği anemisi denir ve yorgunluk en sık belirtisidir."),
      yapi="dizilim", adaylar=["Cr", "Mn", "Fe", "Co"]),

    V("Co", 2, "sanat", "İznik Çinisinin Mavisi",
      "16. yüzyıldan kalma bir İznik çinisinin koyu mavi desenleri dört yüz yılı aşkın süredir solmamış. Bir restoratör, mavi "
      "rengi veren boyayı analiz ettirdi. Görevin: boyadaki geçiş metalini bulmak.",
      [("fiziksel", "Solmayan mavi", "Desenlerin mavisi yüzyıllardır güneşe ve neme maruz kaldığı hâlde solmamış."),
       ("kimyasal", "Boyanın içeriği", "Analiz, mavi boyada bir geçiş metalinin oksidini buldu. Bu oksit, cama karıştırılınca da koyu mavi renk veriyor.")],
      gozlem=S("Desenlerin yüzyıllardır solmaması (K1) boyanın hangi özelliğini gösterir?",
               "Boya, ışık ve nemle bozulmayan, çok kararlı bir madde.",
               Y("Boya her yıl yenilenmiştir.", "kanitsiz", "Çininin boyandığına dair bir kanıt yok; desenler yüzyıllardır değişmemiş.", "K1"),
               Y("Boya suda kolayca çözünür.", "veri", "Suda kolayca çözünen bir boya nemli ortamda yüzyıllarca kalamazdı (K1).", "K1"),
               ipucu="Güneş ve nem birçok boyayı soldurur.",
               aciklama="Çini boyaları sır altında yüksek sıcaklıkta pişirilen metal oksitlerdir. Bu yüzden ışık ve nemle bozulmazlar."),
      kullanim=S("Kobalt oksit çini ve camlarda neden kullanılır?",
                 "Çok az miktarı bile, yüksek sıcaklıkta pişirilince bozulmayan koyu bir mavi renk verir",
                 Y("Çiniyi mıknatısa çekilir yaptığı için", "iliski", "Mıknatıslık bir boyanın renk vermesiyle ilgili değil.", "K2"),
                 Y("Çiniyi daha hafif yaptığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; oksit renk için kullanılıyor (K2).", "K2"),
                 Y("Kobalt metali parlak mavi renkte olduğu için", "iliski", "Kobalt metali gümüşi gridir; mavi renk oksidinden ve camdaki iyonlarından gelir.", "K2"),
                 ipucu="K2'deki oksidin etkisine bak.",
                 aciklama="Kobalt bileşikleri yüzyıllardır çinilere, porselenlere ve camlara koyu mavi renk vermek için kullanılır. İznik çinilerinin ünlü mavisi de kobalttan gelir. Bugün kobaltın en önemli kullanım alanlarından biri lityum iyon pillerdir."),
      yapi="dizilim", adaylar=["Fe", "Co", "Ni", "Cu"], ozellik="erime"),

    V("Ni", 2, "saglik", "Kemer Tokasının İzi",
      "Bir öğrencinin karnında, kemer tokasının değdiği yerde kızarık ve kaşıntılı bir leke oluştu. Dermatolog bunun en "
      "yaygın metal alerjisi olduğunu ve tokadaki bir metalden kaynaklandığını söyledi. Görevin: bu metali bulmak.",
      [("kimyasal", "Alerjinin nedeni", "Ter, tokanın yüzeyinden çok az miktarda metal iyonu çözüyor. Bu iyonlar cilde geçince bazı kişilerde alerjik tepki oluşturuyor."),
       ("deney", "Mıknatıs ve paralar", "Tokanın metali mıknatısa çekiliyor. Aynı metal birçok ülkenin madeni paralarında ve paslanmaz çelikte de kullanılıyor.")],
      gozlem=S("Alerjinin tokanın tam değdiği yerde oluşması (hikâye ve K1) neyi gösterir?",
               "Tepkiye, metalle doğrudan temas eden ciltteki metal iyonları yol açıyor.",
               Y("Alerjinin nedeni kemerin kumaşıdır.", "veri", "Leke tokanın metalinin değdiği yerde oluştu; dermatolog da metali gösterdi (K1).", "K1"),
               Y("Alerji havadaki tozdan kaynaklanır.", "kanitsiz", "Leke yalnızca tokanın değdiği yerde; havadaki toz bütün cildi etkilerdi.", "K1"),
               ipucu="Lekenin yeri neyi düşündürüyor?",
               aciklama="Temas alerjisi, alerjiye yol açan maddenin cilde dokunduğu yerde ortaya çıkar."),
      kullanim=S("Alerji riskine rağmen nikel neden takı, toka ve paralarda sık kullanılır?",
                 "Sert, parlak ve paslanmaya dayanıklıdır; ucuz alaşımlara bu özellikleri kazandırır",
                 Y("Nikel ciltte hiç tepkiye yol açmadığı için", "veri", "Nikel en yaygın metal alerjisine yol açar (hikâye, K1).", "K1"),
                 Y("Nikel hiç mıknatısa çekilmediği için", "veri", "Tokanın metali mıknatısa çekiliyor (K2).", "K2"),
                 Y("Nikel çok yumuşak olduğu için kolay şekil aldığı için", "kanitsiz", "Nikel aslında sert bir metaldir ve alaşımları sağlamlaştırır.", "K2"),
                 ipucu="K2'de nikelin nerelerde kullanıldığı yazıyor.",
                 aciklama="Nikel sert, parlak ve korozyona dayanıklıdır; paslanmaz çeliğin ve birçok madeni paranın bileşenidir. Ancak terle çözünen nikel iyonları bazı insanlarda alerjiye yol açtığı için Avrupa'da ciltle temas eden ürünlerdeki nikel miktarı sınırlandırılmıştır."),
      yapi="dizilim", adaylar=["Fe", "Co", "Ni", "Cu"], ozellik="erime"),

    V("Cu", 2, "sanat", "Özgürlük Heykelinin Yeşili",
      "New York'taki Özgürlük Heykeli 1886'da açıldığında parlak, kızıl kahverengi bir metal renginde parlıyordu. Yaklaşık "
      "20 yıl içinde bugünkü yeşil rengini aldı. Görevin: heykelin dış kaplamasının metalini bulmak.",
      [("fiziksel", "Renk değişimi", "Heykelin dış yüzeyi yıllar içinde kızıl kahverengiden yeşile döndü. Yeşil tabaka metalin üzerinde ince bir katman oluşturuyor."),
       ("iletkenlik", "Başka bir kullanım", "Heykelin dış yüzeyindeki metal, evlerdeki elektrik tellerinde en çok kullanılan metal.")],
      gozlem=S("Heykelin yüzeyinin yıllar içinde yeşile dönmesi (K1) neyi gösterir?",
               "Metal, havadaki oksijen, su ve diğer maddelerle tepkimeye girerek yüzeyinde yeni bir madde oluşturdu.",
               Y("Heykel yeşile boyandı.", "kanitsiz", "Heykelin boyandığına dair bir kanıt yok; renk yıllar içinde kendiliğinden değişti.", "K1"),
               Y("Metal eriyip başka bir metale dönüştü.", "iliski", "Bir metal havada başka bir metale dönüşmez; yüzeyde yeni bir bileşik oluşur.", "K1"),
               ipucu="Demirin paslanması da benzer bir olaydır.",
               aciklama="Metal yüzeyi havadaki maddelerle yavaş yavaş tepkimeye girer ve yeşil bir bileşik tabakası (patina) oluşturur."),
      kullanim=S("Özgürlük Heykeli'nin yeşil tabakası neden temizlenmedi?",
                 "Bakırın havayla tepkimesinden oluşan yeşil tabaka (patina) alttaki metali daha fazla aşınmaktan korur",
                 Y("Yeşil tabaka bakırı elektrik iletmez hâle getirdiği için", "iliski", "Heykelin elektrik iletmesi gerekmiyor; tabakanın değeri metali korumasından geliyor.", "K2"),
                 Y("Yeşil tabaka bakırı daha ağır yaptığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K1"),
                 Y("Yeşil tabaka bakırın erimesini önlediği için", "iliski", "Heykel erime tehlikesiyle karşı karşıya değil; tabaka aşınmaya karşı korur.", "K1"),
                 ipucu="K1'deki 'ince katman' ne işe yarıyor olabilir?",
                 aciklama="Bakır havadaki oksijen, su ve karbondioksitle tepkimeye girerek yeşil bir tabaka oluşturur. Bu tabaka alttaki bakırı korur; bu yüzden heykel yeşil bırakılmıştır."),
      yapi="dizilim", adaylar=["Ni", "Cu", "Zn", "Ag"], ozellik="erime"),

    V("Zn", 2, "saglik", "Cankurtaranın Beyaz Burnu",
      "Bir plajdaki cankurtaran, burnuna kalın beyaz bir krem sürüyor. Bütün gün güneşte kaldığı hâlde burnu yanmıyor. "
      "Kremin etken maddesi bir metal oksidi. Görevin: bu oksidin metalini bulmak.",
      [("fiziksel", "Beyaz tabaka", "Krem ciltte opak beyaz bir tabaka bırakıyor ve güneş ışığındaki morötesi ışınları geçirmiyor."),
       ("kimyasal", "Metalin başka bir görevi", "Aynı metal, çeliği paslanmaya karşı korumak için onu kaplamakta da kullanılıyor.")],
      gozlem=S("Kremin morötesi ışınları geçirmemesi (K1) burnun yanmamasını nasıl açıklar?",
               "Yanığa yol açan morötesi ışınlar cilde ulaşmadan durduruluyor.",
               Y("Krem cildi soğutarak yanmayı önlüyor.", "kanitsiz", "Kanıtlar kremin morötesi ışınları durdurduğunu söylüyor (K1); soğutmadan söz etmiyor.", "K1"),
               Y("Krem güneş ışığını tamamen yansıtarak cildi karanlıkta bırakıyor.", "veri", "Krem görünür ışığı da biraz yansıtır ama asıl önemli olan morötesi ışınları durdurması (K1).", "K1"),
               ipucu="Güneş yanığına ışığın hangi türü yol açar?",
               aciklama="Güneş yanığına morötesi ışınlar yol açar. Bu ışınları durduran bir tabaka cildi korur."),
      kullanim=S("Çinko oksit güneş kremlerinde neden kullanılır?",
                 "Morötesi ışınları soğurup saçar, ciltte kalıcı bir tabaka oluşturur ve zehirsizdir",
                 Y("Çinko oksit cildi bronzlaştırdığı için", "veri", "Krem morötesi ışınları durduruyor (K1); bronzlaşmaya yol açan da bu ışınlardır.", "K1"),
                 Y("Çinko çeliği kapladığı için cildi de kaplayıp sertleştirdiği için", "iliski", "Çeliği kaplamak çinkonun başka bir kullanımıdır (K2); kremdeki görevi morötesi ışınları durdurmak.", "K2"),
                 Y("Çinko oksit suda çok iyi çözündüğü için", "kanitsiz", "Krem ciltte kalıcı bir tabaka bırakıyor (K1); suda çözünse hemen akıp giderdi.", "K1"),
                 ipucu="K1'de kremin ne yaptığı yazıyor.",
                 aciklama="Çinko oksit morötesi ışınları soğurup saçar. Ciltte opak bir tabaka oluşturduğu için özellikle burun ve kulak gibi güneşe en çok maruz kalan yerlerde kullanılır."),
      yapi="dizilim", adaylar=["Ni", "Cu", "Zn", "Ga"]),

    V("Ga", 2, "ev", "Çayda Kaybolan Kaşık",
      "Bir sihirbaz, parlak metal bir kaşıkla sıcak çayı karıştırdı; kaşığın ucu birkaç saniyede eriyip çayın dibine aktı. "
      "Aynı metalden bir parçayı avucunda tutunca da metal eriyip gümüşi bir sıvıya dönüştü. Görevin: kaşığın metalini bulmak.",
      [("fiziksel", "Avuçta eriyen metal", "Metal avuçta birkaç dakika tutulunca eriyor; vücut sıcaklığı (yaklaşık 37 °C) onu eritmeye yetiyor.", "serbest"),
       ("kimyasal", "Işık saçan bileşik", "Bu metalin azotla oluşturduğu bileşik, mavi LED'lerde ve telefonların hızlı şarj cihazlarında kullanılıyor.")],
      gozlem=S("Metalin avuçta erimesi (K1) erime noktası hakkında neyi gösterir?",
               "Metalin erime noktası vücut sıcaklığından (yaklaşık 37 °C) düşük.",
               Y("Metalin erime noktası 100 °C'nin üzerindedir.", "veri", "Vücut sıcaklığı metali eritmeye yetiyor (K1); erime noktası 37 °C'nin altında olmalı.", "K1"),
               Y("Metal oda sıcaklığında sıvıdır.", "veri", "Kaşık oda sıcaklığında katıydı; ancak avuçta ya da sıcak çayda eridi.", "K1"),
               ipucu="Bir madde, sıcaklığı erime noktasını geçince erir.",
               aciklama="Bir katı, erime noktasının üzerindeki bir sıcaklıkta erir. Avuçta eriyen bir metalin erime noktası oda sıcaklığıyla vücut sıcaklığı arasındadır."),
      kullanim=S("Galyum neden geniş sıcaklık aralığında sıvı kalan alaşımlarda kullanılır?",
                 "Erime noktası çok düşük, kaynama noktası ise çok yüksektir; geniş bir sıcaklık aralığında sıvı kalır",
                 Y("Hiç erimediği için", "veri", "Galyum avuçta bile eriyor (K1).", "K1"),
                 Y("Su gibi 100 °C'de kaynadığı için", "kanitsiz", "Galyum çok yüksek sıcaklıkta kaynar; 100 °C'de kaynadığına dair bir kanıt yok.", "{tablo}"),
                 Y("Mavi ışık saçtığı için", "iliski", "Mavi ışık galyumun azotla oluşturduğu bileşikten gelir (K2); alaşımlardaki görevini açıklamaz.", "K2"),
                 ipucu="Erime noktasını ölçümden ({olcum}) oku. Kaynama noktası 2000 °C'nin üzerinde.",
                 aciklama="Galyum 29,8 °C'de erir ama 2000 °C'nin üzerinde kaynar. Bu yüzden düşük sıcaklıkta eriyen alaşımlarda ve bazı termometrelerde kullanılır. Bileşiği galyum nitrür ise mavi LED'lerin ve hızlı şarj cihazlarının temelidir."),
      yapi="dizilim", adaylar=["Al", "Zn", "Ga", "Ge"], ozellik="erime"),

    V("Ge", 2, "tarih", "Mendeleyev'in Boş Kutusu",
      "1871'de Dmitri Mendeleyev, periyodik tablosunda silisyumun altındaki kutuyu boş bıraktı ve 'Burada henüz bulunmamış "
      "bir element var' dedi. Elementin özelliklerini de önceden tahmin etti. On beş yıl sonra bu element bir gümüş madeninden "
      "çıkan mineralde bulundu. Görevin: bu elementi bulmak.",
      [("tarih", "Mendeleyev'in tahmini", "Mendeleyev boş kutudaki elementin yoğunluğunun yaklaşık 5,5 g/cm³, bağıl atom kütlesinin yaklaşık 72 olacağını tahmin etti."),
       ("tarih", "Winkler'in ölçümü", "1886'da Clemens Winkler elementi buldu ve ölçtü: bağıl atom kütlesi 72,6. Ölçümleri tahmine çok yakındı.")],
      gozlem=S("Mendeleyev'in henüz bulunmamış bir elementin özelliklerini tahmin edebilmesi (K1) neyi gösterir?",
               "Periyodik tablodaki örüntü, komşu elementlerin özelliklerinden yola çıkarak bilinmeyen bir elementi öngörmeye izin veriyor.",
               Y("Mendeleyev elementi gizlice bulmuştu.", "kanitsiz", "Element 1886'da Winkler tarafından bulundu (K2); Mendeleyev'in onu önceden bulduğuna dair bir kanıt yok.", "K2"),
               Y("Tahmin yalnızca bir şanstı.", "kanitsiz", "Mendeleyev birçok özelliği birden doğru tahmin etti (K1, K2); bu, şansla değil örüntüyle açıklanır.", "K2"),
               ipucu="Bir grubun elementlerinin özellikleri yukarıdan aşağıya nasıl değişir?",
               aciklama="Mendeleyev, elementleri özelliklerinin düzenli tekrarına göre sıraladı. Bu örüntü sayesinde boş kutudaki elementin özelliklerini komşularından tahmin edebildi."),
      kullanim=S("Germanyumun keşfi periyodik tablo için neden önemli bir kanıttı?",
                 "Periyodik tabloya dayanan bir tahmin ölçümle doğrulandı; tablonun öngörü yapabilen bir model olduğu görüldü",
                 Y("Germanyum en ağır element olduğu için", "veri", "Germanyumun bağıl atom kütlesi yalnızca 72,6 (K2); en ağır element değil.", "K2"),
                 Y("Germanyum tablodaki ilk element olduğu için", "veri", "Germanyum silisyumun altındaki boşluğa yerleşti (hikâye); ilk element değil.", "K1"),
                 Y("Germanyumun keşfi tabloyu tamamen değiştirdiği için", "veri", "Tam tersi: germanyum tabloda önceden ayrılmış yere tam oturdu (K1, K2).", "K1"),
                 ipucu="K1 ve K2'yi karşılaştır.",
                 aciklama="Bilimsel bir modelin gücü, henüz gözlenmemiş olayları doğru öngörebilmesidir. Mendeleyev'in 'eka-silisyum' tahmininin germanyumla doğrulanması periyodik tablonun kabul görmesinde önemli bir rol oynadı. Germanyum daha sonra ilk transistörlerde kullanıldı."),
      yapi="dizilim", adaylar=["Si", "Ga", "Ge", "As"]),

    V("Se", 2, "teknoloji", "Fotokopinin Işıklı Tamburu",
      "1950'lerin fotokopi makinelerinin içinde, ışığa duyarlı bir maddeyle kaplı bir tambur vardı. Makine sayfanın "
      "görüntüsünü tambura yansıtıyor, tambur da toneri yalnızca yazıların olduğu yerlere çekiyordu. Görevin: tamburu "
      "kaplayan elementi bulmak.",
      [("iletkenlik", "Işığa duyarlılık", "Tamburu kaplayan madde karanlıkta elektriği iletmiyor; ışık vurunca iletken hâle geliyor."),
       ("kimyasal", "Başka kullanımlar", "Aynı element kepeğe yol açan mantarlara karşı şampuanlarda ve camlara kırmızı renk vermekte de kullanılıyor.")],
      gozlem=S("Maddenin ışık vurunca iletken hâle gelmesi (K1) fotokopide nasıl işe yarar?",
               "Işık alan beyaz bölgelerdeki elektrik yükü boşalır; yalnızca yazıların gölgesi yüklü kalır ve toner oraya yapışır.",
               Y("Işık vurunca madde erir ve yazıyı oluşturur.", "kanitsiz", "Kanıtlar maddenin iletkenliğinin değiştiğini söylüyor (K1); erimeden söz etmiyor.", "K1"),
               Y("Madde ışığı depolayıp kâğıda aktarır.", "iliski", "Madde ışığı depolamaz; ışık yalnızca iletkenliğini değiştirir (K1).", "K1"),
               ipucu="Toner, elektrik yükü olan yerlere yapışır.",
               aciklama="Tambur önce elektrikle yüklenir. Işık vuran bölgeler iletken olup yükünü kaybeder. Yazıların gölgesinde kalan bölgeler yüklü kalır; toner yalnızca oraya yapışır ve kâğıda aktarılır."),
      kullanim=S("Selenyum ilk fotokopi makinelerinde neden kullanılıyordu?",
                 "Işık vurunca iletken hâle gelen bir madde olduğu için görüntüyü elektrik yükü deseni olarak kaydedebiliyordu",
                 Y("Kepek şampuanlarında kullanıldığı için", "iliski", "Şampuanlar selenyumun başka bir kullanım alanıdır (K2); fotokopideki görevini açıklamaz.", "K2"),
                 Y("Karanlıkta parladığı için", "kanitsiz", "Kanıtlarda böyle bir özellik yok; önemli olan ışıkla iletkenliğinin değişmesi (K1).", "K1"),
                 Y("Her durumda elektriği çok iyi ilettiği için", "veri", "Madde karanlıkta elektriği iletmiyor (K1).", "K1"),
                 ipucu="K1'deki özelliği düşün.",
                 aciklama="Selenyum ışık iletkenidir: aydınlatılınca elektrik direnci azalır. Bu yüzden ilk fotokopi makinelerinde, fotosellerde ve güneş pillerinde kullanıldı."),
      yapi="dizilim", adaylar=["Ge", "As", "Se", "Br"]),

    V("Br", 2, "tarih", "Kralların Mor Boyası",
      "Antik Akdeniz'de Fenikeliler, bir deniz salyangozundan elde ettikleri boyayla kumaşları solmayan bir mora boyardı. "
      "Bu renk o kadar pahalıydı ki uzun süre yalnızca krallar ve imparatorlar giyebildi. Bilim insanları boyanın molekülünü "
      "inceledi. Görevin: molekülde bulunan ve onu özel kılan halojeni bulmak.",
      [("tarih", "Pahalı renk", "Yalnızca bir gram boya elde etmek için binlerce salyangoz gerekiyordu."),
       ("kimyasal", "Molekülün yapısı", "Boya molekülünde karbon, hidrojen, azot ve oksijenin yanında, oda sıcaklığında sıvı hâlde bulunan tek ametal var.", "gerekli")],
      gozlem=S("Bir gram boya için binlerce salyangoz gerekmesi (K1) neyi açıklar?",
               "Boyanın neden çok pahalı ve yalnızca zenginlere özgü olduğunu.",
               Y("Boyanın neden kolay solduğunu.", "veri", "Boya solmayan bir renk veriyordu (hikâye); K1 boyanın pahalılığını açıklıyor.", "K1"),
               Y("Salyangozların neden mor renkli olduğunu.", "kanitsiz", "Kanıtlarda salyangozların rengiyle ilgili bir bilgi yok.", "K1"),
               ipucu="Bir şeyin çok az ve zor elde edilmesi fiyatını nasıl etkiler?",
               aciklama="Az bulunan ve zor elde edilen bir madde pahalı olur. Bu boya 'imparatorluk moru' olarak anıldı."),
      kullanim=S("Boya molekülündeki brom hakkında hangisi kanıtlarla desteklenir?",
                 "Brom, oda sıcaklığında sıvı olan tek ametaldir ve bu doğal boyanın molekülünde bulunur",
                 Y("Brom boyaya tatlı bir koku verir", "kanitsiz", "Kanıtlarda kokudan söz edilmiyor; üstelik brom keskin ve kötü kokuludur.", "K2"),
                 Y("Brom oda sıcaklığında gaz olduğu için boyayı havalandırır", "veri", "Brom oda sıcaklığında sıvıdır (K2).", "K2"),
                 Y("Brom bir metal olduğu için boyaya parlaklık verir", "veri", "Brom bir ametaldir (K2).", "K2"),
                 ipucu="K2'yi yeniden oku.",
                 aciklama="Tyrian moru denilen bu boyanın molekülünde iki brom atomu bulunur. Brom, oda sıcaklığında sıvı olan tek ametaldir; bugün yangın geciktiricilerde ve bazı ilaçlarda kullanılır."),
      yapi="dizilim", adaylar=["Cl", "Se", "Br", "Kr"], ozellik="kaynama"),

    V("Rb", 2, "uzay", "Uydudaki Şaşmaz Saat",
      "Telefonundaki harita uygulaması konumunu birkaç metre hassasiyetle gösterebiliyor. Bunu, uzaydaki GPS uydularının "
      "gönderdiği zaman sinyalleri sağlıyor. Her uyduda, bir alkali metalin atomlarıyla çalışan çok hassas atom saatleri var. "
      "Görevin: bu saatlerde kullanılan elementi bulmak.",
      [("fiziksel", "Işık hızında zaman", "Uydu sinyalleri ışık hızıyla yol alır: saniyenin milyonda biri kadar bir saat hatası, konumda yaklaşık 300 metrelik bir hataya yol açar."),
       ("kimyasal", "Saatin elementi", "Saatlerden birinde kullanılan element yumuşak bir alkali metal. Atomları her zaman aynı, çok kararlı bir frekansta ışıma yapıyor.")],
      gozlem=S("Saniyenin milyonda biri kadar bir hatanın konumda 300 metrelik hataya yol açması (K1) neyi gösterir?",
               "Konumu doğru bulmak için uydulardaki saatlerin son derece hassas olması gerekir.",
               Y("Uydular çok yavaş hareket eder.", "kanitsiz", "Kanıtlar zaman hatasının konumu nasıl etkilediğini anlatıyor (K1); uyduların hızından söz etmiyor.", "K1"),
               Y("Saat hataları konumu hiç etkilemez.", "veri", "Çok küçük bir saat hatası bile büyük bir konum hatasına yol açıyor (K1).", "K1"),
               ipucu="Işık bir saniyede yaklaşık 300 000 km yol alır.",
               aciklama="Alıcı, sinyalin uydudan ne kadar sürede geldiğini ölçerek uzaklığı hesaplar. Işık çok hızlı olduğu için zamandaki çok küçük bir hata uzaklıkta büyük bir hata demektir."),
      kullanim=S("Rubidyum atom saatlerinde neden kullanılır?",
                 "Atomları her zaman aynı, çok kararlı bir frekansta ışıma yapar; bu titreşim zamanı ölçmek için şaşmaz bir sarkaç gibidir",
                 Y("Rubidyum çok ağır olduğu için saati sabit tuttuğu için", "iliski", "Saatin hassasiyeti ağırlıktan değil, atomların kararlı frekansından gelir (K2).", "K2"),
                 Y("Rubidyum hiç tepkimeye girmediği için", "veri", "Rubidyum bir alkali metaldir; çok kolay tepkimeye girer (K2).", "K2"),
                 Y("Rubidyum uzayda bol bulunduğu için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; seçim nedeni atomlarının kararlı frekansı (K2).", "K2"),
                 ipucu="K2'nin ikinci cümlesine bak.",
                 aciklama="Atom saatleri, atomların belli bir enerji geçişinde yaydığı ya da soğurduğu ışığın frekansını sayar. Bu frekans her atomda aynıdır ve değişmez. GPS uydularında rubidyum ve sezyum saatleri bulunur."),
      yapi="izotop", adaylar=["K", "Rb", "Sr", "Cs"]),

    V("Zr", 2, "ev", "Hiç Körelmeyen Bıçak",
      "Bir aşçı, bembeyaz seramik bıçağının aylardır bilenmeden keskin kaldığını ve hiç paslanmadığını söylüyor. Ama bıçak "
      "bir gün yere düşünce ucu kırıldı. Bıçağın malzemesi bir metalin oksidi. Görevin: bu metali bulmak.",
      [("fiziksel", "Sert ama kırılgan", "Bıçak çok sert; aylarca keskin kalıyor ve paslanmıyor. Ama darbeye dayanıksız: yere düşünce kırılabiliyor."),
       ("kimyasal", "Metalin başka bir görevi", "Aynı metal, nötronları çok az yuttuğu için nükleer reaktörlerde yakıt çubuklarının kılıfında kullanılıyor.")],
      gozlem=S("Bıçağın çok sert olduğu hâlde yere düşünce kırılması (K1) neyi gösterir?",
               "Sertlik ve darbeye dayanıklılık farklı özelliklerdir; seramikler sert ama kırılgandır.",
               Y("Bıçak aslında yumuşaktır.", "veri", "Bıçak aylarca keskin kalıyor (K1); bu çok sert olduğunu gösterir.", "K1"),
               Y("Bıçak paslandığı için kırıldı.", "veri", "Bıçak hiç paslanmıyor (K1).", "K1"),
               ipucu="Cam da çok serttir ama düşünce kırılır.",
               aciklama="Sert bir malzeme çizilmeye ve aşınmaya dayanır; ama metaller gibi bükülemediği için ani bir darbede kırılabilir."),
      kullanim=S("Zirkonyum oksit bıçaklarda neden kullanılır?",
                 "Çok sert olduğu için uzun süre keskin kalır, paslanmaz ve yiyeceklerle tepkimeye girmez",
                 Y("Darbeye çok dayanıklı olduğu için", "veri", "Bıçak yere düşünce kırıldı (K1); darbeye dayanıklı değil.", "K1"),
                 Y("Nötronları az yuttuğu için yemeği taze tuttuğu için", "iliski", "Nötron yutmama özelliği reaktörlerde işe yarar (K2); bıçakta bir anlamı yok.", "K2"),
                 Y("Çok hafif olduğu için", "kanitsiz", "Bıçağın seçilme nedeni olarak kanıtlarda sertlik ve paslanmazlık öne çıkıyor (K1).", "K1"),
                 ipucu="K1'deki iyi özelliklere bak.",
                 aciklama="Zirkonyum oksit (zirkonya) çok sert bir seramiktir; bıçaklarda, diş kaplamalarında ve ısıya dayanıklı potalarda kullanılır. Zirkonyum metalinin en büyük kullanım alanı ise nükleer reaktörlerdir."),
      yapi="izotop", adaylar=["Y", "Zr", "Nb", "Ti"]),

    V("Sn", 2, "teknoloji", "Elektronik Kartın Gümüşi Yapıştırıcısı",
      "Bir elektronik atölyesinde öğrenciler devre kartına parça lehimliyor. Havyanın ucunu gümüşi lehim teline değdirince tel "
      "birkaç saniyede eriyip parçanın ayağını sarıyor; soğuyunca hemen katılaşıyor. Görevin: lehimin ana metalini bulmak.",
      [("fiziksel", "Hızlı erime", "Lehim teli havyanın ucuyla birkaç saniyede eriyor ve soğuyunca hemen katılaşarak parçaları birbirine bağlıyor."),
       ("alasim", "Eski bir dost", "Lehimin ana metali, bakırla karıştırılarak tunç yapımında da kullanılıyor ve konserve kutularının içini kaplıyor.")],
      gozlem=S("Lehim telinin havyayla birkaç saniyede erimesi (K1) neyi gösterir?",
               "Lehim metalinin erime noktası, çoğu metale göre düşük.",
               Y("Lehim çok yüksek sıcaklıkta erir.", "veri", "Tel küçük bir havyayla birkaç saniyede eriyor (K1); erime noktası düşük.", "K1"),
               Y("Lehim erimez, yalnızca yumuşar.", "veri", "Tel eriyip parçanın ayağını sarıyor (K1).", "K1"),
               ipucu="Bakır ya da demiri bir havyayla eritebilir miydin?",
               aciklama="Lehimleme için erime noktası düşük bir metal gerekir; böylece devre kartındaki diğer parçalar ısıdan zarar görmez."),
      kullanim=S("Kalay lehimde neden kullanılır?",
                 "Erime noktası düşük olduğu için kolayca erir, elektriği iletir ve soğuyunca parçaları sıkıca birleştirir",
                 Y("Elektriği hiç iletmediği için kısa devreyi önlediği için", "iliski", "Lehimin görevi parçaları elektriksel olarak birleştirmektir; kalay elektriği iletir.", "K1"),
                 Y("Erime noktası çok yüksek olduğu için ısıya dayanıklı olduğu için", "veri", "Kalayın erime noktası düşük ({olcum}).", "{olcum}"),
                 Y("Tunç yapımında kullanıldığı için", "iliski", "Tunç kalayın başka bir kullanım alanıdır (K2); lehimdeki görevini açıklamaz.", "K2"),
                 ipucu="K1 ve ölçümü birleştir.",
                 aciklama="Kalay 232 °C'de erir. Lehimlerin ana metalidir; çevre ve sağlık nedeniyle bugün kurşunsuz lehimlerde kalay, gümüş ve bakırla birlikte kullanılır."),
      yapi="izotop", adaylar=["In", "Sn", "Sb", "Pb"], ozellik="erime"),

    V("I", 2, "saglik", "Tuzdaki Gizli Koruyucu",
      "Bazı dağlık bölgelerde eskiden çok sayıda insanın boynunda guatr denilen şişlik görülüyordu. Sofra tuzuna çok az "
      "miktarda bir element eklenmeye başlanınca guatr büyük ölçüde azaldı. Görevin: tuza eklenen elementi bulmak.",
      [("tarih", "Önce ve sonra", "Bir bölgede sofra tuzuna bu element eklenmeden önce guatr çok yaygındı; eklenmeye başlandıktan birkaç yıl sonra yeni guatr vakaları belirgin biçimde azaldı."),
       ("kimyasal", "Vücuttaki görevi", "Bu element boyundaki tiroit bezinin ürettiği hormonların yapısında bulunuyor. Deniz ürünlerinde ve deniz yosunlarında bol.")],
      gozlem=S("Tuza bu element eklendikten sonra guatrın azalması (K1) neyi gösterir?",
               "Guatrın önemli bir nedeni bu elementin eksikliğidir; eksiklik giderilince hastalık azalır.",
               Y("Tuz guatra yol açar.", "veri", "Guatr, tuza element eklendikten sonra azaldı (K1); tuz guatrın nedeni değil.", "K1"),
               Y("Guatr bulaşıcı bir hastalıktır.", "kanitsiz", "Kanıtlarda bulaşıcılıkla ilgili bir bilgi yok; azalma elementin eklenmesine bağlı.", "K1"),
               ipucu="Önce ve sonra arasındaki fark neydi?",
               aciklama="Bir müdahaleden önceki ve sonraki durumun karşılaştırılması, müdahalenin etkisi hakkında kanıt sağlar."),
      kullanim=S("Sofra tuzuna neden iyot eklenir?",
                 "İyot tiroit hormonları için gereklidir; eksikliğinde guatr oluşur. Tuz herkesin her gün kullandığı bir besin olduğu için iyi bir taşıyıcıdır",
                 Y("İyot tuzun tadını artırdığı için", "kanitsiz", "Kanıtlarda tatla ilgili bir bilgi yok; amaç sağlık (K1, K2).", "K1"),
                 Y("İyot tuzu nemden koruduğu için", "kanitsiz", "Kanıtlar iyotun tiroitteki görevini gösteriyor (K2).", "K2"),
                 Y("İyot mor renkli olduğu için tuzu süslediği için", "iliski", "Tuza eklenen iyot miktarı çok azdır ve tuzun rengini değiştirmez; amaç sağlıktır.", "K2"),
                 ipucu="K2'de iyotun vücuttaki görevi yazıyor.",
                 aciklama="İyot tiroit hormonlarının yapı taşıdır. İyot yetersizliği guatra ve çocuklarda gelişim sorunlarına yol açabilir. Türkiye'de de sofra tuzunun iyotlanması zorunludur."),
      yapi="izotop", adaylar=["Br", "Te", "I", "Xe"], ozellik="erime"),

    V("Ba", 2, "saglik", "Midenin Fotoğrafı",
      "Mide ağrısı çeken bir hastaya röntgen çekilmeden önce beyaz, tebeşir gibi kıvamlı bir sıvı içirildi. Röntgende "
      "mide ve bağırsaklar beyaz olarak belirgin biçimde göründü. Görevin: sıvıdaki ağır elementi bulmak.",
      [("deney", "Röntgen görüntüsü", "Sıvı içildikten sonra çekilen röntgende sindirim kanalı beyaz göründü; çünkü sıvı röntgen ışınlarını geçirmiyor."),
       ("kimyasal", "Güvenli bileşik", "Sıvıdaki bileşik bu elementin sülfatı. Elementin bileşiklerinin çoğu zehirli; ama bu sülfat suda hiç çözünmediği için vücuda geçmiyor.")],
      gozlem=S("Sıvının röntgende beyaz görünmesi (K1) neyi gösterir?",
               "Sıvıdaki madde röntgen ışınlarını durduruyor; ışın geçmeyen yerler filmde beyaz kalıyor.",
               Y("Sıvı karanlıkta parlıyor.", "kanitsiz", "Kanıtlar sıvının röntgen ışınlarını geçirmediğini söylüyor (K1); parlamadan söz etmiyor.", "K1"),
               Y("Sıvı röntgen ışınlarını güçlendiriyor.", "veri", "Sıvı ışınları geçirmiyor (K1); güçlendirmiyor.", "K1"),
               ipucu="Röntgende kemikler neden beyaz görünür?",
               aciklama="Röntgen filminde ışın geçen yerler kararır, ışın geçmeyen yerler beyaz kalır. Kemikler gibi ağır atomlu maddeler beyaz görünür."),
      kullanim=S("Baryum sülfat mide filmlerinde neden kullanılır?",
                 "Ağır baryum atomları röntgen ışınlarını durdurur; bileşik suda çözünmediği için vücuda geçip zehirlemez",
                 Y("Baryum bileşiklerinin hepsi zehirsiz olduğu için", "veri", "Baryum bileşiklerinin çoğu zehirlidir (K2); baryum sülfat çözünmediği için güvenlidir.", "K2"),
                 Y("Baryum sülfat mideyi iyileştirdiği için", "kanitsiz", "Sıvı tedavi için değil, görüntü almak için içiriliyor (hikâye, K1).", "K1"),
                 Y("Baryum sülfat suda çok iyi çözünüp kana geçtiği için", "veri", "Baryum sülfat suda hiç çözünmüyor (K2).", "K2"),
                 ipucu="K1 ve K2'deki iki özelliği birleştir.",
                 aciklama="Baryum ağır bir elementtir ve röntgen ışınlarını saçar. Baryum sülfat suda çözünmediği için bağırsaklardan emilmez ve dışarı atılır. Baryum nitrat ise havai fişeklere yeşil renk verir."),
      yapi="izotop", adaylar=["Sr", "Cs", "Ba", "La"]),

    V("La", 2, "teknoloji", "Netlik Veren Cam",
      "Bir fotoğrafçı, pahalı objektifinin camının sıradan camdan daha ince olduğu hâlde ışığı daha güçlü kırdığını öğrendi. "
      "Üretici cama nadir toprak elementlerinden birinin oksidini kattıklarını söylüyor. Görevin: bu elementi bulmak.",
      [("fiziksel", "Güçlü kırılma", "Objektif camı sıradan camdan daha ince ama ışığı daha güçlü kırıyor; görüntünün kenarlarında renk saçılması daha az."),
       ("kimyasal", "Elementin başka işleri", "Aynı element hibrit arabaların nikel-metal hidrür bataryalarında ve çakmak taşlarında da bulunuyor.")],
      gozlem=S("Camın daha ince olduğu hâlde ışığı daha güçlü kırması (K1) objektif için neden avantajlıdır?",
               "Aynı odaklama gücü daha ince ve daha hafif mercekle sağlanır; görüntü daha net olur.",
               Y("İnce cam daha kolay kırılır, bu yüzden ucuzdur.", "iliski", "Burada 'kırma' ışığın yön değiştirmesi anlamında; camın kırılmasıyla ilgisi yok.", "K1"),
               Y("Işığı güçlü kıran cam ışığı geçirmez.", "veri", "Cam ışığı geçiriyor ve kırıyor (K1); geçirmeseydi objektif çalışmazdı.", "K1"),
               ipucu="Mercek, ışığı kırarak odaklar.",
               aciklama="Bir merceğin gücü camın ışığı kırma yeteneğine bağlıdır. Işığı güçlü kıran camdan daha ince mercekler yapılabilir."),
      kullanim=S("Lantan oksit kamera camlarına neden katılır?",
                 "Camın ışığı kırma gücünü artırır ve renk saçılmasını azaltır; böylece daha ince ve net objektifler yapılır",
                 Y("Camı renkli yapıp güneş gözlüğüne çevirdiği için", "kanitsiz", "Kanıtlar camın ışığı daha güçlü kırdığını söylüyor (K1); renklendirmeden söz etmiyor.", "K1"),
                 Y("Camı mıknatısa çekilir yaptığı için", "iliski", "Mıknatıslık bir objektifin görüntü kalitesini etkilemez.", "K1"),
                 Y("Hibrit araba bataryalarında kullanıldığı için", "iliski", "Bataryalar lantanın başka bir kullanım alanıdır (K2); camdaki görevini açıklamaz.", "K2"),
                 ipucu="K1'deki etkiye bak.",
                 aciklama="Lantan oksit, camın ışığı kırma gücünü artırır ve renk saçılmasını azaltır; özel optik camlarda kullanılır. Lantan ayrıca hibrit arabaların bataryalarında ve hidrojen depolayan alaşımlarda bulunur."),
      yapi="izotop", adaylar=["Ba", "La", "Ce", "Nd"]),

    V("Pr", 2, "sanat", "Cam Ustasının Gözlüğü",
      "Bir cam atölyesinde usta, erimiş camı alevde şekillendirirken özel bir gözlük takıyor. Gözlük olmadan alevden göz "
      "kamaştırıcı sarı bir ışık yayılıyor ve usta camı göremiyor; gözlükle camın şekli net görünüyor. Görevin: gözlük camına "
      "katılan iki lantanitten, cama sarı-yeşil renk vereni bulmak.",
      [("fiziksel", "Kaybolan sarı", "Gözlük, alevden gelen parlak sarı ışığı süzüyor; diğer renkleri büyük ölçüde geçiriyor. Gözlük camı hafif mor-yeşil renkli."),
       ("kimyasal", "Camdaki ikiz elementler", "Gözlük camına iki lantanit katılmış. Aranan element, tuzlarına yeşil, cama ise sarı-yeşil bir renk veriyor.")],
      gozlem=S("Gözlüğün yalnızca parlak sarı ışığı süzmesi (K1) ustaya nasıl yardım eder?",
               "Göz kamaştıran sarı ışık kaybolunca erimiş camın şekli ve rengi net görülür.",
               Y("Gözlük bütün ışığı süzerek ustanın gözünü karanlıkta bırakır.", "veri", "Gözlük diğer renkleri büyük ölçüde geçiriyor (K1).", "K1"),
               Y("Gözlük camı ısıtarak ustanın işini kolaylaştırır.", "kanitsiz", "Kanıtlar gözlüğün ışığı süzdüğünü söylüyor (K1); ısıtmadan söz etmiyor.", "K1"),
               ipucu="Göz kamaştıran ışık bir şeyi görmeyi neden zorlaştırır?",
               aciklama="Sıcak camın içindeki sodyum alevde parlak sarı ışık yayar. Bu ışık süzülünce usta camın kendisini net görür."),
      kullanim=S("Praseodim bu gözlüklerde neden kullanılır?",
                 "Neodimle birlikte, alevdeki sodyumun parlak sarı ışığını süzer; usta erimiş camı net görür",
                 Y("Gözlüğü kırılmaz yaptığı için", "kanitsiz", "Kanıtlarda dayanıklılıktan söz edilmiyor; görevi sarı ışığı süzmek (K1).", "K1"),
                 Y("Karanlıkta parladığı için", "kanitsiz", "Kanıtlarda böyle bir özellik yok.", "K1"),
                 Y("Gözlüğü mıknatıslı yaptığı için", "iliski", "Mıknatıslık ışığın süzülmesiyle ilgili değil.", "K2"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Praseodim ve neodim içeren 'didimyum camı', sodyumun parlak sarı ışığını soğurur. Bu yüzden cam ustalarının ve kaynakçıların gözlüklerinde kullanılır. Praseodim tuzları cama ve sırlara temiz bir sarı renk de verir."),
      yapi="izotop", adaylar=["Ce", "Pr", "Nd", "Pm"], ozellik="erime"),

    V("Sm", 2, "teknoloji", "Sıcağa Dayanan Mıknatıs",
      "Bir uçak motorunun içindeki bir sensörde kullanılan mıknatıs, motor çalışırken 250 °C'ye kadar ısındığı hâlde gücünü "
      "kaybetmiyor. Sıradan mıknatıslar bu sıcaklıkta zayıflardı. Görevin: bu mıknatısın adını veren lantaniti bulmak.",
      [("fiziksel", "Isıya dayanıklılık", "Mıknatıs 250 °C'de bile manyetikliğini koruyor. Aynı sıcaklıkta sıradan bir demir mıknatıs belirgin biçimde zayıflıyor."),
       ("alasim", "Mıknatısın bileşimi", "Mıknatıs, bir lantanit ile kobaltın alaşımından yapılmış. Bu tür mıknatıslar bir zamanlar ilk taşınabilir müzik çalarlardaki küçük kulaklıkları mümkün kılmıştı.")],
      gozlem=S("Aynı sıcaklıkta sıradan mıknatısın zayıflayıp bu mıknatısın zayıflamaması (K1) neyi gösterir?",
               "Mıknatısların ısıya dayanıklılığı yapıldıkları malzemeye bağlıdır.",
               Y("Bütün mıknatıslar ısınınca güçlenir.", "veri", "Sıradan demir mıknatıs ısınınca zayıfladı (K1).", "K1"),
               Y("Mıknatısın gücü yalnızca boyutuna bağlıdır.", "kanitsiz", "Karşılaştırma boyutla değil malzemeyle ilgili (K1, K2).", "K2"),
               ipucu="İki mıknatıs arasındaki fark ne?",
               aciklama="Mıknatıslar ısınınca manyetikliklerini kaybetmeye başlar. Bazı alaşımlar bu etkiye çok daha dayanıklıdır."),
      kullanim=S("Samaryum-kobalt mıknatıslar neden yüksek sıcaklıktaki cihazlarda tercih edilir?",
                 "Yüksek sıcaklıkta da manyetikliklerini korurlar",
                 Y("Hiç mıknatıslık özellikleri olmadığı için", "veri", "Bunlar güçlü mıknatıslardır (K1).", "K1"),
                 Y("Isınınca eriyip şekil değiştirdikleri için", "veri", "Mıknatıs 250 °C'de bile işini yapıyor (K1); erimiyor.", "K1"),
                 Y("En ucuz mıknatıslar oldukları için", "kanitsiz", "Kanıtlarda fiyattan söz edilmiyor; seçilme nedeni ısıya dayanıklılık (K1).", "K1"),
                 ipucu="K1'deki özelliğe bak.",
                 aciklama="Samaryum-kobalt mıknatıslar demir mıknatıslardan çok daha güçlüdür ve yüksek sıcaklıkta manyetikliklerini korur. Bu yüzden uçak, uzay ve mikrodalga cihazlarında kullanılır."),
      yapi="izotop", adaylar=["Nd", "Pm", "Sm", "Eu"]),

    V("Gd", 2, "saglik", "MR'da Parlayan Damarlar",
      "Bir hastaya MR çekilmeden önce damarından küçük bir miktar ilaç verildi. İlaçtan sonraki görüntülerde damarlar ve "
      "küçük bir tümör çok daha parlak ve belirgin göründü. Görevin: ilaçtaki lantanit iyonunu bulmak.",
      [("deney", "Önce ve sonra", "İlaç verilmeden önceki MR görüntüsünde tümör zor seçiliyordu; ilaçtan sonra çevresinden belirgin biçimde ayrıldı."),
       ("fiziksel", "Mıknatıs gibi iyon", "İlaçtaki lantanit iyonunun eşleşmemiş yedi elektronu var. Bu yüzden MR cihazının güçlü manyetik alanından çok etkileniyor.")],
      gozlem=S("İlaçtan önce ve sonra çekilen görüntülerin karşılaştırılması (K1) neyi gösterir?",
               "İlaç, dokular arasındaki farkı belirginleştirerek tümörün görülmesini kolaylaştırıyor.",
               Y("İlaç tümörü tedavi ediyor.", "kanitsiz", "Kanıtlar yalnızca görüntünün değiştiğini gösteriyor (K1); tedaviden söz etmiyor.", "K1"),
               Y("İlaç MR cihazını daha güçlü yapıyor.", "iliski", "Cihaz aynı; değişen, ilacın vücuttaki dokuların sinyalini etkilemesi.", "K1"),
               ipucu="İki görüntü arasındaki tek fark neydi?",
               aciklama="Bu tür ilaçlara 'kontrast madde' denir: görüntüdeki dokular arasındaki farkı (kontrastı) artırırlar."),
      kullanim=S("Gadolinyum MR ilaçlarında neden kullanılır?",
                 "Eşleşmemiş çok sayıda elektronu sayesinde manyetik alandan güçlü etkilenir ve çevresindeki dokuların sinyalini değiştirerek görüntüyü belirginleştirir",
                 Y("Radyoaktif olduğu için görüntüde parladığı için", "iliski", "MR radyasyonla değil, manyetik alanla çalışır; gadolinyumun etkisi manyetik özelliğinden gelir (K2).", "K2"),
                 Y("Hiç manyetik özellik göstermediği için", "veri", "Gadolinyum iyonu manyetik alandan çok etkileniyor (K2).", "K2"),
                 Y("Kemikleri güçlendirdiği için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; ilaç görüntü almak için kullanılıyor (K1).", "K1"),
                 ipucu="K2'deki özelliği düşün.",
                 aciklama="Gadolinyum iyonunun yedi eşleşmemiş elektronu onu çok güçlü bir manyetik iyon yapar. MR'da çevresindeki su moleküllerinin sinyalini değiştirerek damarları ve bazı tümörleri belirginleştirir. Gadolinyum nötronları da çok iyi yuttuğu için nükleer reaktörlerde kullanılır."),
      yapi="izotop", adaylar=["Sm", "Eu", "Gd", "Tb"]),
]
