# -*- coding: utf-8 -*-
"""Seviye 2 (Çıkarım) — yeni vakalar, üçüncü bölüm."""
from sablon import S, V, Y

VAKALAR = [
    V("Dy", 2, "enerji", "Türbinin Sıcak Mıknatısları",
      "Bir rüzgâr türbininin jeneratöründeki güçlü mıknatıslar çalışırken ısınıyor. Mühendis, mıknatısların bu sıcaklıkta "
      "güçlerini kaybetmemesi için içlerine az miktarda bir lantanit katıldığını söylüyor. Görevin: bu lantaniti bulmak.",
      [("fiziksel", "Isınan mıknatıs", "Jeneratör çalışırken mıknatıslar ısınıyor. Katkı maddesi olmayan neodim mıknatıslar yüksek sıcaklıkta manyetikliklerinin bir kısmını kaybediyor."),
       ("kimyasal", "Katkı elementi", "Katkı elementi havada ve suda kolayca tepkimeye girdiği için saf hâlde pek kullanılmıyor. Elektrikli araç motorlarının mıknatıslarına da aynı amaçla katılıyor.")],
      gozlem=S("Katkısız mıknatısların yüksek sıcaklıkta manyetikliğini kaybetmesi (K1) türbin için neden bir sorundur?",
               "Mıknatıs zayıflarsa jeneratör aynı dönüşte daha az elektrik üretir.",
               Y("Mıknatıs zayıflayınca türbin daha hızlı döner.", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; mıknatısın gücü elektrik üretimini etkiler.", "K1"),
               Y("Isınan mıknatıs güçlenir.", "veri", "Katkısız mıknatıslar ısınınca manyetikliklerinin bir kısmını kaybediyor (K1).", "K1"),
               ipucu="Jeneratörde elektriği mıknatıs ile bobin birlikte üretir.",
               aciklama="Jeneratörlerde dönen mıknatıslar bobinlerde elektrik akımı oluşturur. Mıknatıs zayıflarsa üretilen elektrik azalır."),
      kullanim=S("Disprosiyum neodim mıknatıslara neden katılır?",
                 "Mıknatısın yüksek sıcaklıkta manyetikliğini kaybetmesini önler",
                 Y("Mıknatısı soğuttuğu için", "kanitsiz", "Disprosiyum mıknatısı soğutmaz; sıcakken de güçlü kalmasını sağlar (K1).", "K1"),
                 Y("Saf hâlde havada çok kararlı olduğu için", "veri", "Disprosiyum havada ve suda kolayca tepkimeye girer (K2).", "K2"),
                 Y("Mıknatısı hafiflettiği için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; amaç ısıya dayanıklılık (K1).", "K1"),
                 ipucu="K1'deki sorunu hangi katkı çözüyor?",
                 aciklama="Disprosiyum, neodim mıknatısların yüksek sıcaklıkta manyetikliklerini korumasını sağlar. Rüzgâr türbinleri ve elektrikli araçlar yaygınlaştıkça disprosiyuma olan talep hızla artıyor."),
      yapi="izotop", adaylar=["Tb", "Dy", "Ho", "Er"]),

    V("Ho", 2, "saglik", "Taşı Kum Tanesine Çeviren Işık",
      "Böbrek taşı olan bir hastaya ameliyatsız bir tedavi uygulandı. İdrar yolundan ilerletilen çok ince bir kanaldan geçen "
      "lazer ışığı, taşı kum tanesi büyüklüğünde parçalara ayırdı. Lazerin kristaline bir lantanit katılmış. Görevin: bu lantaniti bulmak.",
      [("fiziksel", "İnce lifle gelen ışık", "Lazer ışığı saç teli inceliğinde esnek bir lifle taşa kadar taşınıyor ve enerjisini yalnızca dokunduğu küçük noktaya veriyor."),
       ("kimyasal", "Kristaldeki element", "Lazer kristaline katılan lantanit, nötronları iyi yuttuğu için nükleer reaktörlerde de kullanılıyor; alaşımları bazı güçlü mıknatıslarda bulunuyor.")],
      gozlem=S("Lazerin enerjisini yalnızca dokunduğu küçük noktaya vermesi (K1) tedavide neden önemlidir?",
               "Taş parçalanırken çevresindeki sağlıklı dokular az zarar görür.",
               Y("Lazer bütün böbreği ısıtarak taşı eritir.", "veri", "Lazer enerjisini yalnızca dokunduğu küçük noktaya veriyor (K1).", "K1"),
               Y("Işık lifte ilerlerken kaybolur.", "veri", "Işık lifle taşa kadar taşınıyor (K1).", "K1"),
               ipucu="Ameliyatsız tedavinin avantajı ne olmalı?",
               aciklama="Lazer ışığı ince bir lifle tam hedefe götürülebilir ve enerjisini çok küçük bir alana verir. Böylece taş parçalanır, çevre dokular korunur."),
      kullanim=S("Holmiyumlu lazer böbrek taşı tedavisinde neden kullanılır?",
                 "Ürettiği ışık ince bir lifle taşa kadar taşınabilir ve enerjisini taşın yüzeyine vererek onu parçalar",
                 Y("Holmiyum radyoaktif olduğu için taşı ışınla erittiği için", "iliski", "Lazer radyoaktif ışın değil, yoğun bir ışık demetidir (K1).", "K1"),
                 Y("Holmiyum nötron yuttuğu için taşı küçülttüğü için", "iliski", "Nötron yutma holmiyumun reaktörlerdeki görevidir (K2); lazerle ilgisi yok.", "K2"),
                 Y("Holmiyum taşı mıknatısla çektiği için", "kanitsiz", "Taş mıknatısla değil, lazer ışığıyla parçalanıyor (hikâye, K1).", "K1"),
                 ipucu="K1'deki özellikleri düşün.",
                 aciklama="Holmiyum katkılı kristallerle çalışan lazerler, idrar yolu taşlarını parçalamak için yaygın olarak kullanılır. Işık ince bir lifle taşınır; enerjisi taşın yüzeyinde soğurulur ve taş küçük parçalara ayrılır."),
      yapi="izotop", adaylar=["Dy", "Ho", "Er", "Tm"]),

    V("Tm", 2, "saglik", "Çantadaki Röntgen Cihazı",
      "Elektriğin olmadığı bir afet bölgesinde kurulan sahra hastanesinde, çanta büyüklüğünde bir röntgen cihazı kullanılıyor. "
      "Cihazın içinde düğme büyüklüğünde radyoaktif bir kaynak var; kaynak kendiliğinden röntgen ışını yayıyor. Görevin: "
      "kaynaktaki lantaniti bulmak.",
      [("fiziksel", "Elektriksiz röntgen", "Cihaz prize takılmadan çalışıyor; röntgen ışınlarını içindeki küçük radyoaktif kaynak üretiyor."),
       ("kimyasal", "Kaynağın üretimi", "Kaynak, bir lantanitin nükleer reaktörde nötronlarla ışınlanmasıyla elde ediliyor. Aynı lantanit bazı cerrahi lazerlerde de kullanılıyor.")],
      gozlem=S("Cihazın prize takılmadan röntgen çekebilmesi (K1) afet bölgesinde neden önemlidir?",
               "Elektrik olmayan yerlerde de kırık ve yaralanmalar görüntülenebilir.",
               Y("Cihaz elektrik üretip hastaneye verir.", "kanitsiz", "Cihaz elektrik üretmiyor; röntgen ışını üretiyor (K1).", "K1"),
               Y("Elektriksiz cihazın görüntüsü daha nettir.", "kanitsiz", "Kanıtlarda görüntü netliğiyle ilgili bir bilgi yok.", "K1"),
               ipucu="Sahra hastanesinde neyin eksik olduğu yazıyor?",
               aciklama="Sıradan röntgen cihazları güçlü bir elektrik kaynağına ihtiyaç duyar. Radyoaktif kaynaklı cihazlar elektriksiz çalışabilir."),
      kullanim=S("Tulyumdan elde edilen kaynak taşınabilir röntgen cihazlarında neden kullanılır?",
                 "Kendiliğinden röntgen ışını yayar; böylece cihaz elektriksiz, küçük ve hafif olabilir",
                 Y("Tulyum çok ucuz ve bol olduğu için", "kanitsiz", "Kanıtlarda fiyattan söz edilmiyor; kaynağın üstünlüğü kendiliğinden ışın yayması (K1).", "K1"),
                 Y("Tulyum ışınları tamamen engellediği için", "veri", "Kaynak ışın yayıyor (K1); engellemiyor.", "K1"),
                 Y("Tulyum lazerlerde kullanıldığı için", "iliski", "Lazerler tulyumun başka bir kullanım alanıdır (K2); röntgen cihazındaki görevini açıklamaz.", "K2"),
                 ipucu="K1 ve K2'yi birlikte düşün.",
                 aciklama="Tulyum nükleer reaktörde ışınlanınca röntgen ışını yayan bir izotopa dönüşür. Bu izotoptan yapılmış düğme büyüklüğünde bir kaynak, hafif ve taşınabilir tıbbi röntgen cihazlarında kullanılır."),
      yapi="izotop", adaylar=["Er", "Tm", "Yb", "Lu"]),

    V("Yb", 2, "teknoloji", "Evrenin Yaşı Kadar Şaşmayan Saat",
      "Bir ulusal ölçüm laboratuvarındaki deneysel atom saati o kadar hassas ki evrenin yaşı kadar bir süre çalışsa bile "
      "yaklaşık bir saniye şaşacağı hesaplanıyor. Saatte, lazer ışığıyla bir tuzağa hapsedilmiş binlerce lantanit atomu var. "
      "Görevin: bu atomların elementini bulmak.",
      [("fiziksel", "Atomların titreşimi", "Tuzaktaki atomlar, bir lazerin ışığını yalnızca tam belirli ve hiç değişmeyen bir frekansta soğuruyor. Saat bu frekansı sayarak zamanı ölçüyor."),
       ("kimyasal", "Elementin başka bir işi", "Aynı element, çevreye zararlı bulunan bazı sanayi katalizörlerinin yerine de kullanılmaya başlandı.")],
      gozlem=S("Atomların ışığı yalnızca hiç değişmeyen bir frekansta soğurması (K1) saati neden hassas yapar?",
               "Değişmeyen bir frekans, zamanı ölçmek için şaşmaz bir 'tik tak' sağlar.",
               Y("Atomlar zamanla yavaşlar, bu yüzden saat hassastır.", "veri", "Atomların soğurduğu frekans hiç değişmiyor (K1).", "K1"),
               Y("Lazer ışığı saati ısıtarak hızlandırır.", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K1"),
               ipucu="Bir sarkaçlı saatin hassasiyeti neye bağlıdır?",
               aciklama="Her saat düzenli tekrarlanan bir olayı sayar. Atomların ışık soğurma frekansı her yerde ve her zaman aynı olduğu için en düzenli 'tik tak' budur."),
      kullanim=S("İterbiyum atomları deneysel saatlerde neden kullanılır?",
                 "Atomları çok kararlı bir frekansta ışık soğurur; bu titreşimler sayılarak zaman son derece hassas ölçülür",
                 Y("İterbiyum radyoaktif olduğu için zamanla bozunup süreyi gösterdiği için", "iliski", "Saat radyoaktif bozunmayla değil, atomların ışık soğurma frekansıyla çalışıyor (K1).", "K1"),
                 Y("İterbiyum katalizör olduğu için saatin çarklarını hızlandırdığı için", "iliski", "Katalizörlük iterbiyumun başka bir kullanım alanıdır (K2); atom saatinde çark yoktur.", "K2"),
                 Y("İterbiyum çok ağır olduğu için saati sarsıntıdan koruduğu için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K1"),
                 ipucu="K1'deki özelliği düşün.",
                 aciklama="Optik atom saatleri, atomların belirli bir ışığı soğurma frekansını sayar. İterbiyum ve stronsiyum atomlarıyla çalışan deneysel saatler bugüne kadar yapılmış en hassas saatler arasındadır; ileride saniyenin yeni tanımında kullanılabilirler."),
      yapi="izotop", adaylar=["Er", "Tm", "Yb", "Lu"]),

    V("Lu", 2, "saglik", "PET Tarayıcısının Parlayan Kristalleri",
      "PET taramasında hastaya hafif radyoaktif bir şeker veriliyor. Şekerden çıkan gama ışınları, hastanın çevresindeki halkada "
      "dizili binlerce küçük kristale çarpınca her kristalde kısa bir ışık parlaması oluşuyor. Görevin: kristallerin yapısındaki "
      "lantaniti bulmak.",
      [("deney", "Işık parlamaları", "Gama ışını bir kristale çarpınca kristal çok kısa süren parlak bir ışık yayıyor. Bu ışık bir algılayıcıyla ölçülüyor."),
       ("fiziksel", "Yoğun kristal", "Kristaller bir lantanitin silikatından yapılmış ve çok yoğun; gama ışınlarını iyi durduruyor.")],
      gozlem=S("Kristalin gama ışını çarpınca ışık yayması (K1) tarayıcıda ne işe yarar?",
               "Görünmeyen gama ışınları, ölçülebilen ışık parlamalarına dönüşür; böylece ışınların nereden geldiği bulunur.",
               Y("Kristal hastayı ısıtır.", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; kristal ışın çarpınca ışık yayıyor (K1).", "K1"),
               Y("Kristal gama ışınlarını çoğaltır.", "veri", "Kristal gama ışınlarını çoğaltmaz; onları ışık parlamalarına çevirir (K1).", "K1"),
               ipucu="Gama ışınları gözle görülmez; ışık ise algılayıcıyla ölçülebilir.",
               aciklama="Bu tür kristallere sintilatör denir: yüksek enerjili ışınları görünür ışığa çevirirler. Algılayıcılar bu ışığı ölçerek ışının nereden geldiğini hesaplar."),
      kullanim=S("Lutesyumlu kristaller PET tarayıcılarında neden kullanılır?",
                 "Yoğun oldukları için gama ışınlarını iyi durdurur ve onları hızlı, parlak ışık parlamalarına çevirirler",
                 Y("Lutesyum gama ışınlarını tamamen yok ettiği için", "iliski", "Kristal gama ışınlarını yok etmez; onları ölçülebilir ışığa çevirir (K1).", "K1"),
                 Y("Kristaller çok hafif olduğu için", "veri", "Kristaller çok yoğun (K2 ve ölçüm {olcum}).", "K2"),
                 Y("Lutesyum hastaya verilen şekerin içinde bulunduğu için", "veri", "Lutesyum hastaya verilmiyor; tarayıcının halkasındaki kristallerde (hikâye, K2).", "K2"),
                 ipucu="K1 ve K2'deki iki özelliği birleştir.",
                 aciklama="Lutesyum en yoğun lantanittir. Lutesyumlu silikat kristalleri gama ışınlarını iyi durdurur ve çok kısa sürede parlak ışık verir; bu yüzden modern PET tarayıcılarında kullanılır."),
      yapi="izotop", adaylar=["Tm", "Yb", "Lu", "Hf"]),

    V("Ra", 2, "tarih", "Tonlarca Cevherden Bir Tutam Tuz",
      "1898'de Marie ve Pierre Curie, bir uranyum cevherinin içindeki uranyumdan çok daha güçlü ışınım yaptığını fark etti. "
      "Bu güçlü ışınımın kaynağını bulmak için tonlarca cevheri işlediler ve sonunda yeni bir elementin yalnızca yaklaşık "
      "0,1 gram tuzunu elde ettiler. Görevin: bu elementi bulmak.",
      [("deney", "Fazla ışınım", "Cevher, içerdiği uranyum miktarının açıklayabileceğinden çok daha güçlü ışınım yapıyordu."),
       ("kimyasal", "Yeni elementin davranışı", "Yeni elementin tuzları karanlıkta parlıyordu. Element kimyasal olarak baryuma ve kalsiyuma benziyordu.")],
      gozlem=S("Cevherin, içindeki uranyumun açıklayabileceğinden daha güçlü ışınım yapması (K1) neyi gösterir?",
               "Cevherde uranyumdan daha güçlü ışınım yapan başka bir element daha olmalı.",
               Y("Uranyum ölçülürken bir hata yapılmış.", "kanitsiz", "Curie'ler bu farkın izini sürüp yeni bir element buldu; kanıtlar bir ölçüm hatasını değil yeni bir maddeyi gösteriyor.", "K1"),
               Y("Cevher hiç uranyum içermiyor.", "veri", "Cevher uranyum içeriyor (K1); ışınım ondan beklenenden fazla.", "K1"),
               ipucu="Fazla ışınım nereden geliyor olabilir?",
               aciklama="Beklenenden fazla ışınım, cevherde başka ve daha güçlü radyoaktif bir madde olduğunu düşündürdü. Bu düşünce yeni elementlerin keşfine yol açtı."),
      kullanim=S("Radyum bugün neden çok az kullanılıyor?",
                 "Çok güçlü radyoaktif olduğu için tehlikelidir; saat kadranları gibi eski kullanımları bırakıldı",
                 Y("Radyum hiç ışınım yapmadığı için işe yaramaz", "veri", "Radyum çok güçlü ışınım yapar (K1).", "K1"),
                 Y("Radyum baryuma benzediği için baryum yerine kullanılamaz", "iliski", "Baryuma benzemesi kullanılmamasının nedeni değildir; asıl neden güçlü radyoaktifliği.", "K2"),
                 Y("Radyum doğada çok bol olduğu için değersizdir", "veri", "Tonlarca cevherden yalnızca 0,1 gram tuz elde edildi (hikâye); radyum çok nadirdir.", "K1"),
                 ipucu="K1'deki özellik hem bir avantaj hem de bir tehlike olabilir.",
                 aciklama="Radyum çok güçlü bir radyoaktif elementtir. Eskiden ışıklı boyalarda kullanıldı ama tehlikeli olduğu anlaşılınca bırakıldı. Bugün radyum-223, kalsiyuma benzediği için kemiklere yerleşerek kemiğe yayılmış bazı kanserlerin tedavisinde kullanılıyor."),
      yapi="izotop", adaylar=["Ba", "Ra", "Ac", "Th"]),

    V("Pa", 2, "tarih", "Adı Değişen Element",
      "1913'te iki bilim insanı uranyum cevherinde yeni bir radyoaktif element buldu ve ona Latince 'kısa' anlamına gelen bir "
      "ad verdi. Birkaç yıl sonra aynı elementin çok daha uzun ömürlü bir izotopu bulununca element bugünkü adını aldı. "
      "Görevin: bu elementi bulmak.",
      [("fiziksel", "İlk izotop", "1913'te bulunan izotopun yarılanma süresi yalnızca 1 dakika kadardı; bu yüzden elemente önce 'kısa' anlamına gelen bir ad verildi."),
       ("fiziksel", "İkinci izotop", "1918'de bulunan başka bir izotopunun yarılanma süresi ise yaklaşık 33 bin yıl. Bu izotop bozunarak başka bir radyoaktif elemente dönüşüyor.")],
      gozlem=S("Aynı elementin bir izotopunun 1 dakikada, diğerinin 33 bin yılda yarılanması (K1, K2) neyi gösterir?",
               "Aynı elementin farklı izotopları çok farklı hızlarda bozunabilir.",
               Y("İki izotop farklı elementlerdir.", "veri", "İzotoplar aynı elementin atomlarıdır; yalnızca nötron sayıları farklıdır.", "K2"),
               Y("Bütün izotoplar aynı hızda bozunur.", "veri", "Yarılanma süreleri 1 dakika ve 33 bin yıl (K1, K2); çok farklı.", "K2"),
               ipucu="İzotopların proton sayısı aynı, nötron sayısı farklıdır.",
               aciklama="Bir elementin izotoplarının çekirdeklerindeki nötron sayısı farklıdır; bu fark çekirdeğin kararlılığını ve bozunma hızını değiştirir."),
      kullanim=S("Protaktinyumun neredeyse hiç kullanım alanı olmamasının nedeni hangisidir?",
                 "Doğada çok az bulunur, radyoaktiftir; yalnızca araştırmalarda kullanılır",
                 Y("Çok ucuz ve bol olduğu için kimse ilgilenmez", "kanitsiz", "Protaktinyum uranyum cevherinde çok az miktarda bulunur; bol değildir.", "K1"),
                 Y("İzotoplarının hepsi 1 dakikada bozunduğu için", "veri", "Bir izotopunun yarılanma süresi yaklaşık 33 bin yıl (K2).", "K2"),
                 Y("Adı değiştiği için kullanılması yasaklandığı için", "iliski", "Bir elementin adının değişmesi kullanımını etkilemez.", "K1"),
                 ipucu="Elementin ne kadar bulunduğunu ve radyoaktifliğini düşün.",
                 aciklama="Protaktinyum uranyum cevherlerinde çok az miktarda bulunur ve radyoaktiftir. Bu yüzden yalnızca bilimsel araştırmalarda kullanılır. Adı, bozunarak aktinyuma dönüşmesinden gelir."),
      yapi="izotop", adaylar=["Th", "Pa", "U", "Np"]),

    V("U", 2, "sanat", "Morötesinde Parlayan Vazo",
      "Bir antikacıdaki sarımsı yeşil cam vazo, morötesi bir lambanın altına konunca parlak yeşil bir ışıkla ışıl ışıl parladı. "
      "Antikacı, 1800'lerin sonu ile 1900'lerin başında böyle camların çok moda olduğunu söyledi. Görevin: cama bu rengi veren elementi bulmak.",
      [("deney", "Morötesi lamba", "Vazo morötesi ışık altında parlak yeşil renkte parlıyor; lamba kapanınca parlama hemen duruyor."),
       ("kimyasal", "Camdaki oksit", "Cama renk veren madde zayıf radyoaktif bir metalin oksidi. Aynı metal bugün nükleer santrallerde yakıt olarak kullanılıyor.")],
      gozlem=S("Parlamanın lamba kapanınca hemen durması (K1) neyi gösterir?",
               "Cam, morötesi ışığı soğurup hemen yeşil ışık olarak geri veriyor; ışığı depolamıyor.",
               Y("Cam kendi enerjisiyle sürekli parlıyor.", "veri", "Lamba kapanınca parlama duruyor (K1); enerji lambadan geliyor.", "K1"),
               Y("Cam ışığı saatlerce depolayıp karanlıkta yayıyor.", "veri", "Parlama lamba kapanınca hemen duruyor (K1).", "K1"),
               ipucu="Işık kaynağı kapanınca ne oluyor?",
               aciklama="Bir maddenin bir ışığı soğurup hemen başka renkte bir ışık olarak geri vermesine floresans denir. Kaynak kapanınca floresans da hemen durur."),
      kullanim=S("Uranyum camı morötesi ışıkta neden yeşil parlar?",
                 "Camdaki uranyum bileşikleri morötesi ışığı soğurup yeşil ışık olarak geri yayar",
                 Y("Uranyum yanarken yeşil alev verdiği için", "iliski", "Camda yanma yok; parlama morötesi ışığın soğurulup geri verilmesiyle oluşuyor (K1).", "K1"),
                 Y("Uranyumun radyoaktifliği camı karanlıkta parlattığı için", "veri", "Parlama yalnızca morötesi lamba açıkken görülüyor (K1); radyoaktiflikten değil.", "K1"),
                 Y("Cam yeşile boyandığı için", "kanitsiz", "Renk boyadan değil, camın içindeki uranyum bileşiğinden geliyor (K2).", "K2"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Uranyum camında az miktarda uranyum oksit bulunur. Uranyum bileşikleri morötesi ışığı soğurup yeşil ışık yayar. Bu camlar çok zayıf radyoaktiftir; bugün daha çok koleksiyonlarda bulunur."),
      yapi="izotop", adaylar=["Pa", "U", "Np", "Pu"]),
]
