# -*- coding: utf-8 -*-
"""Seviye 3 (Kanıt) — yeni vakalar, birinci bölüm.
Her vakada K1, rakip adayla da uyumlu genel bir gözlemdir (rakip hipotez görevinde çeldirici olarak kullanılır)."""
from sablon import S, V, Y

VAKALAR = [
    V("H", 3, "uzay", "Güneş Neyle Yanıyor?",
      "Bir gökbilim kulübü, Güneş ışığını bir prizmadan geçirip spektrumunu inceledi. Renklerin arasında koyu çizgiler "
      "vardı; her çizgi, Güneş'in dış katmanlarındaki bir elementin ışığı soğurduğu yeri gösteriyordu. Kulüp en güçlü "
      "çizgilerden birini inceledi. Görevin: bu çizgiyi oluşturan elementi bulmak.",
      [("deney", "Spektrumdaki koyu çizgiler", "Güneş ışığının spektrumunda yüzlerce koyu çizgi var. Her element kendine özgü yerlerde çizgiler oluşturuyor."),
       ("tarih", "Güneş'in yakıtı", "Güneş'in çekirdeğinde bu elementin çekirdekleri birleşerek helyum oluşturuyor; Güneş'in enerjisi buradan geliyor.", "serbest")],
      kullanim=S("Güneş'in enerjisi nereden gelir?",
                 "Çekirdeğinde hidrojen çekirdeklerinin birleşerek helyuma dönüşmesinden (füzyon)",
                 Y("Hidrojenin oksijenle yanmasından", "iliski", "Güneş'te yanma yok; enerji çekirdeklerin birleşmesinden geliyor (K2).", "K2"),
                 Y("Güneş'in içindeki uranyumun bölünmesinden", "kanitsiz", "Kanıtlar Güneş'te çekirdeklerin bölünmesini değil, birleşmesini gösteriyor (K2).", "K2"),
                 Y("Güneş'in yüzeyindeki koyu çizgilerden", "iliski", "Koyu çizgiler ışığın soğurulduğu yerlerdir (K1); enerjinin kaynağı değildir.", "K1"),
                 ipucu="K2'yi yeniden oku.",
                 aciklama="Güneş'in çekirdeğinde dört hidrojen çekirdeği, bir dizi adımda birleşerek bir helyum çekirdeğine dönüşür. Bu sırada kütlenin küçük bir bölümü enerjiye çevrilir. Hidrojen evrende en bol bulunan elementtir."),
      tablo_ozel=dict(
          baslik="1A grubu elementlerinin en güçlü spektrum çizgileri",
          satirlar=[["Element", "En güçlü çizginin dalga boyu (nm)", "Rengi"], ["Hidrojen", "656", "Kırmızı"], ["Lityum", "671", "Kırmızı"],
                    ["Sodyum", "589", "Turuncu-sarı"], ["Potasyum", "767", "Koyu kırmızı"], ["Rubidyum", "780", "Koyu kırmızı"],
                    ["Sezyum", "852", "Kızılötesi (görünmez)"]],
          olcum=("Laboratuvar ölçümü: çizginin yeri", "İncelenen koyu çizginin dalga boyu 656,3 ± 0,5 nm olarak ölçüldü.", "deney"),
          soru="İncelenen çizginin dalga boyu ({olcum}) tablodaki ({tablo}) hangi adayın çizgisiyle eşleşiyor?",
          ipucu="Ölçüm aralığı 655,8 ile 656,8 nm arasıdır.",
          aciklama="Ölçülen 656,3 nm, hidrojenin kırmızı çizgisiyle eşleşiyor. En yakın aday lityumun çizgisi 671 nm'de; ölçüm payının çok dışında.",
          dogru="Hidrojen",
          secenekler=[("Hidrojen", "", ""),
                      ("Lityum", "Lityumun çizgisi 671 nm ({tablo}); ölçülen 656,3 ± 0,5 nm aralığının dışında. Renkleri benzer olsa da dalga boyları farklı.", "birim"),
                      ("Sodyum", "Sodyumun çizgisi 589 nm ({tablo}), turuncu-sarı renkte; ölçülen çizgiyle uyuşmuyor.", "veri"),
                      ("Potasyum", "Potasyumun çizgisi 767 nm ({tablo}); ölçülen çizgiyle uyuşmuyor.", "veri")],
          savunma="ölçülen 656,3 nm'lik çizgi ({olcum}) yalnızca hidrojenin çizgisiyle eşleşiyor"),
      rakip="Li", rakip_neden="Tabloya göre lityumun en güçlü çizgisi 671 nm. Ölçülen çizgi 656,3 ± 0,5 nm; aradaki fark ölçüm payından çok büyük. Bu yüzden ölçüm iddiayı çürütür.",
      rakip_genel_neden="Bu gözlem bütün elementler için geçerli: her element spektrumda çizgi oluşturur. Lityumu elemez."),

    V("He", 3, "saglik", "Derinlerin Gazı",
      "Yüz metreden derine inen profesyonel dalgıçlar, tüplerinde normal hava yerine özel bir gaz karışımı soluyor. "
      "Karışımda azotun yerini bir soy gaz almış. Dalgıçların telsizden gelen sesleri tuhaf biçimde incelmiş. Görevin: "
      "azotun yerine kullanılan soy gazı bulmak.",
      [("kimyasal", "Gazın davranışı", "Gaz renksiz, kokusuz ve hiçbir maddeyle kolay kolay tepkimeye girmiyor."),
       ("fiziksel", "İncelen ses", "Bu gazı soluyan dalgıçların sesi incelip çizgi film karakterlerine benziyor; çünkü ses bu hafif gazın içinde havadakinden daha hızlı ilerliyor.")],
      kullanim=S("Derin dalışlarda solunan karışımda azotun yerine neden helyum kullanılır?",
                 "Helyum yüksek basınçta bile sarhoşluk etkisi yapmaz, tepkimeye girmez ve çok hafiftir",
                 Y("Helyum yanıcı olduğu için dalgıcı ısıttığı için", "veri", "Gaz hiçbir maddeyle kolay kolay tepkimeye girmiyor (K1); yanıcı değil.", "K1"),
                 Y("Helyum dalgıçların sesini incelttiği için konuşmayı kolaylaştırdığı için", "iliski", "Sesin incelmesi bir yan etkidir (K2); hatta konuşmayı zorlaştırır. Seçilme nedeni bu değil.", "K2"),
                 Y("Helyum havadan ağır olduğu için dalgıcı dibe indirdiği için", "veri", "Helyum çok hafif bir gazdır (K2); dalgıcı dibe indirmez.", "K2"),
                 ipucu="Derinde, yüksek basınçta solunan azot ne yapabilir?",
                 aciklama="Yüksek basınçta solunan azot, 'derinlik sarhoşluğu' denilen bir etkiye yol açar. Helyum bu etkiyi yapmaz ve tepkimeye girmez; bu yüzden derin dalışlarda oksijenle karıştırılarak kullanılır."),
      rakip="Ne"),

    V("Li", 3, "sanayi", "Uçağın Hafifleyen Gövdesi",
      "Bir uçak üreticisi, yeni yolcu uçağının gövde parçalarında alüminyuma çok az miktarda bir alkali metal katılmış bir "
      "alaşım kullandığını duyurdu. Böylece uçak tonlarca hafifliyor ve daha az yakıt harcıyor. Görevin: alaşıma katılan "
      "metali bulmak.",
      [("fiziksel", "Saf metalin özellikleri", "Saf hâli yumuşak, gümüşi bir metal; bıçakla kesilebiliyor ve suyla tepkimeye giriyor."),
       ("alasim", "Alaşımın üstünlüğü", "Alaşıma katılan metal alüminyumu hem hafifletiyor hem de sağlamlaştırıyor. Aynı metal telefon pillerinde de kullanılıyor.")],
      kullanim=S("Lityum uçak alaşımlarına neden katılır?",
                 "Bilinen en hafif metal olduğu için alaşımı hafifletir ve sağlamlığını artırır",
                 Y("Lityum çok yoğun olduğu için uçağı rüzgâra karşı sabitlediği için", "veri", "Ölçülen yoğunluk ({olcum}) bütün adaylardan düşük; lityum en hafif metaldir.", "{olcum}"),
                 Y("Lityum suyla tepkimeye girdiği için uçağı yağmurdan koruduğu için", "iliski", "Suyla tepkimeye girmek bir koruma sağlamaz; alaşımda lityum bu yüzden kullanılmıyor.", "K1"),
                 Y("Lityum pillerde kullanıldığı için uçağa elektrik verdiği için", "iliski", "Piller lityumun başka bir kullanım alanıdır (K2); gövde alaşımındaki görevi hafifletmek.", "K2"),
                 ipucu="K2'deki iki etkiye bak.",
                 aciklama="Lityum bilinen en hafif metaldir (0,53 g/cm³). Alüminyum-lityum alaşımları hem hafif hem sağlam olduğu için uçaklarda, bisiklet kadrolarında ve hızlı trenlerde kullanılır."),
      rakip="K"),

    V("O", 3, "uzay", "Apollo 13'ün Patlayan Tankı",
      "Nisan 1970'te Ay'a giden Apollo 13 uzay aracında bir tank patladı. Astronotlar 'Houston, bir sorunumuz var' dedi. "
      "Patlayan tank, hem solunum hem de elektrik üretimi için gereken bir elementin sıvı hâlini taşıyordu. Görevin: bu elementi bulmak.",
      [("kimyasal", "Elementin türü", "Element bir ametal; metallerle bileşik oluşturuyor."),
       ("tarih", "Kritik ihtiyaç", "Astronotlar bu elementi hem nefes almak için soluyor hem de aracın yakıt hücrelerinde hidrojenle birleştirerek elektrik ve su üretiyordu.")],
      kullanim=S("Apollo 13'te bu elementin kaybı neden bu kadar tehlikeliydi?",
                 "Oksijen hem astronotların solunumu hem de yakıt hücrelerinin elektrik üretmesi için gerekliydi",
                 Y("Oksijen aracın dış kaplamasını soğuttuğu için", "kanitsiz", "Kanıtlarda böyle bir görev yok; oksijen solunum ve elektrik için gerekliydi (K2).", "K2"),
                 Y("Oksijen aracı Ay'a doğru ittiği için", "kanitsiz", "Kanıtlar oksijenin solunum ve elektrik üretimi için kullanıldığını söylüyor (K2).", "K2"),
                 Y("Oksijen bir metal olduğu için aracın gövdesini oluşturduğu için", "veri", "Oksijen bir ametaldir (K1).", "K1"),
                 ipucu="K2'deki iki görevi düşün.",
                 aciklama="Apollo araçlarında yakıt hücreleri oksijen ve hidrojenden elektrik ve içme suyu üretiyordu. Tank patlayınca astronotlar Ay modülünü bir 'cankurtaran sandalı' gibi kullanarak Dünya'ya güvenle döndüler."),
      rakip="S"),

    V("F", 3, "ev", "Hiçbir Şeyin Yapışmadığı Tava",
      "1938'de bir kimyacı, soğutucu gaz denemeleri sırasında bir gaz tüpünün boşaldığını sandı. Tüpü kesince içinin beyaz, "
      "kaygan bir tozla kaplandığını gördü. Bu toz bugün yapışmaz tavaların kaplamasında kullanılıyor. Görevin: kaplamadaki "
      "karbon dışındaki elementi bulmak.",
      [("kimyasal", "Elementin türü", "Element çok etkin bir ametal; metallerle tuz oluşturuyor."),
       ("kimyasal", "Güçlü bağ", "Kaplamanın molekülü karbon zincirine bağlı bu elementin atomlarından oluşuyor. Karbonla bu element arasındaki bağ, kimyadaki en güçlü tekli bağlardan biri.")],
      kullanim=S("Teflon kaplamaya yemekler neden yapışmaz?",
                 "Karbon-flor bağları çok güçlüdür; yüzey neredeyse hiçbir maddeyle etkileşmez",
                 Y("Kaplama çok sıcak olduğu için yemekleri iter", "iliski", "Yapışmazlık sıcaklıktan değil, kaplamanın molekül yapısından gelir (K2).", "K2"),
                 Y("Flor çok etkin olduğu için yemekleri yakar", "iliski", "Flor tek başına çok etkindir (K1) ama karbonla bağlandığında bu bağlar çok kararlıdır (K2); kaplama yemekle tepkimeye girmez.", "K2"),
                 Y("Kaplama suyu emdiği için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; kaplama suyu iter.", "K2"),
                 ipucu="K2'deki bağın özelliğine bak.",
                 aciklama="Teflon (PTFE), karbon zincirine bağlı flor atomlarından oluşur. Karbon-flor bağları o kadar güçlüdür ki yüzey neredeyse hiçbir maddeyle etkileşmez. Teflon 1938'de Roy Plunkett tarafından tesadüfen bulundu."),
      rakip="Cl"),

    V("Na", 3, "enerji", "Reaktördeki Sıvı Metal",
      "Bazı hızlı nötron reaktörlerinde çekirdeği soğutmak için su yerine sıvı hâle getirilmiş bir alkali metal kullanılıyor. "
      "Metal borularda dolaşıp reaktörün ısısını taşıyor. Görevin: bu soğutucu metali bulmak.",
      [("fiziksel", "Metalin davranışı", "Metal yumuşak ve gümüşi; havada hızla kararıyor ve suyla şiddetli tepkimeye giriyor."),
       ("fiziksel", "Sıvı hâlde ısı taşıma", "Sıvı metal ısıyı sudan çok daha iyi iletiyor ve yaklaşık 880 °C'ye kadar kaynamıyor.")],
      kullanim=S("Bazı reaktörlerde soğutucu olarak neden sıvı sodyum kullanılır?",
                 "Geniş bir sıcaklık aralığında (yaklaşık 98–883 °C) sıvı kalır ve ısıyı çok iyi iletir",
                 Y("Sodyum suyla tepkimeye girmediği için güvenli olduğu için", "veri", "Sodyum suyla şiddetli tepkimeye girer (K1); bu yüzden reaktörde sudan ayrı tutulmalıdır.", "K1"),
                 Y("Sodyum oda sıcaklığında sıvı olduğu için", "veri", "Sodyum yaklaşık 98 °C'de erir ({olcum}); oda sıcaklığında katıdır.", "{olcum}"),
                 Y("Sodyum nötronları çok iyi yutup tepkimeyi durdurduğu için", "kanitsiz", "Kanıtlar sodyumun ısı taşıma özelliğini anlatıyor (K2).", "K2"),
                 ipucu="K2 ve ölçümü birleştir.",
                 aciklama="Sıvı sodyum yaklaşık 98 °C'de erir, 883 °C'de kaynar; arada çok geniş bir sıvı aralığı vardır ve ısıyı çok iyi iletir. Ancak suyla ve havayla şiddetli tepkimeye girdiği için büyük bir dikkatle kullanılır."),
      ozellik="erime", rakip="K"),

    V("Mg", 3, "teknoloji", "Hafif Dizüstü Bilgisayar",
      "Bir bilgisayar firması, yeni dizüstü bilgisayarının kasasının 'alüminyumdan bile hafif bir metal alaşımından' yapıldığını "
      "söylüyor. Kasadan alınan bir parça laboratuvara gönderildi. Görevin: alaşımdaki ana metali bulmak.",
      [("fiziksel", "Kasanın görünüşü", "Kasa gümüşi gri, metal parlaklığında ve ısıyı iyi iletiyor."),
       ("deney", "Mıknatıs testi", "Kasa parçası mıknatısa çekilmedi.")],
      kullanim=S("Bu metal dizüstü bilgisayar kasalarında neden tercih ediliyor?",
                 "Çok düşük yoğunluklu olduğu için kasayı hafifletirken yeterince sağlam olması",
                 Y("Mıknatısa çekildiği için", "veri", "Kasa parçası mıknatısa çekilmedi (K2).", "K2"),
                 Y("Elektriği hiç iletmediği için", "iliski", "Magnezyum bir metaldir ve elektriği iletir; kasa seçiminin nedeni hafifliğidir.", "K1"),
                 Y("Yoğunluğu çok yüksek olduğu için", "veri", "Ölçülen yoğunluk ({olcum}) tablodaki metallerin çoğundan düşük.", "{olcum}"),
                 ipucu="Firma kasanın neyle övünüyor?",
                 aciklama="Magnezyum yapılarda kullanılan en hafif metaldir (1,74 g/cm³). Alaşımları hem hafif hem sağlam olduğu için dizüstü bilgisayar, kamera ve araç parçalarında kullanılır."),
      rakip="Be"),

    V("Al", 3, "cevre", "Kutunun İkinci Hayatı",
      "Bir okulun geri dönüşüm kampanyasında öğrenciler binlerce içecek kutusu topladı. Belediye, bu kutuların eritilip "
      "yeniden kutu yapılmasının, aynı metali cevherinden elde etmeye göre çok daha az enerji harcadığını söylüyor. Görevin: "
      "kutuların metalini bulmak.",
      [("kimyasal", "Doğadaki hâli", "Element yer kabuğunda bileşikleri hâlinde bulunuyor; saf hâlde doğada neredeyse hiç görülmüyor."),
       ("tarih", "Enerji karşılaştırması", "Kutuları eritip yeniden kullanmak, aynı metali cevherinden elde etmeye göre enerjinin yaklaşık %95'ini tasarruf ettiriyor.")],
      kullanim=S("Alüminyumu geri dönüştürmek neden bu kadar enerji tasarrufu sağlar?",
                 "Alüminyumu cevherinden ayırmak çok fazla elektrik gerektirir; hazır metali eritmek için çok daha az enerji yeter",
                 Y("Alüminyum geri dönüşümde hiç eritilmediği için", "kanitsiz", "Kutular eritilerek yeniden kullanılıyor (hikâye).", "K2"),
                 Y("Alüminyum doğada saf hâlde bol bulunduğu için", "veri", "Alüminyum doğada saf hâlde neredeyse hiç bulunmaz (K1); bileşiklerinden ayrılması çok enerji ister.", "K1"),
                 Y("Alüminyum çok ağır olduğu için taşınması pahalı olduğu için", "veri", "Ölçülen yoğunluk ({olcum}) düşük; alüminyum hafif bir metaldir.", "{olcum}"),
                 ipucu="K1: Metal doğada hangi hâlde bulunuyor?",
                 aciklama="Alüminyum oksijene çok sıkı bağlanır; cevherinden (boksit) ayrılması için çok büyük miktarda elektrik gerekir. Hazır alüminyumu eritmek bu enerjinin yalnızca yaklaşık yirmide birini harcar. Alüminyum kalitesini kaybetmeden defalarca geri dönüştürülebilir."),
      rakip="B"),

    V("Si", 3, "sanat", "Kumdan Doğan Cam",
      "Bir cam ustası, kumu soda ve kireçle birlikte bir fırında 1500 °C'nin üzerinde eritip üfleyerek bir vazo yaptı. "
      "Öğrenciler, kumun ana bileşenindeki elementi merak etti. Görevin: bu elementi bulmak.",
      [("kimyasal", "Dev ağ yapısı", "Elementin atomları dört bağ yaparak birbirine bağlanıyor ve dev ağ yapıları oluşturabiliyor."),
       ("kimyasal", "Kumun bileşeni", "Kumun ana bileşeni bu elementin oksidi. Erimiş kum soğuyunca kristal oluşturmadan saydam, sert bir katıya dönüşüyor.")],
      kullanim=S("Cam yapımında kum neden kullanılır?",
                 "Kumdaki silisyum dioksit eriyip soğuyunca düzenli kristaller oluşturmadan saydam ve sert bir katıya, yani cama dönüşür",
                 Y("Kum metal olduğu için cama parlaklık verdiği için", "veri", "Kumun elementi bir metal değil; parlaklık camın saydamlığından gelir.", "K2"),
                 Y("Kum çok düşük sıcaklıkta eridiği için", "veri", "Cam ustası kumu 1500 °C'nin üzerinde eritiyor (hikâye).", "K2"),
                 Y("Kum suda çözündüğü için camı yumuşattığı için", "kanitsiz", "Kum suda çözünmez; kanıtlar erimiş kumun soğuyunca cama dönüştüğünü söylüyor (K2).", "K2"),
                 ipucu="K2'nin ikinci cümlesine bak.",
                 aciklama="Cam, kumdaki silisyum dioksitin eritilip hızla soğutulmasıyla oluşur. Atomlar düzenli bir kristal oluşturmaya fırsat bulamaz; ortaya saydam, sert ve düzensiz yapılı bir katı çıkar. Soda erime sıcaklığını düşürür, kireç de camı suya dayanıklı yapar."),
      rakip="C"),

    V("P", 3, "tarih", "Simyacının Parlayan Maddesi",
      "1669'da Hamburg'da simyacı Hennig Brandt, değersiz metalleri altına çevirecek 'felsefe taşını' ararken büyük "
      "miktarda idrarı kaynatıp kalıntısını kızıl dereceye kadar ısıttı. Kabın dibinde karanlıkta parlayan beyaz bir madde "
      "oluştu. Görevin: bu maddeyi oluşturan elementi bulmak.",
      [("kimyasal", "Elementin türü", "Element bir ametal; canlıların yapısında bulunuyor."),
       ("deney", "Karanlıkta ışık", "Elde edilen beyaz madde karanlıkta yeşilimsi bir ışıkla parlıyor ve havada kendiliğinden tutuşabiliyor.", "serbest")],
      kullanim=S("Brandt'ın elde ettiği madde karanlıkta neden parlıyordu?",
                 "Beyaz fosfor havadaki oksijenle yavaşça tepkimeye girerken ışık yayar",
                 Y("Madde radyoaktif olduğu için", "kanitsiz", "Fosforun parlaması radyoaktiflikten değil, oksijenle verdiği tepkimeden gelir.", "K2"),
                 Y("Madde gün ışığını depoladığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; madde havayla tepkimeye girerek parlıyor.", "K2"),
                 Y("Madde idrardan geldiği için", "iliski", "Maddenin nereden elde edildiği, neden parladığını açıklamaz.", "K1"),
                 ipucu="K2: Madde havada ne yapabiliyor?",
                 aciklama="Beyaz fosfor havadaki oksijenle yavaşça tepkimeye girer ve bu sırada ışık yayar. Adı da Yunanca 'ışık getiren' anlamına gelir. Brandt felsefe taşını bulamadı ama yeni bir elementi keşfeden ilk kişi oldu."),
      rakip="N"),

    V("S", 3, "sanayi", "Lastiğin Sırrı",
      "1830'larda doğal kauçuktan yapılan eşyalar yazın yapış yapış oluyor, kışın çatlıyordu. 1839'da Charles Goodyear, "
      "kauçuğu sarı bir ametalin tozuyla birlikte ısıtınca sıcağa ve soğuğa dayanıklı, sağlam bir malzeme elde etti. "
      "Görevin: kauçuğa katılan elementi bulmak.",
      [("kimyasal", "Elementin türü", "Element bir ametal; metallerle bileşik oluşturuyor."),
       ("deney", "Isıtılan kauçuk", "Kauçuk bu elementin tozuyla ısıtılınca, sıcakta yapışkanlaşmayan ve soğukta çatlamayan esnek bir malzemeye dönüşüyor.")],
      kullanim=S("Lastik yapımında kauçuk neden kükürtle ısıtılır?",
                 "Kükürt atomları kauçuk zincirleri arasında köprüler kurarak malzemeyi sağlam, esnek ve sıcağa-soğuğa dayanıklı yapar",
                 Y("Kükürt kauçuğu sarıya boyadığı için", "iliski", "Renk önemli değil; kükürdün etkisi kauçuğun yapısını değiştirmesidir (K2).", "K2"),
                 Y("Kükürt kauçuğu eritip sıvı hâlde tuttuğu için", "veri", "İşlemden sonra malzeme katı ve sağlam kalıyor (K2).", "K2"),
                 Y("Kükürt bir metal olduğu için lastiği sertleştirdiği için", "veri", "Kükürt bir ametaldir (K1).", "K1"),
                 ipucu="K2'deki değişikliğe bak.",
                 aciklama="Bu işleme vulkanizasyon denir. Kükürt atomları uzun kauçuk zincirlerini birbirine bağlar; malzeme hem esnek hem de dayanıklı olur. Araba lastikleri bu sayede yazın yumuşamaz, kışın çatlamaz."),
      rakip="O"),

    V("K", 3, "ev", "Suda Dans Eden Metal",
      "Bir kimya gösterisinde, gazyağının içinden çıkarılan küçük bir metal parçası suya atıldı. Parça suyun üzerinde "
      "yüzüp hızla dönerek dolaştı ve lila renkli bir alevle yandı. Görevin: bu metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal yumuşak; bıçakla kesilebiliyor ve kesik yüzeyi havada hızla kararıyor."),
       ("deney", "Sudaki tepkime", "Suya atılan parça suyun üzerinde yüzüp dönerek lila renkli bir alevle yandı.", "serbest")],
      kullanim=S("Potasyum parçası suda neden alev aldı?",
                 "Potasyum suyla şiddetli tepkimeye girip hidrojen gazı ve ısı açığa çıkarır; ısı hidrojeni tutuşturur",
                 Y("Su potasyumu yakan bir yakıt olduğu için", "iliski", "Su bir yakıt değildir; alev, tepkimede oluşan hidrojenin yanmasıdır.", "K2"),
                 Y("Potasyum havadan ağır olduğu için suya batıp ısındığı için", "veri", "Parça suya batmadı, üzerinde yüzdü (K2).", "K2"),
                 Y("Gazyağı potasyumun üzerinde kalıp yandığı için", "kanitsiz", "Alevin gazyağından geldiğine dair bir kanıt yok; lila renk potasyumdan geliyor.", "K2"),
                 ipucu="Alkali metaller suyla tepkimeye girince hangi gaz oluşur?",
                 aciklama="Potasyum suyla tepkimeye girerek potasyum hidroksit ve hidrojen gazı oluşturur; açığa çıkan ısı hidrojeni tutuşturur. Alevin lila rengi potasyumdan gelir. Potasyum bu yüzden havadan ve nemden uzak, gazyağı içinde saklanır."),
      rakip="Na"),

    V("Ca", 3, "tarih", "Süleymaniye'nin Harcı",
      "Bir restorasyon ekibi, 16. yüzyıldan kalma bir caminin taşlarını birbirine bağlayan harçtan örnek aldı. Harcın "
      "bağlayıcısı, yüzyıllar içinde havadan bir gaz emerek taş kadar sertleşmişti. Görevin: harcın bağlayıcısındaki metali bulmak.",
      [("kimyasal", "Elementin türü", "Element bir metal; bileşiklerinde +2 yüklü iyon oluşturuyor."),
       ("kimyasal", "Sertleşen harç", "Harcın bağlayıcısı bu elementin hidroksiti (sönmüş kireç). Harç yıllar içinde havadaki karbondioksiti emerek yeniden kireç taşına dönüşüyor ve sertleşiyor.")],
      kullanim=S("Kireçli harç zamanla neden sertleşir?",
                 "Kalsiyum hidroksit havadaki karbondioksitle tepkimeye girip sert kalsiyum karbonata (kireç taşına) dönüşür",
                 Y("Harç kuruyunca suyu buz gibi donduğu için", "iliski", "Harcın sertleşmesi donmadan değil, bir kimyasal tepkimeden kaynaklanır (K2).", "K2"),
                 Y("Harçtaki kalsiyum metali paslandığı için", "veri", "Harçta kalsiyum metal olarak değil, hidroksiti olarak bulunur (K2).", "K2"),
                 Y("Harç havadaki oksijeni emdiği için", "veri", "Harcın emdiği gaz karbondioksit (K2).", "K2"),
                 ipucu="K2'deki tepkimeyi düşün.",
                 aciklama="Kireç taşı (kalsiyum karbonat) yakılınca sönmemiş kirece, suyla karışınca sönmüş kirece dönüşür. Sönmüş kireç havadaki karbondioksiti emerek yeniden kalsiyum karbonata dönüşür ve sertleşir. Osmanlı mimarisinde kullanılan horasan harcı da kireç ve tuğla tozundan yapılırdı."),
      rakip="Mg"),

    V("Ti", 3, "sanat", "Pul Pul Parlayan Müze",
      "İspanya'nın Bilbao şehrindeki Guggenheim Müzesi'nin kıvrımlı dış yüzeyi, balık pulu gibi binlerce ince metal levhayla "
      "kaplı. Levhalar yağmura ve deniz havasına rağmen yıllardır paslanmadan parlıyor. Görevin: levhaların metalini bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal parlak, gümüşi ve elektriği iletiyor."),
       ("fiziksel", "Kâğıt inceliğinde levhalar", "Levhalar yalnızca yaklaşık 0,4 mm kalınlığında. Bu kadar ince oldukları hâlde rüzgâra dayanıyor ve paslanmıyor.")],
      kullanim=S("Titanyum bu binanın dış kaplamasında neden seçildi?",
                 "Hafif, sağlam ve korozyona çok dayanıklı olduğu için ince levhalar bile yıllarca bozulmaz",
                 Y("Titanyum çok yoğun olduğu için binayı depreme karşı sağlamlaştırdığı için", "veri", "Ölçülen yoğunluk ({olcum}) düşük; titanyum hafif bir metaldir.", "{olcum}"),
                 Y("Titanyum elektriği hiç iletmediği için yıldırımdan koruduğu için", "veri", "Metal elektriği iletiyor (K1).", "K1"),
                 Y("Titanyum yağmur suyuyla tepkimeye girip parlaklaştığı için", "kanitsiz", "Levhalar yağmura rağmen değişmiyor (K2); suyla tepkimeye girdiğine dair bir kanıt yok.", "K2"),
                 ipucu="K2'deki özellikleri düşün.",
                 aciklama="Titanyum çelik kadar sağlam ama çok daha hafiftir; yüzeyinde oluşan ince oksit tabakası onu deniz havasına ve yağmura karşı korur. Bu yüzden ince levhalar binayı yıllarca koruyabilir."),
      rakip="Zr"),

    V("V", 3, "sanayi", "Model T'nin Sağlam Çeliği",
      "1908'de üretilmeye başlanan Ford Model T, milyonlarca kişinin satın alabildiği ilk otomobillerden biriydi. Henry Ford, "
      "aracın aksları ve dişlileri için içine çok az miktarda bir geçiş metali katılmış hafif ama çok sağlam bir çelik seçti. "
      "Görevin: bu metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal sert, gümüşi gri ve elektriği iletiyor."),
       ("alasim", "Az ama etkili", "Çeliğe yüzde birden az miktarda bu metal katılınca çelik darbelere ve titreşime karşı çok dayanıklı hâle geliyor.")],
      kullanim=S("Ford, Model T'nin parçalarında neden vanadyumlu çelik kullandı?",
                 "Az miktarda vanadyum çeliği darbeye ve titreşime karşı çok daha dayanıklı yapar; parçalar hafif ama sağlam olur",
                 Y("Vanadyum çeliği paslanmaz yaptığı için", "kanitsiz", "Kanıtlar vanadyumun çeliği darbeye dayanıklı yaptığını söylüyor (K2); paslanmazlıktan söz etmiyor.", "K2"),
                 Y("Vanadyum çeliği yumuşattığı için kolay şekil verildiği için", "veri", "Vanadyum çeliği yumuşatmıyor, sağlamlaştırıyor (K2).", "K2"),
                 Y("Vanadyum çok ucuz olduğu için çeliğin yerine kullanıldığı için", "veri", "Vanadyum çeliğin yerine değil, çeliğe çok az miktarda katılıyor (K2).", "K2"),
                 ipucu="K2'deki etkiye bak.",
                 aciklama="Üretilen vanadyumun yaklaşık %80'i çeliğe katılır. Vanadyumlu çelikler çok sağlamdır; aks, krank mili ve el aletlerinde (krom-vanadyum anahtarlar gibi) kullanılır."),
      rakip="Nb"),

    V("Cr", 3, "sanayi", "Ayna Gibi Jant",
      "Bir oto kaportacısında eski bir otomobilin tamponu ve jantları yeniden kaplanıyor. Parçalar bir metal tuzunun "
      "çözeltisine daldırılıp elektrik verilince yüzeyleri ayna gibi parlayan ince bir tabakayla kaplanıyor. Görevin: kaplama metalini bulmak.",
      [("fiziksel", "Metalin özellikleri", "Metal çok sert ve parlak; elektriği iletiyor."),
       ("deney", "Elektrikle kaplama", "Parçalar metal tuzunun çözeltisine daldırılıp elektrik verilince yüzeyleri ince bir metal tabakasıyla kaplanıyor; tabaka çizilmeye ve paslanmaya dayanıklı.")],
      kullanim=S("Krom kaplama neden kullanılır?",
                 "Ayna gibi parlak, sert ve korozyona dayanıklı bir yüzey oluşturduğu için",
                 Y("Kromun mıknatıs olması parçaları birbirine tutturduğu için", "iliski", "Kaplamanın görevi parçaları tutturmak değil, yüzeyi korumak ve parlatmak (K2).", "K2"),
                 Y("Krom çok yumuşak olduğu için darbeleri emdiği için", "veri", "Krom çok sert bir metaldir (K1).", "K1"),
                 Y("Krom kaplama parçaları ağırlaştırarak sağlamlaştırdığı için", "iliski", "Kaplama çok ince; ağırlığın bir etkisi yok. Önemli olan yüzeyin sertliği ve parlaklığı.", "K2"),
                 ipucu="K1 ve K2'deki özellikleri birleştir.",
                 aciklama="Krom kaplama, elektrolizle bir yüzeyin ince bir krom tabakasıyla kaplanmasıdır. Krom tabakası ayna gibi parlar, serttir ve paslanmaz. Musluklar, banyo armatürleri ve eski araçların tamponları böyle kaplanır."),
      rakip="Mo"),

    V("Mn", 3, "sanayi", "Darbelerle Sertleşen Ray",
      "Demiryolu makaslarında, rayların birbirini kestiği yerlere her gün yüzlerce ton ağırlığındaki trenler çarpıyor. "
      "Bu bölümler, darbe aldıkça yüzeyi sertleşen özel bir çelikten yapılıyor. Görevin: bu çeliğe yaklaşık %13 oranında "
      "katılan metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal sert ve gümüşi gri."),
       ("alasim", "Darbeyle sertleşme", "Çelik yaklaşık %13 oranında bu metali içeriyor. Trenler geçtikçe yüzeyi darbelerle daha da sertleşiyor ve aşınmaya dayanıyor.")],
      kullanim=S("Demiryolu makaslarında manganlı çelik neden kullanılır?",
                 "Darbe aldıkça yüzeyi sertleşir; böylece sürekli çarpmaya ve aşınmaya dayanır",
                 Y("Mangan çeliği hafiflettiği için trenler daha hızlı geçebildiği için", "kanitsiz", "Kanıtlar manganın çeliği darbeyle sertleştirdiğini söylüyor (K2); hafiflikten söz etmiyor.", "K2"),
                 Y("Mangan çeliği yumuşatarak darbeleri emdiği için", "veri", "Çeliğin yüzeyi darbelerle yumuşamıyor, sertleşiyor (K2).", "K2"),
                 Y("Mangan pillerde kullanıldığı için raylara elektrik verdiği için", "iliski", "Piller manganın başka bir kullanım alanıdır; raydaki görevi darbeye dayanıklılık (K2).", "K2"),
                 ipucu="K2'deki özelliğe bak.",
                 aciklama="Hadfield çeliği denilen bu çelik %11–14 mangan içerir. Darbe aldıkça yüzeyi sertleşir; bu yüzden demiryolu makaslarında, taş kırıcılarda ve iş makinelerinin kepçelerinde kullanılır."),
      rakip="Re"),

    V("Co", 3, "saglik", "Kırmızı Vitaminin Kalbi",
      "Bir beslenme uzmanı, bitkisel beslenen kişilerin B12 vitamini takviyesi alması gerektiğini anlatıyor. B12, en büyük "
      "ve en karmaşık vitaminlerden biri; molekülünün tam merkezinde bir metal atomu var. Görevin: bu metali bulmak.",
      [("kimyasal", "Elementin türü", "Element bir geçiş metali; bileşikleri renkli."),
       ("kimyasal", "Vitaminin merkezi", "B12 vitamininin büyük molekülünün tam merkezinde bu metalin bir atomu bulunuyor; vitamin koyu kırmızı renkli.")],
      kullanim=S("Kobaltın vücudumuzdaki görevi nedir?",
                 "B12 vitamininin merkezinde bulunur; bu vitamin kan hücrelerinin yapımı ve sinir sistemi için gereklidir",
                 Y("Kemiklerin ana yapı taşıdır", "iliski", "Kemiklerin ana yapı taşı kalsiyumdur; kobalt B12 vitamininin merkezinde bulunur (K2).", "K2"),
                 Y("Kanın oksijen taşıyan molekülünün merkezindedir", "iliski", "Oksijen taşıyan hemoglobinin merkezinde demir bulunur; kobalt B12'nin merkezindedir (K2).", "K2"),
                 Y("Vücuda radyasyon koruması sağlar", "kanitsiz", "Kanıtlarda böyle bir görev yok.", "K2"),
                 ipucu="K2'yi oku.",
                 aciklama="B12 vitamini (kobalamin) kobalt içeren tek vitamindir. Kırmızı kan hücrelerinin yapımı ve sinir sisteminin sağlığı için gereklidir. Kobalt ayrıca lityum iyon pillerde ve mavi boyalarda kullanılır."),
      rakip="Rh"),

    V("Ni", 3, "ev", "Otomatın Tanıdığı Para",
      "Bir içecek otomatı, atılan madeni paraların gerçek olup olmadığını saniyeler içinde anlıyor. Teknisyen, otomatın "
      "paranın boyutunu, ağırlığını ve mıknatıs özelliğini ölçtüğünü söylüyor. 1 ve 2 avroluk paraların alaşımında bakırın "
      "yanında başka bir metal de var. Görevin: bu metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal parlak, gümüşi ve paslanmaya dayanıklı."),
       ("deney", "Mıknatıs testi", "Bu metal mıknatısa çekiliyor; otomat paranın mıknatıs özelliğini ölçerek sahteleri ayırabiliyor.", "serbest")],
      kullanim=S("Nikel madeni paralarda neden kullanılır?",
                 "Sert, aşınmaya ve paslanmaya dayanıklıdır; mıknatıs özelliği de otomatların sahte paraları ayırt etmesine yardım eder",
                 Y("Nikel çok yumuşak olduğu için paralara kolay basıldığı için", "kanitsiz", "Nikel sert bir metaldir; kanıtlarda yumuşaklıktan söz edilmiyor.", "K1"),
                 Y("Nikel hiç mıknatısa çekilmediği için", "veri", "Nikel mıknatısa çekiliyor (K2).", "K2"),
                 Y("Nikel paraları daha hafif yaptığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; ölçülen yoğunluk ({olcum}) düşük değil.", "{olcum}"),
                 ipucu="K1 ve K2'deki özellikleri birleştir.",
                 aciklama="Nikel sert, parlak ve korozyona dayanıklıdır; demir ve kobalt gibi mıknatısa çekilir. Bu özellikler onu madeni paralar ve paslanmaz çelik için uygun yapar."),
      rakip="Pd"),

    V("Cu", 3, "saglik", "Mikrop Tutmayan Kapı Kolu",
      "Bir hastanede yapılan deneyde, yoğun kullanılan kapı kollarının bir kısmı paslanmaz çelik, bir kısmı kızıl kahverengi "
      "bir metalden yapıldı. Birkaç hafta sonra kızıl kahverengi kolların üzerinde çok daha az bakteri bulundu. Görevin: bu metali bulmak.",
      [("iletkenlik", "İletkenlik", "Metal elektriği ve ısıyı çok iyi iletiyor."),
       ("deney", "Bakteri sayımı", "Bu metalden yapılan kapı kollarında, paslanmaz çelik kollara göre çok daha az bakteri bulundu. Metal kızıl kahverengi renkte.", "serbest")],
      kullanim=S("Bakır yüzeyler hastanelerde neden kullanılıyor?",
                 "Bakır yüzeyler üzerlerindeki bakterileri kısa sürede öldürür; mikropların dokunmayla yayılması azalır",
                 Y("Bakır elektriği iyi ilettiği için mikropları elektrikle öldürdüğü için", "iliski", "İletkenlik (K1) mikropları öldürmeyi açıklamaz; etkiyi bakır iyonları yapar.", "K1"),
                 Y("Bakır kolları temizlemek daha kolay olduğu için", "kanitsiz", "Deneyde kollar aynı biçimde kullanıldı; fark metalin kendisinden geliyor (K2).", "K2"),
                 Y("Bakır kızıl renkli olduğu için mikroplar ona konmadığı için", "iliski", "Renk mikropları etkilemez; etki bakırın kimyasal özelliğinden gelir.", "K2"),
                 ipucu="K2'deki deneyin sonucunu düşün.",
                 aciklama="Bakır ve pirinç gibi bakır alaşımlarının yüzeyleri birçok bakteriyi saatler içinde öldürür. Bu yüzden bazı hastanelerde kapı kolları, tutamaklar ve yatak korkulukları bakır alaşımlarından yapılır."),
      rakip="Ag"),

    V("Zn", 3, "ev", "Altın Sanılan Tokmak",
      "Eski bir konağın kapısındaki sarı, parlak tokmağı gören bir çocuk 'Bu altından mı?' diye sordu. Usta, tokmağın bakırla "
      "başka bir metalin alaşımı olan pirinçten yapıldığını söyledi. Görevin: pirinçteki ikinci metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal mavimsi beyaz ve parlak."),
       ("alasim", "Sarı alaşım", "Bakır bu metalle karıştırılınca altına benzeyen sarı bir alaşım (pirinç) oluşuyor. Pirinç bakırdan daha sert ve işlenmesi kolay.")],
      kullanim=S("Pirinç kapı tokmaklarında ve müzik aletlerinde neden kullanılır?",
                 "Bakırdan daha sert, kolay işlenen, korozyona dayanıklı ve altına benzeyen parlak sarı bir alaşımdır",
                 Y("Pirinç saf altın olduğu için", "veri", "Pirinç bakır ile başka bir metalin alaşımıdır (K2); altın değildir.", "K2"),
                 Y("Çinko mavimsi beyaz olduğu için pirinci beyaz yaptığı için", "veri", "Pirinç sarı renklidir (K2).", "K2"),
                 Y("Pirinç elektriği hiç iletmediği için", "kanitsiz", "Pirinç bir metal alaşımıdır ve elektriği iletir; kanıtlarda tersi yok.", "K2"),
                 ipucu="K2'deki alaşımın özelliklerine bak.",
                 aciklama="Pirinç, bakır ve çinkonun alaşımıdır. Çinko oranı arttıkça renk açılır. Pirinç trompet ve borazan gibi nefesli çalgılarda, musluklarda, kapı kollarında ve süs eşyalarında kullanılır."),
      rakip="Cd"),
]
