# -*- coding: utf-8 -*-
"""Seviye 3 (Kanıt) — yeni vakalar, ikinci bölüm."""
from sablon import S, V, Y

VAKALAR = [
    V("Ga", 3, "teknoloji", "Mavi Işığın Nobel'i",
      "2014 Nobel Fizik Ödülü, verimli mavi ışık yayan LED'leri yapan üç araştırmacıya verildi. Bu LED'ler sayesinde beyaz "
      "LED ampuller mümkün oldu. Mavi ışığı veren bileşik, azot ile bir metalden oluşuyor. Görevin: bu metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Element yumuşak, gümüşi bir metal."),
       ("kimyasal", "Işık saçan bileşik", "Bu metalin azotla oluşturduğu bileşik bir yarı iletken; içinden akım geçince mavi ışık yayıyor.")],
      kullanim=S("Galyum nitrür neden önemli bir buluştu?",
                 "Verimli mavi ışık yayar; mavi LED'ler sayesinde az enerji harcayan beyaz LED ampuller yapılabildi",
                 Y("Galyum nitrür elektriği hiç iletmediği için", "veri", "Bileşik bir yarı iletken; içinden akım geçince ışık yayıyor (K2).", "K2"),
                 Y("Galyum nitrür kırmızı ışık yaydığı için", "veri", "Bileşik mavi ışık yayıyor (K2).", "K2"),
                 Y("Galyum avuçta eridiği için LED'i soğuttuğu için", "iliski", "Galyumun düşük erime noktası LED'deki görevini açıklamaz; ışığı bileşiği yayar (K2).", "K2"),
                 ipucu="Beyaz ışık için hangi renkler gerekir?",
                 aciklama="Kırmızı ve yeşil LED'ler daha önce vardı; mavi LED uzun süre yapılamadı. Galyum nitrür ile yapılan mavi LED'ler sayesinde beyaz LED ışığı elde edildi. LED ampuller eski ampullerden çok daha az elektrik harcar."),
      rakip="In"),

    V("As", 3, "adli", "Yeşil Duvar Kâğıdı",
      "Napolyon Bonapart sürgünde öldükten yıllar sonra saçlarında yüksek miktarda zehirli bir element bulundu. Bazı "
      "araştırmacılar, kaldığı evin nemli odalarındaki parlak yeşil duvar kâğıdından şüphelendi. Bu bir hipotez; kesinleşmiş "
      "değil. Görevin: yeşil boyadaki zehirli elementi bulmak.",
      [("kimyasal", "Elementin türü", "Element bir yarı metal; bileşiklerinin çoğu zehirli."),
       ("kimyasal", "Yeşil boya", "1800'lerde çok sevilen parlak yeşil boya, bakır ile bu elementin bir bileşiğiydi. Nemli ortamda boyadan zehirli maddeler yayılabildiği düşünülüyor.")],
      kullanim=S("Arsenikli yeşil boya neden zamanla terk edildi?",
                 "Arsenik bileşikleri çok zehirlidir; boyadan yayılan toz ve gazlar insan sağlığını tehdit ediyordu",
                 Y("Boya güneşte hızla solduğu için", "kanitsiz", "Kanıtlar boyanın zehirliliğini anlatıyor (K2); solmasından söz etmiyor.", "K2"),
                 Y("Arsenik bir metal olduğu için boya paslandığı için", "veri", "Arsenik bir yarı metaldir (K1); boyanın terk edilme nedeni zehirliliği.", "K1"),
                 Y("Boya çok pahalı olduğu için", "kanitsiz", "Boya 1800'lerde çok sevilen ve yaygın bir boyaydı (K2); terk edilme nedeni sağlık.", "K2"),
                 ipucu="K1 ve K2'deki uyarılara bak.",
                 aciklama="Scheele yeşili ve Paris yeşili gibi boyalar arsenik içeriyordu ve zamanla yasaklandı. Napolyon'un ölüm nedeni tartışmalıdır; saçındaki arsenik duvar kâğıdından, ilaçlardan ya da çevreden gelmiş olabilir. Bilim, bu tür hipotezleri yeni kanıtlarla sınar."),
      rakip="Sb"),

    V("Se", 3, "ev", "Kepeğe Karşı Şampuan",
      "Bir eczacı, kepek sorunu olan bir müşteriye özel bir şampuan önerdi. Şampuanın etken maddesi, kükürtle aynı grupta "
      "bulunan bir elementin sülfürü. Görevin: bu elementi bulmak.",
      [("iletkenlik", "Elementin türü", "Element bir metal değil; elektriği metaller kadar iyi iletmiyor."),
       ("kimyasal", "Şampuanın etkisi", "Etken madde, saç derisinde kepeğe yol açan mantarlar için zehirli; mantarların çoğalmasını yavaşlatıyor.")],
      kullanim=S("Selenyum sülfür kepek şampuanlarında neden kullanılır?",
                 "Kepeğe yol açan mantarlar için zehirlidir; mantarın çoğalmasını yavaşlatır",
                 Y("Saçı boyadığı için", "kanitsiz", "Kanıtlar maddenin mantarları etkilediğini söylüyor (K2); boyamadan söz etmiyor.", "K2"),
                 Y("Elektriği çok iyi ilettiği için saçtaki elektriği aldığı için", "veri", "Element elektriği metaller kadar iyi iletmiyor (K1).", "K1"),
                 Y("Saç derisini kurutarak kepeği döktüğü için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; etki mantarlar üzerinde (K2).", "K2"),
                 ipucu="K2'yi oku.",
                 aciklama="Selenyum sülfür, kepeğe yol açan mantarlara karşı etkilidir. Selenyum vücut için de çok az miktarda gereklidir, ama fazlası zehirlidir. Ayrıca camlara renk vermek ve ışık algılayıcılar yapmak için kullanılır."),
      rakip="Te"),

    V("Br", 3, "sanayi", "Zor Alev Alan Plastik",
      "Bir televizyonun plastik kasası, içindeki elektronik parçalar ısındığında bile kolay kolay alev almayacak biçimde "
      "üretilmiş. Üretici, plastiğe bir halojenin bileşiklerini kattığını söylüyor. Görevin: bu halojeni bulmak.",
      [("kimyasal", "Elementin türü", "Element çok etkin bir ametal; metallerle tuz oluşturuyor."),
       ("fiziksel", "Saf hâli", "Bu element oda sıcaklığında koyu kırmızı-kahverengi bir sıvı; keskin ve rahatsız edici kokulu buharlar çıkarıyor.", "serbest")],
      kullanim=S("Bromlu bileşikler plastiklere neden katılır?",
                 "Isınınca alevdeki tepkimeleri yavaşlatarak plastiğin tutuşmasını geciktirirler",
                 Y("Plastiği kırmızıya boyadıkları için", "iliski", "Brom koyu kırmızı-kahverengi bir sıvıdır (K2) ama plastiğe katılan bileşiklerin görevi rengi değil, yangını geciktirmek.", "K2"),
                 Y("Plastiği daha iyi elektrik iletken yaptıkları için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K1"),
                 Y("Brom yanıcı bir yakıt olduğu için plastiği ısıttığı için", "kanitsiz", "Bromlu bileşikler yanmayı hızlandırmaz, geciktirir.", "K1"),
                 ipucu="Hikâyede üreticinin amacı ne?",
                 aciklama="Bromlu alev geciktiriciler ısınınca alevdeki zincirleme tepkimeleri yavaşlatır. Ancak bazıları doğada uzun süre kaldığı ve canlılarda biriktiği için birçok ülkede sınırlandırıldı; yerine daha güvenli maddeler aranıyor."),
      rakip="Cl"),

    V("Kr", 3, "tarih", "Işıkla Tanımlanan Metre",
      "Paris yakınlarında saklanan platin-iridyum bir çubuk, 1960'a kadar dünyanın 'resmî metresi'ydi. 1960'ta bilim insanları "
      "metreyi bir çubuk yerine bir soy gazın yaydığı turuncu-kırmızı ışığın dalga boyuyla tanımladı. Görevin: bu soy gazı bulmak.",
      [("kimyasal", "Gazın davranışı", "Gaz renksiz, kokusuz ve neredeyse hiç tepkimeye girmiyor."),
       ("tarih", "Yeni tanım", "1960–1983 arasında 1 metre, bu gazın bir izotopunun yaydığı turuncu-kırmızı ışığın dalga boyunun 1 650 763,73 katı olarak tanımlandı.")],
      kullanim=S("Metreyi bir metal çubuk yerine bir ışığın dalga boyuyla tanımlamak neden daha iyiydi?",
                 "Aynı izotopun atomları her yerde aynı dalga boyunda ışık yayar; tanım her laboratuvarda yeniden üretilebilir ve değişmez",
                 Y("Kripton çubuktan daha ucuz olduğu için", "kanitsiz", "Kanıtlar tanımın değişmezliğiyle ilgili; fiyattan söz etmiyor.", "K2"),
                 Y("Işık çubuktan daha ağır olduğu için", "iliski", "Işığın ağırlığı yoktur; önemli olan dalga boyunun her yerde aynı olması.", "K2"),
                 Y("Kripton tepkimeye girdiği için çubuğu aşındırdığı için", "veri", "Kripton neredeyse hiç tepkimeye girmez (K1).", "K1"),
                 ipucu="Bir çubuk tek bir yerde durur, hasar görebilir. Atomlar ise...",
                 aciklama="Bir metal çubuk tek bir yerde saklanır ve zamanla çok az da olsa değişebilir. Bir atomun yaydığı ışığın dalga boyu ise her yerde aynıdır. 1983'ten beri metre, ışığın boşlukta belirli bir sürede aldığı yolla tanımlanıyor."),
      rakip="Ar"),

    V("Sr", 3, "ev", "Karanlıkta Parlayan Yıldızlar",
      "Bir çocuğun odasının tavanına yapıştırılan plastik yıldızlar, ışık kapanınca saatlerce yeşil yeşil parlıyor. Ambalajda, "
      "parlayan maddenin eski oyuncaklardakinden çok daha uzun parladığı ve radyoaktif olmadığı yazıyor. Görevin: parlayan "
      "maddedeki metali bulmak.",
      [("kimyasal", "Elementin türü", "Element bir metal; bileşiklerinde +2 yüklü iyon oluşturuyor."),
       ("deney", "Uzun süren parıltı", "Parlayan madde bu metalin alüminatı. Gün ışığında birkaç dakika kalınca karanlıkta saatlerce parlıyor.")],
      kullanim=S("Stronsiyum alüminat neden karanlıkta parlayan ürünlerde kullanılır?",
                 "Işığı soğurup enerjisini saatlerce yavaş yavaş ışık olarak geri verir ve radyoaktif değildir",
                 Y("Radyoaktif olduğu için kendiliğinden parladığı için", "veri", "Madde radyoaktif değil; parlaması önceden soğurduğu ışıktan geliyor (hikâye, K2).", "K2"),
                 Y("Yanarak ışık verdiği için", "kanitsiz", "Kanıtlarda yanmadan söz edilmiyor; madde soğurduğu ışığı geri veriyor (K2).", "K2"),
                 Y("Elektrikle çalıştığı için", "kanitsiz", "Yıldızların pili ya da kablosu yok; ışığı gün ışığından alıyor (K2).", "K2"),
                 ipucu="K2: Maddenin parlaması için önce ne gerekiyor?",
                 aciklama="Stronsiyum alüminat ışığı soğurur ve enerjisini saatlerce yavaş yavaş geri verir; buna fosforesans denir. Acil çıkış işaretlerinde ve saat kadranlarında da kullanılır. Stronsiyumun başka bir bileşiği de havai fişeklere kırmızı renk verir."),
      rakip="Be"),

    V("Zr", 3, "enerji", "Yakıtın Görünmez Kılıfı",
      "Bir nükleer santralde uranyum yakıt tabletleri, kalem inceliğinde metal borulara doldurulup reaktöre yerleştiriliyor. "
      "Mühendis, boruların nötronlara 'saydam' gibi davranan bir metalin alaşımından yapıldığını söylüyor. Görevin: bu metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal gümüşi, sert ve korozyona dayanıklı."),
       ("kimyasal", "Nötronlara saydam", "Bu metal nötronları çok az yutuyor; ayrıca reaktördeki sıcak suya ve basınca dayanıyor.")],
      kullanim=S("Zirkonyum alaşımları yakıt çubuklarının kılıfında neden kullanılır?",
                 "Nötronları çok az yutar, böylece zincirleme tepkimeyi engellemez; sıcak suya ve korozyona da dayanır",
                 Y("Nötronları çok iyi yutup tepkimeyi durdurduğu için", "veri", "Metal nötronları çok az yutuyor (K2).", "K2"),
                 Y("Kolayca eriyip yakıtı soğuttuğu için", "kanitsiz", "Kılıfın erimesi istenmez; kanıtlar metalin dayanıklılığını vurguluyor (K2).", "K2"),
                 Y("Radyoaktif olduğu için yakıta enerji kattığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; enerji uranyumdan geliyor.", "K2"),
                 ipucu="K2'deki iki özelliği düşün.",
                 aciklama="Üretilen zirkonyumun %90'ından fazlası nükleer santrallerde kullanılır. Zirkonyum nötronları çok az yuttuğu için tepkimeyi engellemez; ince oksit tabakası da onu korozyondan korur."),
      rakip="Ti"),

    V("Nb", 3, "saglik", "MR Mıknatısının Telleri",
      "Bir MR cihazının dev mıknatısı, kilometrelerce uzunlukta ince bir telden sarılmış bir bobin içeriyor. Teller aşırı "
      "soğutulunca elektriğe hiç direnç göstermiyor. Telin alaşımı titanyum ile başka bir geçiş metalinden oluşuyor. "
      "Görevin: bu metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal gri, sert ve elektriği iletiyor."),
       ("iletkenlik", "Dirençsiz tel", "Bu metalin titanyumla alaşımı, aşırı soğutulunca süper iletken oluyor: elektrik akımı hiç enerji kaybetmeden dolaşıyor.")],
      kullanim=S("Niyobyum-titanyum telleri MR mıknatıslarında neden kullanılır?",
                 "Çok soğukken süper iletken olurlar; dirençsiz akan büyük akım çok güçlü bir manyetik alan oluşturur",
                 Y("Bu teller oda sıcaklığında süper iletken olduğu için", "veri", "Teller ancak aşırı soğutulunca süper iletken oluyor (K2).", "K2"),
                 Y("Niyobyum mıknatısa güçlü çekildiği için", "kanitsiz", "Mıknatıs alanını tellerden geçen akım oluşturur; niyobyumun mıknatısa çekildiğine dair bir kanıt yok.", "K2"),
                 Y("Niyobyum elektriği hiç iletmediği için", "veri", "Metal elektriği iletiyor (K1).", "K1"),
                 ipucu="K2'deki özellik nasıl güçlü bir mıknatıs yapar?",
                 aciklama="Süper iletken tellerde akım hiç kaybolmadan dolaşabilir; bu sayede çok güçlü manyetik alanlar elde edilir. Niyobyum-titanyum telleri MR cihazlarında ve parçacık hızlandırıcılarında kullanılır."),
      rakip="V"),

    V("Mo", 3, "sanat", "Yarış Bisikletinin Kadrosu",
      "Bir bisiklet tamircisi, eski bir yarış bisikletinin kadrosunun çok ince borulardan yapıldığı hâlde yıllardır sağlam "
      "kaldığını gösterdi. Borunun çeliğine krom ve başka bir geçiş metali birlikte katılmış. Görevin: bu ikinci metali bulmak.",
      [("fiziksel", "Metalin özellikleri", "Metal sert, gümüşi gri ve erime noktası yüksek."),
       ("alasim", "Güçlü çelik", "Çeliğe bu metalden az miktarda katılınca çeliğin sağlamlığı ve aşınmaya dayanıklılığı artıyor; ince ama güçlü borular yapılabiliyor.")],
      kullanim=S("Molibden çeliğe neden katılır?",
                 "Çeliğin sağlamlığını, sertliğini ve aşınmaya dayanıklılığını artırır",
                 Y("Çeliği hafifletmek için", "kanitsiz", "Kanıtlar molibdenin çeliği sağlamlaştırdığını söylüyor (K2); hafiflikten söz etmiyor.", "K2"),
                 Y("Çeliği mıknatıstan korumak için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K2"),
                 Y("Çeliğin erime noktasını düşürüp kolay şekil vermek için", "kanitsiz", "Molibdenin erime noktası yüksektir (K1); kanıtlar çeliğin dayanıklılığının arttığını söylüyor.", "K2"),
                 ipucu="K2'yi oku.",
                 aciklama="Molibdenli çelikler motor parçalarında, matkap uçlarında ve bisiklet kadrolarında kullanılır. Molibden disülfür ise kaygan bir yağlayıcıdır. Molibdenin adı, cevherinin uzun süre kurşun cevheriyle karıştırılmasından gelir."),
      rakip="Cr"),

    V("Rh", 3, "sanat", "Kararmayan Gümüş Kolye",
      "Bir kuyumcu, gümüş bir kolyeyi kararmaması için bir değerli metalin çözeltisine daldırıp elektrik verdi. Kolye "
      "çok ince bir metal tabakasıyla kaplandı ve ayna gibi parlamaya başladı. Görevin: kaplama metalini bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal parlak ve gümüşi beyaz."),
       ("kimyasal", "Kararmayan kaplama", "Kaplama metali havayla ve terle neredeyse hiç tepkimeye girmiyor; çok sert ve çizilmeye dayanıklı. Arabaların egzozundaki katalitik konvertörlerde de kullanılıyor.")],
      kullanim=S("Rodyum takı kaplamada neden kullanılır?",
                 "Çok parlak, sert ve korozyona dayanıklıdır; gümüşün kararmasını önler",
                 Y("Rodyum gümüşten daha ucuz olduğu için", "kanitsiz", "Kanıtlarda fiyattan söz edilmiyor; rodyum aslında çok pahalı bir metaldir.", "K2"),
                 Y("Rodyum terle tepkimeye girip takıyı koruduğu için", "veri", "Rodyum terle neredeyse hiç tepkimeye girmiyor (K2).", "K2"),
                 Y("Rodyum takıyı ağırlaştırdığı için", "iliski", "Kaplama çok ince; ağırlığın bir önemi yok.", "K2"),
                 ipucu="K2'deki özelliklere bak.",
                 aciklama="Rodyum en pahalı değerli metallerden biridir. Çok parlak, sert ve kararmaz olduğu için gümüş ve beyaz altın takılar ince bir rodyum tabakasıyla kaplanır. Üretilen rodyumun büyük bölümü ise arabaların katalitik konvertörlerinde kullanılır."),
      rakip="Co"),

    V("Ag", 3, "tarih", "Karanlık Odadaki Görüntü",
      "Bir fotoğraf kulübü, dijital fotoğraf makinelerinden önceki dönemde filmlerin nasıl çalıştığını inceliyor. Filmin "
      "yüzeyinde ışığa duyarlı bir metal tuzu bulunuyor; ışık alan yerler banyo edilince kararıyor. Görevin: bu tuzdaki metali bulmak.",
      [("iletkenlik", "İletkenlik", "Metal elektriği ve ısıyı çok iyi iletiyor."),
       ("kimyasal", "Işığa duyarlı tuz", "Filmdeki tuz bu metalin bromürü. Işık alan tuz tanecikleri banyo sırasında minik siyah metal taneciklerine dönüşüyor.")],
      kullanim=S("Gümüş bromür fotoğraf filmlerinde neden kullanıldı?",
                 "Işık alınca değişip banyoda minik gümüş tanelerine dönüşür; ışık alan yerler kararır ve görüntü kaydedilir",
                 Y("Gümüş bromür karanlıkta parladığı için", "kanitsiz", "Kanıtlarda böyle bir özellik yok; tuz ışık alınca değişiyor (K2).", "K2"),
                 Y("Gümüş elektriği iyi ilettiği için filme elektrik verdiği için", "iliski", "İletkenlik (K1) filmin çalışmasını açıklamaz; önemli olan tuzun ışığa duyarlılığı.", "K1"),
                 Y("Gümüş bromür ışıktan hiç etkilenmediği için", "veri", "Tuz ışığa duyarlı (K2).", "K2"),
                 ipucu="K2'deki değişimi düşün.",
                 aciklama="Fotoğraf filminde ışık alan gümüş bromür tanecikleri banyoda siyah gümüş metaline dönüşür. Böylece 'negatif' bir görüntü oluşur. Gümüş ayrıca elektriği en iyi ileten metaldir."),
      rakip="Cu"),

    V("Sn", 3, "tarih", "Ufalanan Org Boruları",
      "Kuzey Avrupa'daki çok soğuk bir kilisede, yüzyıllık bir orgun bazı metal boruları ufalanıp gri bir toza dönüşmüş. "
      "Halk bunu eskiden 'metal hastalığı' sanıyordu. Görevin: boruların metalini bulmak.",
      [("fiziksel", "Metalin görünüşü", "Element gümüşi grimsi ve parlak bir katı."),
       ("fiziksel", "Soğukta değişen yapı", "Bu metal 13 °C'nin altında uzun süre kalınca yapısı değişebiliyor: parlak hâlinden kırılgan, gri bir toza dönüşüyor.")],
      kullanim=S("Kalay vebası nedir?",
                 "Kalayın 13 °C'nin altında uzun süre kalınca kırılgan, gri bir toza dönüşmesidir",
                 Y("Kalayı yiyen bir mikrobun yol açtığı hastalık", "kanitsiz", "Değişime mikrop değil, düşük sıcaklık yol açar (K2).", "K2"),
                 Y("Kalayın sıcakta erimesi", "veri", "Değişim sıcakta değil, 13 °C'nin altında oluyor (K2).", "K2"),
                 Y("Kalayın havadaki oksijenle paslanması", "iliski", "Kalay vebası bir paslanma değil; aynı elementin yapısının değişmesidir (K2).", "K2"),
                 ipucu="K2'yi oku.",
                 aciklama="Kalay vebası, beyaz kalayın soğukta gri kalaya dönüşmesidir; bu bir paslanma değil, aynı elementin farklı bir yapıya geçmesidir. Bu yüzden kalay alaşımlarına başka metaller katılır."),
      rakip="Ge"),

    V("Sb", 3, "sanat", "Firavunun Göz Boyası",
      "Bir müzedeki eski Mısır sürmedanlığında siyah bir toz kalıntısı bulundu. MÖ 16. yüzyıldan kalma bir papirüste, "
      "bu tozun bir mineralden elde edilip göz boyası olarak kullanıldığı yazıyor. Görevin: mineraldeki elementi (kükürt dışındaki) bulmak.",
      [("fiziksel", "Elementin görünüşü", "Element bir yarı metal; kırılgan ve gümüşi gri."),
       ("kimyasal", "Siyah mineral", "Toz, bu elementin siyah sülfür minerali (stibnit). Mineral ince toz hâline getirilip yağla karıştırılınca göz çevresine sürülebiliyor.")],
      kullanim=S("Antimon bugün akülerde neden kurşuna katılır?",
                 "Kurşunu sertleştirir ve sağlamlaştırır",
                 Y("Kurşunu yumuşatıp kolay eritmek için", "kanitsiz", "Antimon kurşunu yumuşatmaz, sertleştirir.", "K1"),
                 Y("Aküyü siyaha boyamak için", "iliski", "Antimonun siyah minerali göz boyasında kullanılıyordu (K2); akülerdeki görevi kurşunu sertleştirmek.", "K2"),
                 Y("Akünün elektriğini artıran bir yakıt olduğu için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K1"),
                 ipucu="Alaşımlar bir metale hangi özellikleri kazandırır?",
                 aciklama="Antimon, kurşunla alaşım yapınca kurşunu sertleştirir. Bu alaşım akülerde, geçmişte de matbaa harflerinde kullanıldı. Antimon bileşikleri ayrıca alev geciktiricilerde kullanılır."),
      rakip="As"),

    V("I", 3, "saglik", "Yaraya Sürülen Kahverengi Çözelti",
      "Bir okul revirinde hemşire, dizi sıyrılan bir öğrencinin yarasına kahverengi bir çözelti sürdü. Çözeltinin şişesinde "
      "'antiseptik' yazıyor. Görevin: çözeltideki halojeni bulmak.",
      [("kimyasal", "Elementin türü", "Element çok etkin bir ametal; metallerle tuz oluşturuyor."),
       ("fiziksel", "Mor buhar", "Elementin katı hâli koyu gri parlak kristallerden oluşuyor; ısıtılınca sıvılaşmadan doğrudan mor bir buhara dönüşüyor.", "serbest")],
      kullanim=S("İyot çözeltisi yaralarda neden kullanılır?",
                 "İyot mikropları öldürür; yaranın enfeksiyon kapmasını önler",
                 Y("İyot yarayı kahverengiye boyayarak gizlediği için", "iliski", "Renk bir yan etkidir; çözeltinin görevi mikropları öldürmek.", "K1"),
                 Y("İyot kanı hemen pıhtılaştırdığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; şişede 'antiseptik' yazıyor.", "K1"),
                 Y("İyot ısıtılınca mor buhar oluşturduğu için", "iliski", "Süblimleşme iyotun bir özelliğidir (K2) ama yarada mikrop öldürme görevini açıklamaz.", "K2"),
                 ipucu="'Antiseptik' ne demek?",
                 aciklama="İyot ve bileşikleri güçlü bir mikrop öldürücüdür; tentürdiyot ve povidon-iyot gibi antiseptikler bu yüzden yaralarda kullanılır. İyot ayrıca tiroit bezinin hormonları için gereklidir."),
      rakip="Br"),

    V("Xe", 3, "uzay", "Uzay Aracının Mavi Motoru",
      "Asteroit kuşağına giden bir uzay aracının motoru, arkasından soluk mavi bir ışıltı saçıyor. Motor, bir soy gazın "
      "atomlarını elektrikle iyonlaştırıp çok yüksek hızla dışarı fırlatarak aracı itiyor. Görevin: bu soy gazı bulmak.",
      [("kimyasal", "Gazın davranışı", "Gaz renksiz, kokusuz ve neredeyse hiç tepkimeye girmiyor."),
       ("fiziksel", "İyon motoru", "Motorun itmesi bir kâğıt yaprağının ağırlığı kadar küçük; ama aylarca kesintisiz çalışarak aracı çok yüksek hızlara çıkarıyor. Motor bu gazın ağır atomlarını kullanıyor.")],
      kullanim=S("İyon motorlarında neden ksenon kullanılır?",
                 "Ağır atomları kolayca iyonlaşır, tepkimeye girmez ve sıkıştırılarak depolanabilir",
                 Y("Ksenon yanıcı olduğu için roket gibi yandığı için", "veri", "Ksenon neredeyse hiç tepkimeye girmez (K1); motor yanmayla değil, iyonlarla iter.", "K1"),
                 Y("Ksenon çok hafif olduğu için", "veri", "Motor bu gazın ağır atomlarını kullanıyor (K2).", "K2"),
                 Y("Ksenon mavi renkli olduğu için uzayda görünmek için", "iliski", "Mavi ışıltı motorun çalışmasının bir sonucudur; ksenonun seçilme nedeni değil.", "K2"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="İyon motorları ksenon atomlarını iyonlaştırıp elektrik alanıyla hızlandırır. Ksenon ağır, tepkimeye girmeyen ve kolay iyonlaşan bir gazdır. Uydular ve derin uzay araçları bu motorlarla çok az yakıtla uzun yolculuklar yapar."),
      rakip="Kr"),

    V("Cs", 3, "teknoloji", "Saniyenin Tanımı",
      "Bir ölçüm laboratuvarındaki atom saati, ülkenin resmî saatini belirliyor. Saatin kalbinde bir alkali metalin atomları "
      "var; saniyenin kendisi de bu atomların bir ışımasıyla tanımlanıyor. Görevin: bu alkali metali bulmak.",
      [("fiziksel", "Metalin özellikleri", "Metal çok yumuşak ve suyla şiddetli tepkimeye giriyor."),
       ("tarih", "Saniyenin tanımı", "1967'den beri bir saniye, bu metalin atomlarının belirli bir ışımasının 9 192 631 770 titreşimi olarak tanımlanıyor.")],
      kullanim=S("Sezyum atom saatleri neden saniyenin tanımında kullanılır?",
                 "Sezyum atomlarının bu ışıma frekansı değişmez ve her yerde aynıdır; çok hassas ve yeniden üretilebilir bir zaman ölçüsü verir",
                 Y("Sezyum suyla tepkimeye girdiği için saati çalıştırdığı için", "iliski", "Saat suyla tepkimeyle değil, atomların ışımasıyla çalışır (K2).", "K2"),
                 Y("Sezyum ucuz ve bol olduğu için", "kanitsiz", "Kanıtlar sezyumun kararlı ışıma frekansını vurguluyor (K2).", "K2"),
                 Y("Sezyumun ışıması zamanla yavaşladığı için", "veri", "Işıma frekansı değişmez; saniye bu yüzden onunla tanımlanıyor (K2).", "K2"),
                 ipucu="K2'deki tanım neye dayanıyor?",
                 aciklama="Sezyum saatleri çok hassastır; bazıları on beş milyon yılda bir saniye şaşar. İnternet, cep telefonu ağları ve GPS bu saatlere dayanır."),
      ozellik="erime", rakip="Rb"),

    V("Ba", 3, "sanat", "Gökyüzündeki Yeşil Işık",
      "Bir bayram kutlamasında gökyüzünde parlak yeşil ışıklar saçan fişeklerden biri patlamadan yere düştü. İçindeki tuz "
      "incelendi. Görevin: yeşil rengi veren metali bulmak.",
      [("kimyasal", "Elementin türü", "Element bir metal; bileşiklerinde +2 yüklü iyon oluşturuyor."),
       ("deney", "Alev testi", "Fişekteki tuz bu metalin nitratı. Alev testinde tuz alevi açık yeşile boyuyor.", "serbest")],
      kullanim=S("Baryum nitrat havai fişeklerde neden kullanılır?",
                 "Yanarken baryum iyonları alevi yeşile boyar",
                 Y("Baryum fişeği ağırlaştırıp yükseğe çıkardığı için", "iliski", "Fişeğin rengini baryum verir; ağırlık fişeği yükseltmez.", "K2"),
                 Y("Baryum kırmızı ışık verdiği için", "veri", "Tuz alevi yeşile boyuyor (K2).", "K2"),
                 Y("Baryum patlamayı önlediği için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K2"),
                 ipucu="K2'deki alev testine bak.",
                 aciklama="Havai fişeklerin renkleri metal tuzlarından gelir: baryum yeşil, stronsiyum kırmızı, bakır mavi, sodyum sarı renk verir. Baryum sülfat ise mide filmlerinde kullanılır."),
      rakip="Sr"),

    V("Hf", 3, "enerji", "Denizaltının Kontrol Çubukları",
      "Nükleer bir denizaltının reaktöründe tepkimenin hızı, çekirdeğe sokulup çıkarılan çubuklarla ayarlanıyor. Çubuklar, "
      "kimyasal olarak zirkonyuma çok benzeyen ama nötronları çok iyi yutan bir metalden yapılıyor. Görevin: bu metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal gümüşi, sert ve korozyona dayanıklı."),
       ("kimyasal", "Nötron yutan çubuk", "Bu metal nötronları çok iyi yutuyor. Erime noktası da çok yüksek; plazma kaynak makinelerinin uçlarında kullanılıyor.")],
      kullanim=S("Hafniyum kontrol çubuklarında neden kullanılır?",
                 "Nötronları çok iyi yutar; çubuklar reaktöre sokulunca zincirleme tepkime yavaşlar",
                 Y("Nötronları hiç yutmadığı için tepkimeyi hızlandırdığı için", "veri", "Metal nötronları çok iyi yutuyor (K2).", "K2"),
                 Y("Kolayca eridiği için reaktörü soğuttuğu için", "veri", "Metalin erime noktası çok yüksek (K2).", "K2"),
                 Y("Zirkonyuma benzediği için yakıt olarak yandığı için", "iliski", "Zirkonyuma benzemesi yakıt olduğunu göstermez; hafniyumun görevi nötron yutmak.", "K2"),
                 ipucu="K2'deki özellik reaktörde ne işe yarar?",
                 aciklama="Hafniyum ve zirkonyum kimyasal olarak neredeyse ikizdir; ama zirkonyum nötronları çok az yutar, hafniyum ise çok iyi yutar. Bu yüzden zirkonyum yakıt kılıflarında, hafniyum kontrol çubuklarında kullanılır."),
      rakip="Zr"),

    V("W", 3, "sanat", "İnce Ama Ağır Dart Oku",
      "Bir dart turnuvasında oyuncuların okları çok ince olduğu hâlde ellerinde ağır duruyor. Oyuncular, ince okların hedefte "
      "birbirine daha yakın saplanabildiğini söylüyor. Okların gövdesi yüksek oranda bir metal içeriyor. Görevin: bu metali bulmak.",
      [("fiziksel", "Metalin özellikleri", "Metal sert, gri ve erime noktası çok yüksek."),
       ("alasim", "Okun gövdesi", "Profesyonel dart oklarının gövdesi %80–97 oranında bu metalden yapılıyor; ok ince olduğu hâlde ağır.")],
      kullanim=S("Tungsten dart oklarında neden kullanılır?",
                 "Çok yoğun olduğu için ok ince kalırken yeterince ağır olur",
                 Y("Tungsten çok hafif olduğu için ok daha uzağa gittiği için", "veri", "Ok ince olduğu hâlde ağır (K2); tungsten çok yoğun bir metaldir ({olcum}).", "{olcum}"),
                 Y("Tungstenin erime noktası yüksek olduğu için ok ısınmadığı için", "iliski", "Erime noktası (K1) dart oyununda önemli değil; önemli olan yoğunluk.", "K1"),
                 Y("Tungsten yumuşak olduğu için hedefe kolay saplandığı için", "veri", "Tungsten sert bir metaldir (K1).", "K1"),
                 ipucu="İnce ama ağır bir cisim için malzemenin hangi özelliği önemli?",
                 aciklama="Tungstenin yoğunluğu (19,3 g/cm³) kurşununkinin neredeyse iki katıdır ve altınınkiyle aynıdır. Bu yüzden tungsten oklar ince olduğu hâlde ağırdır. Tungstenin erime noktası ise bütün metallerin en yükseğidir."),
      rakip="Mo"),

    V("Re", 3, "sanayi", "Jet Motorunun Sıcak Kanadı",
      "Bir jet motorunun en sıcak bölümündeki türbin kanatları, metallerin çoğunu eritecek sıcaklıktaki gazların içinde dakikada "
      "binlerce kez dönüyor. Kanatlar nikel alaşımından yapılmış ve içine birkaç yüzde nadir bir metal katılmış. Görevin: bu "
      "nadir metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal sert ve gümüşi gri."),
       ("alasim", "Sıcağa dayanıklı kanat", "Bu metal katılan tek kristal türbin kanatları aşırı sıcakta bile şekil değiştirmiyor. Metalin erime noktası 3000 °C'nin üzerinde.", "serbest")],
      kullanim=S("Renyum türbin kanatlarında neden kullanılır?",
                 "Çok yüksek erime noktası ve sağlamlığıyla kanatların aşırı sıcakta şekil değiştirmesini önler",
                 Y("Renyum kanatları hafiflettiği için", "veri", "Ölçülen yoğunluk ({olcum}) çok yüksek; renyum ağır bir metaldir.", "{olcum}"),
                 Y("Renyum düşük sıcaklıkta eridiği için kanatları soğuttuğu için", "veri", "Renyumun erime noktası 3000 °C'nin üzerinde (K2).", "K2"),
                 Y("Renyum yanarak motora ek itme verdiği için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; renyum kanadın dayanıklılığını artırıyor (K2).", "K2"),
                 ipucu="K2'deki özelliğe bak.",
                 aciklama="Renyum, erime noktası en yüksek elementlerden biridir. Nikel alaşımlarına katılınca türbin kanatlarının yüksek sıcaklıkta şekil değiştirmesini önler. Renyum, kararlı izotopu olan elementler arasında en son keşfedilenidir (1925)."),
      rakip="Mn"),

    V("Os", 3, "tarih", "Hiç Körelmeyen Kalem Ucu",
      "Bir koleksiyoncunun 1920'lerden kalma dolma kaleminin ucu, yüz yıla yakın kullanıldığı hâlde hiç aşınmamış. Ucun "
      "tam ortasındaki minik top, bilinen en yoğun elementin bir alaşımından yapılmış. Görevin: bu elementi bulmak.",
      [("fiziksel", "Metalin özellikleri", "Metal çok sert ve parlak."),
       ("alasim", "Kalem ucu", "Kalem ucundaki minik top bu metalin iridyumla alaşımından yapılmış; uç yıllarca kâğıda sürtündüğü hâlde aşınmıyor.")],
      kullanim=S("Osmiyum alaşımları dolma kalem uçlarında neden kullanılır?",
                 "Çok sert ve aşınmaya dayanıklıdır; uç yıllarca kâğıda sürtünse de körelmez",
                 Y("Osmiyum yumuşak olduğu için kâğıda kolay kaydığı için", "veri", "Metal çok sert (K1).", "K1"),
                 Y("Osmiyum mürekkebin rengini değiştirdiği için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K2"),
                 Y("Osmiyum çok hafif olduğu için kalemi hafiflettiği için", "veri", "Osmiyum bilinen en yoğun elementtir ({olcum}).", "{olcum}"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Osmiyum bilinen en yoğun elementtir (22,59 g/cm³). Osmiyum-iridyum alaşımları çok sert olduğu için kalem uçlarında, pusula yataklarında ve elektrik kontaklarında kullanılır."),
      rakip="Ru"),

    V("Pt", 3, "cevre", "Egzozdaki Değerli Metal",
      "Bir oto tamircisi, eski bir arabanın egzoz borusundan çıkardığı katalitik konvertörü kesip içindeki seramik peteği "
      "gösterdi. Peteğin yüzeyi, değerli bir metalin çok ince bir tabakasıyla kaplıydı. Hurdacılar bu parçaları içindeki "
      "metal yüzünden çok değerli buluyor. Görevin: bu metali bulmak.",
      [("fiziksel", "Metalin görünüşü", "Metal gümüşi beyaz, parlak ve paslanmıyor."),
       ("kimyasal", "Zararsızlaşan gazlar", "Egzoz gazları bu metalle kaplı yüzeyden geçerken karbon monoksit gibi zehirli gazlar daha zararsız gazlara dönüşüyor; metalin kendisi tükenmiyor.")],
      kullanim=S("Platin katalitik konvertörlerde neden kullanılır?",
                 "Katalizördür: zehirli gazların daha zararsız gazlara dönüşmesini hızlandırır ve kendisi tükenmez",
                 Y("Platin zehirli gazları emip içinde sakladığı için", "veri", "Gazlar platinin içinde saklanmıyor, başka gazlara dönüşüyor (K2).", "K2"),
                 Y("Platin egzozu ısıtıp gazları yaktığı için", "kanitsiz", "Kanıtlar platinin bir katalizör gibi davrandığını söylüyor (K2).", "K2"),
                 Y("Platin her tepkimede tükendiği için sık değiştirilmesi gerektiği için", "veri", "Metal tükenmiyor (K2).", "K2"),
                 ipucu="K2'nin son cümlesine bak: tepkimeyi hızlandırıp kendisi tükenmeyen maddeye ne denir?",
                 aciklama="Katalizör, bir tepkimeyi hızlandıran ama kendisi tükenmeyen maddedir. Katalitik konvertörlerde platin, paladyum ve rodyum zehirli egzoz gazlarını karbondioksit, su buharı ve azota dönüştürür. Platin talebinin yaklaşık yarısı bu iş içindir."),
      rakip="Pd"),

    V("Pb", 3, "tarih", "Pompeii'nin Su Boruları",
      "Pompeii kazılarında bulunan eski Roma su boruları gri, ağır ve yumuşak bir metalden yapılmış. Arkeologlar, Romalıların "
      "bu metali kolayca bükülüp kaynatılabildiği için sevdiğini söylüyor. Görevin: boruların metalini bulmak.",
      [("fiziksel", "Metalin özellikleri", "Metal yumuşak, gri ve kolayca şekil veriliyor."),
       ("tarih", "Bir kelimenin hikâyesi", "İngilizcedeki 'plumber' (tesisatçı) kelimesi, bu metalin Latince adından geliyor.")],
      kullanim=S("Romalılar su borularında kurşunu neden kullandı, bugün ise neden kullanılmıyor?",
                 "Kurşun yumuşaktır, kolayca şekil alır ve paslanmaz; ama zehirli olduğu için bugün içme suyu borularında kullanılmaz",
                 Y("Kurşun çok hafif olduğu için; bugün daha ağır borular tercih edildiği için", "veri", "Ölçülen yoğunluk ({olcum}) çok yüksek; kurşun ağır bir metaldir.", "{olcum}"),
                 Y("Kurşun çok sert olduğu için; bugün daha yumuşak borular gerektiği için", "veri", "Kurşun yumuşak bir metaldir (K1).", "K1"),
                 Y("Kurşun suyu tatlandırdığı için; bugün tat istenmediği için", "kanitsiz", "Kurşunun bırakılma nedeni zehirliliğidir; tatla ilgili bir kanıt yok.", "K1"),
                 ipucu="K1'deki özellikler bir avantaj, ama kurşunun sağlık açısından bir sorunu var.",
                 aciklama="Kurşun yumuşak ve kolay işlenen bir metal olduğu için Romalılar onu su borularında kullandı. Ancak kurşun zehirlidir; özellikle çocukların gelişimine zarar verir. Bu yüzden kurşunlu borular, boyalar ve benzin katkıları yasaklandı."),
      rakip="Sn"),

    V("Bi", 3, "saglik", "Siyahlaşan Dil",
      "Mide rahatsızlığı için pembe bir şurup içen bir öğrenci, ertesi sabah aynada dilinin siyaha döndüğünü görüp korktu. "
      "Eczacı bunun şuruptaki bir metal bileşiğinden kaynaklanan zararsız ve geçici bir etki olduğunu söyledi. Görevin: bu metali bulmak.",
      [("fiziksel", "Elementin görünüşü", "Element kırılgan, gümüşi bir katı."),
       ("kimyasal", "Siyah renk", "Şuruptaki bileşiğin metali, ağızdaki kükürtlü maddelerle birleşince siyah renkli bir sülfür oluşturuyor.")],
      kullanim=S("Bizmut şurubu içen birinin dili neden kararır?",
                 "Bizmut, ağızdaki kükürtlü maddelerle siyah bizmut sülfür oluşturur; bu zararsızdır ve geçicidir",
                 Y("Şurup dili yaktığı için", "kanitsiz", "Eczacı etkinin zararsız olduğunu söyledi; kanıtlar bir sülfür oluştuğunu gösteriyor (K2).", "K2"),
                 Y("Bizmut radyoaktif olduğu için dili kararttığı için", "kanitsiz", "Kararma bir kimyasal tepkimeden kaynaklanıyor (K2).", "K2"),
                 Y("Şurubun pembe boyası dili kararttığı için", "iliski", "Pembe boya siyah renk oluşturmaz; siyah renk bizmut sülfürden geliyor (K2).", "K2"),
                 ipucu="K2'deki tepkimeyi düşün.",
                 aciklama="Bizmut bileşikleri hazımsızlık ilaçlarında kullanılır. Bizmut, ağızdaki ve bağırsaktaki kükürtlü maddelerle siyah bizmut sülfür oluşturur; bu yüzden dil ya da dışkı geçici olarak kararabilir. Bizmut, kurşunun yerine kullanılabilen, zehirliliği çok düşük ağır bir metaldir."),
      rakip="Sb"),
]
