# -*- coding: utf-8 -*-
"""Seviye 4 (Bilimsel Savunma) — yeni vakalar, birinci bölüm.
Görevler: gözlem, yazılı kimlik (seçeneksiz), özellik-kullanım, kanıt seçimi, savunma."""
from sablon import S, V, Y

VAKALAR = [
    V("H", 4, "enerji", "Dibe Batan Buz",
      "Bir fizik öğretmeni sınıfa iki buz küpü getirdi. İkisini de bir bardak suya attı: biri yüzdü, öteki dibe battı. "
      "Batan buz 'ağır su'dan yapılmıştı. Ağır su, nükleer santrallerde nötronları yavaşlatmak için kullanılıyor. Görevin: "
      "ağır suyu 'ağır' yapan atomların hangi element olduğunu bulmak ve savunmak.",
      [("deney", "Dibe batan buz", "Ağır sudan yapılmış buz küpü, sıradan suya atılınca yüzmek yerine dibe battı."),
       ("fiziksel", "Ağır su", "Ağır su sıradan sudan yaklaşık %11 daha yoğun. Molekülündeki oksijen aynı; fark diğer elementin atomlarında.")],
      gozlem=S("Ağır su buzunun sıradan suda dibe batması (K1) neyi gösterir?",
               "Ağır su buzunun yoğunluğu sıradan suyun yoğunluğundan büyük.",
               Y("Ağır su buzu daha soğuk olduğu için batıyor.", "iliski", "Bir cismin batıp batmaması sıcaklığından değil, yoğunluğundan bağlıdır.", "K1"),
               Y("Ağır su buzu erimiş olduğu için batıyor.", "veri", "Batan şey bir buz küpü; erimiş değil (K1).", "K1"),
               ipucu="Bir cisim hangi durumda bir sıvıda batar?",
               aciklama="Bir katı, yoğunluğu sıvınınkinden büyükse batar. Sıradan buz sudan hafiftir; ağır su buzu ise sıradan sudan ağırdır."),
      kullanim=S("Ağır su neden sıradan sudan daha ağırdır?",
                 "Molekülündeki hidrojen atomlarının çekirdeğinde fazladan bir nötron bulunur; bu yüzden molekül daha ağırdır",
                 Y("Ağır suda daha fazla oksijen atomu bulunduğu için", "veri", "Molekülündeki oksijen aynı (K2); fark diğer elementin atomlarında.", "K2"),
                 Y("Ağır su radyoaktif olduğu için", "kanitsiz", "Kanıtlarda radyoaktiflikten söz edilmiyor; döteryum kararlı bir izotoptur.", "K2"),
                 Y("Ağır suyun içinde tuz çözünmüş olduğu için", "kanitsiz", "Kanıtlarda tuzdan söz edilmiyor; fark atomların çekirdeğinde ({yapi}).", "{yapi}"),
                 ipucu="Kütle analizine ({yapi}) bak: bu atomların çekirdeğinde ne var?",
                 aciklama="Ağır sudaki hidrojen atomları döteryumdur: çekirdeklerinde bir proton ve bir nötron vardır. Bu yüzden ağır su molekülü daha ağırdır. Ağır su, bazı nükleer reaktörlerde nötronları yavaşlatıcı olarak kullanılır."),
      yapi="izotop", izotop=2, olcum=False,
      gerekce="Ağır sudaki hidrojen atomlarının çekirdeğinde fazladan bir nötron vardır; bu yüzden molekülü ve buzu daha ağırdır",
      karsi_kanit="Helyumun da hafif bir izotopu var ama helyum atomlarında 2 proton bulunur; bu atomlarda ise atom numarası 2 − 1 = 1."),

    V("Li", 4, "saglik", "On Yıllık Kalp Pili",
      "Bir kalp hastasına takılan kalp pili, bataryası değiştirilmeden yaklaşık on yıl çalışacak. Doktor, pilin içindeki metalin "
      "bilinen en hafif metal olduğunu ve iyotla birlikte tepkimeye girerek akım ürettiğini söylüyor. Görevin: bu metali "
      "bulmak ve neden seçildiğini savunmak.",
      [("tarih", "Uzun ömür", "Kalp pilinin bataryası değiştirilmeden yaklaşık on yıl çalışıyor; böylece hasta daha az ameliyat oluyor."),
       ("fiziksel", "En hafif metal", "Pildeki metal bilinen en hafif metal; iyotla birlikte tepkimeye girerek akım üretiyor.", "serbest")],
      gozlem=S("Bataryanın on yıl dayanması (K1) hasta için neden önemlidir?",
               "Batarya değişimi bir ameliyat gerektirir; uzun ömürlü batarya daha az ameliyat demektir.",
               Y("Uzun ömürlü batarya kalbi daha hızlı attırır.", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; batarya yalnızca pilin çalışmasını sağlar.", "K1"),
               Y("Batarya on yılda bir şarj edilir.", "kanitsiz", "Kanıtlar bataryanın değiştirildiğini söylüyor (K1); şarj edildiğine dair bir bilgi yok.", "K1"),
               ipucu="Bataryayı değiştirmek için ne yapmak gerekir?",
               aciklama="Kalp pili deri altına yerleştirilir; bataryası bitince pil küçük bir ameliyatla değiştirilir. Uzun ömürlü pil hastanın daha az ameliyat olmasını sağlar."),
      kullanim=S("Kalp pillerinde neden lityum pilleri kullanılır?",
                 "Lityum çok hafiftir ve kütlesine göre çok enerji depolar; pil küçük kalır ve yıllarca dayanır",
                 Y("Lityum çok ağır olduğu için pili yerinde tuttuğu için", "veri", "Lityum bilinen en hafif metal (K2).", "K2"),
                 Y("Lityum hiç tepkimeye girmediği için", "veri", "Pil, lityumun iyotla tepkimesiyle akım üretiyor (K2).", "K2"),
                 Y("Lityum radyoaktif olduğu için kendiliğinden enerji verdiği için", "kanitsiz", "Lityum radyoaktif değildir; enerji kimyasal tepkimeden gelir (K2).", "K2"),
                 ipucu="K1 ve K2'deki özellikleri birleştir.",
                 aciklama="Lityum, kütlesine göre en çok enerji depolayan pil metallerinden biridir. Lityum-iyot pilleri 1970'lerden beri kalp pillerinde kullanılır ve yaklaşık on yıl dayanır."),
      rakip="K"),

    V("B", 4, "adli", "Mermi Durduran Seramik",
      "Polislerin giydiği çelik yelek içindeki plakalar, şaşırtıcı biçimde metalden değil, bir seramikten yapılmış. Plakalar "
      "hem çok sert hem de hafif. Seramik, karbon ile başka bir elementten oluşuyor. Görevin: bu elementi bulmak ve neden "
      "kullanıldığını savunmak.",
      [("fiziksel", "Aşırı sertlik", "Plakalardaki seramik, elmas kadar olmasa da bilinen en sert malzemelerden biri; mermiyi parçalayarak durduruyor."),
       ("kimyasal", "Seramiğin elementi", "Seramikteki element bir yarı metal; dünyadaki rezervlerinin büyük bölümü Türkiye'de bulunuyor.")],
      gozlem=S("Seramiğin çok sert olması (K1) mermiyi durdurmakta nasıl işe yarar?",
               "Sert yüzey mermiyi çarpma anında parçalayıp enerjisini dağıtır.",
               Y("Sert seramik mermiyi geri sektirir ve hiç hasar görmez.", "kanitsiz", "Kanıtlar seramiğin mermiyi parçaladığını söylüyor (K1); geri sektirdiğine dair bir bilgi yok.", "K1"),
               Y("Seramik yumuşak olduğu için mermiyi yavaşça emer.", "veri", "Seramik çok sert (K1).", "K1"),
               ipucu="Mermi çok sert bir yüzeye çarpınca ne olur?",
               aciklama="Çok sert bir seramik plaka, mermiyi çarpma anında parçalar ve enerjisini geniş bir alana dağıtır."),
      kullanim=S("Bor karbür zırh plakalarında neden kullanılır?",
                 "Son derece sert ve hafiftir; mermiyi durdururken taşıyanı fazla yormaz",
                 Y("Bor karbür çok ağır olduğu için mermiyi ağırlığıyla durdurduğu için", "veri", "Plakalar hafif (hikâye); ölçülen yoğunluk da ({olcum}) düşük.", "{olcum}"),
                 Y("Bor karbür elektriği iyi ilettiği için", "iliski", "İletkenliğin mermiyi durdurmakla ilgisi yok; önemli olan sertlik ve hafiflik (K1).", "K1"),
                 Y("Bor Türkiye'de bol olduğu için zırhı sertleştirdiği için", "iliski", "Bolluk bir maddeyi ucuzlatır ama sert yapmaz; sertlik bor karbürün yapısından gelir (K1).", "K2"),
                 ipucu="K1 ve hikâyedeki iki özelliği birleştir.",
                 aciklama="Bor karbür (B₄C), elmas ve kübik bor nitrürden sonra bilinen en sert malzemelerden biridir ve çok hafiftir. Bu yüzden zırh plakalarında kullanılır. Bor-10 izotopu nötronları da iyi yuttuğu için bor karbür nükleer reaktörlerin kontrol çubuklarında da bulunur."),
      rakip="Al"),

    V("C", 4, "cevre", "Hawaii'deki Ölçüm Eğrisi",
      "Hawaii'deki Mauna Loa gözlemevinde 1958'den beri havadaki bir gazın miktarı ölçülüyor. Gazın miktarı her yıl biraz daha "
      "artıyor. Bilim insanları artışın büyük bölümünü kömür, petrol ve doğal gazın yakılmasına bağlıyor. Görevin: bu gazın "
      "oksijen dışındaki elementini bulmak ve artışın nedenini savunmak.",
      [("deney", "Yükselen eğri", "Gazın havadaki miktarı 1958'de milyonda yaklaşık 315 iken 2023'te 420'yi aştı. Eğri her yıl yükseliyor."),
       ("kimyasal", "Fosil yakıtlar", "Kömür, petrol ve doğal gaz milyonlarca yıl önce yaşamış canlıların kalıntılarından oluştu. Yakılınca içlerindeki bu element havadaki oksijenle birleşip o gazı oluşturuyor.")],
      gozlem=S("Gazın miktarının 65 yılda milyonda 315'ten 420'nin üzerine çıkması (K1) neyi gösterir?",
               "Havadaki bu gazın miktarı onlarca yıldır sürekli artıyor.",
               Y("Gazın miktarı her yıl azalıyor.", "veri", "Eğri her yıl yükseliyor (K1).", "K1"),
               Y("Artış yalnızca tek bir yıla özgü bir hatadır.", "veri", "Ölçümler 1958'den beri her yıl aynı yönde değişiyor (K1); tek bir yıla özgü değil.", "K1"),
               ipucu="Eğrinin yönüne bak.",
               aciklama="Uzun süre aynı yöntemle yapılan ölçümler, bir değişimin gerçek olup olmadığını gösterir. Mauna Loa ölçümleri havadaki bu gazın sürekli arttığını kanıtlar."),
      kullanim=S("Fosil yakıtların yakılması havadaki karbondioksiti neden artırır?",
                 "Fosil yakıtlar milyonlarca yıl önce yer altına gömülmüş karbonu içerir; yakılınca bu karbon oksijenle birleşip karbondioksit olarak havaya geçer",
                 Y("Fosil yakıtlar yanınca havadaki oksijen karbondioksite dönüştüğü için, karbon gerekmez", "veri", "Karbondioksit oluşması için karbon gerekir; karbon yakıttan geliyor (K2).", "K2"),
                 Y("Fosil yakıtlar havadaki azotu karbondioksite çevirdiği için", "iliski", "Azot bir elementtir; karbona dönüşmez. Karbon yakıtın içinden gelir (K2).", "K2"),
                 Y("Karbondioksit artışının yakıtlarla ilgisi olmadığı için", "kanitsiz", "Kanıtlar yakıtların yakılmasının bu gazı oluşturduğunu söylüyor (K2).", "K2"),
                 ipucu="K2'yi yeniden oku.",
                 aciklama="Fosil yakıtlar, uzun süre yer altında kalmış karbon depolarıdır. Yakılınca bu karbon karbondioksit olarak havaya geçer. Karbondioksit ısıyı tutan bir sera gazıdır; miktarının artması iklim değişikliğinin başlıca nedenidir."),
      yapi="dizilim", olcum=False,
      gerekce="Fosil yakıtlar milyonlarca yıl önce gömülmüş karbon içerir; yakılınca bu karbon oksijenle birleşip karbondioksit olarak havaya geçer ve miktarını artırır",
      karsi_kanit="Silisyum da 4A grubundadır, ama dizilimi 3. katmanda biter; bu dizilim ise 2. katmanda bitiyor."),

    V("C", 4, "adli", "Yüzükteki Taş Gerçek mi?",
      "Bir kuyumcuya getirilen yüzükteki parlak taşın 'gerçek elmas' olduğu söyleniyor. Kuyumcu taşın sahte olabileceğinden "
      "şüpheleniyor: kübik zirkonya, moissanit ya da cam olabilir. Taş üzerinde testler yapıldı. Görevin: taşın hangi elementten "
      "oluştuğunu bulmak ve gerçek olup olmadığını savunmak.",
      [("deney", "Isı testi", "Elmas test kalemiyle yapılan ölçümde taş ısıyı çok hızlı iletti."),
       ("deney", "Çizme testi", "Taş bir cam parçasını kolayca çizdi; kendisinde hiç çizik oluşmadı.")],
      gozlem=S("Taşın camı çizip kendisinin çizilmemesi (K2) neyi gösterir?",
               "Taş camdan çok daha sert.",
               Y("Taş camdan daha yumuşak.", "veri", "Daha yumuşak olan malzeme çizilir; taş çizilmedi (K2).", "K2"),
               Y("Taş kesinlikle elmastır.", "kanitsiz", "Camdan sert başka malzemeler de var (örneğin moissanit ve kübik zirkonya); tek başına bu test yetmez.", "K2"),
               ipucu="Hangi malzeme diğerini çizer?",
               aciklama="Bir malzeme kendinden daha yumuşak olanları çizebilir. Taş camdan serttir; ama camdan sert birkaç malzeme olduğu için başka kanıtlar da gerekir."),
      kullanim=S("Elmas neden bu kadar serttir?",
                 "Her karbon atomu dört komşusuna güçlü bağlarla bağlıdır; bu üç boyutlu ağ çok zor kırılır",
                 Y("Elmasın içinde metal bulunduğu için", "veri", "Elmas tek bir elementten, karbondan oluşur ({yapi}); metal içermez.", "{yapi}"),
                 Y("Elmas çok yoğun olduğu için", "iliski", "Yoğunluk sertliği belirlemez; kübik zirkonya elmastan yoğundur ama daha yumuşaktır ({tablo}).", "{tablo}"),
                 Y("Elmas ısıyı iyi ilettiği için", "iliski", "Isı iletimi (K1) bir tanıma testidir; sertliği açıklamaz.", "K1"),
                 ipucu="Elmas ile grafitin ikisi de karbondur ama grafit yumuşaktır. Fark atomların nasıl bağlandığında.",
                 aciklama="Elmasta her karbon atomu dört komşusuna güçlü kovalent bağlarla bağlanır ve üç boyutlu bir ağ oluşur. Grafitte ise atomlar katmanlar hâlinde dizilir; katmanlar kolayca kayar. Aynı elementin bu farklı biçimlerine allotrop denir."),
      yapi="dizilim",
      tablo_ozel=dict(
          baslik="Elmas ve benzerlerinin özellikleri",
          satirlar=[["Malzeme", "Yoğunluk (g/cm³)", "Isı iletimi"], ["Elmas (karbon)", "3,51", "Çok yüksek"],
                    ["Moissanit (silisyum karbür)", "3,22", "Yüksek"], ["Kübik zirkonya (zirkonyum oksit)", "5,6–6,0", "Düşük"],
                    ["Cam", "2,4–2,8", "Düşük"]],
          olcum=("Laboratuvar ölçümü: yoğunluk", "Taşın yoğunluğu 3,52 ± 0,03 g/cm³ olarak ölçüldü.", "yogunluk"),
          savunma="ölçülen yoğunluk (3,52 ± 0,03 g/cm³, {olcum}) tablodaki malzemelerden yalnızca elmasla uyumlu; moissanitin yoğunluğu 3,22 g/cm³"),
      gerekce="Elmasta her karbon atomu dört komşusuna güçlü bağlarla bağlıdır; bu yüzden taş camı çizecek kadar serttir ve ısıyı çok iyi iletir",
      karsi_kanit="Moissanit de camdan serttir ve ısıyı iyi iletir, ama yoğunluğu 3,22 g/cm³; ölçülen 3,52 ± 0,03 g/cm³ ile uyuşmuyor. Kübik zirkonya ise çok daha yoğundur ve ısıyı az iletir."),

    V("N", 4, "sanayi", "Otuz Milisaniyede Şişen Yastık",
      "Bir kaza testinde arabanın hava yastığı çarpışmadan sonraki otuz milisaniye içinde şişti. Yastığı şişiren gaz, bir katı "
      "maddenin çok hızlı ayrışmasıyla oluşuyor. Görevin: yastığı dolduran gazın hangi element olduğunu bulmak ve neden bu "
      "gazın seçildiğini savunmak.",
      [("deney", "Gazın davranışı", "Yastıktan alınan gaz renksiz ve kokusuz; yanan bir kibriti söndürüyor."),
       ("fiziksel", "Havayla karşılaştırma", "Bu gaz, soluduğumuz havanın da en büyük bölümünü oluşturuyor.", "serbest")],
      gozlem=S("Gazın yanan kibriti söndürmesi (K1) neyi gösterir?",
               "Gaz yanmayı desteklemiyor ve kendisi de yanmıyor.",
               Y("Gaz yanmayı destekleyen bir gazdır.", "veri", "Yanmayı destekleyen bir gaz kibriti daha parlak yakardı; bu gaz söndürdü (K1).", "K1"),
               Y("Gaz zehirlidir.", "kanitsiz", "Kibritin sönmesi gazın zehirli olduğunu göstermez.", "K1"),
               ipucu="Kibritin yanması için havadaki hangi gaz gerekir?",
               aciklama="Yanma için oksijen gerekir. Kibriti söndüren gaz, yanmayı desteklemeyen bir gazdır."),
      kullanim=S("Hava yastığında bu gazın kullanılmasının en önemli nedeni hangisidir?",
                 "Tepkimeye girmeyen, zehirsiz ve havada zaten bol bulunan bir gaz olması",
                 Y("Yanıcı olduğu için yastığı ısıtması", "veri", "Gaz yanan kibriti söndürüyor (K1); yanıcı değil.", "K1"),
                 Y("Havadan çok daha ağır olduğu için", "veri", "Bu gaz havanın büyük bölümünü oluşturur (K2); havadan çok ağır değildir. Üstelik yastığın şişmesi ağırlıkla ilgili değil.", "K2"),
                 Y("Renkli olduğu için şiştiğinin görülmesi", "veri", "Gaz renksiz (K1).", "K1"),
                 ipucu="Yolcular yastık açıldığında bu gazı solur. Gaz güvenli olmalı.",
                 aciklama="Hava yastığında sodyum azit gibi bir katı çok hızlı ayrışarak azot gazı oluşturur. Azot tepkimeye girmez, zehirli değildir ve soluduğumuz havanın yaklaşık %78'ini oluşturur."),
      yapi="dizilim", adaylar=["N", "O", "F", "Ne"],
      gerekce="Azot tepkimeye girmez, zehirli değildir ve havada zaten bol bulunur; bu yüzden yolcular için güvenlidir"),

    V("O", 4, "cevre", "Yüzeye Çıkan Balıklar",
      "Çok sıcak bir yaz günü, sığ ve durgun bir göletteki balıklar yüzeye çıkıp ağızlarını açıp kapatmaya başladı. Ertesi gün "
      "bazı balıklar ölmüştü. Bir çevre mühendisi, suda çözünmüş bir gazın azaldığını söyledi. Görevin: bu gazın elementini "
      "bulmak ve balıkların neden öldüğünü savunmak.",
      [("deney", "Yüzeydeki balıklar", "Balıklar suyun yüzeyine çıkıp ağızlarını hızla açıp kapatıyor; sanki havadan bir şey almaya çalışıyorlar."),
       ("fiziksel", "Isınan su", "Bu gaz suda çözünüyor; ama su ısındıkça suda çözünebilen miktarı azalıyor. Durgun su da havadan bu gazı yavaş alıyor.")],
      gozlem=S("Balıkların yüzeye çıkıp ağızlarını açıp kapatması (K1) neyi düşündürür?",
               "Sudaki çözünmüş gaz balıkların solunumuna yetmiyor; yüzeye yakın suda biraz daha fazla var.",
               Y("Balıklar yiyecek arıyor.", "kanitsiz", "Mühendis sudaki bir gazın azaldığını söyledi; davranış solunumla ilgili görünüyor.", "K1"),
               Y("Balıklar sıcakta oyun oynuyor.", "kanitsiz", "Ertesi gün balıkların ölmesi bu davranışın bir sıkıntıyı gösterdiğini düşündürüyor.", "K1"),
               ipucu="Balıklar suda neyi solungaçlarıyla alır?",
               aciklama="Balıklar sudaki çözünmüş gazı solungaçlarıyla alır. Bu gaz azalınca, havayla temas eden ve biraz daha fazla gaz içeren yüzeye çıkarlar."),
      kullanim=S("Sıcak ve durgun göletlerde balıklar neden boğulur?",
                 "Su ısındıkça içinde çözünebilen oksijen azalır ve durgun su havadan yeterince oksijen alamaz",
                 Y("Sıcak su balıkları haşladığı için", "kanitsiz", "Gölet suyu balıkları haşlayacak kadar ısınmaz; kanıtlar çözünmüş gazın azaldığını gösteriyor (K2).", "K2"),
                 Y("Isınan suda oksijen arttığı için balıklar zehirlendiği için", "veri", "Su ısındıkça çözünen oksijen azalır, artmaz (K2).", "K2"),
                 Y("Oksijen sudan ağır olduğu için dibe çöktüğü için", "iliski", "Çözünmüş gaz dibe çökmez; sorun suyun daha az gaz çözebilmesi (K2).", "K2"),
                 ipucu="K2'de sıcaklığın etkisi yazıyor.",
                 aciklama="Gazların suda çözünürlüğü sıcaklık arttıkça azalır. Sıcak ve durgun suda çözünmüş oksijen düşer; balıklar yeterince oksijen alamaz. Bu yüzden sıcak yaz günlerinde balık ölümleri artar."),
      yapi="iyon", adaylar=["N", "O", "F", "Ar"],
      gerekce="Su ısındıkça içinde çözünebilen oksijen azalır ve durgun su havadan yeterince oksijen alamaz; balıklar solunum için gereken oksijeni bulamaz"),

    V("Ne", 4, "teknoloji", "Kasadaki Kırmızı Çizgi",
      "Eski bir süpermarket kasasındaki barkod okuyucu, ürünlerin üzerinde ince kırmızı bir lazer çizgisi gezdiriyor. Lazer "
      "tüpünde helyumla karıştırılmış başka bir soy gaz var; kırmızı ışığı bu gazın atomları yayıyor. Görevin: kırmızı ışığı "
      "yayan soy gazı bulmak ve savunmak.",
      [("fiziksel", "Lazer ışığı", "Lazer ışını ince ve tek renkli: dalga boyu 633 nanometre, yani kırmızı."),
       ("kimyasal", "Tüpteki gaz", "Lazer tüpünde iki soy gaz var. Helyum, enerjisini diğer gaza aktarıyor; ışığı o gazın atomları yayıyor.")],
      gozlem=S("Lazer ışınının tek renkli olması (K1) neyi gösterir?",
               "Işık, atomların belirli iki enerji düzeyi arasındaki tek bir geçişten geliyor.",
               Y("Lazer ışını beyaz ışıktır.", "veri", "Lazer ışını tek renkli, kırmızı (K1).", "K1"),
               Y("Işık, tüpün camının rengidir.", "iliski", "Lazer ışığını cam değil, tüpteki gazın atomları üretiyor (K2).", "K2"),
               ipucu="Her element kendine özgü renklerde ışık yayar.",
               aciklama="Atomlar belirli enerji düzeyleri arasında geçiş yaparken belirli dalga boylarında ışık yayar. Lazer, bu geçişlerden birini çok güçlü ve düzenli hâle getirir."),
      kullanim=S("Helyum-neon lazeri neden kırmızı ışık verir?",
                 "Işığı yayan neon atomlarıdır; neonun enerji düzeyleri arasındaki geçiş 633 nanometrelik kırmızı ışığa karşılık gelir",
                 Y("Helyum kırmızı renkli bir gaz olduğu için", "veri", "Helyum renksizdir; ayrıca ışığı helyum değil, diğer gaz yayıyor (K2).", "K2"),
                 Y("Neon yanarken kırmızı alev verdiği için", "iliski", "Neon yanmaz; ışık, uyarılmış atomların ışımasından gelir.", "K2"),
                 Y("Lazer tüpü kırmızı boyalı olduğu için", "kanitsiz", "Kanıtlar ışığı tüpteki gazın atomlarının yaydığını söylüyor (K2).", "K2"),
                 ipucu="K2: Işığı hangi atomlar yayıyor?",
                 aciklama="Helyum-neon lazerinde elektrik akımı helyum atomlarını uyarır; helyum enerjisini neona aktarır ve neon atomları 632,8 nm'de kırmızı ışık yayar. Bu lazerler barkod okuyucularda ve okul laboratuvarlarında kullanıldı."),
      yapi="dizilim", adaylar=["H", "He", "Ne", "Ar"],
      gerekce="Lazerin kırmızı ışığını neon atomları yayar; neonun enerji düzeyleri arasındaki geçiş 633 nanometrelik kırmızı ışığa karşılık gelir"),

    V("Mg", 4, "sanayi", "Denizden Çıkan Metal",
      "1941'de Amerika'da bir şirket, deniz suyundan büyük miktarlarda hafif bir metal üretmeye başladı. Metal, savaş "
      "uçaklarının parçaları için gerekiyordu. Görevin: deniz suyundan elde edilen bu metali bulmak ve neden bu kadar "
      "gerekli olduğunu savunmak.",
      [("kimyasal", "Denizdeki hazine", "Deniz suyunun her litresinde yaklaşık 1,3 gram bu metalin iyonu çözünmüş hâlde bulunuyor."),
       ("deney", "Üretim yöntemi", "Deniz suyuna kireç eklenince bu metalin hidroksiti çöküyor. Çökelti işlenip erimiş tuzu elektrikle ayrıştırılınca metal elde ediliyor.")],
      gozlem=S("Deniz suyunun her litresinde 1,3 gram bu metalin bulunması (K1) neden önemlidir?",
               "Okyanuslar çok büyük olduğu için bu metalin neredeyse tükenmez bir kaynağı demektir.",
               Y("1,3 gram çok az olduğu için deniz suyu kaynak olamaz.", "iliski", "Bir litrede az görünse de okyanuslardaki toplam miktar çok büyüktür.", "K1"),
               Y("Deniz suyu bu metali saf hâlde içerir.", "veri", "Metal suda iyon olarak çözünmüş hâlde (K1); saf metal değil.", "K1"),
               ipucu="Okyanuslarda kaç litre su var?",
               aciklama="Okyanuslarda milyarlarca ton bu metal çözünmüş hâlde bulunur. Bu yüzden deniz suyu önemli bir kaynaktır."),
      kullanim=S("Savaş yıllarında uçak üretimi için magnezyuma neden bu kadar ihtiyaç vardı?",
                 "Magnezyum alaşımları çok hafif ve sağlamdır; uçakların ağırlığını azaltır",
                 Y("Magnezyum çok yoğun olduğu için uçakları sağlamlaştırdığı için", "veri", "Ölçülen yoğunluk ({olcum}) çok düşük; magnezyum çok hafif bir metaldir.", "{olcum}"),
                 Y("Magnezyum deniz suyunda çözündüğü için uçakları paslanmaktan koruduğu için", "iliski", "Suda çözünmüş olması bir kaynak avantajıdır (K1); uçaktaki görevini açıklamaz.", "K1"),
                 Y("Magnezyum radyoaktif olduğu için uçaklara enerji verdiği için", "kanitsiz", "Magnezyum radyoaktif değildir.", "K2"),
                 ipucu="Bir uçağın malzemesinde en önemli özellik nedir?",
                 aciklama="Magnezyum yapılarda kullanılan en hafif metaldir; alaşımları uçak, araba ve bilgisayar parçalarında kullanılır. Deniz suyundan magnezyum üretimi 1940'larda büyük ölçekte başladı."),
      rakip="Be"),

    V("Al", 4, "enerji", "Direkler Arasındaki Teller",
      "Şehirler arasında uzanan yüksek gerilim hatlarının telleri, ortası çelik, dışı başka bir metal olan örgü kablolardan "
      "yapılıyor. Bir öğrenci, evdeki tellerin bakır olduğunu bildiği için 'Neden bunlar da bakır değil?' diye soruyor. "
      "Görevin: hatların dış metalini bulmak ve neden seçildiğini savunmak.",
      [("fiziksel", "Kablonun yapısı", "Kablonun ortasında sağlamlık için çelik, dışında elektriği taşıyan gümüşi bir metal var."),
       ("iletkenlik", "Ağırlığa göre iletkenlik", "Bu metal elektriği bakırdan biraz daha az iletiyor; ama aynı ağırlıktaki bir tel bakırdan yaklaşık iki kat fazla akım taşıyabiliyor.")],
      gozlem=S("Bu metalin aynı ağırlıkta bakırdan iki kat fazla akım taşıyabilmesi (K2) neyi gösterir?",
               "Metal bakırdan çok daha hafif; kalın bir tel bile hafif kalıyor.",
               Y("Metal elektriği bakırdan çok daha iyi iletiyor.", "veri", "Metal elektriği bakırdan biraz daha az iletiyor (K2); avantajı hafifliğinden geliyor.", "K2"),
               Y("Metal elektriği hiç iletmiyor.", "veri", "Kabloda elektriği bu metal taşıyor (K1).", "K1"),
               ipucu="İletkenliği biraz düşük ama aynı ağırlıkta daha çok akım taşıyorsa ne avantajı var?",
               aciklama="Bu metal bakırdan yaklaşık üç kat hafiftir. Biraz daha kalın bir tel kullanılarak aynı akım çok daha hafif bir kabloyla taşınabilir."),
      kullanim=S("Yüksek gerilim hatlarında neden bakır yerine alüminyum kullanılır?",
                 "Alüminyum bakırdan çok daha hafif ve ucuzdur; aynı ağırlıkla daha fazla akım taşır ve direkler daha az yük taşır",
                 Y("Alüminyum elektriği bakırdan daha iyi ilettiği için", "veri", "Alüminyum elektriği bakırdan biraz daha az iletir (K2).", "K2"),
                 Y("Alüminyum mıknatısa çekildiği için telleri direklere tutturduğu için", "kanitsiz", "Alüminyum mıknatısa çekilmez; teller direklere mekanik olarak tutturulur.", "K1"),
                 Y("Alüminyum çok ağır olduğu için rüzgârda sallanmadığı için", "veri", "Ölçülen yoğunluk ({olcum}) düşük; alüminyum hafif bir metaldir.", "{olcum}"),
                 ipucu="K2'deki karşılaştırmayı düşün.",
                 aciklama="Alüminyum bakırın yaklaşık üçte biri yoğunluktadır ve daha ucuzdur. Direkler arasında asılı duran uzun teller için hafiflik çok önemlidir; bu yüzden yüksek gerilim hatlarında çelik çekirdekli alüminyum kablolar kullanılır."),
      rakip="B"),

    V("Si", 4, "ev", "Erimeyen Mutfak Eldiveni",
      "Bir aşçı, kırmızı silikon fırın eldiveniyle 250 °C'lik tepsiyi fırından çıkardı. Eldiven erimedi, yanmadı ve yumuşaklığını "
      "korudu. Aşçının oğlu 'Silikon bir element mi?' diye sordu. Görevin: silikonun yapısındaki kilit elementi bulmak ve "
      "silikonun neden ısıya dayanıklı olduğunu savunmak.",
      [("fiziksel", "Isıya dayanıklılık", "Silikon eldiven 250 °C'lik tepsiyi tuttuğunda erimedi, yanmadı ve esnek kaldı."),
       ("kimyasal", "Silikonun zinciri", "Silikonun uzun zincirleri, oksijen atomlarıyla bir elementin atomlarının art arda dizilmesinden oluşuyor. Aynı element kumun ve bilgisayar çiplerinin de temel elementi.")],
      gozlem=S("Eldivenin 250 °C'de erimeyip esnek kalması (K1) silikon hakkında neyi gösterir?",
               "Silikonun zincirleri yüksek sıcaklıkta bile bozulmuyor.",
               Y("Silikon bir metaldir.", "kanitsiz", "Isıya dayanıklılık bir maddenin metal olduğunu göstermez; silikon bir polimerdir (K2).", "K2"),
               Y("Silikon ısıyı çok iyi iletir.", "iliski", "Eldiven ısıyı iyi iletseydi aşçının elini yakardı; silikon ısıyı az iletir.", "K1"),
               ipucu="Sıradan plastikler sıcak tepsiye değince ne olur?",
               aciklama="Sıradan plastikler yüksek sıcaklıkta yumuşar ya da erir. Silikonun zincirleri ise çok güçlü bağlarla bağlı olduğu için ısıya dayanır."),
      kullanim=S("Silikonlar neden ısıya dayanıklıdır?",
                 "Zincirlerindeki silisyum-oksijen bağları çok güçlüdür; yüksek sıcaklıkta bile kopmaz",
                 Y("Silikon saf silisyum metalinden yapıldığı için", "veri", "Silikon saf bir element değil; silisyum ve oksijen atomlarından oluşan bir zincirdir (K2).", "K2"),
                 Y("Silikon suyla soğutulduğu için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K1"),
                 Y("Silikon kırmızı renkli olduğu için ısıyı yansıttığı için", "iliski", "Eldivenin rengi boyadan gelir; ısıya dayanıklılığın nedeni zincirin bağları (K2).", "K2"),
                 ipucu="K2'deki zincirin yapısına bak.",
                 aciklama="'Silikon' bir element değil, silisyum ve oksijen atomlarından oluşan bir polimerdir; elementin adı 'silisyum'dur. Silisyum-oksijen bağları çok güçlü olduğu için silikonlar ısıya dayanıklı ve esnektir; mutfak eşyalarında, conta ve yalıtım malzemelerinde kullanılır."),
      rakip="C"),

    V("P", 4, "cevre", "Yeşile Boğulan Göl",
      "Tarlaların arasındaki bir gölün yüzeyi yazın kalın, yeşil bir yosun tabakasıyla kaplandı. Birkaç hafta sonra göldeki "
      "balıklar ölmeye başladı. Çevre mühendisi, gübrelerden ve bazı deterjanlardan göle karışan bir elementin bileşiklerinden "
      "şüpheleniyor. Görevin: bu elementi bulmak ve balıkların neden öldüğünü savunmak.",
      [("deney", "Yeşil göl", "Gölün yüzeyi yeşil bir yosun tabakasıyla kaplandı; birkaç hafta sonra balıklar ölmeye başladı."),
       ("kimyasal", "Yosunların besini", "Gübrelerden ve bazı deterjanlardan suya karışan bu elementin oksijenli bileşikleri yosunlar için besin; bu bileşikler göle karıştıkça yosunlar hızla çoğalıyor.")],
      gozlem=S("Yosunların çoğalmasından birkaç hafta sonra balıkların ölmeye başlaması (K1) neyi düşündürür?",
               "Yosunların aşırı çoğalması gölün dengesini bozmuş; balıkların ölümü bununla bağlantılı olabilir.",
               Y("Balıklar yosunları yiyip zehirlendi.", "kanitsiz", "Kanıtlarda balıkların yosun yiyip zehirlendiğine dair bir bilgi yok.", "K1"),
               Y("Yosunlarla balık ölümleri arasında hiçbir ilişki olamaz.", "kanitsiz", "İki olayın sırayla gerçekleşmesi bir ilişki olabileceğini düşündürür; bu, araştırılması gereken bir hipotezdir.", "K1"),
               ipucu="İki olay hangi sırayla gerçekleşti?",
               aciklama="Bir olayın ardından başka bir olayın gelmesi bir neden-sonuç ilişkisini akla getirir; ama bunu kanıtlamak için mekanizmanın da açıklanması gerekir."),
      kullanim=S("Fosfat göllere karışınca neden balıklar ölür?",
                 "Fosfat yosunların aşırı çoğalmasına yol açar; ölen yosunlar çürürken sudaki oksijeni tüketir",
                 Y("Fosfat balıklar için doğrudan zehirli olduğu için", "kanitsiz", "Kanıtlar fosfatın yosunlar için besin olduğunu söylüyor (K2); balıkları doğrudan zehirlediğine dair bir kanıt yok.", "K2"),
                 Y("Fosfor suyu ısıttığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K2"),
                 Y("Yosunlar sudaki oksijeni artırdığı için balıklar zehirlendiği için", "iliski", "Yosunlar gündüz oksijen üretir ama ölüp çürürken sudaki oksijeni tüketirler.", "K1"),
                 ipucu="Yosunlar ölünce çürür. Çürüme sırasında sudaki hangi gaz tükenir?",
                 aciklama="Bu olaya ötrofikasyon denir. Fazla fosfat yosunların patlarcasına çoğalmasına yol açar; yosunlar ölünce onları ayrıştıran bakteriler sudaki oksijeni tüketir ve balıklar boğulur. Bu yüzden birçok ülkede deterjanlardaki fosfat sınırlandırıldı."),
      rakip="N"),

    V("S", 4, "cevre", "Aşınan Heykeller",
      "Bir kömür santralinin yakınındaki ormanda ağaçların yaprakları sararmış; şehirdeki mermer heykellerin yüzleri zamanla "
      "aşınıp silikleşmiş. Ölçümler yağmur suyunun normalden çok daha asitli olduğunu gösterdi. Görevin: asit yağmuruna yol "
      "açan, kömürün içindeki elementi bulmak ve savunmak.",
      [("deney", "Hasar belirtileri", "Ormandaki ağaçların yaprakları sararmış; mermer heykellerin yüzeyleri aşınmış. Yağmur suyu normalden çok daha asitli."),
       ("kimyasal", "Kömürdeki element", "Kömürün içindeki bu element yakılınca keskin kokulu bir oksit gazı oluşturuyor. Bu gaz havadaki su ve oksijenle birleşip asit oluşturuyor.")],
      gozlem=S("Mermer heykellerin yüzeyinin aşınması (K1) yağmur hakkında neyi gösterir?",
               "Yağmur suyu mermeri çözebilecek kadar asitli.",
               Y("Heykeller rüzgârla aşındı.", "kanitsiz", "Ölçümler yağmur suyunun çok asitli olduğunu gösteriyor (K1); aşınmayı rüzgâra bağlayan bir kanıt yok.", "K1"),
               Y("Mermer suda kendiliğinden çözünür.", "veri", "Mermer sıradan suda çok az çözünür; asitli su ise onu hızla aşındırır.", "K1"),
               ipucu="Mermer (kalsiyum karbonat) asitle karşılaşınca ne olur?",
               aciklama="Mermer kalsiyum karbonattır; asitlerle tepkimeye girerek çözünür. Asitli yağmur heykelleri ve binaları bu yüzden aşındırır."),
      kullanim=S("Kükürt dioksit neden asit yağmuruna yol açar?",
                 "Havadaki su ve oksijenle birleşip sülfürik asit oluşturur; bu asit yağmurla yere iner",
                 Y("Kükürt dioksit yağmuru ısıttığı için", "kanitsiz", "Kanıtlar gazın asit oluşturduğunu söylüyor (K2); ısıtmadan söz etmiyor.", "K2"),
                 Y("Kükürt dioksit sarı renkli olduğu için yaprakları sarıya boyadığı için", "iliski", "Yaprakların sararması asit hasarından kaynaklanır; gazın rengiyle ilgili değil.", "K2"),
                 Y("Kükürt yanmaz bir element olduğu için", "veri", "Kükürt kömürle birlikte yanarak oksit gazı oluşturuyor (K2).", "K2"),
                 ipucu="K2'deki tepkimeyi izle.",
                 aciklama="Kömür yakılınca içindeki kükürt kükürt dioksite dönüşür; bu gaz havada sülfürik asit oluşturur. Bugün santrallerin bacalarına konan filtreler (baca gazı arıtma) kükürt dioksiti büyük ölçüde tutuyor."),
      rakip="O"),

    V("Cl", 4, "sanayi", "Boruların Gizli Elementi",
      "Bir binanın su ve kanalizasyon tesisatı PVC denilen bir plastikten yapılmış. Bir öğrenci, PVC'nin kütlesinin yarıdan "
      "fazlasının karbondan ya da hidrojenden değil, başka bir elementten geldiğini öğrenince şaşırdı. Görevin: bu elementi "
      "bulmak ve PVC'nin neden tesisatta kullanıldığını savunmak.",
      [("kimyasal", "PVC'nin bileşimi", "PVC plastiğinin kütlesinin yarıdan fazlası tek bir elementten geliyor; geri kalanı karbon ve hidrojen."),
       ("kimyasal", "Elementin bilinen hâlleri", "Bu element sofra tuzunda sodyumla birlikte bulunuyor; saf hâli sarımsı yeşil, zehirli bir gaz.", "serbest")],
      gozlem=S("PVC'nin kütlesinin yarıdan fazlasının tek bir elementten gelmesi (K1) neyi gösterir?",
               "Bu element PVC'nin yapısının çok önemli bir parçası; özellikleri PVC'yi de etkiler.",
               Y("PVC tamamen bu elementten yapılmıştır.", "veri", "PVC'nin geri kalanı karbon ve hidrojen (K1).", "K1"),
               Y("PVC bir metaldir.", "kanitsiz", "PVC bir plastiktir; kanıtlarda metal olduğuna dair bir bilgi yok.", "K1"),
               ipucu="Bir maddenin kütlesinin yarısından fazlası bir elementten geliyorsa ne düşünürsün?",
               aciklama="Bir elementin bir maddenin kütlesinin büyük bölümünü oluşturması, o maddenin özelliklerinde bu elementin önemli bir rolü olduğunu düşündürür."),
      kullanim=S("PVC borular neden su tesisatında yaygın kullanılır?",
                 "Klor içeren bu plastik paslanmaz, hafiftir, ucuzdur ve kolay alev almaz",
                 Y("PVC zehirli bir gaz olduğu için mikropları öldürdüğü için", "iliski", "Saf klor zehirli bir gazdır (K2) ama PVC'de klor plastiğin yapısına sıkıca bağlıdır; PVC bir gaz değil, katıdır.", "K2"),
                 Y("PVC elektriği çok iyi ilettiği için", "kanitsiz", "PVC bir yalıtkandır; kanıtlarda iletkenlikten söz edilmiyor.", "K1"),
                 Y("PVC suda çözündüğü için suyu dezenfekte ettiği için", "kanitsiz", "Bir boru suda çözünseydi işe yaramazdı; kanıtlarda böyle bir bilgi yok.", "K1"),
                 ipucu="Bir su borusunda hangi özellikler önemli?",
                 aciklama="PVC kütlece yaklaşık %57 klor içerir. Klor plastiğin kolay alev almamasına katkıda bulunur. PVC paslanmaz, hafiftir ve ucuzdur; bu yüzden su borularında, pencere çerçevelerinde ve kablo kılıflarında kullanılır."),
      rakip="Br"),

    V("K", 4, "saglik", "Dedenin Az Sodyumlu Tuzu",
      "Tansiyonu yüksek bir dede için markette 'az sodyumlu tuz' alındı. Dede tuzun biraz acımsı bir tadı olduğunu söyledi. "
      "Paketin üzerinde, sodyum klorürün bir kısmının yerine aynı gruptaki başka bir metalin klorürünün kullanıldığı yazıyor. "
      "Görevin: bu metali bulmak ve neden kullanıldığını savunmak.",
      [("kimyasal", "Tuzun tadı", "Tuz sofra tuzuna benzer biçimde tuzlu ama biraz acımsı bir tadı var."),
       ("kimyasal", "Yerine geçen metal", "Kullanılan metal sodyumla aynı grupta. Muz ve patates bu metal bakımından zengin.")],
      gozlem=S("Tuzun tadının sofra tuzuna benzemesi ama biraz farklı olması (K1) neyi gösterir?",
               "Tuzda sodyuma benzeyen ama aynı olmayan başka bir metalin bileşiği var.",
               Y("Tuz tamamen sofra tuzudur.", "veri", "Tuzun tadı biraz acımsı (K1); paket de sodyum klorürün bir kısmının yerine başka bir tuz konduğunu söylüyor.", "K1"),
               Y("Tuzun içinde şeker var.", "kanitsiz", "Kanıtlarda şekerden söz edilmiyor; tat tuzlu ve acımsı.", "K1"),
               ipucu="Aynı gruptaki elementlerin bileşikleri birbirine benzer ama aynı değildir.",
               aciklama="Aynı gruptaki elementlerin bileşikleri benzer özellikler gösterir. Bu yüzden tuzun tadı sofra tuzuna benziyor ama tamamen aynı değil."),
      kullanim=S("Az sodyumlu tuzlarda potasyum klorür neden kullanılır?",
                 "Potasyum sodyumla aynı grupta olduğu için klorürü sofra tuzuna benzer bir tuzlu tat verir; böylece sodyum alımı azalır",
                 Y("Potasyum klorür hiç tat vermediği için", "veri", "Tuz tuzlu ve biraz acımsı bir tat veriyor (K1).", "K1"),
                 Y("Potasyum metali tansiyonu kendiliğinden düşürdüğü için", "kanitsiz", "Tuzda metal potasyum değil, potasyum klorür var; amaç sodyum alımını azaltmak.", "K2"),
                 Y("Potasyum klorür sodyumdan daha fazla sodyum içerdiği için", "veri", "Potasyum klorür sodyum içermez; amaç sodyumu azaltmak.", "K2"),
                 ipucu="Tansiyonu yüksek birine neyi azaltması önerilir?",
                 aciklama="Fazla sodyum tansiyonu yükseltebilir. Potasyum klorür sofra tuzuna benzer bir tuzlu tat verdiği için az sodyumlu tuzlarda kullanılır. Ancak böbrek hastaları gibi bazı kişiler potasyumu kısıtlamalıdır; bu yüzden doktora danışmak gerekir."),
      rakip="Na"),

    V("Ca", 4, "ev", "Kabuksuz Yumurta",
      "Bir öğrenci evde bir deney yaptı: çiğ bir yumurtayı bir kavanoz sirkenin içine koydu. Kabuğun üzerinde hemen kabarcıklar "
      "belirdi; iki gün sonra kabuk tamamen kaybolmuştu ve yumurta lastik gibi esnek bir zarla kalmıştı. Görevin: yumurta "
      "kabuğundaki metali bulmak ve deneyi kanıtlarla savunmak.",
      [("deney", "Kaybolan kabuk", "Sirkedeki yumurtanın kabuğundan kabarcıklar çıktı; iki gün sonra kabuk tamamen kayboldu, yumurta esnek bir zarla kaldı."),
       ("kimyasal", "Kabuğun yapısı", "Yumurta kabuğunun yaklaşık %95'i bu metalin karbonatı. Aynı karbonat kireç taşında ve mermerde de bulunuyor.")],
      gozlem=S("Kabuktan kabarcıklar çıkması (K1) neyi gösterir?",
               "Kabuk sirkedeki asitle tepkimeye girip gaz oluşturuyor.",
               Y("Yumurtanın içindeki hava dışarı çıkıyor.", "kanitsiz", "Kabarcıklar kabuğun yüzeyinde oluşuyor ve kabuk zamanla kayboluyor (K1); bu bir tepkimeyi gösteriyor.", "K1"),
               Y("Sirke kaynıyor.", "veri", "Deney oda sıcaklığında yapıldı; kabarcıklar kaynamadan değil, kabukla tepkimeden geliyor.", "K1"),
               ipucu="Karbonatlar asitle karşılaşınca ne olur?",
               aciklama="Karbonatlar asitlerle tepkimeye girerek karbondioksit gazı çıkarır. Kabarcıklar bu gazdır; kabuk tepkimede tükenir."),
      kullanim=S("Tavuklar sağlam kabuklu yumurta için neden kalsiyuma ihtiyaç duyar?",
                 "Yumurta kabuğu büyük ölçüde kalsiyum karbonattan yapılır; kalsiyum eksik olursa kabuk ince ve kırılgan olur",
                 Y("Kalsiyum yumurtanın sarısını renklendirdiği için", "kanitsiz", "Kanıtlar kalsiyumun kabuktaki görevini anlatıyor (K2); sarının rengiyle ilgili bir bilgi yok.", "K2"),
                 Y("Kalsiyum kabuğu sirkeye dayanıklı yaptığı için", "veri", "Kabuk sirkede çözündü (K1); kalsiyum karbonat asitle tepkimeye girer.", "K1"),
                 Y("Kalsiyum yumurtayı hafiflettiği için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K2"),
                 ipucu="K2'de kabuğun bileşimi yazıyor.",
                 aciklama="Yumurta kabuğu %95 oranında kalsiyum karbonattır. Tavuklar kabuk için yemlerinden bol kalsiyum almalıdır. Kalsiyum karbonat sirkedeki asetik asitle tepkimeye girip karbondioksit çıkararak çözünür."),
      rakip="Mg"),

    V("Mn", 4, "sanat", "Mağara Duvarındaki Siyah Çizgiler",
      "On binlerce yıllık bir mağara resminin siyah çizgilerinden alınan çok küçük bir örnek incelendi. Siyah boyanın bir "
      "kısmının odun kömürü, bir kısmının da bir geçiş metalinin siyah oksidi olduğu anlaşıldı. Görevin: bu metali bulmak ve "
      "resimlerin neden bu kadar uzun süre dayandığını savunmak.",
      [("tarih", "Binlerce yıllık resim", "Resimler on binlerce yıldır mağara duvarında duruyor; siyah çizgiler hâlâ seçilebiliyor."),
       ("kimyasal", "Siyah oksit", "Siyah boyanın bir kısmı bir geçiş metalinin oksidi. Bu oksit bugün alkalin pillerin içinde de kullanılıyor.")],
      gozlem=S("Siyah çizgilerin on binlerce yıl dayanması (K1) boya hakkında neyi gösterir?",
               "Boya ışıkla ve zamanla kolay kolay bozulmayan, kararlı maddelerden yapılmış.",
               Y("Boya her yıl yenilenmiştir.", "kanitsiz", "Resimlerin yenilendiğine dair bir kanıt yok.", "K1"),
               Y("Boya suda kolayca çözünür.", "veri", "Suda kolayca çözünen bir boya nemli bir mağarada on binlerce yıl kalamazdı (K1).", "K1"),
               ipucu="Bitkisel boyalar zamanla solar. Mineraller ise...",
               aciklama="Mineral boyalar (metal oksitleri gibi) ışık, nem ve zamanla bozulmaz. Bu yüzden mağara resimleri on binlerce yıl korunabildi."),
      kullanim=S("Mangan oksit mağara resimlerinde neden bu kadar uzun süre dayanmıştır?",
                 "Mineral bir boyadır; ışıkla ve zamanla bozulmaz ve kayaya sıkıca tutunur",
                 Y("Mangan oksit karanlıkta parladığı için", "kanitsiz", "Kanıtlarda böyle bir özellik yok.", "K2"),
                 Y("Mangan oksit pillerde kullanıldığı için elektrikle korunduğu için", "iliski", "Pillerde kullanılması manganın bugünkü bir kullanımıdır (K2); resmin dayanıklılığını açıklamaz.", "K2"),
                 Y("Mangan oksit çok yumuşak olduğu için duvara işlediği için", "kanitsiz", "Kanıtlar boyanın dayanıklılığını vurguluyor (K1).", "K1"),
                 ipucu="K1 ve K2'deki bilgileri birleştir.",
                 aciklama="Tarih öncesi ressamlar siyah için odun kömürü ve mangan oksit, kırmızı ve sarı için demir oksitler kullandılar. Bu mineral boyalar kararlı olduğu için resimler günümüze ulaştı. Mangan bugün çelik yapımında ve pillerde kullanılır."),
      rakip="Re"),

    V("Fe", 4, "uzay", "Tarladaki Ağır Taş",
      "Bir çiftçi tarlasını sürerken aynı büyüklükteki taşlardan çok daha ağır, kararmış bir taş buldu. Taş mıknatısa güçlü "
      "biçimde çekiliyordu. Bir üniversitedeki uzmanlar taşın bir göktaşı olduğunu düşünüyor. Görevin: taşın ana metalini "
      "bulmak ve göktaşı olduğunu kanıtlarla savunmak.",
      [("fiziksel", "Ağır ve mıknatıslı", "Taş aynı büyüklükteki sıradan taşlardan çok daha ağır ve mıknatısa güçlü biçimde çekiliyor."),
       ("deney", "Gizli desen", "Taş kesilip asitle dağlanınca yüzeyinde çapraz çizgilerden oluşan bir desen ortaya çıktı. Bu desen ancak uzayda milyonlarca yılda çok yavaş soğuyan metal alaşımlarında oluşuyor.", "serbest")],
      gozlem=S("Taşın çok ağır olması ve mıknatısa güçlü çekilmesi (K1) neyi gösterir?",
               "Taş büyük ölçüde mıknatısa çekilen yoğun bir metalden oluşuyor.",
               Y("Taş sıradan bir kayaçtır.", "veri", "Sıradan kayaçlar bu kadar ağır değildir ve mıknatısa güçlü çekilmez (K1).", "K1"),
               Y("Taş içi boş bir taştır.", "veri", "İçi boş bir taş daha hafif olurdu; bu taş çok ağır (K1).", "K1"),
               ipucu="Hangi maddeler hem ağır hem de mıknatısa güçlü çekilir?",
               aciklama="Sıradan kayaçlar büyük ölçüde silikat minerallerinden oluşur. Çok ağır ve mıknatısa güçlü çekilen bir taş, mıknatısa çekilen yoğun metaller içerir."),
      kullanim=S("Demir göktaşlarının mıknatısa güçlü çekilmesinin nedeni nedir?",
                 "Büyük ölçüde demir ve nikelden oluşurlar; bu metaller mıknatısa güçlü çekilir",
                 Y("Göktaşları uzayda mıknatıslandığı için", "kanitsiz", "Kanıtlar taşın bileşimini gösteriyor; uzayda mıknatıslandığına dair bir bilgi yok.", "K1"),
                 Y("Göktaşlarının çok sıcak olduğu için", "iliski", "Mıknatısa çekilmek sıcaklıkla ilgili değil; hatta ısınan mıknatıslar zayıflar.", "K1"),
                 Y("Göktaşları altından yapıldığı için", "veri", "Altın mıknatısa çekilmez; ölçülen yoğunluk ({olcum}) da altınınkinden çok düşük.", "{olcum}"),
                 ipucu="Mıknatısa güçlü çekilen metalleri düşün.",
                 aciklama="Demir göktaşları büyük ölçüde demir-nikel alaşımından oluşur. Kesilip dağlandıklarında görülen 'Widmanstätten deseni' ancak milyonlarca yılda çok yavaş soğumayla oluşur; bu desen göktaşı olduklarının güçlü bir kanıtıdır."),
      rakip="Ru"),

    V("Co", 4, "teknoloji", "Bataryanın Etik Bedeli",
      "Bir öğrenci, telefonunun bataryasının katodunda lityumun yanında bir geçiş metali daha bulunduğunu öğrendi. Bu metalin "
      "dünyadaki üretiminin büyük bölümü tek bir ülkeden geliyor ve madenlerde çocuk işçiliği raporlanıyor. Görevin: bu metali "
      "bulmak ve bataryadaki görevini savunmak.",
      [("kimyasal", "Katodun yapısı", "Bataryanın katodu lityum ve bir geçiş metalinin oksidinden yapılmış. Şarjda lityum iyonları bu katmanlı yapıdan çıkıyor, kullanımda geri giriyor."),
       ("tarih", "Üretimin bedeli", "Bu metalin dünyadaki üretiminin büyük bölümü Demokratik Kongo Cumhuriyeti'nden geliyor; bazı madenlerde çocuk işçiliği ve güvenlik sorunları raporlanıyor.")],
      gozlem=S("Bir metalin üretiminin büyük bölümünün tek bir ülkeden gelmesi ve madenlerde sorunlar olması (K2) neden önemlidir?",
               "Hem tedarik riski oluşturur hem de bu metali kullanan ürünlerin üretiminde etik sorumluluk doğurur.",
               Y("Hiçbir önemi yoktur; yalnızca pilin çalışması önemlidir.", "kanitsiz", "Kanıtlar üretimde insan hakları sorunları olduğunu gösteriyor (K2); bilim ve teknoloji bu sorunlardan bağımsız değildir.", "K2"),
               Y("Bu durum metalin daha ucuz olmasını garanti eder.", "kanitsiz", "Üretimin tek bir yere bağlı olması fiyatları ve tedariki daha riskli yapar; ucuzluğu garanti etmez.", "K2"),
               ipucu="Bir ürünün yapımında kullanılan maddelerin nereden ve nasıl geldiği kimin sorumluluğudur?",
               aciklama="Teknolojinin hammaddeleri bazen insan hakları ve çevre sorunlarıyla birlikte gelir. Bu yüzden geri dönüşüm, bu tür metalleri daha az kullanan piller ve sorumlu madencilik önemlidir."),
      kullanim=S("Kobalt lityum iyon pillerin katodunda neden kullanılır?",
                 "Kobalt oksidin katmanlı yapısı lityum iyonlarını şarj ve kullanım sırasında defalarca alıp bırakabilir; pil çok enerji depolar",
                 Y("Kobalt pili mavi renge boyadığı için", "iliski", "Kobalt bileşikleri mavi olabilir ama pildeki görevi renk vermek değil, lityum iyonlarını tutmak (K1).", "K1"),
                 Y("Kobalt radyoaktif olduğu için pile enerji verdiği için", "kanitsiz", "Pildeki kobalt radyoaktif değildir; enerji kimyasal tepkimeden gelir.", "K1"),
                 Y("Kobalt hiç tepkimeye girmediği için pili koruduğu için", "veri", "Katot, şarj ve kullanım sırasında kimyasal olarak değişiyor (K1).", "K1"),
                 ipucu="K1'de katodun ne yaptığı yazıyor.",
                 aciklama="Lityum kobalt oksit katotlarda lityum iyonları katmanların arasına girip çıkar. Bu yapı yüksek enerji depolar. Ancak kobaltın etik ve çevresel sorunları nedeniyle daha az kobalt kullanan ya da hiç kullanmayan piller geliştiriliyor."),
      rakip="Rh"),
]
