# -*- coding: utf-8 -*-
"""Seviye 4 (Bilimsel Savunma) — yeni vakalar, ikinci bölüm."""
from sablon import S, V, Y

VAKALAR = [
    V("Ni", 4, "enerji", "Yüzlerce Kez Dolan Pil",
      "Bir öğrenci kumandasının şarj edilebilir AA pillerini yüzlerce kez doldurup boşalttı; piller hâlâ çalışıyor. Pilin "
      "etiketinde '... metal hidrür' yazıyor; ilk kısım silinmiş. Görevin: pilin elektrotlarından birindeki metali bulmak "
      "ve neden kullanıldığını savunmak.",
      [("deney", "Tekrar tekrar şarj", "Pil yüzlerce kez şarj edilip boşaltıldığı hâlde hâlâ çalışıyor."),
       ("kimyasal", "Elektrottaki metal", "Pilin elektrotlarından biri bu metalin hidroksitinden yapılmış. Metal mıknatısa çekiliyor ve paslanmaz çeliğin de bileşeni.")],
      gozlem=S("Pilin yüzlerce kez şarj edilebilmesi (K1) içindeki tepkimeler hakkında neyi gösterir?",
               "Pildeki tepkimeler şarj edilince geri döndürülebiliyor (tersinir).",
               Y("Pilin içinde hiç tepkime olmuyor.", "kanitsiz", "Piller kimyasal tepkimelerle çalışır; şarj bu tepkimeleri tersine çevirir.", "K1"),
               Y("Pil her şarjda yeni maddelerle dolduruluyor.", "kanitsiz", "Pil kapalıdır; içine yeni madde konmuyor. Şarj, mevcut maddeleri eski hâline döndürür.", "K1"),
               ipucu="Şarj, pildeki maddelere ne yapar?",
               aciklama="Şarj edilebilir pillerde boşalma sırasındaki tepkimeler elektrik verilerek tersine çevrilir; maddeler eski hâline döner."),
      kullanim=S("Nikel şarj edilebilir pillerde neden kullanılır?",
                 "Nikel hidroksit elektrotu şarj ve boşalma sırasında defalarca tersinir tepkime verebilir; pil yüzlerce kez kullanılabilir",
                 Y("Nikel mıknatısa çekildiği için pili cihaza tutturduğu için", "iliski", "Mıknatıslık (K2) pilin çalışmasıyla ilgili değil; önemli olan elektrotun tersinir tepkimesi.", "K2"),
                 Y("Nikel hiç tepkimeye girmediği için", "veri", "Pil, elektrotlardaki tepkimelerle çalışıyor (K1).", "K1"),
                 Y("Nikel radyoaktif olduğu için kendiliğinden elektrik ürettiği için", "kanitsiz", "Nikel radyoaktif değildir; elektrik kimyasal tepkimeden gelir.", "K1"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Nikel-metal hidrür pillerde bir elektrot nikel hidroksittir. Tepkimeler tersinir olduğu için pil yüzlerce kez doldurulup boşaltılabilir. Bu piller hibrit arabalarda da kullanılır."),
      rakip="Pd"),

    V("Cu", 4, "tarih", "Tunç Çağı'nın Kılıcı",
      "Anadolu'daki bir kazıda bulunan yaklaşık 5000 yıllık bir kılıç incelendi. Kılıç, kızıl kahverengi bir metale az "
      "miktarda kalay katılarak yapılmıştı. Görevin: kılıcın ana metalini bulmak ve insanların neden saf metal yerine bu "
      "alaşımı kullandığını savunmak.",
      [("alasim", "Kılıcın alaşımı", "Kılıç, kızıl kahverengi bir metale yaklaşık %10 kalay katılarak yapılmış bir alaşımdan (tunç) oluşuyor."),
       ("fiziksel", "Saf metal ve alaşım", "Saf hâldeki kızıl metal yumuşak; kalay katılınca elde edilen alaşım çok daha sert ve daha düşük sıcaklıkta eriyor.")],
      gozlem=S("Kalay katılınca alaşımın saf metalden daha sert olması (K2) neyi gösterir?",
               "Alaşımlar, içindeki saf metallerden farklı ve daha kullanışlı özellikler gösterebilir.",
               Y("Kalay, karıştırıldığı her metali yumuşatır.", "veri", "Kalay katılınca alaşım daha sert oldu (K2).", "K2"),
               Y("Alaşım ile saf metal arasında hiçbir fark yoktur.", "veri", "Alaşım daha sert ve daha düşük sıcaklıkta eriyor (K2).", "K2"),
               ipucu="Saf metal ile alaşımı karşılaştır.",
               aciklama="Bir metale başka bir metal katılınca atomların düzeni bozulur; katmanlar birbiri üzerinde kolay kayamaz ve alaşım sertleşir."),
      kullanim=S("Tunç Çağı'nda insanlar neden saf bakır yerine tunç kullandı?",
                 "Bakıra kalay katılınca elde edilen tunç çok daha sert ve daha kolay dökülür; daha iyi aletler ve silahlar yapılabildi",
                 Y("Tunç bakırdan daha yumuşak olduğu için", "veri", "Tunç bakırdan daha sert (K2).", "K2"),
                 Y("Tunç çok daha yüksek sıcaklıkta eridiği için", "veri", "Tunç bakırdan daha düşük sıcaklıkta erir (K2).", "K2"),
                 Y("Tunç tamamen kalaydan yapıldığı için", "veri", "Tunç büyük ölçüde bakırdır; yalnızca yaklaşık %10 kalay içerir (K1).", "K1"),
                 ipucu="K2'deki iki avantajı düşün.",
                 aciklama="Bakıra yaklaşık %10 kalay katılınca tunç elde edilir. Tunç daha serttir ve daha düşük sıcaklıkta erir; bu yüzden kalıplara dökülmesi kolaydır. İnsanlık tarihindeki 'Tunç Çağı' adını bu alaşımdan alır."),
      rakip="Ag"),

    V("Zn", 4, "enerji", "Delinen Pil Kabı",
      "Bir öğrenci, yıllarca bir el fenerinde unutulmuş eski tip bir kuru pili açtı. Pilin gri metal kabının bazı yerleri "
      "incelmiş, hatta delinmişti. Görevin: kabın metalini bulmak ve pilin çalışırken kabın neden inceldiğini savunmak.",
      [("fiziksel", "İncelen kap", "Pilin dış kabı gri bir metalden; pil bittikten sonra kabın bazı yerleri incelmiş ve delinmiş."),
       ("kimyasal", "Kabın görevi", "Pil çalışırken kabın metali elektron vererek iyonlarına dönüşüyor; kap pilin eksi kutbu.")],
      gozlem=S("Pil bittikten sonra kabın incelmesi (K1) neyi gösterir?",
               "Kabın metali pil çalışırken tepkimeye girerek tükendi.",
               Y("Kap el fenerinin ısısıyla eridi.", "kanitsiz", "Bir el feneri bir metali eritecek kadar ısınmaz; kanıtlar metalin tepkimeye girdiğini gösteriyor (K2).", "K2"),
               Y("Kap hiç değişmedi.", "veri", "Kabın bazı yerleri incelmiş ve delinmiş (K1).", "K1"),
               ipucu="K2'de kabın pil çalışırken ne yaptığı yazıyor.",
               aciklama="Pilde eksi kutup olan metal, elektron vererek iyonlarına dönüşür ve yavaş yavaş tükenir. Kabın incelmesi bunun gözle görülen sonucudur."),
      kullanim=S("Çinko kuru pillerde neden kullanılır?",
                 "Kolayca elektron verir; pilin eksi kutbu olarak akımın kaynağıdır ve ucuzdur",
                 Y("Çinko hiç tepkimeye girmediği için pili koruduğu için", "veri", "Çinko pil çalışırken tepkimeye giriyor ve tükeniyor (K1, K2).", "K2"),
                 Y("Çinko elektron aldığı için pilin artı kutbu olduğu için", "veri", "Çinko elektron veriyor ve eksi kutup (K2).", "K2"),
                 Y("Çinko çok ağır olduğu için pili sağlamlaştırdığı için", "iliski", "Kabın ağırlığı akım üretimini açıklamaz; çinkonun görevi elektron vermek (K2).", "K2"),
                 ipucu="K2'yi oku.",
                 aciklama="Çinko-karbon ve alkalin pillerde çinko elektron vererek yükseltgenir; bu elektronlar devreden geçerek cihazı çalıştırır. Çinko ucuz ve kolay işlenen bir metal olduğu için pillerde yaygın kullanılır."),
      rakip="Cd"),

    V("Ge", 4, "adli", "Karanlıkta Gören Kamera",
      "Bir arama kurtarma ekibi, gece ormanda kaybolan bir yürüyüşçüyü termal kamerayla buldu. Kameranın merceği gözle "
      "bakınca koyu gri ve ışık geçirmez görünüyor; ama insan vücudunun yaydığı kızılötesi ışınları geçiriyor. Görevin: "
      "mercek malzemesindeki elementi bulmak ve savunmak.",
      [("fiziksel", "Garip mercek", "Mercek gözle bakınca koyu gri ve opak görünüyor; ama vücut sıcaklığındaki cisimlerin yaydığı kızılötesi ışınları geçiriyor."),
       ("iletkenlik", "Mercek malzemesi", "Mercek malzemesi bir yarı iletken element; bu element bir zamanlar ilk transistörlerde kullanıldı.")],
      gozlem=S("Merceğin görünür ışığı geçirmeyip kızılötesi ışınları geçirmesi (K1) neyi gösterir?",
               "Bir malzeme bazı ışık türlerine saydam, bazılarına opak olabilir.",
               Y("Mercek bozuk olduğu için koyu görünüyor.", "kanitsiz", "Kamera yürüyüşçüyü buldu; mercek doğru çalışıyor.", "K1"),
               Y("Kızılötesi ışınlar görünür ışıkla tamamen aynıdır.", "veri", "Mercek birini geçirip diğerini geçirmiyor (K1); demek ki farklı ışınlar.", "K1"),
               ipucu="Cam görünür ışığı geçirir; bu mercek ise...",
               aciklama="Görünür ışık ve kızılötesi ışınlar farklı dalga boylarındadır. Bir malzeme bunlardan birini geçirip diğerini durdurabilir."),
      kullanim=S("Germanyum termal kamera merceklerinde neden kullanılır?",
                 "Görünür ışığı geçirmese de kızılötesi ışınları geçirir; sıcak cisimlerin görüntüsü bu ışınlarla oluşturulur",
                 Y("Germanyum karanlıkta parladığı için", "kanitsiz", "Kanıtlarda böyle bir özellik yok; mercek ışık yaymıyor, kızılötesi ışınları geçiriyor (K1).", "K1"),
                 Y("Germanyum görünür ışığı çok iyi geçirdiği için", "veri", "Mercek görünür ışığı geçirmiyor (K1).", "K1"),
                 Y("Germanyum transistörlerde kullanıldığı için", "iliski", "Transistörler germanyumun eski bir kullanım alanıdır (K2); mercekteki görevini açıklamaz.", "K2"),
                 ipucu="K1'deki özelliği düşün.",
                 aciklama="Germanyum ve oksidi kızılötesi ışınlara saydamdır; bu yüzden termal kameraların ve kızılötesi cihazların merceklerinde kullanılır. Bugün germanyumun en büyük kullanım alanları optik lifler ve özel merceklerdir."),
      rakip="Sn"),

    V("As", 4, "adli", "Soğuk Tabaktaki Ayna",
      "1836'da kimyacı James Marsh, şüpheli bir ölümün ardından alınan örneği bir düzenekte özel bir gazla tepkimeye soktu ve "
      "çıkan alevi soğuk bir porselen tabağa tuttu. Tabakta parlak, siyah-gümüşi bir 'ayna' oluştu. Görevin: bu testin ortaya "
      "çıkardığı zehirli elementi bulmak ve savunmak.",
      [("deney", "Marsh testi", "Örnek zehirli element içeriyorsa soğuk porselen tabakta parlak, siyah-gümüşi bir leke ('ayna') oluşuyor; içermiyorsa leke oluşmuyor."),
       ("tarih", "Zehirlerin kralı", "Bu test, eskiden 'zehirlerin kralı' diye anılan bir elementin çok küçük miktarlarını bile ortaya çıkarabiliyordu.")],
      gozlem=S("Lekenin yalnızca örnek zehirli elementi içerdiğinde oluşması (K1) testi neden güçlü yapar?",
               "Testin sonucu elementin varlığına bağlı; leke varsa element var, yoksa yok.",
               Y("Test her örnekte leke oluşturur.", "veri", "Örnek elementi içermiyorsa leke oluşmuyor (K1).", "K1"),
               Y("Lekenin rengi elementin miktarını kesin olarak gösterir.", "kanitsiz", "Kanıtlar lekenin elementin varlığını gösterdiğini söylüyor (K1); miktarını kesin olarak değil.", "K1"),
               ipucu="İyi bir test, aranan madde varsa bir sonuç, yoksa başka bir sonuç vermelidir.",
               aciklama="Bir testin güvenilir olması için aranan madde varken olumlu, yokken olumsuz sonuç vermesi gerekir. Marsh testi bu özelliği sayesinde mahkemelerde kanıt olarak kullanıldı."),
      kullanim=S("Marsh testi adli bilimde neden önemli bir dönüm noktasıydı?",
                 "Arseniğin çok küçük miktarlarını bile güvenilir biçimde gösterdi; zehirlenme şüphelerinde bilimsel kanıt toplamak mümkün oldu",
                 Y("Test arseniği zararsız hâle getirdiği için", "kanitsiz", "Test arseniği bulur; zararsız hâle getirmez.", "K1"),
                 Y("Test yalnızca büyük miktarlardaki arseniği bulabildiği için", "veri", "Test çok küçük miktarları bile ortaya çıkarabiliyordu (K2).", "K2"),
                 Y("Arsenik parlak olduğu için gözle hemen görüldüğü için", "iliski", "Arsenik zehirlenmeleri gözle fark edilemezdi; testin değeri görünmeyeni ortaya çıkarmasından geliyordu.", "K2"),
                 ipucu="K2'yi oku: Test ne kadar küçük miktarları bulabiliyordu?",
                 aciklama="Marsh testi, arseniğin çok küçük miktarlarını bile gösterebilen ilk güvenilir testlerden biriydi. Adli kimyanın gelişmesinde önemli bir adım oldu. Antimon da benzer bir leke verebildiği için iki elementi ayıran ek testler geliştirildi."),
      rakip="Sb"),

    V("Ru", 4, "enerji", "Penceredeki Kırmızı Güneş Pili",
      "Bir binanın penceresine, içinden dışarısı görülebilen kırmızımsı bir güneş pili yerleştirildi. Pil, içindeki özel bir "
      "boya sayesinde ışığı soğurup elektrik üretiyor. Boya molekülünün merkezinde bir geçiş metali bulunuyor. Görevin: bu "
      "metali bulmak ve neden kullanıldığını savunmak.",
      [("fiziksel", "Yarı saydam pil", "Pil yarı saydam ve kırmızımsı renkli; içindeki boya ışığın bir kısmını soğurup elektrik üretiyor."),
       ("kimyasal", "Boyanın metali", "Boya molekülünün merkezinde bir geçiş metalinin atomu var. Bu metal platini ve paladyumu sertleştirmek için de kullanılıyor.")],
      gozlem=S("Pilin hem yarı saydam olması hem de elektrik üretmesi (K1) neyi gösterir?",
               "Boya ışığın yalnızca bir kısmını soğurup elektriğe çeviriyor; geri kalanı geçiyor.",
               Y("Pil hiç ışık soğurmuyor.", "veri", "Boya ışığın bir kısmını soğurup elektrik üretiyor (K1).", "K1"),
               Y("Pil bütün ışığı soğurduğu için siyah görünüyor.", "veri", "Pil yarı saydam ve kırmızımsı (K1).", "K1"),
               ipucu="İçinden dışarısı görülebiliyorsa ışığın bir kısmı geçiyor demektir.",
               aciklama="Bu tür güneş pilleri ışığın bir kısmını soğurur, kalanını geçirir. Bu yüzden pencere camı gibi kullanılabilirler."),
      kullanim=S("Rutenyumlu boyalar güneş pillerinde neden kullanılır?",
                 "Rutenyum içeren boya molekülleri görünür ışığın büyük kısmını soğurur ve elektronlarını yarı iletkene aktararak akım oluşturur",
                 Y("Rutenyum platini sertleştirdiği için pili sağlamlaştırdığı için", "iliski", "Platin sertleştirmek rutenyumun başka bir kullanım alanıdır (K2); güneş pilindeki görevi ışığı soğurmak.", "K2"),
                 Y("Rutenyum ışığı tamamen yansıttığı için", "veri", "Boya ışığın bir kısmını soğuruyor (K1); yansıtsaydı elektrik üretemezdi.", "K1"),
                 Y("Rutenyum radyoaktif olduğu için kendiliğinden elektrik ürettiği için", "kanitsiz", "Pilin elektriği ışıktan geliyor (K1).", "K1"),
                 ipucu="K1'deki boyanın görevini düşün.",
                 aciklama="Boya duyarlı güneş pillerinde rutenyum içeren boyalar ışığı soğurur ve elektronlarını titanyum dioksit gibi bir yarı iletkene aktarır. Rutenyum ayrıca elektronik devrelerde ve platin alaşımlarını sertleştirmekte kullanılır."),
      rakip="Fe"),

    V("Pd", 4, "enerji", "Hidrojen Yutan Metal",
      "Bir laboratuvarda gümüşi bir metal tel, hidrojen gazıyla dolu bir kaba kondu. Tel, kendi hacminin yüzlerce katı hidrojen "
      "gazını emdi. Isıtılan aynı metalden yapılmış bir zarın içinden de yalnızca hidrojen geçebildi. Görevin: bu metali "
      "bulmak ve neden kullanıldığını savunmak.",
      [("deney", "Hidrojen süngeri", "Metal tel, kendi hacminin yüzlerce katı hidrojen gazını emdi."),
       ("deney", "Seçici zar", "Isıtılan bu metalden yapılmış bir zarın içinden yalnızca hidrojen geçebiliyor; diğer gazlar geçemiyor. Metal arabaların katalitik konvertörlerinde de kullanılıyor.")],
      gozlem=S("Metalin kendi hacminin yüzlerce katı hidrojeni emmesi (K1) neyi gösterir?",
               "Hidrojen atomları metalin içine girip atomlarının arasındaki boşluklara yerleşebiliyor.",
               Y("Metal hidrojeni yakıyor.", "kanitsiz", "Kanıtlarda yanmadan söz edilmiyor; metal hidrojeni emiyor.", "K1"),
               Y("Metal hidrojeni dışarı itiyor.", "veri", "Metal hidrojeni emiyor (K1).", "K1"),
               ipucu="Hidrojen en küçük atomdur.",
               aciklama="Hidrojen atomları çok küçüktür; bazı metallerin atomları arasındaki boşluklara girebilir. Bu metal bu konuda olağanüstüdür."),
      kullanim=S("Paladyum hidrojeni saflaştırmada neden kullanılır?",
                 "Isıtılınca yalnızca hidrojenin içinden geçmesine izin verir; diğer gazlar geçemez",
                 Y("Paladyum diğer gazları da hidrojene çevirdiği için", "kanitsiz", "Paladyum gazları hidrojene çevirmez; yalnızca hidrojeni geçirir (K2).", "K2"),
                 Y("Paladyum hidrojenle tepkimeye girip onu yok ettiği için", "veri", "Hidrojen paladyumun içinden geçiyor (K2); yok olmuyor.", "K2"),
                 Y("Paladyum çok ucuz olduğu için", "kanitsiz", "Paladyum değerli ve pahalı bir metaldir; seçilme nedeni seçici geçirgenliği.", "K2"),
                 ipucu="K2'deki zarın özelliğine bak.",
                 aciklama="Isıtılan paladyumdan yalnızca hidrojen geçebilir; bu yolla çok saf hidrojen elde edilir. Paladyumun en büyük kullanım alanı ise arabaların katalitik konvertörleridir."),
      rakip="Ni"),

    V("Cd", 4, "cevre", "'Ah, Acıyor!' Hastalığı",
      "1900'lerin ortasında Japonya'da Jinzu Nehri çevresinde yaşayan birçok kişinin kemikleri kolayca kırılıyor, şiddetli "
      "ağrılar görülüyordu. Hastalığa yerel dilde 'itai-itai' (ah acıyor, acıyor) adı verildi. Nehrin yukarısında bir maden "
      "vardı. Görevin: hastalığa yol açan metali bulmak ve savunmak.",
      [("tarih", "Hastalığın yeri", "Hastalık en çok, maden atıklarının karıştığı nehrin suyuyla sulanan pirinç tarlalarının çevresinde görülüyordu."),
       ("kimyasal", "Atıktaki metal", "Atıklarda, çinko cevheriyle birlikte bulunan zehirli bir metal vardı. Bu metal pirince geçiyor ve vücutta birikerek kemiklerden kalsiyum kaybına yol açıyordu.")],
      gozlem=S("Hastalığın en çok maden atıklarıyla kirlenen suyla sulanan tarlaların çevresinde görülmesi (K1) neyi düşündürür?",
               "Hastalığın nedeni madenden suya ve pirince geçen bir madde olabilir.",
               Y("Hastalık bulaşıcıdır.", "kanitsiz", "Hastalığın yeri kirli suyla bağlantılı (K1); bulaşıcı olduğuna dair bir kanıt yok.", "K1"),
               Y("Hastalığın nedeni pirincin kendisidir.", "veri", "Hastalık her pirinç yiyende değil, kirli suyla sulanan tarlaların çevresinde görülüyordu (K1).", "K1"),
               ipucu="Hastalık nerede yoğunlaşıyordu?",
               aciklama="Bir hastalığın belirli bir kirlilik kaynağının çevresinde yoğunlaşması, o kaynakla bağlantılı olduğunu düşündürür. Bu, çevre sağlığı araştırmalarının temel yöntemlerinden biridir."),
      kullanim=S("Kadmiyum neden bu kadar tehlikelidir?",
                 "Vücutta, özellikle böbreklerde birikir ve kemiklerden kalsiyum kaybına yol açar",
                 Y("Kadmiyum vücuttan hemen atıldığı için", "veri", "Kadmiyum vücutta birikir (K2).", "K2"),
                 Y("Kadmiyum kemikleri güçlendirdiği için", "veri", "Kadmiyum kemiklerden kalsiyum kaybına yol açar (K2).", "K2"),
                 Y("Kadmiyum radyoaktif olduğu için", "kanitsiz", "Kadmiyumun zararı radyoaktiflikten değil, zehirliliğinden gelir.", "K2"),
                 ipucu="K2'nin son cümlesine bak.",
                 aciklama="Kadmiyum vücutta birikir; böbreklere zarar verir ve kemiklerden kalsiyum kaybına yol açar. İtai-itai hastalığı bunun en ağır örneğidir. Bu yüzden kadmiyumun pillerde ve boyalarda kullanımı sınırlandırılıyor."),
      rakip="Zn"),

    V("Te", 4, "teknoloji", "Silinip Yeniden Yazılan Disk",
      "Bir öğrenci eski bir yeniden yazılabilir DVD'ye film kaydetti, sonra silip başka bir film kaydetti. Diskin kayıt "
      "katmanı, lazerle ısıtılınca yapısı değişen bir alaşımdan yapılmış. Alaşımda germanyum ve antimonun yanında bir "
      "yarı metal daha var. Görevin: bu yarı metali bulmak ve savunmak.",
      [("deney", "Değişen yapı", "Kayıt katmanı lazerle ısıtılınca düzenli kristal yapıdan düzensiz yapıya geçiyor; farklı bir ısıtmayla da geri dönüyor. İki yapı ışığı farklı yansıtıyor."),
       ("kimyasal", "Alaşımın üçüncü elementi", "Alaşımın üçüncü elementi kükürtle aynı grupta bulunan bir yarı metal. Bu element bazı güneş panellerinde de kullanılıyor.")],
      gozlem=S("Kayıt katmanının iki yapı arasında ileri geri geçebilmesi (K1) neden önemlidir?",
               "Disk silinip yeniden yazılabilir.",
               Y("Disk yalnızca bir kez yazılabilir.", "veri", "Yapı geri dönebildiğine göre disk silinip yeniden yazılabilir (K1).", "K1"),
               Y("İki yapı ışığı aynı biçimde yansıtır.", "veri", "İki yapı ışığı farklı yansıtıyor (K1).", "K1"),
               ipucu="Bir yapı değişikliği geri döndürülebiliyorsa ne olur?",
               aciklama="Düzenli (kristal) ve düzensiz yapılar ışığı farklı yansıtır; okuyucu lazer bu farkı 0 ve 1 olarak okur. Yapı geri döndürülebildiği için disk yeniden yazılabilir."),
      kullanim=S("Tellürlü alaşımlar yeniden yazılabilir disklerde neden kullanılır?",
                 "Lazerle ısıtılınca kristal ve düzensiz hâller arasında defalarca geçiş yapabilir; iki hâl ışığı farklı yansıttığı için veri okunabilir",
                 Y("Tellür hiç ısınmadığı için", "veri", "Kayıt katmanı lazerle ısıtılıyor (K1).", "K1"),
                 Y("Tellür güneş panellerinde kullanıldığı için diske elektrik verdiği için", "iliski", "Güneş panelleri tellürün başka bir kullanım alanıdır (K2); diskteki görevini açıklamaz.", "K2"),
                 Y("Tellür ışığı hiç yansıtmadığı için", "veri", "İki yapı ışığı farklı yansıtıyor (K1); hiç yansıtmasaydı veri okunamazdı.", "K1"),
                 ipucu="K1'deki özelliği düşün.",
                 aciklama="Germanyum-antimon-tellür alaşımları 'faz değiştiren' malzemelerdir: lazerle kristal ve düzensiz hâller arasında hızla geçerler. Bu özellik yeniden yazılabilir disklerde ve yeni nesil bellek çiplerinde kullanılır."),
      rakip="Se"),

    V("I", 4, "tarih", "Yosun Külünden Mor Duman",
      "1811'de Paris'te barut için güherçile üreten Bernard Courtois, deniz yosunu külüne sülfürik asit ekleyince mor dumanların "
      "yükseldiğini gördü. Dumanlar soğuk bir yüzeye değince metal parlaklığında koyu kristallere dönüştü. Görevin: Courtois'nın "
      "bulduğu elementi bulmak ve savunmak.",
      [("deney", "Mor duman", "Deniz yosunu külüne sülfürik asit eklenince mor renkli dumanlar yükseldi."),
       ("fiziksel", "Doğrudan kristal", "Mor dumanlar soğuk bir yüzeye değince sıvıya dönüşmeden doğrudan metal parlaklığında koyu kristallere dönüştü.")],
      gozlem=S("Mor dumanların sıvıya dönüşmeden doğrudan katı kristallere dönüşmesi (K2) neyi gösterir?",
               "Bu madde gaz hâlinden doğrudan katı hâle geçebiliyor (tersi de süblimleşme).",
               Y("Madde önce erimiş, sonra donmuştur.", "veri", "Duman sıvıya dönüşmeden doğrudan kristale dönüştü (K2).", "K2"),
               Y("Kristaller yosunun kendisidir.", "kanitsiz", "Kristaller yükselen dumanlardan oluştu (K2); yosundan değil.", "K2"),
               ipucu="K2'de 'sıvıya dönüşmeden' ifadesine dikkat et.",
               aciklama="Bazı maddeler katı hâlden doğrudan gaz hâline geçer (süblimleşme) ya da gazdan doğrudan katıya döner. Bu madde bunun bilinen bir örneğidir."),
      kullanim=S("İyotun keşfi neden deniz yosunu külünden oldu?",
                 "Deniz yosunları denizdeki iyotu bünyelerinde biriktirir; külleri iyot bakımından zengindir",
                 Y("Yosun külü iyotu kendisi ürettiği için", "kanitsiz", "Yosunlar iyotu üretmez, denizden alıp biriktirir.", "K1"),
                 Y("İyot havada çok bol bulunduğu için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; iyot yosun külünden elde edildi.", "K1"),
                 Y("Sülfürik asit iyot elementi oluşturduğu için", "iliski", "Asit yeni bir element oluşturmaz; yalnızca küldeki iyot bileşiklerinden iyotu açığa çıkarır.", "K1"),
                 ipucu="Deniz yosunları denizden neler alır?",
                 aciklama="Deniz suyunda az miktarda iyot bulunur; deniz yosunları onu bünyelerinde biriktirir. Courtois, yosun külüne asit ekleyince iyotu mor buhar olarak açığa çıkardı. İyot adını da Yunanca 'mor' anlamına gelen kelimeden alır."),
      rakip="Br"),

    V("Xe", 4, "sanayi", "Gece Yolunu Aydınlatan Far",
      "Bazı arabaların farları açıldığında birkaç saniye içinde mavimsi beyaz, çok parlak bir ışık veriyor. Far ampulünün içinde "
      "telden bir filaman yok; ışık, bir soy gazın içinde oluşan parlak bir elektrik arkından geliyor. Görevin: bu soy gazı "
      "bulmak ve savunmak.",
      [("fiziksel", "Mavimsi beyaz ışık", "Farın ışığı mavimsi beyaz ve çok parlak; ampulde filaman yok."),
       ("kimyasal", "Ampuldeki gaz", "Ampulde elektrik verilince parlak bir ark oluşturan bir soy gaz var. Aynı gaz fotoğraf flaşlarında da kullanılıyor.")],
      gozlem=S("Ampulde filaman olmadığı hâlde ışık çıkması (K1) neyi gösterir?",
               "Işık, kızgın bir telden değil, elektrik geçen gazın atomlarından geliyor.",
               Y("Işık ampulün camından geliyor.", "kanitsiz", "Kanıtlar ışığın gazın içindeki arktan geldiğini söylüyor (K2).", "K2"),
               Y("Ampul ışığı güneşten depolamış.", "kanitsiz", "Far elektrikle çalışıyor; güneş ışığı depolamıyor.", "K1"),
               ipucu="Eski ampullerde ışık neyden gelirdi? Bu farda o parça yok.",
               aciklama="Akkor ampullerde ışık kızgın bir telden gelir. Gaz deşarj lambalarında ise elektrik akımı gazın atomlarını uyarır ve atomlar ışık yayar."),
      kullanim=S("Ksenon farlarda neden kullanılır?",
                 "Elektrik arkıyla uyarılınca gün ışığına yakın, çok parlak bir ışık verir; tepkimeye girmediği için ampul uzun ömürlüdür",
                 Y("Ksenon yanıcı olduğu için alev verdiği için", "kanitsiz", "Ksenon bir soy gazdır ve yanmaz; ışık arktan gelir (K2).", "K2"),
                 Y("Ksenon kırmızı ışık verdiği için", "veri", "Farın ışığı mavimsi beyaz (K1).", "K1"),
                 Y("Ksenon ampulün içindeki teli soğuttuğu için", "veri", "Ampulde tel (filaman) yok (K1).", "K1"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Ksenon, elektrik arkıyla uyarılınca gün ışığına benzeyen parlak bir ışık verir. Bu yüzden bazı araba farlarında, sinema projektörlerinde ve fotoğraf flaşlarında kullanılır. Soy gaz olduğu için ampulün içinde bozulmaz."),
      rakip="Kr"),

    V("Cs", 4, "adli", "Mavi Parlayan Toz",
      "1987'de Brezilya'nın Goiânia şehrinde, terk edilmiş bir hastanedeki eski bir kanser tedavi cihazı hurdacılar tarafından "
      "parçalandı. Cihazın içinden karanlıkta mavi parlayan bir toz çıktı; insanlar tozu merakla birbirine gösterdi ve "
      "dağıttı. Toz radyoaktifti; dört kişi hayatını kaybetti, yüzlerce kişi radyasyona maruz kaldı. Görevin: tozdaki radyoaktif "
      "elementi bulmak ve kazanın neden bu kadar ağır olduğunu savunmak.",
      [("fiziksel", "Kolay yayılan toz", "Toz suda kolayca çözünen bir tuz. Ellere, giysilere ve eşyalara bulaşarak hızla yayıldı."),
       ("kimyasal", "Tozun elementi", "Tozdaki radyoaktif izotopun yarılanma süresi yaklaşık 30 yıl. Element bir alkali metal.")],
      gozlem=S("Tozun suda kolayca çözünmesi ve her yere bulaşması (K1) kazayı neden ağırlaştırdı?",
               "Radyoaktif madde ellerle, sularla ve eşyalarla hızla yayıldı; birçok kişi farkında olmadan maruz kaldı.",
               Y("Suda çözünen madde radyoaktifliğini kaybeder.", "veri", "Çözünmek radyoaktifliği yok etmez; tam tersine maddenin yayılmasını kolaylaştırdı (K1).", "K1"),
               Y("Toz yalnızca tek bir kişiye zarar verdi.", "veri", "Toz hızla yayıldı (K1); hikâyeye göre yüzlerce kişi maruz kaldı.", "K1"),
               ipucu="Kolay çözünen ve bulaşan bir madde nasıl yayılır?",
               aciklama="Radyoaktif bir maddenin tehlikesi yalnızca ışınımına değil, ne kadar kolay yayıldığına da bağlıdır. Suda çözünen bir toz, yutulabilir ve bulaştığı her yere taşınabilir."),
      kullanim=S("Bu kaza radyoaktif kaynaklarla ilgili hangi kuralın önemini gösterir?",
                 "Radyoaktif kaynaklar kullanılmadığında bile güvenli biçimde saklanmalı, kayıt altında tutulmalı ve işaretlenmelidir",
                 Y("Radyoaktif kaynaklar terk edilince zamanla tamamen zararsız olur", "veri", "Bu izotopun yarılanma süresi yaklaşık 30 yıl (K2); terk edilen kaynak onlarca yıl tehlikeli kalır.", "K2"),
                 Y("Parlayan maddeler her zaman zararsızdır", "kanitsiz", "Toz parlıyordu ama ölümcüldü; parlaklık bir maddenin güvenli olduğunu göstermez.", "K1"),
                 Y("Sezyum suda çözünmediği için kaza kendiliğinden sınırlı kaldı", "veri", "Toz suda kolayca çözünüyordu (K1) ve hızla yayıldı.", "K1"),
                 ipucu="Kaza nasıl başladı?",
                 aciklama="Goiânia kazası, terk edilmiş bir tıbbi cihazdaki sezyum-137 kaynağının açılmasıyla oluştu. Bu kaza sonrasında radyoaktif kaynakların kaydı, saklanması ve uyarı işaretleri konusunda dünyada kurallar sıkılaştırıldı. Sezyumun kararlı izotopu ise atom saatlerinde kullanılır."),
      ozellik="erime", rakip="Rb",
      gerekce="Tozdaki sezyum-137 radyoaktiftir ve yarılanma süresi uzundur; tuzu suda kolayca çözündüğü için hızla yayıldı. Bu yüzden radyoaktif kaynaklar güvenli biçimde saklanmalıdır"),

    V("Nd", 4, "sanayi", "Sessiz Motorun Mıknatısları",
      "Bir elektrikli arabanın motorunun içinde, birkaç kilogram ağırlığında çok güçlü kalıcı mıknatıslar var. Mühendis, bu "
      "mıknatıslar sayesinde motorun küçük ve hafif olduğu hâlde çok güçlü olduğunu söylüyor. Görevin: mıknatısa adını veren "
      "lantaniti bulmak ve savunmak.",
      [("fiziksel", "Güçlü mıknatıs", "Motorun dönen parçasında çok güçlü kalıcı mıknatıslar var; motor küçük ve hafif olduğu hâlde çok güçlü."),
       ("alasim", "Mıknatısın bileşimi", "Mıknatıs demir, bor ve bir lantanitin alaşımından yapılmış. Bu tür mıknatıslar 1983'te bulundu.")],
      gozlem=S("Motorun küçük ve hafif olduğu hâlde çok güçlü olması (K1) mıknatıslar hakkında neyi gösterir?",
               "Mıknatıslar küçük boyutlarına göre çok güçlü bir manyetik alan oluşturuyor.",
               Y("Motorun gücü mıknatıslardan bağımsızdır.", "kanitsiz", "Mühendis motorun gücünü mıknatıslara bağlıyor (hikâye, K1).", "K1"),
               Y("Mıknatıslar çok zayıf olduğu için motor küçük.", "veri", "Mıknatıslar çok güçlü (K1).", "K1"),
               ipucu="Elektrik motorunda dönme hareketini mıknatıs ile akım birlikte oluşturur.",
               aciklama="Elektrik motorlarında mıknatıs ile bobinlerden geçen akım birbirini iter ya da çeker. Mıknatıs ne kadar güçlüyse aynı boyutta o kadar güçlü bir motor yapılabilir."),
      kullanim=S("Neodim mıknatıslar elektrikli araç motorlarında neden kullanılır?",
                 "Çok güçlü oldukları için küçük ve hafif bir motor yüksek güç üretebilir",
                 Y("Neodim mıknatıslar hiç manyetik olmadığı için", "veri", "Mıknatıslar çok güçlü (K1).", "K1"),
                 Y("Neodim radyoaktif olduğu için motora enerji verdiği için", "kanitsiz", "Neodim radyoaktif değildir; motorun enerjisi bataryadan gelir.", "K2"),
                 Y("Mıknatıslar tamamen neodimden yapıldığı için", "veri", "Mıknatıs demir, bor ve neodimin alaşımı (K2).", "K2"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Neodim-demir-bor mıknatısları bilinen en güçlü kalıcı mıknatıslardır. Elektrikli araçların ve rüzgâr türbinlerinin küçük ama güçlü motor ve jeneratörlerinde kullanılırlar. Yüksek sıcaklıkta güçlerini korumaları için içlerine disprosiyum katılır."),
      yapi="izotop", adaylar=["Pr", "Nd", "Pm", "Sm"]),

    V("Ta", 4, "teknoloji", "Telefonun İçindeki Koltan",
      "Bir akıllı telefonun devre kartında pirinç tanesi büyüklüğünde çok sayıda kapasitör var. Bu küçük parçalar boyutlarına "
      "göre çok fazla elektrik yükü depoluyor. Kapasitörlerin metali, 'koltan' denilen bir cevherden elde ediliyor. Görevin: "
      "bu metali bulmak ve savunmak.",
      [("iletkenlik", "Küçük ama güçlü kapasitör", "Kapasitörler çok küçük olduğu hâlde çok fazla elektrik yükü depoluyor. Metalin yüzeyinde oluşan çok ince bir oksit tabakası yalıtkan görevi görüyor."),
       ("tarih", "Cevherin bedeli", "Koltan cevherinin bir kısmı Orta Afrika'daki madenlerden geliyor; bu madenlerin bazıları silahlı çatışmaların finansmanıyla ilişkilendiriliyor.")],
      gozlem=S("Bazı madenlerin silahlı çatışmalarla ilişkilendirilmesi (K2) teknoloji kullanıcıları için neden önemlidir?",
               "Kullandığımız cihazların hammaddelerinin nereden ve nasıl geldiği etik bir sorumluluk doğurur.",
               Y("Cihazın nereden geldiği önemli değildir.", "kanitsiz", "Kanıtlar hammadde üretiminin insanların yaşamını etkilediğini gösteriyor (K2).", "K2"),
               Y("Bu durum telefonların daha iyi çalışmasını sağlar.", "iliski", "Madenlerdeki çatışmalar cihazın çalışmasıyla ilgili değil; bu bir etik sorundur.", "K2"),
               ipucu="Bir ürünün yapımında kullanılan maddeler kimlerin hayatını etkiliyor?",
               aciklama="Bazı mineraller 'çatışma minerali' olarak anılır. Bu yüzden şirketlerden hammaddelerinin kaynağını açıklamaları istenir; geri dönüşüm de talebi azaltır."),
      kullanim=S("Tantal kapasitörler telefonlarda neden kullanılır?",
                 "Tantalın yüzeyindeki çok ince oksit tabakası iyi bir yalıtkandır; küçük hacimde çok yüksek kapasite elde edilir",
                 Y("Tantal elektriği hiç iletmediği için", "kanitsiz", "Tantal bir metaldir ve elektriği iletir; yalıtkan olan yüzeyindeki oksit tabakası (K1).", "K1"),
                 Y("Tantal kapasitörler çok büyük olduğu için", "veri", "Kapasitörler pirinç tanesi büyüklüğünde (K1).", "K1"),
                 Y("Koltan cevheri çatışma bölgelerinden geldiği için ucuz olduğu için", "iliski", "Cevherin kaynağı bir etik sorundur (K2); tantalın teknik üstünlüğünü açıklamaz.", "K2"),
                 ipucu="K1'deki oksit tabakasının görevini düşün.",
                 aciklama="Tantal kapasitörlerde tantalın yüzeyinde oluşturulan çok ince oksit tabakası yalıtkan görevi görür. Bu sayede çok küçük bir hacimde yüksek kapasite elde edilir. Tantal vücutla uyumlu olduğu için cerrahi implantlarda da kullanılır."),
      rakip="Nb"),

    V("Ir", 4, "tarih", "Dinozorları Yok Eden Kanıt",
      "1980'de Luis ve Walter Alvarez, İtalya'daki kayaçlarda dinozorların yok olduğu döneme denk gelen ince bir kil tabakasını "
      "incelediler. Tabakada, yer kabuğunda çok nadir bulunan bir metal normalden kat kat fazlaydı. Görevin: bu metali bulmak ve "
      "neden büyük bir göktaşı çarpmasının kanıtı sayıldığını savunmak.",
      [("tarih", "Garip kil tabakası", "Dinozorların yok olduğu döneme denk gelen ince kil tabakasında bu metal, üstündeki ve altındaki kayaçlara göre kat kat fazla."),
       ("kimyasal", "Uzaydan gelen metal", "Bu metal yer kabuğunda çok az ama göktaşlarında çok daha bol bulunuyor. Bilinen en korozyona dayanıklı malzeme.")],
      gozlem=S("Metalin yalnızca o ince tabakada kat kat fazla olması (K1) neyi gösterir?",
               "O dönemde bu metalin bol olduğu bir kaynaktan (örneğin bir göktaşından) gelen malzeme kısa sürede çökmüş olabilir.",
               Y("Metal bütün kayaçlarda aynı miktarda bulunur.", "veri", "Metal yalnızca bu tabakada kat kat fazla (K1).", "K1"),
               Y("Tabaka milyonlarca yıl boyunca yavaşça oluştu.", "kanitsiz", "Tabaka çok ince; kanıtlar kısa sürede biriken bir olayı düşündürüyor.", "K1"),
               ipucu="İnce bir tabaka uzun mu, kısa mı bir sürede oluşur?",
               aciklama="İnce bir tabakada birden artan bir element, kısa süreli ve olağanüstü bir olayın izi olabilir. Alvarez'ler bunu bir göktaşı çarpmasının izi olarak yorumladı."),
      kullanim=S("İridyum anomalisi neden büyük bir göktaşı çarpmasının kanıtı sayıldı?",
                 "İridyum yer kabuğunda çok nadir ama göktaşlarında boldur; dünyanın birçok yerinde aynı yaşlı tabakada bulunması dev bir çarpmanın toz bulutunu gösterir",
                 Y("İridyum dinozorların kemiklerinde bulunduğu için", "kanitsiz", "İridyum kil tabakasında bulundu (K1); kemiklerde değil.", "K1"),
                 Y("İridyum yer kabuğunda çok bol olduğu için", "veri", "İridyum yer kabuğunda çok nadirdir (K2).", "K2"),
                 Y("İridyum korozyona dayanıklı olduğu için dinozorları koruyamadığı için", "iliski", "Korozyon direnci iridyumun bir özelliğidir (K2) ama dinozorların yok oluşuyla neden-sonuç bağı kurmaz.", "K2"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Alvarez hipotezine göre yaklaşık 66 milyon yıl önce dev bir göktaşı Dünya'ya çarptı; havaya yayılan iridyumca zengin toz bütün dünyaya yayılarak ince bir tabaka oluşturdu. Daha sonra Meksika'da Chicxulub kraterinin bulunması hipotezi güçlendirdi."),
      rakip="Rh"),

    V("Pt", 4, "tarih", "Fanusların Altındaki Kilogram",
      "1889'dan 2019'a kadar dünyadaki bütün tartılar, Paris yakınlarında üç cam fanus altında saklanan küçük bir metal silindire "
      "göre ayarlanıyordu: Uluslararası Kilogram Prototipi. Silindirin %90'ı değerli bir metal, %10'u iridyumdu. Görevin: bu "
      "değerli metali bulmak ve neden seçildiğini savunmak.",
      [("tarih", "Tek bir silindir", "Kilogram 130 yıl boyunca tek bir metal silindirin kütlesiyle tanımlandı; silindir çok nadiren fanuslarından çıkarıldı."),
       ("alasim", "Silindirin alaşımı", "Silindir %90 aranan metal ve %10 iridyumdan oluşan bir alaşım. Alaşım çok yoğun, çok sert ve neredeyse hiç tepkimeye girmiyor.")],
      gozlem=S("Kilogramın tek bir silindirle tanımlanması (K1) ne tür bir sorun yaratabilirdi?",
               "Silindirin kütlesi çok az da olsa değişirse, dünyadaki bütün ölçümler de değişmiş olurdu.",
               Y("Hiçbir sorun yaratmazdı; silindir sonsuza kadar aynı kalır.", "kanitsiz", "Hiçbir nesne kesinlikle değişmez değildir; yüzeyine toz ya da gaz tutunabilir.", "K1"),
               Y("Silindir çok büyük olduğu için taşınamazdı.", "kanitsiz", "Kanıtlarda silindirin büyüklüğünden söz edilmiyor; sorun tek bir nesneye bağlı olmak.", "K1"),
               ipucu="Bütün dünya tek bir nesneye güvenirse ne olur?",
               aciklama="Bir birimi tek bir nesneye bağlamak risklidir. Bu yüzden 2019'da kilogram, değişmeyen bir doğa sabitiyle (Planck sabiti) yeniden tanımlandı."),
      kullanim=S("Kilogram prototipi için neden platin-iridyum alaşımı seçildi?",
                 "Çok yoğun olduğu için küçük bir silindir 1 kg olabilir; neredeyse hiç tepkimeye girmez ve aşınmaz, kütlesi korunur",
                 Y("Platin çok hafif olduğu için", "veri", "Alaşım çok yoğun (K2).", "K2"),
                 Y("Platin havadaki oksijenle hızla tepkimeye girdiği için", "veri", "Alaşım neredeyse hiç tepkimeye girmiyor (K2).", "K2"),
                 Y("Platin çok ucuz olduğu için", "kanitsiz", "Platin çok değerli bir metaldir; seçilme nedeni dayanıklılığı (K2).", "K2"),
                 ipucu="K2'deki üç özelliği düşün.",
                 aciklama="Platin-iridyum alaşımı çok yoğun, sert ve kimyasal olarak çok dayanıklıdır; yüzeyinde paslanma olmaz. Bu yüzden kilogram ve eski metre prototipleri bu alaşımdan yapıldı."),
      rakip="Pd"),

    V("Hg", 4, "cevre", "Minamata'nın Kedileri",
      "1950'lerde Japonya'nın Minamata körfezinde balık yiyen kediler tuhaf davranışlar gösterip ölmeye başladı. Kısa süre "
      "sonra körfezin balıklarını yiyen insanlarda da ağır sinir sistemi hastalıkları görüldü. Bir fabrika atık sularını "
      "körfeze boşaltıyordu. Görevin: hastalığa yol açan metali bulmak ve savunmak.",
      [("tarih", "Önce kediler", "Hastalık önce balık yiyen kedilerde, sonra körfezin balıklarını yiyen insanlarda görüldü."),
       ("kimyasal", "Atıktaki metal", "Fabrikanın atık suyunda oda sıcaklığında sıvı olan bir metalin bileşikleri vardı. Bu bileşikler balıkların vücudunda birikiyordu.", "serbest")],
      gozlem=S("Hastalığın önce balık yiyen kedilerde görülmesi (K1) neyi düşündürür?",
               "Zehir besin yoluyla, yani balıklar aracılığıyla geçiyor olabilir.",
               Y("Hastalık havadan bulaşıyor.", "kanitsiz", "Hastalık balık yiyen canlılarda görülüyor (K1); havadan bulaştığına dair bir kanıt yok.", "K1"),
               Y("Kediler hastalığı insanlara bulaştırdı.", "kanitsiz", "Ortak nokta kedilerin ve insanların aynı balıkları yemesi (K1).", "K1"),
               ipucu="Kedilerle insanların ortak noktası neydi?",
               aciklama="Hastalığın balık yiyen canlılarda görülmesi, zehrin besin zinciri yoluyla geçtiğini düşündürdü. Bu, çevre sağlığı tarihindeki en önemli olaylardan biridir."),
      kullanim=S("Cıva neden balık yiyen canlılarda ve insanlarda daha çok birikir?",
                 "Metil cıva canlıların vücudundan kolay atılamaz; besin zincirinin her basamağında birikerek artar",
                 Y("Cıva sudan buharlaşıp kaybolduğu için", "veri", "Cıva bileşikleri balıklarda birikiyor (K2); kaybolmuyor.", "K2"),
                 Y("Cıva yalnızca kedilere zararlı olduğu için", "veri", "İnsanlarda da ağır hastalıklar görüldü (K1).", "K1"),
                 Y("Cıva vücutta hemen atıldığı için", "veri", "Cıva bileşikleri birikiyor (K2).", "K2"),
                 ipucu="Küçük balıkları büyük balıklar, büyük balıkları da kediler ve insanlar yer.",
                 aciklama="Metil cıva vücuttan çok yavaş atılır. Küçük canlılar onu alır, onları yiyen daha büyük canlılarda birikir; besin zincirinin tepesindeki canlılarda en yüksek düzeye ulaşır. 2013'te imzalanan Minamata Sözleşmesi cıva kullanımını sınırlandırıyor."),
      rakip="Cd"),

    V("Tl", 4, "adli", "Romandaki Zehir",
      "1977'de Londra'daki bir hastanede ağır hasta bir çocuk tedavi ediliyordu: saçları dökülüyor, sinirleri zarar görüyordu. "
      "Bir hemşire, okuduğu bir Agatha Christie romanındaki zehirlenme belirtilerinin aynısı olduğunu fark etti. Testler "
      "hemşireyi haklı çıkardı. Görevin: romandaki ve gerçekteki zehrin metalini bulmak ve savunmak.",
      [("tarih", "Hemşirenin fark ettiği", "Çocuktaki saç dökülmesi ve sinir hasarı, romandaki zehirlenme belirtileriyle birebir aynıydı."),
       ("kimyasal", "Sessiz zehir", "Romandaki zehir, kokusuz ve tatsız olduğu için eskiden fare zehirlerinde kullanılan bir metalin tuzuydu. Bu kullanım bugün birçok ülkede yasak.")],
      gozlem=S("Hemşirenin belirtileri romandakilerle karşılaştırması (K1) bilimsel açıdan neye örnektir?",
               "Gözlemlerden yola çıkarak bir hipotez kurmaya; hipotez daha sonra testlerle doğrulandı.",
               Y("Kesin bir kanıta.", "kanitsiz", "Benzerlik bir hipotez kurdurur; kesin kanıt ancak testlerle elde edildi.", "K1"),
               Y("Bilimle ilgisi olmayan bir tahmine.", "veri", "Hemşire belirtileri dikkatle karşılaştırıp bir hipotez kurdu ve hipotez testlerle doğrulandı.", "K1"),
               ipucu="Hipotez ile kanıt arasındaki fark nedir?",
               aciklama="Gözlemlerden kurulan bir açıklama hipotezdir. Hipotez, testlerle sınanıp doğrulandığında güçlü bir bilimsel sonuca dönüşür."),
      kullanim=S("Talyum tuzları neden çok tehlikeli bir zehirdir?",
                 "Kokusuz ve tatsızdır, fark edilmeden yiyeceğe karışabilir; vücutta potasyumun yerine geçerek hücrelere zarar verir",
                 Y("Talyum çok kötü koktuğu için", "veri", "Talyum tuzları kokusuz ve tatsız (K2).", "K2"),
                 Y("Talyum vücuttan hemen atıldığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; talyum ağır hasara yol açıyor (K1).", "K1"),
                 Y("Talyum radyoaktif olduğu için", "kanitsiz", "Talyumun zararı radyoaktiflikten değil, kimyasal zehirliliğinden gelir.", "K2"),
                 ipucu="K2'deki özellik bir zehri neden daha tehlikeli yapar?",
                 aciklama="Talyum iyonu, vücutta potasyum iyonuna benzediği için hücrelere girer ve onların çalışmasını bozar. Kokusuz ve tatsız olması onu çok sinsi bir zehir yapar. 1977'deki olayda hemşire Marsha Maitland'in fark etmesiyle çocuk tedavi edilip kurtarıldı."),
      rakip="In"),

    V("Pb", 4, "enerji", "Arabanın Ağır Kutusu",
      "Bir oto servisinde usta, eski bir arabanın aküsünü çıkarırken zorlandı: akü boyutuna göre çok ağırdı. İçinde sülfürik "
      "asit çözeltisine daldırılmış metal plakalar vardı. Görevin: plakaların metalini bulmak ve akülerde neden kullanıldığını savunmak.",
      [("fiziksel", "Ağır akü", "Akü boyutuna göre çok ağır; içinde sülfürik asit çözeltisine daldırılmış metal plakalar var."),
       ("kimyasal", "Plakaların metali", "Plakalar yumuşak, gri, çok yoğun bir metalden ve onun oksidinden yapılmış. Eski aküler geri dönüşümle neredeyse tamamen yeniden kullanılıyor.")],
      gozlem=S("Akünün boyutuna göre çok ağır olması (K1) plakalar hakkında neyi gösterir?",
               "Plakalar çok yoğun bir metalden yapılmış.",
               Y("Akü içi boş olduğu için ağırdır.", "veri", "İçi boş bir kutu hafif olurdu; akünün içi metal plakalar ve asitle dolu (K1).", "K1"),
               Y("Akünün ağırlığı yalnızca asitten gelir.", "kanitsiz", "Plakaların metali çok yoğun (K2); ağırlığın büyük kısmı plakalardan gelir.", "K2"),
               ipucu="Aynı boyutta iki kutudan biri çok daha ağırsa içinde ne olabilir?",
               aciklama="Bir cismin kütlesi, hacmi ile yoğunluğunun çarpımına eşittir. Aynı boyutta çok ağır bir akü, içinde çok yoğun bir malzeme olduğunu gösterir."),
      kullanim=S("Otomobil akülerinde neden kurşun kullanılır?",
                 "Kurşun ve kurşun dioksit plakaları sülfürik asitte tersinir tepkime verir; akü yüksek akım verebilir ve yeniden şarj edilebilir",
                 Y("Kurşun hafif olduğu için arabayı hafiflettiği için", "veri", "Akü çok ağır (K1); kurşun çok yoğun bir metaldir.", "K1"),
                 Y("Kurşun asitle hiç tepkimeye girmediği için", "veri", "Akü, plakaların asitle tepkimesiyle çalışır.", "K1"),
                 Y("Kurşun radyasyonu durdurduğu için aküyü koruduğu için", "iliski", "Radyasyonu durdurmak kurşunun başka bir kullanım alanıdır; aküdeki görevini açıklamaz.", "K2"),
                 ipucu="Akü şarj edilebilen bir pildir.",
                 aciklama="Kurşun-asit aküler motoru çalıştırmak için kısa sürede yüksek akım verebilir ve yeniden şarj edilebilir. Kurşun zehirli olduğu için eski aküler mutlaka geri dönüşüme verilmelidir; akülerdeki kurşunun neredeyse tamamı yeniden kullanılır."),
      rakip="Sn"),

    V("Pb", 4, "cevre", "Benzindeki Görünmez Tehlike",
      "1970'lerde benzinlere, motordaki vuruntuyu azaltmak için ağır bir metalin bir bileşiği katılıyordu. Egzozla havaya "
      "karışan bu metal, şehirlerde yaşayan çocukların kanında ölçülebiliyordu. Görevin: bu metali bulmak ve neden "
      "benzinden çıkarıldığını savunmak.",
      [("kimyasal", "Kanda ölçülen metal", "Benzine katılan bileşik egzozla havaya karışıyor; bu metal yoğun trafiğin olduğu şehirlerdeki çocukların kanında daha yüksek ölçülüyordu."),
       ("tarih", "Yasaktan sonra", "Bu katkılı benzin yasaklandıktan sonra çocukların kanındaki metal miktarı belirgin biçimde azaldı. Dünyada bu benzinin satışı 2021'de tamamen sona erdi.")],
      gozlem=S("Benzin yasaklandıktan sonra çocukların kanındaki metal miktarının azalması (K2) neyi gösterir?",
               "Kandaki metalin önemli bir kaynağı benzindi; kaynak kesilince miktar azaldı.",
               Y("Benzin ile kandaki metal arasında hiçbir ilişki yoktur.", "veri", "Yasaktan sonra kandaki miktar belirgin biçimde azaldı (K2); bu bir ilişki olduğunu gösteriyor.", "K2"),
               Y("Çocuklar yasaktan sonra daha az süt içti.", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; değişim benzin yasağıyla zamanlıyor.", "K2"),
               ipucu="Bir kaynak kesildiğinde ne değişti?",
               aciklama="Bir kaynağın kesilmesinden sonra etkinin azalması, o kaynağın etkiye yol açtığına dair güçlü bir kanıttır."),
      kullanim=S("Kurşun neden benzinden çıkarıldı?",
                 "Kurşun zehirlidir; egzozla havaya yayılıp insanlar, özellikle çocuklar tarafından solunuyor ve sinir sistemine zarar veriyordu",
                 Y("Kurşun motoru çok hızlandırdığı için", "iliski", "Kurşun bileşiği vuruntuyu azaltmak için katılıyordu; çıkarılma nedeni zehirliliği.", "K1"),
                 Y("Kurşun çok pahalı olduğu için", "kanitsiz", "Kanıtlar sağlık etkisini gösteriyor (K1, K2); fiyattan söz etmiyor.", "K2"),
                 Y("Kurşun havada hemen kaybolduğu için", "veri", "Kurşun havadan çocukların kanına geçiyordu (K1).", "K1"),
                 ipucu="K1 ve K2'deki sağlık bilgisine bak.",
                 aciklama="Kurşun, özellikle çocukların beyin gelişimine zarar verir. Kurşunlu benzin ülke ülke yasaklandı; dünyada son satış 2021'de Cezayir'de sona erdi. Bu, çevre sağlığı alanındaki en büyük başarılardan biri sayılır."),
      yapi="izotop", adaylar=["Hg", "Tl", "Pb", "Bi"]),

    V("Bi", 4, "sanat", "Gökkuşağı Renkli Kristal",
      "Bir mineral fuarında satılan, merdiven basamakları gibi iç içe kare şekilli kristaller gökkuşağının bütün renkleriyle "
      "parlıyor. Satıcı kristalleri, erittiği bir metalin yavaşça soğumasıyla kendisinin yaptığını söylüyor. Görevin: bu "
      "metali bulmak ve savunmak.",
      [("fiziksel", "Katılaşırken genleşen metal", "Bu metal erimiş hâlden soğuyup katılaşırken genleşiyor; suyun donarken genleşmesi gibi."),
       ("fiziksel", "Renklerin kaynağı", "Kristalin renkleri boyadan değil, yüzeyindeki çok ince oksit tabakasından geliyor; tabakanın kalınlığı rengi belirliyor.")],
      gozlem=S("Kristalin renklerinin boyadan değil, yüzeydeki ince oksit tabakasından gelmesi (K2) neyi gösterir?",
               "Renkler, ışığın çok ince tabakada yansımasıyla oluşuyor; sabun köpüğündeki renkler gibi.",
               Y("Kristal gökkuşağı renklerine boyanmıştır.", "veri", "Renkler boyadan gelmiyor (K2).", "K2"),
               Y("Metalin kendisi gökkuşağı renklidir.", "veri", "Renkler metalden değil, yüzeyindeki oksit tabakasından geliyor (K2).", "K2"),
               ipucu="Sabun köpüğü neden renkli görünür?",
               aciklama="Çok ince bir tabakanın üst ve alt yüzeyinden yansıyan ışınlar birbirini güçlendirir ya da zayıflatır; tabakanın kalınlığına göre farklı renkler görülür."),
      kullanim=S("Bizmut kurşunun yerine nerede kullanılabilir ve neden?",
                 "Kurşuna yakın yoğunlukta ama zehirliliği çok düşük bir metal olduğu için balık ağırlıklarında, av saçmalarında ve kurşunsuz lehimlerde",
                 Y("Bizmut kurşundan çok daha hafif olduğu için", "veri", "Ölçülen yoğunluk ({olcum}) kurşununkine yakın; bizmut ağır bir metaldir.", "{olcum}"),
                 Y("Bizmut çok zehirli olduğu için", "kanitsiz", "Bizmutun zehirliliği çok düşüktür; bu yüzden kurşunun yerine kullanılır.", "K1"),
                 Y("Bizmut gökkuşağı renkli olduğu için", "iliski", "Renkler oksit tabakasından geliyor (K2); kurşunun yerine kullanılmasının nedeni değil.", "K2"),
                 ipucu="Kurşunun en büyük sakıncası nedir?",
                 aciklama="Bizmut, ağır metaller arasında zehirliliği çok düşük olanlardan biridir. Bu yüzden kurşunun yerine av saçmalarında, balık ağırlıklarında ve lehimlerde kullanılır. Bileşikleri hazımsızlık ilaçlarında da bulunur."),
      rakip="Sb"),

    V("U", 4, "tarih", "Çekmecedeki Fotoğraf Plakası",
      "1896'da Paris'te Henri Becquerel, bir metal tuzunun güneş ışığıyla parlayıp parlamadığını araştırıyordu. Bulutlu bir "
      "günde tuzu, siyah kâğıda sarılı bir fotoğraf plakasının üzerinde çekmeceye kaldırdı. Günler sonra plakayı banyo edince "
      "plakanın güneş görmediği hâlde karardığını gördü. Görevin: tuzdaki metali bulmak ve keşfin önemini savunmak.",
      [("deney", "Kararan plaka", "Siyah kâğıda sarılı fotoğraf plakası, üzerindeki tuz güneş görmediği hâlde karardı."),
       ("kimyasal", "Işınımın kaynağı", "Plakayı karartan ışınım, tuzun içindeki metalden geliyordu. Bu metal bugün nükleer santrallerde yakıt olarak kullanılıyor.")],
      gozlem=S("Plakanın güneş görmediği hâlde kararması (K1) neyi gösterir?",
               "Tuz, güneş ışığına gerek olmadan kendiliğinden görünmez ışınlar yayıyor.",
               Y("Plaka güneş ışığıyla karardı.", "veri", "Plaka çekmecede, siyah kâğıda sarılıydı (K1); güneş görmedi.", "K1"),
               Y("Plaka zaten bozuktu.", "kanitsiz", "Kararma tuzun bulunduğu yerde oluştu; plakanın bozuk olduğuna dair bir kanıt yok.", "K1"),
               ipucu="Işık olmadan bir fotoğraf plakasını ne karartabilir?",
               aciklama="Becquerel, tuzun güneş ışığından bağımsız olarak kendiliğinden görünmez ışınlar yaydığını anladı. Bu, radyoaktifliğin keşfiydi."),
      kullanim=S("Becquerel'in deneyi neden önemli bir keşifti?",
                 "Bazı elementlerin kendiliğinden görünmez ışınlar yaydığını, yani radyoaktifliği ortaya çıkardı",
                 Y("Uranyumun güneş ışığıyla parladığını kanıtladığı için", "veri", "Plaka güneş görmediği hâlde karardı (K1); ışınım güneşten bağımsızdı.", "K1"),
                 Y("Fotoğraf makinesini icat ettiği için", "kanitsiz", "Fotoğraf plakaları Becquerel'den önce de vardı; keşfi radyoaktiflikti.", "K1"),
                 Y("Uranyumun hiç ışınım yapmadığını gösterdiği için", "veri", "Uranyum tuzu plakayı karartacak ışınım yaptı (K2).", "K2"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Becquerel'in 1896'daki gözlemi radyoaktifliğin keşfiydi. Marie ve Pierre Curie bu yolda ilerleyerek polonyum ve radyumu buldular; üçü 1903 Nobel Fizik Ödülü'nü paylaştı."),
      yapi="izotop", adaylar=["Pa", "U", "Np", "Pu"]),

    V("Pu", 4, "saglik", "Otuz Yıl Atan Kalp Pili",
      "1970'lerde bazı hastalara takılan kalp pillerinin içinde, radyoaktif bozunmayla sürekli ısı üreten küçük bir kapsül "
      "vardı. Bu ısı elektriğe çevriliyordu. Bu pillerin bazıları 30 yıldan uzun süre çalıştı. Görevin: kapsüldeki elementi "
      "bulmak ve neden seçildiğini savunmak.",
      [("tarih", "Uzun ömür", "Bu kalp pillerinin bazıları değiştirilmeden 30 yıldan uzun süre çalıştı."),
       ("fiziksel", "Kapsüldeki izotop", "Kapsüldeki izotopun yarılanma süresi yaklaşık 88 yıl. Yaydığı alfa parçacıkları kapsülün ince duvarından bile geçemiyor.")],
      gozlem=S("Pillerin 30 yıldan uzun süre çalışabilmesi (K1) kapsüldeki izotop hakkında neyi gösterir?",
               "İzotop çok yavaş bozunuyor; ısı üretimi yıllarca neredeyse sabit kalıyor.",
               Y("İzotop birkaç günde bitiyor.", "veri", "Piller 30 yıldan uzun çalıştı (K1); izotopun yarılanma süresi yaklaşık 88 yıl (K2).", "K2"),
               Y("Pil her yıl yeniden dolduruluyor.", "kanitsiz", "Piller değiştirilmeden çalıştı (K1).", "K1"),
               ipucu="88 yıllık yarılanma süresine göre 30 yıl uzun mu?",
               aciklama="Yarılanma süresi 88 yıl olan bir izotop 30 yılda yalnızca yaklaşık beşte bir oranında azalır. Bu yüzden ısı üretimi yıllarca yeterli kalır."),
      kullanim=S("Plütonyum-238 kalp pillerinde neden kullanıldı?",
                 "Yarılanma süresi uzun olduğu için yıllarca sabite yakın ısı verir; alfa ışınları kolayca durdurulduğu için kapsül içinde güvenle taşınabilir",
                 Y("Plütonyum hiç radyoaktif olmadığı için", "veri", "Kapsül radyoaktif bozunmayla ısı üretiyor (hikâye, K2).", "K2"),
                 Y("Alfa ışınları vücudun her yerine kolayca ulaşabildiği için", "veri", "Alfa parçacıkları kapsülün ince duvarından bile geçemiyor (K2).", "K2"),
                 Y("Plütonyum birkaç ayda bütün enerjisini verdiği için", "veri", "Yarılanma süresi yaklaşık 88 yıl (K2).", "K2"),
                 ipucu="K2'deki iki özelliği birleştir.",
                 aciklama="Plütonyum-238 yavaş bozunur ve alfa parçacıkları yayar; alfa parçacıkları ince bir kapsül duvarında durur. Bu yüzden hem kalp pillerinde hem uzay araçlarında kullanıldı. Bugün kalp pillerinde uzun ömürlü lityum piller kullanılıyor."),
      yapi="izotop", adaylar=["U", "Np", "Pu", "Am"]),

    V("Au", 4, "teknoloji", "Kararmayan Bağlantı Uçları",
      "Bir bilgisayar teknisyeni, yıllarca kullanılmış bir ekran kartının anakarta takılan bağlantı uçlarının hâlâ sarı ve "
      "parlak olduğunu gösterdi. Uçların üzerinde çok ince bir değerli metal kaplaması var. Görevin: kaplama metalini bulmak "
      "ve neden kullanıldığını savunmak.",
      [("fiziksel", "Kararmayan uçlar", "Bağlantı uçları yıllarca kullanıldığı hâlde kararmamış; sarı ve parlak."),
       ("iletkenlik", "Kaplamanın özellikleri", "Kaplama metali elektriği çok iyi iletiyor ve neredeyse hiçbir maddeyle tepkimeye girmiyor.")],
      gozlem=S("Bağlantı uçlarının yıllarca kararmaması (K1) neden önemlidir?",
               "Yüzeyde yalıtkan bir tabaka oluşmadığı için elektrik bağlantısı bozulmuyor.",
               Y("Kararma bağlantıyı güçlendirir.", "iliski", "Kararma, yüzeyde elektriği iyi iletmeyen bir tabaka oluşturur; bağlantıyı zayıflatır.", "K1"),
               Y("Uçların rengi bilgisayarın hızını belirler.", "iliski", "Renk bilgisayarın hızını belirlemez; önemli olan yüzeyin iyi iletmesi.", "K1"),
               ipucu="Kararmış bir yüzey elektriği nasıl iletir?",
               aciklama="Metal yüzeylerde oluşan oksit ya da sülfür tabakaları elektriği kötü iletir. Kararmayan bir kaplama, bağlantının yıllarca iyi çalışmasını sağlar."),
      kullanim=S("Elektronik bağlantı uçları neden altınla kaplanır?",
                 "Altın kararmaz ve paslanmaz; yüzeyde yalıtkan bir tabaka oluşmadığı için bağlantı yıllarca iyi iletir",
                 Y("Altın elektriği hiç iletmediği için", "veri", "Kaplama metali elektriği çok iyi iletiyor (K2).", "K2"),
                 Y("Altın havadaki oksijenle hızla tepkimeye girdiği için", "veri", "Altın neredeyse hiçbir maddeyle tepkimeye girmiyor (K2).", "K2"),
                 Y("Altın kaplama kartı daha değerli göstermek için yapıldığı için", "iliski", "Kaplama çok ince ve görünüş için değil; amaç güvenilir bir elektrik bağlantısı.", "K1"),
                 ipucu="K1 ve K2'yi birleştir.",
                 aciklama="Altın soy bir metaldir: kararmaz, paslanmaz ve elektriği iyi iletir. Bu yüzden elektronik cihazlardaki bağlantı uçları ve kontaklar çok ince bir altın tabakasıyla kaplanır. Eski telefonlar bu yüzden 'kentsel maden' olarak geri dönüştürülür."),
      yapi="izotop", adaylar=["Ir", "Pt", "Au", "Hg"]),

    V("Tb", 4, "teknoloji", "Ampulün Yeşil Tozu",
      "Bir öğrenci kırılmış eski bir tasarruflu ampulün camının iç yüzeyinin beyaz bir tozla kaplı olduğunu gördü. Öğretmen, "
      "bu tozun ampulün içindeki morötesi ışığı görünür ışığa çevirdiğini ve tozdaki bileşiklerden birinin yeşil ışık verdiğini "
      "anlattı. Görevin: yeşil ışığı veren bileşikteki lantaniti bulmak ve savunmak.",
      [("fiziksel", "Işık dönüştüren toz", "Ampulün içindeki gaz morötesi ışık üretiyor; camın iç yüzeyindeki toz bu görünmez ışığı soğurup görünür ışık olarak yayıyor. Tozdaki bileşiklerden biri yeşil ışık veriyor."),
       ("alasim", "Lantanitin başka bir işi", "Yeşil ışığı veren bileşikteki lantanit, demir ve disprosiyumla oluşturduğu bir alaşım sayesinde düz bir cam yüzeyi bile hoparlöre çevirebiliyor.")],
      gozlem=S("Tozun morötesi ışığı görünür ışığa çevirmesi (K1) ampul için neden gereklidir?",
               "Morötesi ışık gözle görülmez; toz olmasaydı ampul odayı aydınlatamazdı.",
               Y("Morötesi ışık zaten görünür ışıktır.", "veri", "Morötesi ışık görünmez (K1); toz onu görünür ışığa çeviriyor.", "K1"),
               Y("Toz ampulü soğutmak için konmuştur.", "kanitsiz", "Kanıtlar tozun ışığı dönüştürdüğünü söylüyor (K1).", "K1"),
               ipucu="Gözümüz morötesi ışığı görebilir mi?",
               aciklama="Floresan lambalarda gaz morötesi ışık üretir. Camın içindeki 'fosfor' denilen tozlar bu ışığı soğurup görünür renklerde yayar."),
      kullanim=S("Terbiyum bileşikleri ampullerde neden kullanılır?",
                 "Morötesi ışığı soğurup parlak yeşil ışık olarak yayar; kırmızı ve mavi ile birleşince beyaz ışık oluşur",
                 Y("Terbiyum ampulü hoparlöre çevirdiği için", "iliski", "Hoparlör etkisi terbiyumun başka bir alaşımının özelliğidir (K2); ampuldeki görevi yeşil ışık vermek.", "K2"),
                 Y("Terbiyum morötesi ışığı artırdığı için", "veri", "Toz morötesi ışığı görünür ışığa çeviriyor (K1).", "K1"),
                 Y("Terbiyum ampulü radyoaktif yaptığı için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok.", "K1"),
                 ipucu="K1'de tozun görevi yazıyor.",
                 aciklama="Terbiyum bileşikleri parlak yeşil ışık verir; evropiyumun kırmızısı ve başka bir bileşiğin mavisiyle birleşince beyaz ışık elde edilir. Terbiyum ayrıca bazı tıbbi görüntüleme ekranlarında ve özel hoparlörlerde kullanılır."),
      yapi="izotop", adaylar=["Gd", "Tb", "Dy", "Ho"]),

    V("Y", 4, "tarih", "Havada Asılı Duran Mıknatıs",
      "1987'de araştırmacılar, sıvı azotla soğutulunca elektriğe hiç direnç göstermeyen yeni bir seramik buldular. Seramiğin "
      "üzerine konan küçük bir mıknatıs havada asılı kaldı. Bu buluş fizik dünyasında büyük heyecan yarattı. Görevin: seramiğin "
      "içindeki geçiş metalini bulmak ve buluşun neden önemli olduğunu savunmak.",
      [("deney", "Havada asılı mıknatıs", "Seramik sıvı azotla (−196 °C) soğutulunca elektriğe hiç direnç göstermiyor ve üzerindeki mıknatısı havada asılı tutuyor."),
       ("kimyasal", "Seramiğin bileşimi", "Seramik baryum, bakır, oksijen ve bir geçiş metalinden oluşuyor. Bu metal lazer kristallerinde ve beyaz LED'lerde de kullanılıyor.")],
      gozlem=S("Mıknatısın seramiğin üzerinde havada asılı kalması (K1) neyi gösterir?",
               "Soğutulan seramik, mıknatısın manyetik alanını dışarı iterek onu havada tutuyor.",
               Y("Mıknatıs çok hafif olduğu için uçuyor.", "kanitsiz", "Mıknatıs seramik soğutulunca havada kalıyor (K1); hafiflikle açıklanamaz.", "K1"),
               Y("Seramik mıknatısı çekiyor.", "veri", "Mıknatıs seramiğe yapışmıyor, üzerinde havada duruyor (K1).", "K1"),
               ipucu="Mıknatıs seramiğe yapışıyor mu, yoksa üzerinde mi duruyor?",
               aciklama="Süper iletkenler manyetik alanı içlerinden dışarı iter (Meissner etkisi). Bu yüzden üzerlerine konan mıknatıs havada asılı kalır."),
      kullanim=S("İtriyumlu süper iletkenin bulunması neden önemliydi?",
                 "Ucuz ve kolay bulunan sıvı azotla soğutulunca süper iletken oluyordu; önceki süper iletkenler çok daha pahalı sıvı helyum gerektiriyordu",
                 Y("Oda sıcaklığında süper iletken olduğu için", "veri", "Seramik ancak sıvı azotla (−196 °C) soğutulunca süper iletken oluyor (K1).", "K1"),
                 Y("İtriyum radyoaktif olduğu için", "kanitsiz", "Kanıtlarda böyle bir bilgi yok; önemli olan soğutma sıcaklığı.", "K1"),
                 Y("İtriyum LED'lerde kullanıldığı için", "iliski", "LED'ler itriyumun başka bir kullanım alanıdır (K2); buluşun önemini açıklamaz.", "K2"),
                 ipucu="K1'deki soğutucuyu düşün: sıvı azot mu, sıvı helyum mu daha kolay bulunur?",
                 aciklama="İtriyum-baryum-bakır oksit (YBCO), −180 °C civarında süper iletken olur; bu sıcaklık ucuz sıvı azotla sağlanabilir. Bu buluş süper iletkenlerin daha geniş kullanımının yolunu açtı."),
      yapi="izotop", adaylar=["Rb", "Sr", "Y", "Zr"]),
]
